MapMap: Media Class Reference
Media Class Reference
Paint that is a Texture retrieved via a video file.
#include <Paint.h>
Public Types
typedef QSharedPointer< Paint > ptr
Public Member Functions
Media (const QString uri_, bool live, double rate, uid id=NULL_UID)
virtual ~Media ()
const QString getUri () const
bool setUri (const QString &uri)
virtual void build ()
virtual void update ()
This method should be called at each call of draw().
virtual void play ()
Starts playback.
virtual void pause ()
Pauses playback.
virtual void rewind ()
Rewinds.
virtual void lockMutex ()
Locks mutex (default = no effect).
virtual void unlockMutex ()
Unlocks mutex (default = no effect).
virtual QString getType () const
virtual int getWidth () const
virtual int getHeight () const
virtual const uchar * getBits ()
Returns image bits data. Next call to bitsHaveChanged() will be false.
virtual bool bitsHaveChanged () const
Returns true iff bits have changed since last call to getBits().
virtual void setRate (double rate=100.0)
Sets playback rate (in %). Negative values mean reverse playback.
double getRate () const
Returns playback rate.
virtual void setVolume (double volume=0.0)
Sets audio playback volume (in %).
double getVolume () const
Returns audio playback volume.
GLuint getTextureId () const
virtual void setPosition (GLfloat xPos, GLfloat yPos)
virtual GLfloat getX () const
virtual GLfloat getY () const
virtual QRectF getRect () const
void setName (const QString &name)
QString getName () const
uid getId () const
float getOpacity () const
void setOpacity (float opacity)
Static Public Member Functions
static bool hasVideoSupport ()
Checks whether or not video is supported on this platform.
static const UidAllocator & getUidAllocator ()
Protected Attributes
QString uri
GLuint textureId
GLfloat x
GLfloat y
bool bitsChanged
Private Attributes
MediaImpl * impl_
Private implementation, so that GStreamer headers don't need to be included from every file in the project.
Detailed Description
Paint that is a Texture retrieved via a video file.
Definition at line 208 of file Paint.h.
Member Typedef Documentation
typedef QSharedPointer<Paint> Paint::ptr inherited
Definition at line 57 of file Paint.h.
Constructor & Destructor Documentation
Media::Media (const QString uri_, bool live, double rate, uid id = NULL_UID)
Definition at line 55 of file Paint.cpp.
References impl_, and setRate().
                                                               :
     Texture(id),
     uri(uri_),
     impl_(NULL)
 {
   impl_ = new MediaImpl(uri_, live);
   setRate(rate);
 }
Media::~Media () virtual
Definition at line 66 of file Paint.cpp.
References impl_.
 {
   delete impl_;
 }
Member Function Documentation
const QString Media::getUri () const
Definition at line 215 of file Paint.h.
References uri.
Referenced by ProjectWriter::writeItem().
   {
     return uri;
   }
bool Media::setUri (const QString & uri)
Definition at line 150 of file Paint.cpp.
References impl_, MediaImpl::loadMovie(), and uri.
Referenced by MainWindow::setTextureUri().
 {
   bool success = false;
   this->uri = uri;
   success = this->impl_->loadMovie(uri);
   if (! success)
     qDebug() << "Cannot load movie " << uri << "." << endl;
   return success;
 }
void Media::build () virtual
Reimplemented from Paint.
Definition at line 71 of file Paint.cpp.
References MediaImpl::build(), and impl_.
 {
   this->impl_->build();
 }
void Media::update () virtual
This method should be called at each call of draw().
Reimplemented from Paint.
Definition at line 88 of file Paint.cpp.
References impl_, and MediaImpl::update().
                    {
   impl_->update();
 }
void Media::play () virtual
Starts playback.
Reimplemented from Paint.
Definition at line 92 of file Paint.cpp.
References impl_, and MediaImpl::setPlayState().
 {
   impl_->setPlayState(true);
 }
void Media::pause () virtual
Pauses playback.
Reimplemented from Paint.
Definition at line 97 of file Paint.cpp.
References impl_, and MediaImpl::setPlayState().
 {
   impl_->setPlayState(false);
 }
void Media::rewind () virtual
Rewinds.
Reimplemented from Paint.
Definition at line 102 of file Paint.cpp.
References impl_, and MediaImpl::resetMovie().
 {
   impl_->resetMovie();
 }
void Media::lockMutex () virtual
Locks mutex (default = no effect).
Reimplemented from Paint.
Definition at line 107 of file Paint.cpp.
References impl_, and MediaImpl::lockMutex().
                       {
   impl_->lockMutex();
 }
void Media::unlockMutex () virtual
Unlocks mutex (default = no effect).
Reimplemented from Paint.
Definition at line 111 of file Paint.cpp.
References impl_, and MediaImpl::unlockMutex().
{
   impl_->unlockMutex();
 }
virtual QString Media::getType () const virtual
Implements Paint.
Definition at line 236 of file Paint.h.
   {
     return "media";
   }
int Media::getWidth () const virtual
Implements Texture.
Definition at line 76 of file Paint.cpp.
References MediaImpl::getWidth(), impl_, and MediaImpl::videoIsConnected().
 {
   while (!this->impl_->videoIsConnected());
   return this->impl_->getWidth();
 }
int Media::getHeight () const virtual
Implements Texture.
Definition at line 82 of file Paint.cpp.
References MediaImpl::getHeight(), impl_, and MediaImpl::videoIsConnected().
 {
   while (!this->impl_->videoIsConnected());
   return this->impl_->getHeight();
 }
const uchar * Media::getBits () virtual
Returns image bits data. Next call to bitsHaveChanged() will be false.
Implements Texture.
Definition at line 115 of file Paint.cpp.
References MediaImpl::getBits(), and impl_.
 {
   return this->impl_->getBits();
 }
bool Media::bitsHaveChanged () const virtual
Returns true iff bits have changed since last call to getBits().
Implements Texture.
Definition at line 120 of file Paint.cpp.
References MediaImpl::bitsHaveChanged(), and impl_.
 {
   return this->impl_->bitsHaveChanged();
 }
void Media::setRate (double rate = 100.0) virtual
Sets playback rate (in %). Negative values mean reverse playback.
Definition at line 125 of file Paint.cpp.
References impl_, and MediaImpl::setRate().
Referenced by Media(), and MainWindow::setTextureRate().
 {
   impl_->setRate(rate / 100.0);
 }
double Media::getRate () const
Returns playback rate.
Definition at line 130 of file Paint.cpp.
References MediaImpl::getRate(), and impl_.
Referenced by ProjectWriter::writeItem().
 {
   return impl_->getRate() * 100.0;
 }
void Media::setVolume (double volume = 0.0) virtual
Sets audio playback volume (in %).
Definition at line 135 of file Paint.cpp.
References impl_, and MediaImpl::setVolume().
Referenced by MainWindow::setTextureVolume().
 {
   impl_->setVolume(rate / 100.0);
 }
double Media::getVolume () const
Returns audio playback volume.
Definition at line 140 of file Paint.cpp.
References MediaImpl::getVolume(), and impl_.
 {
   return impl_->getVolume() * 100.0;
 }
bool Media::hasVideoSupport () static
Checks whether or not video is supported on this platform.
Definition at line 145 of file Paint.cpp.
References MediaImpl::hasVideoSupport().
Referenced by MainWindow::MainWindow().
 {
   return MediaImpl::hasVideoSupport();
 }
GLuint Texture::getTextureId () const inherited
Definition at line 144 of file Paint.h.
References Texture::textureId.
 { return textureId; }
virtual void Texture::setPosition (GLfloat xPos, GLfloat yPos) virtual inherited
Definition at line 154 of file Paint.h.
Referenced by MainWindow::createMediaPaint().
{
     x = xPos;
     y = yPos;
   }
virtual GLfloat Texture::getX () const virtual inherited
Definition at line 158 of file Paint.h.
References Texture::x.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), Texture::getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return x; }
virtual GLfloat Texture::getY () const virtual inherited
Definition at line 159 of file Paint.h.
References Texture::y.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), Texture::getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return y; }
virtual QRectF Texture::getRect () const virtual inherited
Definition at line 161 of file Paint.h.
References Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
 { return QRectF(getX(), getY(), getWidth(), getHeight()); }
static const UidAllocator& Paint::getUidAllocator () static inherited
Definition at line 61 of file Paint.h.
References Paint::allocator.
Referenced by MainWindow::createColorPaint(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMediaPaint(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deletePaint().
 { return allocator; }
void Paint::setName (const QString & name) inherited
Definition at line 83 of file Paint.h.
References Paint::_name.
 { _name = name; }
QString Paint::getName () const inherited
Definition at line 84 of file Paint.h.
References Paint::_name.
Referenced by ProjectWriter::writeItem().
 { return _name; }
uid Paint::getId () const inherited
Definition at line 85 of file Paint.h.
References Paint::_id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
float Paint::getOpacity () const inherited
Definition at line 87 of file Paint.h.
References Paint::_opacity.
 { return _opacity; }
void Paint::setOpacity (float opacity) inherited
Definition at line 88 of file Paint.h.
References Paint::_opacity.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
Member Data Documentation
QString Media::uri protected
Definition at line 211 of file Paint.h.
Referenced by getUri(), and setUri().
MediaImpl* Media::impl_ private
Private implementation, so that GStreamer headers don't need to be included from every file in the project.
Definition at line 269 of file Paint.h.
Referenced by bitsHaveChanged(), build(), getBits(), getHeight(), getRate(), getVolume(), getWidth(), lockMutex(), Media(), pause(), play(), rewind(), setRate(), setUri(), setVolume(), unlockMutex(), update(), and ~Media().
GLuint Texture::textureId protected inherited
Definition at line 123 of file Paint.h.
Referenced by Texture::getTextureId().
GLfloat Texture::x protected inherited
Definition at line 124 of file Paint.h.
Referenced by Texture::getX().
GLfloat Texture::y protected inherited
Definition at line 125 of file Paint.h.
Referenced by Texture::getY().
bool Texture::bitsChanged mutable protected inherited
Definition at line 126 of file Paint.h.
Referenced by Image::bitsHaveChanged(), Image::build(), and Image::getBits().
The documentation for this class was generated from the following files:
Paint.h
Paint.cpp