MapMap: PreferencesDialog Class Reference
PreferencesDialog Class Reference
#include <PreferencesDialog.h>
Signals
void closed ()
Public Member Functions
PreferencesDialog (MainWindow *mainWindow, QWidget *parent=0)
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void accept_cb ()
void reject_cb ()
Private Member Functions
void resetValues ()
Private Attributes
QSpinBox * _osc_port_numbox
MainWindow * _main_window
QDialogButtonBox * _button_box
Detailed Description
Definition at line 32 of file PreferencesDialog.h.
Constructor & Destructor Documentation
PreferencesDialog::PreferencesDialog (MainWindow * mainWindow, QWidget * parent = 0)
Definition at line 25 of file PreferencesDialog.cpp.
References _button_box, _main_window, _osc_port_numbox, accept_cb(), reject_cb(), and resetValues().
                                                                             :
     QDialog(parent)
 {
   _main_window = mainWindow;
   // static const int width = 600;
   // static const int height = 400;
   // resize(MainWindow::OUTPUT_WINDOW_MINIMUM_WIDTH, MainWindow::OUTPUT_WINDOW_MINIMUM_HEIGHT);
   // OSC port number
   QLabel* osc_port_label = new QLabel(tr("OSC port number"));
   _osc_port_numbox  = new QSpinBox;
   _osc_port_numbox->setRange(1024, 65534);
   QLayout* hbox_osc_port = new QHBoxLayout;
   hbox_osc_port->addWidget(osc_port_label);
   hbox_osc_port->addWidget(_osc_port_numbox);
   // cancel / ok
   _button_box = new QDialogButtonBox(QDialogButtonBox::Ok | QDialogButtonBox::Cancel);
   connect(_button_box, SIGNAL(accepted()), this, SLOT(accept_cb()));
   connect(_button_box, SIGNAL(rejected()), this, SLOT(reject_cb()));
   //QLayout* hbox_confirm = new QHBoxLayout;
   //hbox_confirm->addWidget(_button_box);
   hbox_osc_port->addWidget(_button_box);
   // pack all rows
   //QLayout* vbox = new QVBoxLayout;
   //vbox->addWidget(hbox_osc_port);
   setLayout(hbox_osc_port);
   this->resetValues();
 }
Member Function Documentation
void PreferencesDialog::closeEvent (QCloseEvent * event) protected
Definition at line 60 of file PreferencesDialog.cpp.
References closed().
 {
   emit closed();
   event->accept();
 }
void PreferencesDialog::closed () signal
Referenced by closeEvent().
void PreferencesDialog::accept_cb () private slot
Definition at line 78 of file PreferencesDialog.cpp.
References _main_window, _osc_port_numbox, and MainWindow::setOscPort().
Referenced by PreferencesDialog().
 {
   std::cout << "Values:" <<
     " osc port=" << _osc_port_numbox->value() <<
     std::endl;
   this->_main_window->setOscPort(this->_osc_port_numbox->value());
   this->setResult(QMessageBox::Ok);
   this->close();
 }
void PreferencesDialog::reject_cb () private slot
Definition at line 66 of file PreferencesDialog.cpp.
References resetValues().
Referenced by PreferencesDialog().
 {
   this->resetValues();
   this->setResult(QMessageBox::Cancel);
   this->close();
 }
void PreferencesDialog::resetValues () private
Definition at line 73 of file PreferencesDialog.cpp.
References _main_window, _osc_port_numbox, and MainWindow::getOscPort().
Referenced by PreferencesDialog(), and reject_cb().
 {
   this->_osc_port_numbox->setValue(this->_main_window->getOscPort());
 }
Member Data Documentation
QSpinBox* PreferencesDialog::_osc_port_numbox private
Definition at line 50 of file PreferencesDialog.h.
Referenced by accept_cb(), PreferencesDialog(), and resetValues().
MainWindow* PreferencesDialog::_main_window private
Definition at line 51 of file PreferencesDialog.h.
Referenced by accept_cb(), PreferencesDialog(), and resetValues().
QDialogButtonBox* PreferencesDialog::_button_box private
Definition at line 52 of file PreferencesDialog.h.
Referenced by PreferencesDialog().
The documentation for this class was generated from the following files:
PreferencesDialog.h
PreferencesDialog.cpp