MapMap: AddShapesCommand Class Reference
AddShapesCommand Class Reference
#include <Commands.h>
Public Member Functions
AddShapesCommand (MainWindow *mainWindow, uid mappingId, QUndoCommand *parent=0)
void undo ()
void redo ()
Private Attributes
MainWindow * m_mainWindow
Mapping::ptr m_mappingPtr
uid m_mappingId
Detailed Description
Definition at line 36 of file Commands.h.
Constructor & Destructor Documentation
AddShapesCommand::AddShapesCommand (MainWindow * mainWindow, uid mappingId, QUndoCommand * parent = 0)
Definition at line 4 of file Commands.cpp.
References m_mainWindow, and m_mappingId.
                                                                                              :
   QUndoCommand(parent)
 {
   setText(QObject::tr("Add mapping"));
   m_mainWindow = mainWindow;
   m_mappingId = mappingId;
 }
Member Function Documentation
void AddShapesCommand::undo ()
Definition at line 12 of file Commands.cpp.
References MainWindow::deleteMapping(), MappingManager::getMappingById(), MainWindow::getMappingManager(), m_mainWindow, m_mappingId, and m_mappingPtr.
 {
   m_mappingPtr = m_mainWindow->getMappingManager().getMappingById(m_mappingId);
   m_mainWindow->deleteMapping(m_mappingId);
 }
void AddShapesCommand::redo ()
Definition at line 18 of file Commands.cpp.
References MappingManager::addMapping(), MainWindow::addMappingItem(), MainWindow::getMappingManager(), m_mainWindow, and m_mappingPtr.
 {
   if(m_mappingPtr != NULL)
     {
       uint currentId = m_mainWindow->getMappingManager().addMapping(m_mappingPtr);
       m_mainWindow->addMappingItem(currentId);
     }
 }
Member Data Documentation
MainWindow* AddShapesCommand::m_mainWindow private
Definition at line 44 of file Commands.h.
Referenced by AddShapesCommand(), redo(), and undo().
Mapping::ptr AddShapesCommand::m_mappingPtr private
Definition at line 45 of file Commands.h.
Referenced by redo(), and undo().
uid AddShapesCommand::m_mappingId private
Definition at line 46 of file Commands.h.
Referenced by AddShapesCommand(), and undo().
The documentation for this class was generated from the following files:
Commands.h
Commands.cpp