MapMap: ProjectReader Class Reference
ProjectReader Class Reference
#include <ProjectReader.h>
Public Member Functions
ProjectReader (MainWindow *window)
bool readFile (QIODevice *device)
QString errorString () const
Private Member Functions
void readProject ()
void parseProject (const QDomElement &project)
void parsePaint (const QDomElement &paint)
void parseMapping (const QDomElement &mapping)
void _parseStandardShape (const QString &type, const QDomElement &shape, QVector< QPointF > &points, int nVertices=-1)
void _parseQuad (const QDomElement &quad, QVector< QPointF > &points)
void _parseTriangle (const QDomElement &triangle, QVector< QPointF > &points)
void _parseMesh (const QDomElement &mesh, QVector< QPointF > &points, int &nColumns, int &nRows)
void _parseEllipse (const QDomElement &ellipse, QVector< QPointF > &points)
QPointF _parseVertex (const QDomElement &vertex)
Private Attributes
QXmlStreamReader _xml
MainWindow * _window
Detailed Description
Definition at line 27 of file ProjectReader.h.
Constructor & Destructor Documentation
ProjectReader::ProjectReader (MainWindow * window)
Definition at line 25 of file ProjectReader.cpp.
                                                : _window(window)
 {
 }
Member Function Documentation
bool ProjectReader::readFile (QIODevice * device)
Definition at line 29 of file ProjectReader.cpp.
References _xml, and parseProject().
Referenced by MainWindow::loadFile().
 {
   QString errorStr;
   int errorLine;
   int errorColumn;
   QDomDocument doc;
   if (!doc.setContent(device, false, &errorStr, &errorLine, &errorColumn)) {
     std::cerr << "Error: Parse error at line " << errorLine << ", "
               << "column " << errorColumn << ": "
               << qPrintable(errorStr) << std::endl;
     return false;
   }
   QDomElement root = doc.documentElement();
   // The handling of the version number will get fancier as we go.
   if (root.tagName() != "project" || root.attribute("version") != "0.1")
   {
     _xml.raiseError(QObject::tr("The file is not a mapmap version 0.1 file."));
     return false;
   }
   parseProject(root);
   return (! _xml.hasError() );
 }
QString ProjectReader::errorString () const
Definition at line 56 of file ProjectReader.cpp.
References _xml.
Referenced by MainWindow::loadFile().
 {
   return QObject::tr("%1\nLine %2, column %3")
     .arg(_xml.errorString())
     .arg(_xml.lineNumber())
     .arg(_xml.columnNumber());
 }
void ProjectReader::readProject () private
void ProjectReader::parseProject (const QDomElement & project) private
Definition at line 65 of file ProjectReader.cpp.
References parseMapping(), and parsePaint().
Referenced by readFile().
 {
   QDomElement paints = project.firstChildElement("paints");
   QDomElement mappings = project.firstChildElement("mappings");
   // Parse paints.
   QDomNode paint = paints.firstChild();
   while (!paint.isNull())
   {
     parsePaint(paint.toElement());
     paint = paint.nextSibling();
   }
   // Parse mappings.
   QDomNode mapping = mappings.firstChild();
   while (!mapping.isNull())
   {
     parseMapping(mapping.toElement());
     mapping = mapping.nextSibling();
   }
 }
void ProjectReader::parsePaint (const QDomElement & paint) private
Definition at line 87 of file ProjectReader.cpp.
References _window, _xml, MainWindow::createColorPaint(), MainWindow::createMediaPaint(), NULL_UID, and MainWindow::renamePaint().
Referenced by parseProject().
 {
   QString paintAttrId   = paint.attribute("id", QString::number(NULL_UID));
   QString paintAttrName = paint.attribute("name", "");
   QString paintAttrType = paint.attribute("type", "");
   if (paintAttrType == "media" || paintAttrType == "image")
   {
     QString uri  = paint.firstChildElement("uri").text();
     QString x    = paint.firstChildElement("x").text();
     QString y    = paint.firstChildElement("y").text();
     QString rate = paint.firstChildElement("rate").text();
     uid id = _window->createMediaPaint(paintAttrId.toInt(), uri, x.toFloat(), y.toFloat(), paintAttrType == "image", false, rate.toDouble());
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create media with uri %1.").arg(uri));
     // Restore Paint name
     if (!paintAttrName.isEmpty())
       _window->renamePaint(id, paintAttrName);
   }
   else if (paintAttrType == "color")
   {
     QString rgb = paint.firstChildElement("rgb").text();
     QColor color(rgb);
     uid id = _window->createColorPaint(paintAttrId.toInt(), color);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create color with RGB hex code %1.").arg(rgb));
     // Restore Paint name
     if (!paintAttrName.isEmpty())
       _window->renamePaint(id, paintAttrName);
   }
   else
     _xml.raiseError(QObject::tr("Unsupported paint type: %1.").arg(paintAttrType));
 }
void ProjectReader::parseMapping (const QDomElement & mapping) private
Definition at line 126 of file ProjectReader.cpp.
References _parseEllipse(), _parseMesh(), _parseQuad(), _parseTriangle(), _window, _xml, MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), NULL_UID, MainWindow::renameMapping(), MainWindow::setMappingLocked(), MainWindow::setMappingSolo(), and MainWindow::setMappingVisible().
Referenced by parseProject().
 {
   uid id = NULL_UID;
   QString mappingAttrId      = mapping.attribute("id", QString::number(NULL_UID));
   QString mappingAttrName    = mapping.attribute("name", "");
   QString mappingAttrPaintId = mapping.attribute("paint_id", QString::number(NULL_UID));
   QString mappingAttrType    = mapping.attribute("type", "");
   bool isLocked = (mapping.attribute("locked", QString::number(1)) == "1");
   bool isSolo = (mapping.attribute("solo", QString::number(1)) == "1");
   bool isVisible = (mapping.attribute("visible", QString::number(1)) == "1");
   // Get destination shape.
   QDomElement dst = mapping.firstChildElement("destination");
   QVector<QPointF> dstPoints;
   if (mappingAttrType == "triangle_texture")
   {
     // Parse destination triangle.
     _parseTriangle(dst, dstPoints);
     // Get / parse source shape.
     QDomElement src = mapping.firstChildElement("source");
     QVector<QPointF> srcPoints;
     _parseTriangle(src, srcPoints);
     id = _window->createTriangleTextureMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), srcPoints, dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create triangle texture mapping"));
   }
   else if (mappingAttrType == "mesh_texture")
   {
     // Parse destination mesh.
     int nColumns;
     int nRows;
     _parseMesh(dst, dstPoints, nColumns, nRows);
     // Get / parse source shape.
     QDomElement src = mapping.firstChildElement("source");
     QVector<QPointF> srcPoints;
     _parseMesh(src, srcPoints, nColumns, nRows);
     id = _window->createMeshTextureMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), nColumns, nRows, srcPoints, dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create mesh texture mapping"));
   }
   else if (mappingAttrType == "ellipse_texture")
   {
     // Parse destination ellipse.
     _parseEllipse(dst, dstPoints);
     // Get / parse source shape.
     QDomElement src = mapping.firstChildElement("source");
     QVector<QPointF> srcPoints;
     _parseEllipse(src, srcPoints);
     id = _window->createEllipseTextureMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), srcPoints, dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create ellipse texture mapping"));
   }
   else if (mappingAttrType == "triangle_color")
   {
     // Parse destination triangle.
     _parseTriangle(dst, dstPoints);
     id = _window->createTriangleColorMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create triangle color mapping"));
   }
   else if (mappingAttrType == "quad_color")
   {
     // Parse destination quad.
     _parseQuad(dst, dstPoints);
     id = _window->createQuadColorMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create quad color mapping"));
   }
   else if (mappingAttrType == "ellipse_color")
   {
     // Parse destination ellipse.
     _parseEllipse(dst, dstPoints);
     id = _window->createEllipseColorMapping(mappingAttrId.toInt(), mappingAttrPaintId.toInt(), dstPoints);
     if (id == NULL_UID)
       _xml.raiseError(QObject::tr("Cannot create ellipse color mapping"));
   }
   else
     _xml.raiseError(QObject::tr("Unsupported mapping type: %1.").arg(mappingAttrType));
   // and then set some more attributes:
   if (id != NULL_UID)
   {
     _window->setMappingVisible(id, isVisible);
     _window->setMappingSolo   (id, isSolo);
     _window->setMappingLocked (id, isLocked);
     if (!mappingAttrName.isEmpty())
       _window->renameMapping(id, mappingAttrName);
   }
 }
void ProjectReader::_parseStandardShape (const QString & type, const QDomElement & shape, QVector< QPointF > & points, int nVertices = -1) private
Definition at line 234 of file ProjectReader.cpp.
References _parseVertex(), and _xml.
Referenced by _parseEllipse(), _parseQuad(), and _parseTriangle().
 {
   // Check that the element is really a triangle.
   QString typeAttr = shape.attribute("shape", "");
   if (typeAttr != type)
     _xml.raiseError(QObject::tr("Wrong shape type \"%1\" for destination: expected \"%2\".").arg(typeAttr).arg(type));
   // Reset list of points.
   points.clear();
   // Add vertices.
   QDomElement vertex = shape.firstChildElement("vertex");
   while (!vertex.isNull())
   {
     points.push_back(_parseVertex(vertex));
     vertex = vertex.nextSiblingElement("vertex");
   }
   if (nVertices >= 0 && points.size() != nVertices)
     _xml.raiseError(QObject::tr("Shape of type '%1' has %2 vertices: expected %3.").arg(type).arg(points.size()).arg(nVertices));
 }
void ProjectReader::_parseQuad (const QDomElement & quad, QVector< QPointF > & points) private
Definition at line 256 of file ProjectReader.cpp.
References _parseStandardShape().
Referenced by parseMapping().
 {
   _parseStandardShape("quad", quad, points, 4);
 }
void ProjectReader::_parseTriangle (const QDomElement & triangle, QVector< QPointF > & points) private
Definition at line 261 of file ProjectReader.cpp.
References _parseStandardShape().
Referenced by parseMapping().
 {
   _parseStandardShape("triangle", triangle, points, 3);
 }
void ProjectReader::_parseMesh (const QDomElement & mesh, QVector< QPointF > & points, int & nColumns, int & nRows) private
Definition at line 273 of file ProjectReader.cpp.
References _parseVertex(), and _xml.
Referenced by parseMapping().
 {
   // Check that the element is really a mash.
   QString type = mesh.attribute("shape", "");
   if (type != "mesh")
     _xml.raiseError(QObject::tr("Wrong shape type for destination: %1.").arg(type));
   // Reset list of points.
   points.clear();
   // Check columns and rows.
   nColumns = mesh.firstChildElement("dimensions").attribute("columns").toInt();
   nRows    = mesh.firstChildElement("dimensions").attribute("rows").toInt();
   // Add vertices.
   QDomElement vertex = mesh.firstChildElement("vertex");
   while (!vertex.isNull())
   {
     points.push_back(_parseVertex(vertex));
     vertex = vertex.nextSiblingElement("vertex");
   }
   if (points.size() != nColumns*nRows)
     _xml.raiseError(QObject::tr("Shape has wrong number of vertices."));
 }
void ProjectReader::_parseEllipse (const QDomElement & ellipse, QVector< QPointF > & points) private
Definition at line 266 of file ProjectReader.cpp.
References _parseStandardShape(), and _xml.
Referenced by parseMapping().
 {
   _parseStandardShape("ellipse", ellipse, points);
   if (points.size() != 4 && points.size() != 5)
     _xml.raiseError(QObject::tr("Shape has %1 vertices: expected 4 or 5.").arg(points.size()));
 }
QPointF ProjectReader::_parseVertex (const QDomElement & vertex) private
Definition at line 300 of file ProjectReader.cpp.
Referenced by _parseMesh(), and _parseStandardShape().
 {
   return QPointF(
       vertex.attribute("x", "0").toFloat(),
       vertex.attribute("y", "0").toFloat()
       );
 }
Member Data Documentation
QXmlStreamReader ProjectReader::_xml private
Definition at line 50 of file ProjectReader.h.
Referenced by _parseEllipse(), _parseMesh(), _parseStandardShape(), errorString(), parseMapping(), parsePaint(), and readFile().
MainWindow* ProjectReader::_window private
Definition at line 51 of file ProjectReader.h.
Referenced by parseMapping(), and parsePaint().
The documentation for this class was generated from the following files:
ProjectReader.h
ProjectReader.cpp