MapMap: Mesh Class Reference
Mesh Class Reference
#include <Shape.h>
Public Types
typedef QSharedPointer< MShape > ptr
Public Member Functions
Mesh ()
Mesh (QPointF p1, QPointF p2, QPointF p3, QPointF p4)
Mesh (const QVector< QPointF > &points, int nColumns, int nRows)
virtual ~Mesh ()
void init (const QVector< QPointF > &points, int nColumns, int nRows)
virtual QString getType () const
virtual QPolygonF toPolygon () const
Returns a polygon that is formed by all the contour points of the mesh.
virtual void setVertex (int i, const QPointF &v)
QPointF getVertex2d (int i, int j) const
void setVertex2d (int i, int j, const QPointF &v)
void setVertex2d (int i, int j, double x, double y)
void resizeVertices2d (IndexVector2d &vertices2d, int nColumns, int nRows)
void addColumn ()
void addRow ()
void removeColumn (int columnId)
void removeRow (int rowId)
void resize (int nColumns_, int nRows_)
QVector< Quad > getQuads () const
QVector< QVector< Quad > > getQuads2d () const
int nColumns () const
int nRows () const
int nHorizontalQuads () const
int nVerticalQuads () const
virtual bool includesPoint (const QPointF &p)
virtual bool includesPoint (qreal x, qreal y)
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
virtual void setVertex (int i, qreal x, qreal y)
virtual void build ()
int nVertices () const
QPointF getVertex (int i) const
virtual void translate (const QPointF &offset)
Translate all vertices of shape by the vector (x,y).
virtual void copyFrom (const MShape &shape)
virtual MShape * clone () const
Protected Member Functions
void _reorderVertices ()
Reorder vertices in a standard order:
virtual MShape * _create () const
Returns a new MShape (using default constructor).
QVector< QLineF > _getSegments () const
Returns all line segments of the polygon.
void _addVertex (const QPointF &vertex)
void _rawSetVertex (int i, const QPointF &v)
Static Protected Member Functions
static QVector< QLineF > _getSegments (const QPolygonF &polygon)
Returns all line segments of a polygon.
static void _constrainVertex (const QPolygonF &polygon, int i, QPointF &v)
Makes sure vertex v as the i-th point of polygon stays inside the polygon.
Protected Attributes
int _nColumns
int _nRows
IndexVector2d _vertices2d
QVector< QPointF > vertices
Private Types
typedef QVector< QVector< int > > IndexVector2d
Detailed Description
Definition at line 183 of file Shape.h.
Member Typedef Documentation
typedef QVector<QVector<int> > Mesh::IndexVector2d private
Definition at line 185 of file Shape.h.
typedef QSharedPointer<MShape> MShape::ptr inherited
Definition at line 47 of file Shape.h.
Constructor & Destructor Documentation
Mesh::Mesh ()
Definition at line 130 of file Shape.cpp.
Referenced by _create().
 : Quad(), _nColumns(0), _nRows(0) {}
Mesh::Mesh (QPointF p1, QPointF p2, QPointF p3, QPointF p4)
Definition at line 132 of file Shape.cpp.
References init().
                                                          : Quad()
 {
   // Add points in standard order.
   QVector<QPointF> points;
   points.push_back(p1);
   points.push_back(p2);
   points.push_back(p4);
   points.push_back(p3);
   // Init.
   init(points, 2, 2);
 }
Mesh::Mesh (const QVector< QPointF > & points, int nColumns, int nRows)
Definition at line 145 of file Shape.cpp.
References init().
                                                                   : Quad()
 {
   init(points, nColumns, nRows);
 }
virtual Mesh::~Mesh () virtual
Definition at line 197 of file Shape.h.
 {}
Member Function Documentation
void Mesh::init (const QVector< QPointF > & points, int nColumns, int nRows)
Definition at line 150 of file Shape.cpp.
References _nColumns, _nRows, _vertices2d, nColumns(), nRows(), resizeVertices2d(), and MShape::vertices.
Referenced by Mesh().
 {
   Q_ASSERT(nColumns >= 2 && nRows >= 2);
   Q_ASSERT(points.size() == nColumns * nRows);
   _nColumns = nColumns;
   _nRows    = nRows;
   // Resize the vertices2d vector to appropriate dimensions.
   resizeVertices2d(_vertices2d, _nColumns, _nRows);
   // Just build vertices2d in the standard order.
   int k = 0;
   for (int y=0; y<_nRows; y++)
     for (int x=0; x<_nColumns; x++)
     {
       vertices.push_back( points[k] );
       _vertices2d[x][y] = k;
       k++;
     }
 }
virtual QString Mesh::getType () const virtual
Reimplemented from Quad.
Definition at line 202 of file Shape.h.
 { return "mesh"; }
QPolygonF Mesh::toPolygon () const virtual
Returns a polygon that is formed by all the contour points of the mesh.
Reimplemented from Polygon.
Definition at line 172 of file Shape.cpp.
References getVertex2d(), nColumns(), and nRows().
Referenced by MeshControlPainter::_paintShape(), and Util::drawControlsMesh().
 {
   QPolygonF polygon;
   for (int i=0; i<nColumns(); i++)
     polygon.append(getVertex2d(i, 0));
   for (int i=0; i<nRows(); i++)
     polygon.append(getVertex2d(nColumns()-1, i));
   for (int i=nColumns()-1; i>=0; i--)
     polygon.append(getVertex2d(i, nRows()-1));
   for (int i=nRows()-1; i>=1; i--)
     polygon.append(getVertex2d(0, i));
   return polygon;
 }
void Mesh::setVertex (int i, const QPointF & v) virtual
Reimplemented from Polygon.
Definition at line 186 of file Shape.cpp.
References Polygon::_constrainVertex(), MShape::_rawSetVertex(), getVertex2d(), nColumns(), nRows(), and Polygon::toPolygon().
 {
   // Extract column and row of vertex.
   int col = i % nColumns();
   int row = i / nColumns();
   // Make a copy.
   QPointF realV = v;
   // Constrain vertex to stay within the internal quads it is part of.
   if (col < nColumns()-1)
   {
     if (row < nRows() - 1)
     {
       Quad quad(getVertex2d(col, row), getVertex2d(col+1, row), getVertex2d(col+1, row+1), getVertex2d(col, row+1));
       _constrainVertex(quad.toPolygon(), 0, realV);
     }
     if (row > 0)
     {
       Quad quad(getVertex2d(col, row), getVertex2d(col+1, row), getVertex2d(col+1, row-1), getVertex2d(col, row-1));
       _constrainVertex(quad.toPolygon(), 0, realV);
     }
   }
   if (col > 0)
   {
     if (row < nRows() - 1)
     {
       Quad quad(getVertex2d(col, row), getVertex2d(col-1, row), getVertex2d(col-1, row+1), getVertex2d(col, row+1));
       _constrainVertex(quad.toPolygon(), 0, realV);
     }
     if (row > 0)
     {
       Quad quad(getVertex2d(col, row), getVertex2d(col-1, row), getVertex2d(col-1, row-1), getVertex2d(col, row-1));
       _constrainVertex(quad.toPolygon(), 0, realV);
     }
   }
   // Do set vertex.
   _rawSetVertex(i, realV);
 }
QPointF Mesh::getVertex2d (int i, int j) const
Definition at line 210 of file Shape.h.
References _vertices2d, and MShape::vertices.
Referenced by _reorderVertices(), addColumn(), addRow(), getQuads(), getQuads2d(), removeColumn(), removeRow(), setVertex(), and toPolygon().
   {
     return vertices[_vertices2d[i][j]];
   }
void Mesh::setVertex2d (int i, int j, const QPointF & v)
Definition at line 215 of file Shape.h.
References _vertices2d, and MShape::vertices.
   {
     vertices[_vertices2d[i][j]] = v; // copy
   }
void Mesh::setVertex2d (int i, int j, double x, double y)
Definition at line 220 of file Shape.h.
References _vertices2d, and MShape::vertices.
   {
     vertices[_vertices2d[i][j]] = QPointF(x, y);
   }
void Mesh::resizeVertices2d (IndexVector2d & vertices2d, int nColumns, int nRows)
Definition at line 227 of file Shape.cpp.
References nColumns(), and resize().
Referenced by addColumn(), addRow(), init(), removeColumn(), and removeRow().
 {
   vertices2d.resize(nColumns);
   for (int i=0; i<nColumns; i++)
     vertices2d[i].resize(nRows);
 }
void Mesh::addColumn ()
Definition at line 255 of file Shape.cpp.
References MShape::_addVertex(), _nColumns, MShape::_rawSetVertex(), _reorderVertices(), _vertices2d, getVertex2d(), nColumns(), nRows(), MShape::nVertices(), and resizeVertices2d().
Referenced by resize().
 {
   // Create new vertices 2d (temporary).
   IndexVector2d newVertices2d;
   resizeVertices2d(newVertices2d, nColumns()+1, nRows());
   // Left displacement of points already there.
   qreal leftMoveProp = 1.0f/(nColumns()-1) - 1.0f/nColumns();
   // Add a point at each row.
   int k = nVertices();
   for (int y=0; y<nRows(); y++)
   {
     // Get left and right vertices.
     QPointF left  = getVertex2d( 0,            y );
     QPointF right = getVertex2d( nColumns()-1, y );
     QPointF diff  = right - left;
     // First pass: move middle points.
     for (int x=1; x<nColumns()-1; x++)
     {
       QPointF p = getVertex2d(x, y);
       p -= diff * x * leftMoveProp;
       _rawSetVertex( _vertices2d[x][y], p );
     }
     // Create and add new point.
     QPointF newPoint = right - diff * 1.0f/nColumns();
     _addVertex(newPoint);
     // Assign new vertices 2d.
     for (int x=0; x<nColumns()-1; x++)
       newVertices2d[x][y] = _vertices2d[x][y];
     // The new point.
     newVertices2d[nColumns()-1][y] = k;
     // The rightmost point.
     newVertices2d[nColumns()][y]   = _vertices2d[nColumns()-1][y];
     k++;
   }
   // Copy new mapping.
   _vertices2d = newVertices2d;
   // Increment number of columns.
   _nColumns++;
   // Reorder.
   _reorderVertices();
 }
void Mesh::addRow ()
Definition at line 308 of file Shape.cpp.
References MShape::_addVertex(), _nRows, MShape::_rawSetVertex(), _reorderVertices(), _vertices2d, getVertex2d(), nColumns(), nRows(), MShape::nVertices(), and resizeVertices2d().
Referenced by resize().
 {
   // Create new vertices 2d (temporary).
   IndexVector2d newVertices2d;
   resizeVertices2d(newVertices2d, nColumns(), nRows()+1);
   // Top displacement of points already there.
   qreal topMoveProp = 1.0f/(nRows()-1) - 1.0f/nRows();
   // Add a point at each row.
   int k = nVertices();
   for (int x=0; x<nColumns(); x++)
   {
     // Get left and right vertices.
     QPointF top    = getVertex2d(x, 0);
     QPointF bottom = getVertex2d(x, nRows()-1);
     QPointF diff   = bottom - top;
     // First pass: move middle points.
     for (int y=1; y<nRows()-1; y++)
     {
       QPointF p = getVertex2d(x, y);
       p -= diff * y * topMoveProp;
       _rawSetVertex( _vertices2d[x][y], p );
     }
     // Create and add new point.
     QPointF newPoint = bottom - diff * 1.0f/nRows();
     _addVertex(newPoint);
     // Assign new vertices 2d.
     for (int y=0; y<nRows()-1; y++)
       newVertices2d[x][y] = _vertices2d[x][y];
     // The new point.
     newVertices2d[x][nRows()-1] = k;
     // The rightmost point.
     newVertices2d[x][nRows()]   = _vertices2d[x][nRows()-1];
     k++;
   }
   // Copy new mapping.
   _vertices2d = newVertices2d;
   // Increment number of columns.
   _nRows++;
   // Reorder.
   _reorderVertices();
 }
void Mesh::removeColumn (int columnId)
Definition at line 361 of file Shape.cpp.
References _nColumns, _reorderVertices(), _vertices2d, getVertex2d(), nColumns(), nRows(), resizeVertices2d(), and MShape::vertices.
Referenced by resize().
 {
   // Cannot remove first and last columns
   Q_ASSERT(columnId >= 1 && columnId < nColumns()-1);
   // Temporary containers that will be used to rebuild new vertex space.
   IndexVector2d newVertices2d;
   resizeVertices2d(newVertices2d, nColumns()-1, nRows());
   QVector<QPointF> newVertices(vertices.size()-nRows());
   // Right displacement of points already there.
   qreal rightMoveProp = 1.0f/(nColumns()-2) - 1.0f/(nColumns()-1);
   // Process all rows.
   int k = 0;
   for (int y=0; y<nRows(); y++)
   {
     // Get left and right vertices.
     QPointF left  = getVertex2d( 0,            y );
     QPointF right = getVertex2d( nColumns()-1, y );
     QPointF diff  = right - left;
     // Move all columns.
     for (int x=0; x<nColumns(); x++)
     {
       // Ignore points from target column.
       if (x == columnId)
         continue;
       // Get current vertex.
       QPointF p = getVertex2d( x, y );
       // The x value of this point in the new space.
       int newX = x < columnId ? x : x-1;
       // Move middle points.
       if (x > 0 && x < nColumns()-1)
       {
         p += (x < columnId ? +1 : -1) * diff * newX * rightMoveProp;
       }
       // Assign new containers.
       newVertices[k]         = p;
       newVertices2d[newX][y] = k;
       k++;
     }
   }
   // Copy new mapping.
   vertices    = newVertices;
   _vertices2d = newVertices2d;
   // Decrement number of columns.
   _nColumns--;
   // Reorder.
   _reorderVertices();
 }
void Mesh::removeRow (int rowId)
Definition at line 421 of file Shape.cpp.
References _nRows, _reorderVertices(), _vertices2d, getVertex2d(), nColumns(), nRows(), resizeVertices2d(), and MShape::vertices.
Referenced by resize().
 {
   // Cannot remove first and last columns
   Q_ASSERT(rowId >= 1 && rowId < nRows()-1);
   // Temporary containers that will be used to rebuild new vertex space.
   IndexVector2d newVertices2d;
   resizeVertices2d(newVertices2d, nColumns(), nRows()-1);
   QVector<QPointF> newVertices(vertices.size()-nColumns());
   // Bottom displacement of points already there.
   qreal bottomMoveProp = 1.0f/(nRows()-2) - 1.0f/(nRows()-1);
   // Process all columns.
   int k = 0;
   for (int x=0; x<nColumns(); x++)
   {
     // Get top and bottom vertices.
     QPointF top    = getVertex2d(x, 0);
     QPointF bottom = getVertex2d(x, nRows()-1);
     QPointF diff   = bottom - top;
     // Move all rows.
     for (int y=0; y<nRows(); y++)
     {
       // Ignore points from target row.
       if (y == rowId)
         continue;
       // Get current vertex.
       QPointF p = getVertex2d( x, y );
       // The y value of this point in the new space.
       int newY = y < rowId ? y : y-1;
       // Move middle points.
       if (y > 0 && y < nRows()-1)
       {
         p += (y < rowId ? +1 : -1) * diff * newY * bottomMoveProp;
       }
       // Assign new containers.
       newVertices[k]         = p;
       newVertices2d[x][newY] = k;
       k++;
     }
   }
   // Copy new mapping.
   vertices    = newVertices;
   _vertices2d = newVertices2d;
   // Decrement number of rows.
   _nRows--;
   // Reorder.
   _reorderVertices();
 }
void Mesh::resize (int nColumns_, int nRows_)
Definition at line 482 of file Shape.cpp.
References addColumn(), addRow(), nColumns(), nRows(), removeColumn(), and removeRow().
Referenced by resizeVertices2d().
 {
   // Brutal: if asked to reduce columns or rows, just delete and redo.
   if (nColumns_ < nColumns())
   {
     while (nColumns_ != nColumns())
       removeColumn(nColumns()-2);
   }
   if (nRows_ < nRows())
   {
     while (nRows_ != nRows())
       removeRow(nRows()-2);
   }
   if (nColumns_ > nColumns())
   {
     while (nColumns_ != nColumns())
       addColumn();
   }
   if (nRows_ > nRows())
   {
     while (nRows_ != nRows())
       addRow();
   }
 }
QVector< Quad > Mesh::getQuads () const
Definition at line 506 of file Shape.cpp.
References getVertex2d(), nHorizontalQuads(), and nVerticalQuads().
Referenced by MeshControlPainter::_paintShape(), and Util::drawControlsMesh().
 {
   QVector<Quad> quads;
   for (int i=0; i<nHorizontalQuads(); i++)
   {
     for (int j=0; j<nVerticalQuads(); j++)
     {
       Quad quad(
           getVertex2d(i,   j  ),
           getVertex2d(i+1, j  ),
           getVertex2d(i+1, j+1),
           getVertex2d(i,   j+1)
       );
       quads.push_back(quad);
     }
   }
   return quads;
 }
QVector< QVector< Quad > > Mesh::getQuads2d () const
Definition at line 526 of file Shape.cpp.
References getVertex2d(), nHorizontalQuads(), and nVerticalQuads().
 {
   QVector< QVector<Quad> > quads2d;
   for (int i=0; i<nHorizontalQuads(); i++)
   {
     QVector<Quad> column;
     for (int j=0; j<nVerticalQuads(); j++)
     {
       Quad quad(
           getVertex2d(i,   j  ),
           getVertex2d(i+1, j  ),
           getVertex2d(i+1, j+1),
           getVertex2d(i,   j+1)
       );
       column.push_back(quad);
     }
     quads2d.push_back(column);
   }
   return quads2d;
 }
int Mesh::nColumns () const
Definition at line 239 of file Shape.h.
References _nColumns.
Referenced by _reorderVertices(), addColumn(), addRow(), init(), removeColumn(), removeRow(), resize(), resizeVertices2d(), setVertex(), toPolygon(), and ProjectWriter::writeShapeVertices().
 { return _nColumns; }
int Mesh::nRows () const
Definition at line 240 of file Shape.h.
References _nRows.
Referenced by _reorderVertices(), addColumn(), addRow(), init(), removeColumn(), removeRow(), resize(), setVertex(), toPolygon(), and ProjectWriter::writeShapeVertices().
 { return _nRows; }
int Mesh::nHorizontalQuads () const
Definition at line 242 of file Shape.h.
References _nColumns.
Referenced by getQuads(), and getQuads2d().
 { return _nColumns-1; }
int Mesh::nVerticalQuads () const
Definition at line 243 of file Shape.h.
References _nRows.
Referenced by getQuads(), and getQuads2d().
 { return _nRows-1; }
void Mesh::_reorderVertices () protected
Reorder vertices in a standard order:
0-—1-—2-—3 | | | | 4-—5-—6-—7 | | | | 8-—9—10-—11
Definition at line 547 of file Shape.cpp.
References _vertices2d, getVertex2d(), nColumns(), nRows(), and MShape::vertices.
Referenced by addColumn(), addRow(), removeColumn(), and removeRow().
 {
   // Populate new vertices vector.
   QVector<QPointF> newVertices(vertices.size());
   int k = 0;
   for (int y=0; y<nRows(); y++)
     for (int x=0; x<nColumns(); x++)
       newVertices[k++] = getVertex2d( x, y );
   // Populate _vertices2d.
   k = 0;
   for (int y=0; y<nRows(); y++)
     for (int x=0; x<nColumns(); x++)
       _vertices2d[x][y] = k++;
   // Copy.
   vertices = newVertices;
 }
virtual MShape* Mesh::_create () const protected virtual
Returns a new MShape (using default constructor).
Reimplemented from Quad.
Definition at line 264 of file Shape.h.
References Mesh().
 { return new Mesh(); }
virtual bool Polygon::includesPoint (const QPointF & p) virtual inherited
Implements MShape.
Definition at line 121 of file Shape.h.
References Polygon::toPolygon().
{
     return toPolygon().containsPoint(p, Qt::OddEvenFill);
   }
virtual bool MShape::includesPoint (qreal x, qreal y) virtual inherited
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
Reimplemented in Ellipse.
Definition at line 80 of file Shape.h.
{
     return includesPoint(QPoint(x, y));
   }
virtual void MShape::setVertex (int i, qreal x, qreal y) virtual inherited
Definition at line 69 of file Shape.h.
References MShape::setVertex().
   {
     setVertex(i, QPointF(x, y));
   }
QVector< QLineF > Polygon::_getSegments () const protected inherited
Returns all line segments of the polygon.
Definition at line 106 of file Shape.cpp.
References Polygon::toPolygon().
Referenced by Polygon::_constrainVertex().
 {
   return _getSegments(toPolygon());
 }
QVector< QLineF > Polygon::_getSegments (const QPolygonF & polygon) static protected inherited
Returns all line segments of a polygon.
Definition at line 111 of file Shape.cpp.
 {
   QVector<QLineF> segments;
   for (int i=0; i<polygon.size(); i++)
     segments.push_back(QLineF(polygon.at(i), polygon.at( (i+1) % polygon.size() )));
   return segments;
 }
void Polygon::_constrainVertex (const QPolygonF & polygon, int i, QPointF & v) static protected inherited
Makes sure vertex v as the i-th point of polygon stays inside the polygon.
Definition at line 50 of file Shape.cpp.
References Polygon::_getSegments(), and wrapAround().
Referenced by Polygon::setVertex(), and setVertex().
 {
   // Weird, but nothing to do.
   if (polygon.size() <= 3)
     return;
   // Save previous position of vertex.
   QPointF prevV = polygon.at(i);
   // Look at the two adjunct segments to vertex i and see if they
   // intersect with any non-adjacent segments.
   // Construct the list of segments (with the new candidate vertex).
   QVector<QLineF> segments = _getSegments(polygon);
   int prev = wrapAround(i - 1, segments.size());
   int next = wrapAround(i + 1, segments.size());
   segments[prev] = QLineF(polygon.at(prev), v);
   segments[i]    = QLineF(v, polygon.at(next));
   // We now stretch segments a little bit to cope with approximation errors.
   for (QVector<QLineF>::Iterator it = segments.begin(); it != segments.end(); ++it)
   {
     QLineF& seg = *it;
     QPointF p1 = seg.p1();
     QPointF p2 = seg.p2();
     seg.setP1( p1 + (p1 - p2) * 0.35f);
     seg.setP2( p2 + (p2 - p1) * 0.35f);
   }
   // For each adjunct segment.
   for (int adj=0; adj<2; adj++)
   {
     int idx = wrapAround(i + adj - 1, segments.size());
     for (int j=0; j<segments.size(); j++)
     {
       // If the segment to compare to is valid (ie. if it is not
       // the segment itself nor an adjacent one) then check for
       // intersection.
       if (j != idx &&
           j != wrapAround(idx-1, segments.size()) &&
           j != wrapAround(idx+1, segments.size()))
       {
         QPointF intersection;
         if (segments[idx].intersect(segments[j], &intersection) == QLineF::BoundedIntersection)
         {
           // Rearrange segments with new position at intersection point.
           v = intersection;
           segments[prev] = QLineF(polygon.at(prev), v);
           segments[i]    = QLineF(v, polygon.at(next));
         }
       }
     }
   }
 }
virtual void MShape::build () virtual inherited
Definition at line 55 of file Shape.h.
 {}
int MShape::nVertices () const inherited
Definition at line 57 of file Shape.h.
References MShape::vertices.
Referenced by MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MappingGui::_updateShapeProperty(), addColumn(), addRow(), Util::drawControlsVertices(), Ellipse::hasCenterControl(), and ProjectWriter::writeShapeVertices().
 { return vertices.size(); }
QPointF MShape::getVertex (int i) const inherited
Definition at line 59 of file Shape.h.
References MShape::vertices.
Referenced by MeshTextureGraphicsItem::_buildCacheQuadItem(), MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MeshTextureGraphicsItem::_split(), MappingGui::_updateShapeProperty(), Util::drawControlsVertices(), Ellipse::getCenter(), Ellipse::getHorizontalAxis(), Ellipse::getVerticalAxis(), Ellipse::sanitize(), MappingGui::setValue(), Ellipse::setVertex(), and ProjectWriter::writeShapeVertices().
   {
     return vertices[i];
   }
void MShape::translate (const QPointF & offset) virtual inherited
Translate all vertices of shape by the vector (x,y).
Definition at line 34 of file Shape.cpp.
References MShape::vertices.
 {
   // We can feel free to translate every vertex without check by default.
   for (QVector<QPointF>::iterator it = vertices.begin(); it != vertices.end(); ++it)
     *it += offset;
 }
void MShape::copyFrom (const MShape & shape) virtual inherited
Definition at line 22 of file Shape.cpp.
References MShape::vertices.
Referenced by MShape::clone().
 {
   // Just copy vertices.
   vertices = shape.vertices;
 }
MShape * MShape::clone () const virtual inherited
Definition at line 28 of file Shape.cpp.
References MShape::_create(), and MShape::copyFrom().
{
   MShape* copyShape = _create();
   copyShape->copyFrom(*this);
   return copyShape;
 }
void MShape::_addVertex (const QPointF & vertex) protected inherited
Definition at line 96 of file Shape.h.
Referenced by addColumn(), addRow(), Ellipse::Ellipse(), Quad::Quad(), and Triangle::Triangle().
   {
     vertices.push_back(vertex);
   }
void MShape::_rawSetVertex (int i, const QPointF & v) protected inherited
Definition at line 101 of file Shape.h.
Referenced by addColumn(), addRow(), MShape::setVertex(), Polygon::setVertex(), setVertex(), and Ellipse::setVertex().
   {
     vertices[i] = v;
   }
Member Data Documentation
int Mesh::_nColumns protected
Definition at line 247 of file Shape.h.
Referenced by addColumn(), init(), nColumns(), nHorizontalQuads(), and removeColumn().
int Mesh::_nRows protected
Definition at line 248 of file Shape.h.
Referenced by addRow(), init(), nRows(), nVerticalQuads(), and removeRow().
IndexVector2d Mesh::_vertices2d protected
Definition at line 250 of file Shape.h.
Referenced by _reorderVertices(), addColumn(), addRow(), getVertex2d(), init(), removeColumn(), removeRow(), and setVertex2d().
QVector<QPointF> MShape::vertices protected inherited
Definition at line 94 of file Shape.h.
Referenced by _reorderVertices(), MShape::copyFrom(), MShape::getVertex(), getVertex2d(), init(), MShape::nVertices(), removeColumn(), removeRow(), setVertex2d(), Polygon::toPolygon(), and MShape::translate().
The documentation for this class was generated from the following files:
Shape.h
Shape.cpp