MapMap: UidAllocator Class Reference
UidAllocator Class Reference
Allocates uids for instances by appending an incremental number to a given string.
#include <UidAllocator.h>
Public Member Functions
uid allocate ()
bool free (uid id)
bool reserve (uid id)
bool exists (uid id) const
std::vector< uid > list () const
Private Attributes
std::vector< uid > _ids
Detailed Description
Allocates uids for instances by appending an incremental number to a given string.
Manages a pool of unique names.
Definition at line 42 of file UidAllocator.h.
Member Function Documentation
uid UidAllocator::allocate ()
Definition at line 26 of file UidAllocator.cpp.
References _ids, and exists().
Referenced by Mapping::Mapping(), and Paint::Paint().
 {
   // Iterate until we find an id that has not been taken.
   uid id = 0;
   while (exists(id))
     id++;
   // Add id to the list.
   _ids.push_back(id);
   // Return it.
   return id;
 }
bool UidAllocator::free (uid id)
Definition at line 51 of file UidAllocator.cpp.
References _ids.
Referenced by Mapping::~Mapping(), and Paint::~Paint().
 {
   std::vector<uid>::iterator it = std::find(_ids.begin(), _ids.end(), id);
   if (it != _ids.end())
   {
     _ids.erase(it);
     return true;
   }
   else
     return false;
 }
bool UidAllocator::reserve (uid id)
Definition at line 40 of file UidAllocator.cpp.
References _ids, and exists().
Referenced by Mapping::Mapping(), and Paint::Paint().
 {
   if (exists(id))
     return false;
   else
   {
     _ids.push_back(id);
     return true;
   }
 }
bool UidAllocator::exists (uid id) const
Definition at line 63 of file UidAllocator.cpp.
References _ids.
Referenced by allocate(), Mapping::Mapping(), Paint::Paint(), and reserve().
 {
   return ( std::find(_ids.begin(), _ids.end(), id) != _ids.end() );
 }
std::vector<uid> UidAllocator::list () const
Definition at line 49 of file UidAllocator.h.
References _ids.
 { return _ids; }
Member Data Documentation
std::vector<uid> UidAllocator::_ids private
Definition at line 52 of file UidAllocator.h.
Referenced by allocate(), exists(), free(), list(), and reserve().
The documentation for this class was generated from the following files:
UidAllocator.h
UidAllocator.cpp