MapMap: EllipseTextureGraphicsItem Class Reference
EllipseTextureGraphicsItem Class Reference
Graphics item for textured mesh.
#include <ShapeGraphicsItem.h>
Classes
class DrawingData
Public Types
typedef QSharedPointer
< ShapeGraphicsItem > ptr
Public Member Functions
EllipseTextureGraphicsItem (Mapping::ptr mapping, bool output=true)
virtual ~EllipseTextureGraphicsItem ()
virtual QPainterPath shape () const
virtual QRectF boundingRect () const
Returns the bounding rectangle of this item.
virtual void _doDrawOutput (QPainter *painter)
MShape::ptr getShape () const
Returns the MShape (depends on mapping and whether this is an input or output).
Mapping::ptr getMapping () const
Returns the mapping.
QSharedPointer
< ShapeControlPainter > getControlPainter ()
Returns the control painter (see below).
bool isOutput () const
Return whether the item is in the destination/output (true) or source/input (false).
MapperGLCanvas * getCanvas () const
Returns pointer to GL canvas.
bool isMappingCurrent () const
Returns whether the mapping this shape is associated with is currently selected.
bool isMappingVisible () const
Returns whether the mapping this shape is associated should be visible.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Built-in function: paints the shape.
QPen getRescaledShapeStroke (bool innerStroke=false)
Utility function: returns a stroke with rescaled width such that the stroke appears invariant to the zoom level (to be used in paint functions).
Static Public Member Functions
static void _setPointOfEllipseAtAngle (QPointF &point, const QPointF &center, float hRadius, float vRadius, float rotation, float circularAngle)
Protected Member Functions
virtual void _doPaint (QPainter *painter, const QStyleOptionGraphicsItem *option)
Main paint function that needs to be overriden (called by paint()).
void _prePaint (QPainter *painter, const QStyleOptionGraphicsItem *option)
Can be overriden to perform operations before _doPaint() is called.
void _postPaint (QPainter *painter, const QStyleOptionGraphicsItem *option)
Can be overriden to perform operations after _doPaint() is called.
virtual void _doDrawInput (QPainter *painter)
Protected Attributes
QWeakPointer< TextureMapping > _textureMapping
QWeakPointer< Texture > _texture
QWeakPointer< MShape > _inputShape
QWeakPointer< Mapping > _mapping
QWeakPointer< MShape > _shape
QSharedPointer
< ShapeControlPainter > _controlPainter
bool _output
Static Private Attributes
static const int N_QUARTERS = 4
Detailed Description
Graphics item for textured mesh.
Definition at line 251 of file ShapeGraphicsItem.h.
Member Typedef Documentation
typedef QSharedPointer<ShapeGraphicsItem> ShapeGraphicsItem::ptr inherited
Definition at line 51 of file ShapeGraphicsItem.h.
Constructor & Destructor Documentation
EllipseTextureGraphicsItem::EllipseTextureGraphicsItem (Mapping::ptr mapping, bool output = true)
Definition at line 517 of file ShapeGraphicsItem.cpp.
References ShapeGraphicsItem::_controlPainter.
                                                                                       : TextureGraphicsItem(mapping, output) {
   _controlPainter.reset(new EllipseControlPainter(this));
 }
virtual EllipseTextureGraphicsItem::~EllipseTextureGraphicsItem () virtual
Definition at line 271 of file ShapeGraphicsItem.h.
 {}
Member Function Documentation
QPainterPath EllipseTextureGraphicsItem::shape () const virtual
Definition at line 521 of file ShapeGraphicsItem.cpp.
References ShapeGraphicsItem::_shape, Ellipse::getCenter(), Ellipse::getHorizontalRadius(), Ellipse::getRotation(), and Ellipse::getVerticalRadius().
Referenced by boundingRect().
 {
   // Create path for ellipse.
   QPainterPath path;
   Ellipse* ellipse = static_cast<Ellipse*>(_shape.data());
   Q_ASSERT(ellipse);
   QTransform transform;
   transform.translate(ellipse->getCenter().x(), ellipse->getCenter().y());
   transform.rotate(ellipse->getRotation());
   path.addEllipse(QPoint(0,0), ellipse->getHorizontalRadius(), ellipse->getVerticalRadius());
   return mapFromScene(transform.map(path));
 }
QRectF EllipseTextureGraphicsItem::boundingRect () const virtual
Returns the bounding rectangle of this item.
Reimplemented from ShapeGraphicsItem.
Definition at line 534 of file ShapeGraphicsItem.cpp.
References shape().
 {
   return shape().boundingRect();
 }
void EllipseTextureGraphicsItem::_doDrawOutput (QPainter * painter) virtual
Implements TextureGraphicsItem.
Definition at line 539 of file ShapeGraphicsItem.cpp.
References TextureGraphicsItem::_inputShape, ShapeGraphicsItem::_shape, TextureGraphicsItem::_texture, EllipseTextureGraphicsItem::DrawingData::controlCenter, MM::ELLIPSE_N_TRIANGLES, EllipseTextureGraphicsItem::DrawingData::getSpanInQuarter(), N_QUARTERS, EllipseTextureGraphicsItem::DrawingData::quarterAngles, Util::setGlTexPoint(), and EllipseTextureGraphicsItem::DrawingData::setPointOfEllipseAtAngle().
 {
   Q_UNUSED(painter);
   // Get input and output ellipses.
   QSharedPointer<Ellipse> inputEllipse  = qSharedPointerCast<Ellipse>(_inputShape);
   QSharedPointer<Ellipse> outputEllipse = qSharedPointerCast<Ellipse>(_shape);
   QSharedPointer<Texture> texture = _texture.toStrongRef();
   // Data for calculating drawing.
   DrawingData inputData(inputEllipse);
   DrawingData outputData(outputEllipse);
   // Points that contain the triangle positions on the border of the ellipse.
   QPointF currentInputPoint;
   QPointF prevInputPoint(0, 0);
   QPointF currentOutputPoint;
   QPointF prevOutputPoint(0, 0);
   // Draw each quarter of the ellipse.
   for (int i=0; i<N_QUARTERS; i++)
   {
     // Total angle range of current quarter.
     float inputAngleSpanInQuarter  = inputData.getSpanInQuarter(i);
     float outputAngleSpanInQuarter = outputData.getSpanInQuarter(i);
     // N. triangles (computed according to output).
     int nTrianglesInQuarter  = ceil(outputAngleSpanInQuarter / (2*M_PI) * MM::ELLIPSE_N_TRIANGLES);
     // Angle per triangle.
     float inputAnglePerTriangle  = inputAngleSpanInQuarter / nTrianglesInQuarter;
     float outputAnglePerTriangle = outputAngleSpanInQuarter / nTrianglesInQuarter;
     float inputAngle  = inputData.quarterAngles[i];
     float outputAngle = outputData.quarterAngles[i];
     for (int j=0; j<=nTrianglesInQuarter; j++, inputAngle += inputAnglePerTriangle, outputAngle += outputAnglePerTriangle)
     {
       // Set next (current) points.
       inputData.setPointOfEllipseAtAngle(currentInputPoint, inputAngle);
       outputData.setPointOfEllipseAtAngle(currentOutputPoint, outputAngle);
       if (j > 0) // We don't draw the first triangle.
       {
         // Draw triangle.
         glBegin(GL_TRIANGLES);
         Util::setGlTexPoint(*texture, inputData.controlCenter, outputData.controlCenter);
         Util::setGlTexPoint(*texture, prevInputPoint,     prevOutputPoint);
         Util::setGlTexPoint(*texture, currentInputPoint,  currentOutputPoint);
         glEnd();
       }
       // Save point for next iteration.
       prevInputPoint.setX(currentInputPoint.x());
       prevInputPoint.setY(currentInputPoint.y());
       prevOutputPoint.setX(currentOutputPoint.x());
       prevOutputPoint.setY(currentOutputPoint.y());
     }
   }
 }
static void EllipseTextureGraphicsItem::_setPointOfEllipseAtAngle (QPointF & point, const QPointF & center, float hRadius, float vRadius, float rotation, float circularAngle) static
void TextureGraphicsItem::_doPaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected virtual inherited
Main paint function that needs to be overriden (called by paint()).
Implements ShapeGraphicsItem.
Definition at line 188 of file ShapeGraphicsItem.cpp.
References TextureGraphicsItem::_doDrawInput(), TextureGraphicsItem::_doDrawOutput(), and ShapeGraphicsItem::isOutput().
 {
   Q_UNUSED(option);
   // Perform the actual mapping (done by subclasses).
   if (isOutput())
     _doDrawOutput(painter);
   else
     _doDrawInput(painter);
 }
void TextureGraphicsItem::_prePaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected virtual inherited
Can be overriden to perform operations before _doPaint() is called.
Reimplemented from ShapeGraphicsItem.
Definition at line 225 of file ShapeGraphicsItem.cpp.
References TextureGraphicsItem::_texture, ShapeGraphicsItem::getMapping(), and ShapeGraphicsItem::isOutput().
 {
   Q_UNUSED(option);
   painter->beginNativePainting();
   QSharedPointer<Texture> texture = _texture.toStrongRef();
   // Only works for similar shapes.
   // TODO:remettre
   //Q_ASSERT( _inputShape->nVertices() == outputShape->nVertices());
   // Project source texture and sent it to destination.
   texture->update();
   // Allow alpha blending.
   glEnable (GL_BLEND);
   glBlendFunc (GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
   // Get texture.
   glEnable (GL_TEXTURE_2D);
   glBindTexture(GL_TEXTURE_2D, texture->getTextureId());
   // Copy bits to texture iff necessary.
   texture->lockMutex();
   if (texture->bitsHaveChanged())
   {
     glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA,
         texture->getWidth(), texture->getHeight(), 0, GL_RGBA,
       GL_UNSIGNED_BYTE, texture->getBits());
   }
   texture->unlockMutex();
   glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_BORDER);
   glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_BORDER);
   glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
   glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
   // Set texture color (apply opacity).
   glColor4f(1.0f, 1.0f, 1.0f,
             isOutput() ? getMapping()->getOpacity() : getMapping()->getPaint()->getOpacity());
 }
void TextureGraphicsItem::_postPaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected virtual inherited
Can be overriden to perform operations after _doPaint() is called.
Reimplemented from ShapeGraphicsItem.
Definition at line 268 of file ShapeGraphicsItem.cpp.
 {
   Q_UNUSED(option);
   glDisable(GL_TEXTURE_2D);
   painter->endNativePainting();
 }
void TextureGraphicsItem::_doDrawInput (QPainter * painter) protected virtual inherited
Definition at line 199 of file ShapeGraphicsItem.cpp.
References TextureGraphicsItem::_texture, ShapeGraphicsItem::boundingRect(), Util::correctGlTexCoord(), and ShapeGraphicsItem::isMappingCurrent().
Referenced by TextureGraphicsItem::_doPaint().
 {
   Q_UNUSED(painter);
   if (isMappingCurrent())
   {
     // FIXME: Does this draw the quad counterclockwise?
     glBegin (GL_QUADS);
     {
       QRectF rect = mapFromScene(_texture.toStrongRef()->getRect()).boundingRect();
       Util::correctGlTexCoord(0, 0);
       glVertex3f (rect.x(), rect.y(), 0);
       Util::correctGlTexCoord(1, 0);
       glVertex3f (rect.x() + rect.width(), rect.y(), 0);
       Util::correctGlTexCoord(1, 1);
       glVertex3f (rect.x()+rect.width(), rect.y()+rect.height(), 0);
       Util::correctGlTexCoord(0, 1);
       glVertex3f (rect.x(), rect.y()+rect.height(), 0);
     }
     glEnd ();
   }
 }
MShape::ptr ShapeGraphicsItem::getShape () const inherited
Returns the MShape (depends on mapping and whether this is an input or output).
Definition at line 60 of file ShapeGraphicsItem.h.
References ShapeGraphicsItem::_shape.
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), and ShapeControlPainter::getShape().
 { return _shape.toStrongRef(); }
Mapping::ptr ShapeGraphicsItem::getMapping () const inherited
Returns the mapping.
Definition at line 63 of file ShapeGraphicsItem.h.
References ShapeGraphicsItem::_mapping.
Referenced by ColorGraphicsItem::_prePaint(), TextureGraphicsItem::_prePaint(), ShapeGraphicsItem::isMappingCurrent(), ShapeGraphicsItem::isMappingVisible(), ShapeGraphicsItem::paint(), and ShapeGraphicsItem::ShapeGraphicsItem().
 { return _mapping.toStrongRef(); }
QSharedPointer<ShapeControlPainter> ShapeGraphicsItem::getControlPainter () inherited
Returns the control painter (see below).
Definition at line 66 of file ShapeGraphicsItem.h.
References ShapeGraphicsItem::_controlPainter.
 { return _controlPainter; }
bool ShapeGraphicsItem::isOutput () const inherited
Return whether the item is in the destination/output (true) or source/input (false).
Definition at line 69 of file ShapeGraphicsItem.h.
References ShapeGraphicsItem::_output.
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), MeshTextureGraphicsItem::_doDrawOutput(), TextureGraphicsItem::_doPaint(), TextureGraphicsItem::_prePaint(), ShapeGraphicsItem::getCanvas(), and ShapeGraphicsItem::paint().
 { return _output; }
MapperGLCanvas * ShapeGraphicsItem::getCanvas () const inherited
Returns pointer to GL canvas.
Definition at line 31 of file ShapeGraphicsItem.cpp.
References MainWindow::getDestinationCanvas(), MainWindow::getSourceCanvas(), MainWindow::instance(), and ShapeGraphicsItem::isOutput().
Referenced by MeshTextureGraphicsItem::_doDrawOutput(), ShapeControlPainter::_paintVertices(), and ShapeGraphicsItem::getRescaledShapeStroke().
 {
   MainWindow* win = MainWindow::instance();
   return isOutput() ? win->getDestinationCanvas() : win->getSourceCanvas();
 }
bool ShapeGraphicsItem::isMappingCurrent () const inherited
Returns whether the mapping this shape is associated with is currently selected.
Definition at line 37 of file ShapeGraphicsItem.cpp.
References MainWindow::getCurrentMappingId(), ShapeGraphicsItem::getMapping(), and MainWindow::instance().
Referenced by TextureGraphicsItem::_doDrawInput(), and MeshTextureGraphicsItem::_doDrawOutput().
{
   return MainWindow::instance()->getCurrentMappingId() == getMapping()->getId();
 }
bool ShapeGraphicsItem::isMappingVisible () const inherited
Returns whether the mapping this shape is associated should be visible.
Definition at line 78 of file ShapeGraphicsItem.h.
References ShapeGraphicsItem::getMapping().
Referenced by ShapeGraphicsItem::paint().
 { return getMapping()->isVisible(); }
void ShapeGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual inherited
Built-in function: paints the shape.
Definition at line 41 of file ShapeGraphicsItem.cpp.
References ShapeGraphicsItem::_doPaint(), ShapeGraphicsItem::_postPaint(), ShapeGraphicsItem::_prePaint(), ShapeGraphicsItem::getMapping(), ShapeGraphicsItem::isMappingVisible(), and ShapeGraphicsItem::isOutput().
 {
   Q_UNUSED(widget);
   // Sync depth of figure with that of mapping (for layered output).
   if (isOutput())
     setZValue(getMapping()->getDepth());
   // Paint if visible.
   if (isMappingVisible())
   {
     // Paint whatever needs to be painted.
     _prePaint(painter, option);
     _doPaint(painter, option);
     _postPaint(painter, option);
   }
 }
QPen ShapeGraphicsItem::getRescaledShapeStroke (bool innerStroke = false) inherited
Utility function: returns a stroke with rescaled width such that the stroke appears invariant to the zoom level (to be used in paint functions).
Definition at line 60 of file ShapeGraphicsItem.cpp.
References MM::CONTROL_COLOR, ShapeGraphicsItem::getCanvas(), MM::SHAPE_INNER_STROKE_WIDTH, and MM::SHAPE_STROKE_WIDTH.
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), and MeshControlPainter::_paintShape().
 {
   return QPen(QBrush(MM::CONTROL_COLOR), (innerStroke ? MM::SHAPE_INNER_STROKE_WIDTH : MM::SHAPE_STROKE_WIDTH) / getCanvas()->getZoomFactor());
 }
Member Data Documentation
const int EllipseTextureGraphicsItem::N_QUARTERS = 4 static private
Definition at line 253 of file ShapeGraphicsItem.h.
Referenced by _doDrawOutput(), and EllipseTextureGraphicsItem::DrawingData::getSpanInQuarter().
QWeakPointer<TextureMapping> TextureGraphicsItem::_textureMapping protected inherited
Definition at line 176 of file ShapeGraphicsItem.h.
Referenced by TextureGraphicsItem::TextureGraphicsItem().
QWeakPointer<Texture> TextureGraphicsItem::_texture protected inherited
Definition at line 177 of file ShapeGraphicsItem.h.
Referenced by TextureGraphicsItem::_doDrawInput(), TriangleTextureGraphicsItem::_doDrawOutput(), MeshTextureGraphicsItem::_doDrawOutput(), _doDrawOutput(), TextureGraphicsItem::_prePaint(), and TextureGraphicsItem::TextureGraphicsItem().
QWeakPointer<MShape> TextureGraphicsItem::_inputShape protected inherited
Definition at line 178 of file ShapeGraphicsItem.h.
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), MeshTextureGraphicsItem::_doDrawOutput(), _doDrawOutput(), and TextureGraphicsItem::TextureGraphicsItem().
QWeakPointer<Mapping> ShapeGraphicsItem::_mapping protected inherited
Definition at line 112 of file ShapeGraphicsItem.h.
Referenced by ShapeGraphicsItem::getMapping().
QWeakPointer<MShape> ShapeGraphicsItem::_shape protected inherited
Definition at line 113 of file ShapeGraphicsItem.h.
Referenced by MeshTextureGraphicsItem::_doDrawOutput(), _doDrawOutput(), PolygonColorGraphicsItem::_doPaint(), ShapeGraphicsItem::getShape(), PolygonColorGraphicsItem::shape(), EllipseColorGraphicsItem::shape(), PolygonTextureGraphicsItem::shape(), shape(), and ShapeGraphicsItem::ShapeGraphicsItem().
QSharedPointer<ShapeControlPainter> ShapeGraphicsItem::_controlPainter protected inherited
Definition at line 114 of file ShapeGraphicsItem.h.
Referenced by EllipseColorGraphicsItem::EllipseColorGraphicsItem(), EllipseTextureGraphicsItem(), ShapeGraphicsItem::getControlPainter(), MeshTextureGraphicsItem::MeshTextureGraphicsItem(), PolygonColorGraphicsItem::PolygonColorGraphicsItem(), and PolygonTextureGraphicsItem::PolygonTextureGraphicsItem().
bool ShapeGraphicsItem::_output protected inherited
Definition at line 115 of file ShapeGraphicsItem.h.
Referenced by ShapeGraphicsItem::isOutput().
The documentation for this class was generated from the following files:
ShapeGraphicsItem.h
ShapeGraphicsItem.cpp