MapMap: MeshControlPainter Class Reference
MeshControlPainter Class Reference
Control painter for meshes.
#include <ShapeControlPainter.h>
Public Types
typedef QSharedPointer
< ShapeControlPainter > ptr
Public Member Functions
MeshControlPainter (ShapeGraphicsItem *shapeItem)
virtual ~MeshControlPainter ()
MShape::ptr getShape () const
virtual void paint (QPainter *painter, const QList< int > &selectedVertices=QList< int >())
Protected Member Functions
virtual void _paintShape (QPainter *painter)
virtual void _paintVertices (QPainter *painter, const QList< int > &selectedVertices=QList< int >())
Protected Attributes
ShapeGraphicsItem * _shapeItem
Detailed Description
Control painter for meshes.
Definition at line 76 of file ShapeControlPainter.h.
Member Typedef Documentation
typedef QSharedPointer<ShapeControlPainter> ShapeControlPainter::ptr inherited
Definition at line 37 of file ShapeControlPainter.h.
Constructor & Destructor Documentation
MeshControlPainter::MeshControlPainter (ShapeGraphicsItem * shapeItem)
Definition at line 79 of file ShapeControlPainter.h.
 : ShapeControlPainter(shapeItem) {}
virtual MeshControlPainter::~MeshControlPainter () virtual
Definition at line 80 of file ShapeControlPainter.h.
 {}
Member Function Documentation
void MeshControlPainter::_paintShape (QPainter * painter) protected virtual
Implements ShapeControlPainter.
Definition at line 77 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_shapeItem, Mesh::getQuads(), ShapeGraphicsItem::getRescaledShapeStroke(), ShapeControlPainter::getShape(), and Mesh::toPolygon().
 {
   Mesh* mesh = static_cast<Mesh*>(getShape().data());
   Q_ASSERT(mesh);
   // Init colors and stroke.
   painter->setPen(_shapeItem->getRescaledShapeStroke(true));
   // Draw inner quads.
   QVector<Quad> quads = mesh->getQuads();
   for (QVector<Quad>::const_iterator it = quads.begin(); it != quads.end(); ++it)
   {
     painter->drawPolygon(it->toPolygon());
   }
   // Draw outer quad.
   painter->setPen(_shapeItem->getRescaledShapeStroke());
   painter->drawPolygon(_shapeItem->mapFromScene(mesh->toPolygon()));
 }
MShape::ptr ShapeControlPainter::getShape () const inherited
Definition at line 28 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_shapeItem, and ShapeGraphicsItem::getShape().
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), _paintShape(), and ShapeControlPainter::_paintVertices().
 { return _shapeItem->getShape(); }
void ShapeControlPainter::paint (QPainter * painter, const QList< int > & selectedVertices = QList<int>()) virtual inherited
Definition at line 30 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_paintShape(), and ShapeControlPainter::_paintVertices().
 {
   _paintShape(painter);
   _paintVertices(painter, selectedVertices);
 }
void ShapeControlPainter::_paintVertices (QPainter * painter, const QList< int > & selectedVertices = QList<int>()) protected virtual inherited
Definition at line 36 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_shapeItem, Util::drawControlsVertex(), ShapeGraphicsItem::getCanvas(), ShapeControlPainter::getShape(), MapperGLCanvas::getZoomFactor(), MM::VERTEX_SELECT_RADIUS, and MM::VERTEX_SELECT_STROKE_WIDTH.
Referenced by ShapeControlPainter::paint().
 {
   qreal zoomFactor = _shapeItem->getCanvas()->getZoomFactor();
   qreal selectRadius = MM::VERTEX_SELECT_RADIUS / zoomFactor;
   qreal strokeWidth  = MM::VERTEX_SELECT_STROKE_WIDTH / zoomFactor;
   for (int i=0; i<getShape()->nVertices(); i++)
     Util::drawControlsVertex(painter, getShape()->getVertex(i), selectedVertices.contains(i), selectRadius, strokeWidth);
 }
Member Data Documentation
ShapeGraphicsItem* ShapeControlPainter::_shapeItem protected inherited
Definition at line 50 of file ShapeControlPainter.h.
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), _paintShape(), ShapeControlPainter::_paintVertices(), and ShapeControlPainter::getShape().
The documentation for this class was generated from the following files:
ShapeControlPainter.h
ShapeControlPainter.cpp