MapMap: DestinationGLCanvas Class Reference
DestinationGLCanvas Class Reference
#include <DestinationGLCanvas.h>
Public Slots
void updateCanvas ()
void deselectVertices ()
void deselectAll ()
void wheelEvent (QWheelEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
bool eventFilter (QObject *target, QEvent *event)
Signals
void shapeChanged (MShape *)
void imageChanged ()
Public Member Functions
DestinationGLCanvas (MainWindow *mainWindow, QWidget *parent=0, const QGLWidget *shareWidget=0, QGraphicsScene *scene=0)
virtual ~DestinationGLCanvas ()
virtual bool isOutput () const
Returns shape associated with mapping id.
virtual MShape::ptr getShapeFromMappingId (uid mappingId) const
virtual QSharedPointer
< ShapeGraphicsItem > getShapeGraphicsItemFromMappingId (uid mappingId) const
MShape::ptr getCurrentShape ()
QSharedPointer< ShapeGraphicsItem > getCurrentShapeGraphicsItem ()
void drawForeground (QPainter *painter, const QRectF &rect)
MainWindow * getMainWindow () const
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
bool hasActiveVertex () const
Returns true iff one of the vertices is currently active.
int getActiveVertexIndex () const
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
void setActiveVertexIndex (int activeVertex)
Set the currently active vertex.
bool shapeGrabbed () const
bool vertexGrabbed () const
qreal getZoomFactor () const
void currentShapeWasChanged ()
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Static Public Attributes
static const int NO_VERTEX = -1
Protected Member Functions
void _glueVertex (QPointF *p)
Detailed Description
Definition at line 29 of file DestinationGLCanvas.h.
Constructor & Destructor Documentation
DestinationGLCanvas::DestinationGLCanvas (MainWindow * mainWindow, QWidget * parent = 0, const QGLWidget * shareWidget = 0, QGraphicsScene * scene = 0)
Definition at line 24 of file DestinationGLCanvas.cpp.
 : MapperGLCanvas(mainWindow, parent, shareWidget, scene)
 {
 }
virtual DestinationGLCanvas::~DestinationGLCanvas () virtual
Definition at line 35 of file DestinationGLCanvas.h.
 {}
Member Function Documentation
virtual bool DestinationGLCanvas::isOutput () const virtual
Returns shape associated with mapping id.
Implements MapperGLCanvas.
Definition at line 37 of file DestinationGLCanvas.h.
 { return true; }
MShape::ptr DestinationGLCanvas::getShapeFromMappingId (uid mappingId) const virtual
Implements MapperGLCanvas.
Definition at line 29 of file DestinationGLCanvas.cpp.
References MapperGLCanvas::getMainWindow(), MappingManager::getMappingById(), MainWindow::getMappingManager(), and NULL_UID.
 {
   if (mappingId == NULL_UID)
     return MShape::ptr();
   else
     return getMainWindow()->getMappingManager().getMappingById(mappingId)->getShape();
 }
QSharedPointer< ShapeGraphicsItem > DestinationGLCanvas::getShapeGraphicsItemFromMappingId (uid mappingId) const virtual
Implements MapperGLCanvas.
Definition at line 37 of file DestinationGLCanvas.cpp.
References MainWindow::getMappingGuiByMappingId(), MainWindow::instance(), and NULL_UID.
 {
   if (mappingId == NULL_UID)
     return QSharedPointer<ShapeGraphicsItem>();
   else
   {
     return MainWindow::instance()->getMappingGuiByMappingId(mappingId)->getGraphicsItem();
   }
 }
MShape::ptr MapperGLCanvas::getCurrentShape () inherited
Definition at line 64 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getShapeFromMappingId(), and MainWindow::instance().
Referenced by MapperGLCanvas::_glueVertex(), MapperGLCanvas::currentShapeWasChanged(), MapperGLCanvas::keyPressEvent(), MapperGLCanvas::mouseMoveEvent(), MapperGLCanvas::mousePressEvent(), and TransformShapeCommand::TransformShapeCommand().
 {
   return getShapeFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
QSharedPointer< ShapeGraphicsItem > MapperGLCanvas::getCurrentShapeGraphicsItem () inherited
Definition at line 69 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getShapeGraphicsItemFromMappingId(), and MainWindow::instance().
Referenced by MapperGLCanvas::drawForeground().
 {
   return getShapeGraphicsItemFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
void MapperGLCanvas::drawForeground (QPainter * painter, const QRectF & rect) inherited
Definition at line 75 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_mainWindow, MainWindow::displayControls(), MapperGLCanvas::getActiveVertexIndex(), MainWindow::getCurrentMappingId(), MapperGLCanvas::getCurrentShapeGraphicsItem(), MapperGLCanvas::hasActiveVertex(), and NULL_UID.
Referenced by OutputGLCanvas::drawForeground().
 {
   Q_UNUSED(rect);
   if (_mainWindow->displayControls())
   {
     uid mid = _mainWindow->getCurrentMappingId();
     if (mid != NULL_UID)
     {
       // Use current shape graphics item to draw controls.
       ShapeGraphicsItem::ptr item = getCurrentShapeGraphicsItem();
       if (item)
       {
         QList<int> selected;
         if (hasActiveVertex())
           selected.push_back(getActiveVertexIndex());
         item->getControlPainter()->paint(painter, selected);
       }
     }
   }
 }
MainWindow* MapperGLCanvas::getMainWindow () const inherited
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
The distance per coordinate is currently set in dist_stick variable.Returns pointer to main window.
Definition at line 75 of file MapperGLCanvas.h.
Referenced by OutputGLCanvas::drawForeground(), MapperGLCanvas::eventFilter(), getShapeFromMappingId(), SourceGLCanvas::getShapeFromMappingId(), MapperGLCanvas::keyPressEvent(), MapperGLCanvas::mouseMoveEvent(), MapperGLCanvas::mousePressEvent(), OutputGLWindow::OutputGLWindow(), and OutputGLWindow::setFullScreen().
 { return _mainWindow; }
bool MapperGLCanvas::hasActiveVertex () const inherited
Returns true iff one of the vertices is currently active.
Definition at line 78 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex, and MapperGLCanvas::NO_VERTEX.
Referenced by MapperGLCanvas::drawForeground(), MapperGLCanvas::keyPressEvent(), and MapperGLCanvas::mouseMoveEvent().
 { return _activeVertex != NO_VERTEX; }
int MapperGLCanvas::getActiveVertexIndex () const inherited
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
Definition at line 81 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex.
Referenced by MapperGLCanvas::drawForeground(), and MapperGLCanvas::eventFilter().
 { return _activeVertex; }
void MapperGLCanvas::setActiveVertexIndex (int activeVertex) inherited
Set the currently active vertex.
Definition at line 84 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex.
Referenced by MapperGLCanvas::eventFilter().
 { _activeVertex = activeVertex; }
bool MapperGLCanvas::shapeGrabbed () const inherited
Definition at line 86 of file MapperGLCanvas.h.
References MapperGLCanvas::_shapeGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _shapeGrabbed; }
bool MapperGLCanvas::vertexGrabbed () const inherited
Definition at line 87 of file MapperGLCanvas.h.
References MapperGLCanvas::_vertexGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _vertexGrabbed; }
qreal MapperGLCanvas::getZoomFactor () const inherited
Definition at line 89 of file MapperGLCanvas.h.
References MapperGLCanvas::_zoomLevel, MM::ZOOM_FACTOR, MM::ZOOM_MAX, and MM::ZOOM_MIN.
Referenced by ShapeControlPainter::_paintVertices(), and MapperGLCanvas::wheelEvent().
 { return qBound(qPow(MM::ZOOM_FACTOR, _zoomLevel), MM::ZOOM_MIN, MM::ZOOM_MAX); }
void MapperGLCanvas::currentShapeWasChanged () inherited
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Definition at line 96 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getCurrentShape(), and MapperGLCanvas::shapeChanged().
Referenced by TransformShapeCommand::redo(), and TransformShapeCommand::undo().
 {
   emit shapeChanged(getCurrentShape().data());
 }
void MapperGLCanvas::shapeChanged (MShape *) signal inherited
Referenced by MapperGLCanvas::currentShapeWasChanged().
void MapperGLCanvas::imageChanged () signal inherited
void MapperGLCanvas::updateCanvas () slot inherited
Definition at line 423 of file MapperGLCanvas.cpp.
 {
   update();
   scene()->update();
 }
void MapperGLCanvas::deselectVertices () slot inherited
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are
Definition at line 454 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_vertexGrabbed, and MapperGLCanvas::NO_VERTEX.
Referenced by MapperGLCanvas::deselectAll(), and MapperGLCanvas::mousePressEvent().
 {
   _activeVertex = NO_VERTEX;
   _vertexGrabbed = false;
 }
void MapperGLCanvas::deselectAll () slot inherited
Definition at line 460 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_shapeFirstGrab, MapperGLCanvas::_shapeGrabbed, and MapperGLCanvas::deselectVertices().
Referenced by MapperGLCanvas::mousePressEvent().
 {
   deselectVertices();
   _shapeGrabbed = false;
   _shapeFirstGrab = false;
 }
void MapperGLCanvas::wheelEvent (QWheelEvent * event) slot inherited
Definition at line 467 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_zoomLevel, MapperGLCanvas::getZoomFactor(), MM::ZOOM_FACTOR, MM::ZOOM_MAX, and MM::ZOOM_MIN.
 {
   int deltaLevel = event->delta() / 120;
   qreal zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
   if (deltaLevel > 0)
   {
     // First check if we're already at max.
     while (deltaLevel && zoomFactor < MM::ZOOM_MAX) {
       _zoomLevel++;
       deltaLevel--;
       zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
     }
     zoomFactor = qMin(zoomFactor, MM::ZOOM_MAX);
   }
   else
   {
     // First check if we're already at min.
     while (deltaLevel && zoomFactor > MM::ZOOM_MIN) {
       _zoomLevel--;
       deltaLevel++;
       zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
     }
     zoomFactor = qMax(zoomFactor, MM::ZOOM_MIN);
   }
   // Re-bound zoom (for consistency).
   zoomFactor = getZoomFactor();
   // Apply zoom to view.
   QGraphicsView* view = scene()->views().first();
   view->resetMatrix();
   view->scale(zoomFactor, zoomFactor);
   view->update();
   // Accept wheel scrolling event.
   event->accept();
 }
void MapperGLCanvas::mousePressEvent (QMouseEvent * event) slot inherited
Definition at line 103 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_grabbedObjectStartScenePosition, MapperGLCanvas::_mousePressedPosition, MapperGLCanvas::_shapeFirstGrab, MapperGLCanvas::_shapeGrabbed, MapperGLCanvas::_vertexGrabbed, MapperGLCanvas::deselectAll(), MapperGLCanvas::deselectVertices(), dist(), distSq(), MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getMainWindow(), MainWindow::getMappingManager(), MapperGLCanvas::getShapeFromMappingId(), MappingManager::getVisibleMappings(), MapperGLCanvas::isOutput(), MainWindow::setCurrentMapping(), sq(), and MM::VERTEX_SELECT_RADIUS.
 {
   bool mousePressedOnSomething = false;
   _mousePressedPosition = event->pos();
   QPointF pos = mapToScene(event->pos());
   // Drag the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     // NOTE: This is a trick code to implement scroll hand drag using the middle button.
     QMouseEvent releaseEvent(QEvent::MouseButtonRelease, event->pos(), event->globalPos(), Qt::LeftButton, 0, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&releaseEvent);
     setDragMode(QGraphicsView::ScrollHandDrag);
     // We need to pretend it is actually the left button that was pressed!
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
                           Qt::LeftButton, event->buttons() | Qt::LeftButton, event->modifiers());
     QGraphicsView::mousePressEvent(&fakeEvent);
   }
   // Check for vertex selection first.
   else if (event->buttons() & Qt::LeftButton)
   {
     MShape::ptr shape = getCurrentShape();
     if (shape)
     {
       // Note: we compare with the square value for fastest computation of the distance
       int minDistance = sq(MM::VERTEX_SELECT_RADIUS);
       // Find the ID of the nearest vertex (from currently selected shape)
       for (int i = 0; i < shape->nVertices(); i++)
       {
         int dist = distSq(_mousePressedPosition, mapFromScene(shape->getVertex(i))); // squared distance
         if (dist < minDistance)
         {
           _activeVertex = i;
           minDistance = dist;
           _vertexGrabbed = true;
           mousePressedOnSomething = true;
           _grabbedObjectStartScenePosition = shape->getVertex(i);
         }
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Check for shape selection.
   if (event->buttons() & (Qt::LeftButton | Qt::RightButton)) // Add Right click for context menu
   {
     MShape::ptr selectedShape = getCurrentShape();
     // Possibility of changing shape in output by clicking on it.
     MappingManager manager = getMainWindow()->getMappingManager();
     QVector<Mapping::ptr> mappings = manager.getVisibleMappings();
     for (QVector<Mapping::ptr>::const_iterator it = mappings.end() - 1; it >= mappings.begin(); --it)
     {
       MShape::ptr shape = getShapeFromMappingId((*it)->getId());
       // Check if mouse was pressed on that shape.
       if (shape && shape->includesPoint(pos))
       {
         mousePressedOnSomething = true;
         // Deselect vertices.
         deselectVertices();
         // Change mapping (only available in destination).
         if (isOutput() && shape != selectedShape)
         {
           // Change current mapping.
           getMainWindow()->setCurrentMapping((*it)->getId());
           // Reset selected shape to new one.
           selectedShape = getCurrentShape();
         }
         break;
       }
     }
     // Grab the shape.
     if (event->buttons() & Qt::LeftButton) // This preserve me from duplicate code above
     {
       if (selectedShape && selectedShape->includesPoint(pos))
       {
         _shapeGrabbed = true;
         _shapeFirstGrab = true;
         _grabbedObjectStartScenePosition = pos;
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Deactivate.
   deselectAll();
 }
void MapperGLCanvas::mouseReleaseEvent (QMouseEvent * event) slot inherited
Definition at line 208 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_glueVertex(), MapperGLCanvas::_mainWindow, MapperGLCanvas::_shapeGrabbed, MapperGLCanvas::_vertexGrabbed, TransformShapeCommand::RELEASE, MainWindow::stickyVertices(), and MapperGLCanvas::undoStack.
 {
   Q_UNUSED(event);
   // Wrap-up dragging the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
         Qt::LeftButton, event->buttons() & ~Qt::LeftButton, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&fakeEvent);
     setDragMode(QGraphicsView::NoDrag);
     setCursor(Qt::ArrowCursor);
   }
 //  // Click on vertex ==> select the vertex.
 //  if ((event->buttons() & Qt::LeftButton) && _mousePressedOnVertex)
 //  {
 //  }
   if (_vertexGrabbed)
   {
     // TODO : code repetition here!!!
     QPointF p = mapToScene(event->pos());
     // Stick to vertices.
     if (_mainWindow->stickyVertices())
       _glueVertex(&p);
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::RELEASE, _activeVertex, p));
   }
   else if (_shapeGrabbed)
   {
     undoStack->push(new TranslateShapeCommand(this, TransformShapeCommand::RELEASE, QPointF()));
   }
   _vertexGrabbed = false;
   _shapeGrabbed = false;
 }
void MapperGLCanvas::mouseMoveEvent (QMouseEvent * event) slot inherited
Definition at line 244 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_glueVertex(), MapperGLCanvas::_mainWindow, MapperGLCanvas::_mousePressedPosition, MapperGLCanvas::_shapeFirstGrab, MapperGLCanvas::_shapeGrabbed, MapperGLCanvas::_vertexGrabbed, TransformShapeCommand::FREE, MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getMainWindow(), MainWindow::getUndoStack(), MapperGLCanvas::hasActiveVertex(), MainWindow::stickyVertices(), and MapperGLCanvas::undoStack.
Referenced by OutputGLCanvas::mouseMoveEvent().
 {
   static QPoint lastMousePos;
   QPointF scenePos = mapToScene(event->pos());
   // Prepare to store commands
   undoStack = getMainWindow()->getUndoStack();
   // Vertex grab.
   if (_vertexGrabbed)
   {
     // std::cout << "Move event " << std::endl;
     MShape::ptr shape = getCurrentShape();
     if (shape && hasActiveVertex())
     {
 //      QPointF p = shape->getVertex(_activeVertex);
 //      // Set point to mouse coordinates.
 //      p.setX(pos.x());
 //      p.setY(pos.y());
       QPointF p = scenePos;
       // Stick to vertices.
       if (_mainWindow->stickyVertices())
         _glueVertex(&p);
       undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::FREE, _activeVertex, p));
     }
   }
   // Shape grab.
   else if (_shapeGrabbed)
   {
     // std::cout << "Move event " << std::endl;
     MShape::ptr shape = getCurrentShape();
     if (shape)
     {
       if (_shapeFirstGrab)
       {
         lastMousePos = _mousePressedPosition;
         _shapeFirstGrab = false;
       }
     }
     QPointF diff = scenePos - mapToScene(lastMousePos);
     undoStack->push(new TranslateShapeCommand(this, TransformShapeCommand::FREE, diff));
   }
   // Window translation action
   else if (event->buttons() & Qt::MiddleButton)
   {
     QPointF diff = event->pos() - lastMousePos;
     QGraphicsView* view = scene()->views().first();
     view->translate(diff.x(), diff.y());
 //    view->update();
   }
   // Reset last mouse position.
   lastMousePos = event->pos();
 }
void MapperGLCanvas::keyPressEvent (QKeyEvent * event) slot inherited
Definition at line 307 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getMainWindow(), MainWindow::getUndoStack(), MapperGLCanvas::hasActiveVertex(), TransformShapeCommand::STEP, and MapperGLCanvas::undoStack.
Referenced by MapperGLCanvas::eventFilter().
 {
   // Prepare to store commands.
   undoStack = getMainWindow()->getUndoStack();
   // Checks if the key has been handled by this function or needs to be deferred to superclass.
   bool handledKey = false;
   // Active vertex selected.
   if (hasActiveVertex())
   {
     MShape::ptr shape = getCurrentShape();
     QPoint pos = mapFromScene(shape->getVertex(_activeVertex));
     handledKey = true;
     switch (event->key()) {
     // TODO: key tab should switch to next vertex: not working because somehow caught at a higher level
     // to switch between frames of the layout
 //    case Qt::Key_Tab:
 //      if (shape)
 //        _activeVertex = (_activeVertex + 1) % shape->nVertices();
 //        p = shape->getVertex(_activeVertex); // reset to new vertex
 //        qDebug() << "New active vertex : " << _activeVertex << endl;
 //      break;
     // Handle pixel-wise adjustments of vertex.
     case Qt::Key_Up:
       pos.ry()--;
       break;
     case Qt::Key_Down:
       pos.ry()++;
       break;
     case Qt::Key_Right:
       pos.rx()++;
       break;
     case Qt::Key_Left:
       pos.rx()--;
       break;
     default:
       if (event->matches(QKeySequence::Undo))
         undoStack->undo();
       else if (event->matches(QKeySequence::Redo))
         undoStack->redo();
       else
         handledKey = false;
       break;
     }
     // Remap window position to scene.
     QPointF scenePos = mapToScene(pos);
     // TODO: this will always be called even if no arrow key has been pressed (small performance issue).
     // Enable to Undo and Redo when arrow keys move the position of vertices
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::STEP, _activeVertex, scenePos));
   }
   // Defer unhandled keys to parent.
   if (!handledKey)
   {
     QWidget::keyPressEvent(event);
   }
 //  std::cout << "Key pressed" << std::endl;
 //  int xMove = 0;
 //  int yMove = 0;
 //  switch (event->key()) {
 //  case Qt::Key_Tab:
 //    if (event->modifiers() & Qt::ControlModifier)
 //      switchImage( (Common::getCurrentSourceId() + 1) % Common::nImages());
 //    else
 //    {
 //      Quad& quad = getQuad();
 //      _active_vertex = (_active_vertex + 1 ) % 4;
 //    }
 //    break;
 //  case Qt::Key_Up:
 //    yMove = -1;
 //    break;
 //  case Qt::Key_Down:
 //    yMove = +1;
 //    break;
 //  case Qt::Key_Left:
 //    xMove = -1;
 //    break;
 //  case Qt::Key_Right:
 //    xMove = +1;
 //    break;
 //  default:
 //    std::cerr << "Unhandled key" << std::endl;
 //    QWidget::keyPressEvent(event);
 //    break;
 //  }
 //
 //  Quad& quad = getQuad();
 //  Point *p = quad.getVertex(_active_vertex);
 //  p->x += xMove;
 //  p->y += yMove;
 //  quad.setVertex(_active_vertex, p);
 //
 //  update();
 //
 //  emit quadChanged();
 }
bool MapperGLCanvas::eventFilter (QObject * target, QEvent * event) slot inherited
Definition at line 505 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getActiveVertexIndex(), MapperGLCanvas::getMainWindow(), MapperGLCanvas::keyPressEvent(), and MapperGLCanvas::setActiveVertexIndex().
 {
   if (event->type() == QEvent::KeyPress)
   {
     QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
     setActiveVertexIndex(getMainWindow()->getOutputWindow()->getCanvas()->getActiveVertexIndex());
     MapperGLCanvas::keyPressEvent(keyEvent);
     return true;
   }
   else
   {
     return QObject::eventFilter(target, event);
   }
 }
void MapperGLCanvas::_glueVertex (QPointF * p) protected inherited
Definition at line 521 of file MapperGLCanvas.cpp.
References distIsInside(), MapperGLCanvas::getCurrentShape(), MappingManager::getMapping(), MainWindow::getMappingManager(), MShape::getVertex(), MainWindow::instance(), MappingManager::nMappings(), MShape::nVertices(), and MM::VERTEX_STICK_RADIUS.
Referenced by MapperGLCanvas::mouseMoveEvent(), and MapperGLCanvas::mouseReleaseEvent().
 {
   MappingManager manager = MainWindow::instance()->getMappingManager();
   for (int i = 0; i < manager.nMappings(); i++)
   {
     MShape *shape = manager.getMapping(i)->getShape().data();
     if (shape && shape != getCurrentShape())
     {
       for (int vertex = 0; vertex < shape->nVertices(); vertex++)
       {
         const QPointF& v = shape->getVertex(vertex);
         if (distIsInside(v, *p, MM::VERTEX_STICK_RADIUS))
         {
           p->setX(v.x());
           p->setY(v.y());
         }
       }
     }
   }
 }
Member Data Documentation
const int MapperGLCanvas::NO_VERTEX = -1 static inherited
Definition at line 176 of file MapperGLCanvas.h.
Referenced by MapperGLCanvas::deselectVertices(), and MapperGLCanvas::hasActiveVertex().
The documentation for this class was generated from the following files:
DestinationGLCanvas.h
DestinationGLCanvas.cpp