MapMap: MShape Class Reference
MShape Class Reference abstract
Shape represented by a series of control points.
#include <Shape.h>
Public Types
typedef QSharedPointer< MShape > ptr
Public Member Functions
MShape ()
MShape (QVector< QPointF > vertices_)
virtual ~MShape ()
virtual void build ()
int nVertices () const
QPointF getVertex (int i) const
virtual void setVertex (int i, const QPointF &v)
virtual void setVertex (int i, qreal x, qreal y)
virtual QString getType () const =0
virtual bool includesPoint (qreal x, qreal y)
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
virtual bool includesPoint (const QPointF &p)=0
virtual void translate (const QPointF &offset)
Translate all vertices of shape by the vector (x,y).
virtual void copyFrom (const MShape &shape)
virtual MShape * clone () const
Protected Member Functions
void _addVertex (const QPointF &vertex)
void _rawSetVertex (int i, const QPointF &v)
virtual MShape * _create () const =0
Returns a new MShape (using default constructor).
Protected Attributes
QVector< QPointF > vertices
Detailed Description
Shape represented by a series of control points.
Definition at line 44 of file Shape.h.
Member Typedef Documentation
typedef QSharedPointer<MShape> MShape::ptr
Definition at line 47 of file Shape.h.
Constructor & Destructor Documentation
MShape::MShape ()
Definition at line 49 of file Shape.h.
 {}
MShape::MShape (QVector< QPointF > vertices_)
Definition at line 50 of file Shape.h.
                                      :
     vertices(vertices_)
   {}
virtual MShape::~MShape () virtual
Definition at line 53 of file Shape.h.
 {}
Member Function Documentation
virtual void MShape::build () virtual
Definition at line 55 of file Shape.h.
 {}
int MShape::nVertices () const
Definition at line 57 of file Shape.h.
References vertices.
Referenced by MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MappingGui::_updateShapeProperty(), Mesh::addColumn(), Mesh::addRow(), Util::drawControlsVertices(), Ellipse::hasCenterControl(), and ProjectWriter::writeShapeVertices().
 { return vertices.size(); }
QPointF MShape::getVertex (int i) const
Definition at line 59 of file Shape.h.
References vertices.
Referenced by MeshTextureGraphicsItem::_buildCacheQuadItem(), MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MeshTextureGraphicsItem::_split(), MappingGui::_updateShapeProperty(), Util::drawControlsVertices(), Ellipse::getCenter(), Ellipse::getHorizontalAxis(), Ellipse::getVerticalAxis(), Ellipse::sanitize(), MappingGui::setValue(), Ellipse::setVertex(), and ProjectWriter::writeShapeVertices().
   {
     return vertices[i];
   }
virtual void MShape::setVertex (int i, const QPointF & v) virtual
Reimplemented in Ellipse, Mesh, and Polygon.
Definition at line 64 of file Shape.h.
References _rawSetVertex().
Referenced by Ellipse::sanitize(), MappingGui::setValue(), setVertex(), and Ellipse::setVertex().
   {
     _rawSetVertex(i, v);
   }
virtual void MShape::setVertex (int i, qreal x, qreal y) virtual
Definition at line 69 of file Shape.h.
References setVertex().
   {
     setVertex(i, QPointF(x, y));
   }
virtual QString MShape::getType () const pure virtual
Implemented in Ellipse, Mesh, Triangle, and Quad.
Referenced by ProjectWriter::writeItem(), and ProjectWriter::writeShapeVertices().
virtual bool MShape::includesPoint (qreal x, qreal y) virtual
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
Reimplemented in Ellipse.
Definition at line 80 of file Shape.h.
{
     return includesPoint(QPoint(x, y));
   }
virtual bool MShape::includesPoint (const QPointF & p) pure virtual
Implemented in Ellipse, and Polygon.
void MShape::translate (const QPointF & offset) virtual
Translate all vertices of shape by the vector (x,y).
Definition at line 34 of file Shape.cpp.
References vertices.
 {
   // We can feel free to translate every vertex without check by default.
   for (QVector<QPointF>::iterator it = vertices.begin(); it != vertices.end(); ++it)
     *it += offset;
 }
void MShape::copyFrom (const MShape & shape) virtual
Definition at line 22 of file Shape.cpp.
References vertices.
Referenced by clone().
 {
   // Just copy vertices.
   vertices = shape.vertices;
 }
MShape * MShape::clone () const virtual
Definition at line 28 of file Shape.cpp.
References _create(), and copyFrom().
{
   MShape* copyShape = _create();
   copyShape->copyFrom(*this);
   return copyShape;
 }
void MShape::_addVertex (const QPointF & vertex) protected
Definition at line 96 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), Ellipse::Ellipse(), Quad::Quad(), and Triangle::Triangle().
   {
     vertices.push_back(vertex);
   }
void MShape::_rawSetVertex (int i, const QPointF & v) protected
Definition at line 101 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), setVertex(), Polygon::setVertex(), Mesh::setVertex(), and Ellipse::setVertex().
   {
     vertices[i] = v;
   }
virtual MShape* MShape::_create () const protected pure virtual
Returns a new MShape (using default constructor).
Implemented in Ellipse, Mesh, Triangle, and Quad.
Referenced by clone().
Member Data Documentation
QVector<QPointF> MShape::vertices protected
Definition at line 94 of file Shape.h.
Referenced by Mesh::_reorderVertices(), copyFrom(), getVertex(), Mesh::getVertex2d(), Mesh::init(), nVertices(), Mesh::removeColumn(), Mesh::removeRow(), Mesh::setVertex2d(), Polygon::toPolygon(), and translate().
The documentation for this class was generated from the following files:
Shape.h
Shape.cpp