MapMap: Color Class Reference
Color Class Reference
#include <Paint.h>
Public Types
typedef QSharedPointer< Paint > ptr
Public Member Functions
Color (uid id=NULL_UID)
Color (const QColor &color_, uid id=NULL_UID)
QColor getColor () const
virtual void setColor (const QColor &color_)
virtual QString getType () const
virtual void build ()
virtual void update ()
This method should be called at each call of draw().
virtual void play ()
Starts playback.
virtual void pause ()
Pauses playback.
virtual void rewind ()
Rewinds.
virtual void lockMutex ()
Locks mutex (default = no effect).
virtual void unlockMutex ()
Unlocks mutex (default = no effect).
void setName (const QString &name)
QString getName () const
uid getId () const
float getOpacity () const
void setOpacity (float opacity)
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Attributes
QColor color
Detailed Description
Definition at line 100 of file Paint.h.
Member Typedef Documentation
typedef QSharedPointer<Paint> Paint::ptr inherited
Definition at line 57 of file Paint.h.
Constructor & Destructor Documentation
Color::Color (uid id = NULL_UID)
Definition at line 106 of file Paint.h.
 : Paint(id) {}
Color::Color (const QColor & color_, uid id = NULL_UID)
Definition at line 107 of file Paint.h.
 : Paint(id), color(color_) {}
Member Function Documentation
QColor Color::getColor () const
Definition at line 109 of file Paint.h.
References color.
Referenced by ColorGraphicsItem::_prePaint(), and ProjectWriter::writeItem().
 { return color; }
virtual void Color::setColor (const QColor & color_) virtual
Definition at line 110 of file Paint.h.
 { color = color_; }
virtual QString Color::getType () const virtual
Implements Paint.
Definition at line 112 of file Paint.h.
 { return "color"; }
static const UidAllocator& Paint::getUidAllocator () static inherited
Definition at line 61 of file Paint.h.
References Paint::allocator.
Referenced by MainWindow::createColorPaint(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMediaPaint(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deletePaint().
 { return allocator; }
virtual void Paint::build () virtual inherited
Reimplemented in Media, and Image.
Definition at line 63 of file Paint.h.
 {}
virtual void Paint::update () virtual inherited
This method should be called at each call of draw().
Reimplemented in Media.
Definition at line 66 of file Paint.h.
 {}
virtual void Paint::play () virtual inherited
Starts playback.
Reimplemented in Media.
Definition at line 69 of file Paint.h.
 {}
virtual void Paint::pause () virtual inherited
Pauses playback.
Reimplemented in Media.
Definition at line 72 of file Paint.h.
 {}
virtual void Paint::rewind () virtual inherited
Rewinds.
Reimplemented in Media.
Definition at line 75 of file Paint.h.
 {}
virtual void Paint::lockMutex () virtual inherited
Locks mutex (default = no effect).
Reimplemented in Media.
Definition at line 78 of file Paint.h.
 {}
virtual void Paint::unlockMutex () virtual inherited
Unlocks mutex (default = no effect).
Reimplemented in Media.
Definition at line 81 of file Paint.h.
 {}
void Paint::setName (const QString & name) inherited
Definition at line 83 of file Paint.h.
References Paint::_name.
 { _name = name; }
QString Paint::getName () const inherited
Definition at line 84 of file Paint.h.
References Paint::_name.
 { return _name; }
uid Paint::getId () const inherited
Definition at line 85 of file Paint.h.
References Paint::_id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
float Paint::getOpacity () const inherited
Definition at line 87 of file Paint.h.
References Paint::_opacity.
 { return _opacity; }
void Paint::setOpacity (float opacity) inherited
Definition at line 88 of file Paint.h.
References Paint::_opacity.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
Member Data Documentation
QColor Color::color protected
Definition at line 103 of file Paint.h.
Referenced by getColor().
The documentation for this class was generated from the following file:
Paint.h