MapMap: Quad Class Reference
Quad Class Reference
Four-vertex shape.
#include <Shape.h>
Public Types
typedef QSharedPointer< MShape > ptr
Public Member Functions
Quad ()
Quad (QPointF p1, QPointF p2, QPointF p3, QPointF p4)
virtual ~Quad ()
virtual QString getType () const
virtual QPolygonF toPolygon () const
virtual bool includesPoint (const QPointF &p)
virtual bool includesPoint (qreal x, qreal y)
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
virtual void setVertex (int i, const QPointF &v)
virtual void setVertex (int i, qreal x, qreal y)
virtual void build ()
int nVertices () const
QPointF getVertex (int i) const
virtual void translate (const QPointF &offset)
Translate all vertices of shape by the vector (x,y).
virtual void copyFrom (const MShape &shape)
virtual MShape * clone () const
Protected Member Functions
virtual MShape * _create () const
Returns a new MShape (using default constructor).
QVector< QLineF > _getSegments () const
Returns all line segments of the polygon.
void _addVertex (const QPointF &vertex)
void _rawSetVertex (int i, const QPointF &v)
Static Protected Member Functions
static QVector< QLineF > _getSegments (const QPolygonF &polygon)
Returns all line segments of a polygon.
static void _constrainVertex (const QPolygonF &polygon, int i, QPointF &v)
Makes sure vertex v as the i-th point of polygon stays inside the polygon.
Protected Attributes
QVector< QPointF > vertices
Detailed Description
Four-vertex shape.
Definition at line 142 of file Shape.h.
Member Typedef Documentation
typedef QSharedPointer<MShape> MShape::ptr inherited
Definition at line 47 of file Shape.h.
Constructor & Destructor Documentation
Quad::Quad ()
Definition at line 145 of file Shape.h.
Referenced by _create().
 {}
Quad::Quad (QPointF p1, QPointF p2, QPointF p3, QPointF p4)
Definition at line 146 of file Shape.h.
References MShape::_addVertex().
   {
     _addVertex(p1);
     _addVertex(p2);
     _addVertex(p3);
     _addVertex(p4);
   }
virtual Quad::~Quad () virtual
Definition at line 153 of file Shape.h.
 {}
Member Function Documentation
virtual QString Quad::getType () const virtual
Implements MShape.
Reimplemented in Mesh.
Definition at line 155 of file Shape.h.
 { return "quad"; }
virtual MShape* Quad::_create () const protected virtual
Returns a new MShape (using default constructor).
Implements MShape.
Reimplemented in Mesh.
Definition at line 159 of file Shape.h.
References Quad().
 { return new Quad(); }
QPolygonF Polygon::toPolygon () const virtual inherited
Reimplemented in Mesh.
Definition at line 119 of file Shape.cpp.
References MShape::vertices.
Referenced by MeshTextureGraphicsItem::_doDrawOutput(), PolygonColorGraphicsItem::_doPaint(), Polygon::_getSegments(), PolygonControlPainter::_paintShape(), Util::drawControlsPolygon(), Util::drawControlsQuad(), Polygon::includesPoint(), Polygon::setVertex(), Mesh::setVertex(), PolygonColorGraphicsItem::shape(), and PolygonTextureGraphicsItem::shape().
 {
   QPolygonF polygon;
   for (QVector<QPointF>::const_iterator it = vertices.begin() ;
       it != vertices.end(); ++it)
   {
     polygon.append(*it);
   }
   return polygon;
 }
virtual bool Polygon::includesPoint (const QPointF & p) virtual inherited
Implements MShape.
Definition at line 121 of file Shape.h.
References Polygon::toPolygon().
{
     return toPolygon().containsPoint(p, Qt::OddEvenFill);
   }
virtual bool MShape::includesPoint (qreal x, qreal y) virtual inherited
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
Reimplemented in Ellipse.
Definition at line 80 of file Shape.h.
{
     return includesPoint(QPoint(x, y));
   }
void Polygon::setVertex (int i, const QPointF & v) virtual inherited
Reimplemented from MShape.
Reimplemented in Mesh.
Definition at line 41 of file Shape.cpp.
References Polygon::_constrainVertex(), MShape::_rawSetVertex(), and Polygon::toPolygon().
 {
   // Constrain vertex.
   QPointF realV = v;
   _constrainVertex(toPolygon(), i, realV);
   // Really set the vertex.
   _rawSetVertex(i, realV);
 }
virtual void MShape::setVertex (int i, qreal x, qreal y) virtual inherited
Definition at line 69 of file Shape.h.
References MShape::setVertex().
   {
     setVertex(i, QPointF(x, y));
   }
QVector< QLineF > Polygon::_getSegments () const protected inherited
Returns all line segments of the polygon.
Definition at line 106 of file Shape.cpp.
References Polygon::toPolygon().
Referenced by Polygon::_constrainVertex().
 {
   return _getSegments(toPolygon());
 }
QVector< QLineF > Polygon::_getSegments (const QPolygonF & polygon) static protected inherited
Returns all line segments of a polygon.
Definition at line 111 of file Shape.cpp.
 {
   QVector<QLineF> segments;
   for (int i=0; i<polygon.size(); i++)
     segments.push_back(QLineF(polygon.at(i), polygon.at( (i+1) % polygon.size() )));
   return segments;
 }
void Polygon::_constrainVertex (const QPolygonF & polygon, int i, QPointF & v) static protected inherited
Makes sure vertex v as the i-th point of polygon stays inside the polygon.
Definition at line 50 of file Shape.cpp.
References Polygon::_getSegments(), and wrapAround().
Referenced by Polygon::setVertex(), and Mesh::setVertex().
 {
   // Weird, but nothing to do.
   if (polygon.size() <= 3)
     return;
   // Save previous position of vertex.
   QPointF prevV = polygon.at(i);
   // Look at the two adjunct segments to vertex i and see if they
   // intersect with any non-adjacent segments.
   // Construct the list of segments (with the new candidate vertex).
   QVector<QLineF> segments = _getSegments(polygon);
   int prev = wrapAround(i - 1, segments.size());
   int next = wrapAround(i + 1, segments.size());
   segments[prev] = QLineF(polygon.at(prev), v);
   segments[i]    = QLineF(v, polygon.at(next));
   // We now stretch segments a little bit to cope with approximation errors.
   for (QVector<QLineF>::Iterator it = segments.begin(); it != segments.end(); ++it)
   {
     QLineF& seg = *it;
     QPointF p1 = seg.p1();
     QPointF p2 = seg.p2();
     seg.setP1( p1 + (p1 - p2) * 0.35f);
     seg.setP2( p2 + (p2 - p1) * 0.35f);
   }
   // For each adjunct segment.
   for (int adj=0; adj<2; adj++)
   {
     int idx = wrapAround(i + adj - 1, segments.size());
     for (int j=0; j<segments.size(); j++)
     {
       // If the segment to compare to is valid (ie. if it is not
       // the segment itself nor an adjacent one) then check for
       // intersection.
       if (j != idx &&
           j != wrapAround(idx-1, segments.size()) &&
           j != wrapAround(idx+1, segments.size()))
       {
         QPointF intersection;
         if (segments[idx].intersect(segments[j], &intersection) == QLineF::BoundedIntersection)
         {
           // Rearrange segments with new position at intersection point.
           v = intersection;
           segments[prev] = QLineF(polygon.at(prev), v);
           segments[i]    = QLineF(v, polygon.at(next));
         }
       }
     }
   }
 }
virtual void MShape::build () virtual inherited
Definition at line 55 of file Shape.h.
 {}
int MShape::nVertices () const inherited
Definition at line 57 of file Shape.h.
References MShape::vertices.
Referenced by MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MappingGui::_updateShapeProperty(), Mesh::addColumn(), Mesh::addRow(), Util::drawControlsVertices(), Ellipse::hasCenterControl(), and ProjectWriter::writeShapeVertices().
 { return vertices.size(); }
QPointF MShape::getVertex (int i) const inherited
Definition at line 59 of file Shape.h.
References MShape::vertices.
Referenced by MeshTextureGraphicsItem::_buildCacheQuadItem(), MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MeshTextureGraphicsItem::_split(), MappingGui::_updateShapeProperty(), Util::drawControlsVertices(), Ellipse::getCenter(), Ellipse::getHorizontalAxis(), Ellipse::getVerticalAxis(), Ellipse::sanitize(), MappingGui::setValue(), Ellipse::setVertex(), and ProjectWriter::writeShapeVertices().
   {
     return vertices[i];
   }
void MShape::translate (const QPointF & offset) virtual inherited
Translate all vertices of shape by the vector (x,y).
Definition at line 34 of file Shape.cpp.
References MShape::vertices.
 {
   // We can feel free to translate every vertex without check by default.
   for (QVector<QPointF>::iterator it = vertices.begin(); it != vertices.end(); ++it)
     *it += offset;
 }
void MShape::copyFrom (const MShape & shape) virtual inherited
Definition at line 22 of file Shape.cpp.
References MShape::vertices.
Referenced by MShape::clone().
 {
   // Just copy vertices.
   vertices = shape.vertices;
 }
MShape * MShape::clone () const virtual inherited
Definition at line 28 of file Shape.cpp.
References MShape::_create(), and MShape::copyFrom().
{
   MShape* copyShape = _create();
   copyShape->copyFrom(*this);
   return copyShape;
 }
void MShape::_addVertex (const QPointF & vertex) protected inherited
Definition at line 96 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), Ellipse::Ellipse(), Quad(), and Triangle::Triangle().
   {
     vertices.push_back(vertex);
   }
void MShape::_rawSetVertex (int i, const QPointF & v) protected inherited
Definition at line 101 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), MShape::setVertex(), Polygon::setVertex(), Mesh::setVertex(), and Ellipse::setVertex().
   {
     vertices[i] = v;
   }
Member Data Documentation
QVector<QPointF> MShape::vertices protected inherited
Definition at line 94 of file Shape.h.
Referenced by Mesh::_reorderVertices(), MShape::copyFrom(), MShape::getVertex(), Mesh::getVertex2d(), Mesh::init(), MShape::nVertices(), Mesh::removeColumn(), Mesh::removeRow(), Mesh::setVertex2d(), Polygon::toPolygon(), and MShape::translate().
The documentation for this class was generated from the following file:
Shape.h