MapMap: DeleteMappingCommand Class Reference
DeleteMappingCommand Class Reference
#include <Commands.h>
Public Member Functions
DeleteMappingCommand (MainWindow *mainWindow, uid mappingId, QUndoCommand *parent=0)
void undo ()
void redo ()
Private Attributes
MainWindow * m_mainWindow
Mapping::ptr m_mappingPtr
uid m_mappingId
Detailed Description
Definition at line 112 of file Commands.h.
Constructor & Destructor Documentation
DeleteMappingCommand::DeleteMappingCommand (MainWindow * mainWindow, uid mappingId, QUndoCommand * parent = 0)
Definition at line 138 of file Commands.cpp.
References m_mainWindow, and m_mappingId.
                                                                                                       :
   QUndoCommand(parent)
 {
   setText(QObject::tr("Delete mapping"));
   m_mainWindow = mainWindow;
   m_mappingId = mappingId;
 }
Member Function Documentation
void DeleteMappingCommand::undo ()
Definition at line 146 of file Commands.cpp.
References MappingManager::addMapping(), MainWindow::addMappingItem(), MainWindow::getMappingManager(), m_mainWindow, and m_mappingPtr.
 {
   if(m_mappingPtr != NULL)
     {
       uint currentId = m_mainWindow->getMappingManager().addMapping(m_mappingPtr);
       m_mainWindow->addMappingItem(currentId);
     }
 }
void DeleteMappingCommand::redo ()
Definition at line 155 of file Commands.cpp.
References MainWindow::deleteMapping(), MappingManager::getMappingById(), MainWindow::getMappingManager(), m_mainWindow, m_mappingId, and m_mappingPtr.
 {
   m_mappingPtr = m_mainWindow->getMappingManager().getMappingById(m_mappingId);
   m_mainWindow->deleteMapping(m_mappingId);
 }
Member Data Documentation
MainWindow* DeleteMappingCommand::m_mainWindow private
Definition at line 120 of file Commands.h.
Referenced by DeleteMappingCommand(), redo(), and undo().
Mapping::ptr DeleteMappingCommand::m_mappingPtr private
Definition at line 121 of file Commands.h.
Referenced by redo(), and undo().
uid DeleteMappingCommand::m_mappingId private
Definition at line 122 of file Commands.h.
Referenced by DeleteMappingCommand(), and redo().
The documentation for this class was generated from the following files:
Commands.h
Commands.cpp