MapMap: MappingManager Class Reference
MappingManager Class Reference
This is a container class for all the paints and mappings ie.
#include <MappingManager.h>
Public Member Functions
MappingManager ()
Constructor.
QMap< uid, Mapping::ptr > getPaintMappings (const Paint::ptr paint) const
Returns the list of mappings associated with given paint.
QMap< uid, Mapping::ptr > getPaintMappingsById (uid paintId) const
Returns the list of mappings associated with given paint uid.
uid addPaint (Paint::ptr paint)
Adds a paint and returns its uid.
uid getPaintId (Paint::ptr paint) const
Returns the uid of a paint.
bool removePaint (uid paintId)
Removes a paint of given uid.
bool replacePaintMappings (Paint::ptr oldpaint, Paint::ptr newpaint)
DEPRECATED.
int nPaints () const
Returns the number of paints.
Paint::ptr getPaint (int i)
Returns the i-th paint in the vector. Good for iterating over all paints.
Paint::ptr getPaintById (uid id)
Returns paint with given uid.
uid addMapping (Mapping::ptr mapping)
Adds a mapping and returns its uid.
bool removeMapping (uid mappingId)
Removes a mapping of given uid.
int nMappings () const
Returns the number of mappings.
Mapping::ptr getMapping (int i)
Returns the i-th mapping in the vector.
Mapping::ptr getMappingById (uid id)
Returns mapping with given uid.
void reorderMappings (QVector< uid > mappingIds)
Reorders the mappings according to given list of uids. QVector needs to.
QVector< Mapping::ptr > getVisibleMappings () const
void clearAll ()
Private Attributes
QVector< Paint::ptr > paintVector
Container for all paints.
QMap< uid, Paint::ptr > paintMap
Maps from uids to paints.
QVector< Mapping::ptr > mappingVector
Container for all mappings (ordered from bottom layer to top layer).
QMap< uid, Mapping::ptr > mappingMap
Maps from uids to mappings.
Detailed Description
This is a container class for all the paints and mappings ie.
the main model object that allows CRUD over paints and mappings.
Definition at line 34 of file MappingManager.h.
Constructor & Destructor Documentation
MappingManager::MappingManager ()
Constructor.
Definition at line 24 of file MappingManager.cpp.
 {
   // TODO Auto-generated constructor stub
 }
Member Function Documentation
QMap< uid, Mapping::ptr > MappingManager::getPaintMappings (const Paint::ptr paint) const
Returns the list of mappings associated with given paint.
Definition at line 30 of file MappingManager.cpp.
References mappingVector.
Referenced by getPaintMappingsById(), removePaint(), MainWindow::removePaintItem(), and replacePaintMappings().
 {
   QMap<uid, Mapping::ptr> paintMappings;
   for (QVector<Mapping::ptr>::const_iterator it = mappingVector.begin(); it != mappingVector.end(); ++it)
   {
     if ((*it)->getPaint() == paint)
       paintMappings[(*it)->getId()] = *it;
   }
   return paintMappings;
 }
QMap< uid, Mapping::ptr > MappingManager::getPaintMappingsById (uid paintId) const
Returns the list of mappings associated with given paint uid.
Definition at line 41 of file MappingManager.cpp.
References getPaintMappings(), and paintMap.
 {
   return getPaintMappings( paintMap[paintId] );
 }
uid MappingManager::addPaint (Paint::ptr paint)
Adds a paint and returns its uid.
Definition at line 46 of file MappingManager.cpp.
References paintMap, and paintVector.
Referenced by MainWindow::createColorPaint(), and MainWindow::createMediaPaint().
 {
   paintVector.push_back(paint);
   paintMap[paint->getId()] = paint;
   return paint->getId();
 }
uid MappingManager::getPaintId (Paint::ptr paint) const
Returns the uid of a paint.
Definition at line 65 of file MappingManager.h.
Referenced by MainWindow::handlePaintChanged().
 { return paintMap.key(paint); }
bool MappingManager::removePaint (uid paintId)
Removes a paint of given uid.
Definition at line 53 of file MappingManager.cpp.
References getPaintById(), getPaintMappings(), paintMap, paintVector, and removeMapping().
Referenced by MainWindow::removePaintItem().
 {
   // Make sure the paint to which this paint refers to exists in the manager.
   Paint::ptr paint = getPaintById(paintId);
   if (paint)
   {
     // Remove all mappings associated with paint.
     QMap<uid, Mapping::ptr> paintMappings = getPaintMappings(paint);
     for (QMap<uid, Mapping::ptr>::const_iterator it = paintMappings.constBegin();
          it != paintMappings.constEnd(); ++it)
       removeMapping(it.key());
     // Remove paint.
     int idx = paintVector.lastIndexOf(paint);
     Q_ASSERT( idx != -1 ); // Q_ASSERT(mappingVector.contains(mapping));
     paintVector.remove(idx);
     paintMap.remove(paintId);
     return true;
   }
   return false;
 }
bool MappingManager::replacePaintMappings (Paint::ptr oldpaint, Paint::ptr newpaint)
DEPRECATED.
Definition at line 77 of file MappingManager.cpp.
References getPaintMappings().
 {
   // Make sure the paint to which this paint refers to exists in the manager.
   if (oldpaint && newpaint)
   {
     QMap<uid, Mapping::ptr> paintMappings = getPaintMappings(oldpaint);
     for (QMap<uid, Mapping::ptr>::const_iterator it = paintMappings.constBegin();
          it != paintMappings.constEnd(); ++it) {
       Mapping::ptr mapping = it.value();
       mapping->setPaint(newpaint);
     }
     return true;
   }
   return false;
 }
int MappingManager::nPaints () const
Returns the number of paints.
Definition at line 74 of file MappingManager.h.
Referenced by MainWindow::pause(), MainWindow::play(), MainWindow::rewind(), and ProjectWriter::writeFile().
 { return paintVector.size(); }
Paint::ptr MappingManager::getPaint (int i)
Returns the i-th paint in the vector. Good for iterating over all paints.
Definition at line 77 of file MappingManager.h.
Referenced by MainWindow::pause(), MainWindow::play(), MainWindow::rewind(), and ProjectWriter::writeFile().
 { return paintVector[i]; }
Paint::ptr MappingManager::getPaintById (uid id)
Returns paint with given uid.
Definition at line 80 of file MappingManager.h.
Referenced by MainWindow::addColorPaint(), MainWindow::addEllipse(), MainWindow::addMesh(), MainWindow::addPaintItem(), MainWindow::addTriangle(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), MainWindow::importMediaFile(), removePaint(), MainWindow::removePaintItem(), MainWindow::renamePaint(), MainWindow::setTexturePlayState(), MainWindow::setTextureRate(), MainWindow::setTextureUri(), and MainWindow::setTextureVolume().
 { return paintMap[id]; }
uid MappingManager::addMapping (Mapping::ptr mapping)
Adds a mapping and returns its uid.
Definition at line 94 of file MappingManager.cpp.
References mappingMap, mappingVector, and paintVector.
Referenced by MainWindow::addEllipse(), MainWindow::addMesh(), MainWindow::addTriangle(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), MainWindow::duplicateMapping(), AddShapesCommand::redo(), and DeleteMappingCommand::undo().
 {
   // Make sure the paint to which this mapping refers to exists in the manager.
   Q_ASSERT ( paintVector.contains(mapping->getPaint()) );
   mappingVector.push_back(mapping);
   mappingMap[mapping->getId()] = mapping;
   return mapping->getId();
 }
bool MappingManager::removeMapping (uid mappingId)
Removes a mapping of given uid.
Definition at line 105 of file MappingManager.cpp.
References getMappingById(), mappingMap, and mappingVector.
Referenced by MainWindow::removeMappingItem(), and removePaint().
 {
   // Make sure the paint to which this mapping refers to exists in the manager.
   Mapping::ptr mapping = getMappingById(mappingId);
   if (mapping)
   {
     int idx = mappingVector.lastIndexOf(mapping);
     Q_ASSERT( idx != -1 ); // Q_ASSERT(mappingVector.contains(mapping));
     mappingVector.remove(idx);
     mappingMap.remove(mappingId);
     return true;
   }
   return false;
 }
int MappingManager::nMappings () const
Returns the number of mappings.
Definition at line 89 of file MappingManager.h.
Referenced by MapperGLCanvas::_glueVertex(), and ProjectWriter::writeFile().
 { return mappingVector.size(); }
Mapping::ptr MappingManager::getMapping (int i)
Returns the i-th mapping in the vector.
Good for iterating over all mappings. Vector is ordered from bottom to top layer.
Definition at line 95 of file MappingManager.h.
Referenced by MapperGLCanvas::_glueVertex(), and ProjectWriter::writeFile().
 { return mappingVector[i]; }
Mapping::ptr MappingManager::getMappingById (uid id)
Returns mapping with given uid.
Definition at line 98 of file MappingManager.h.
Referenced by MainWindow::addMappingItem(), MainWindow::duplicateMapping(), DestinationGLCanvas::getShapeFromMappingId(), SourceGLCanvas::getShapeFromMappingId(), MainWindow::handleMappingItemSelectionChanged(), DeleteMappingCommand::redo(), removeMapping(), MainWindow::removeMappingItem(), MainWindow::renameMapping(), MainWindow::setMappingVisible(), and AddShapesCommand::undo().
 { return mappingMap[id]; }
void MappingManager::reorderMappings (QVector< uid > mappingIds)
Reorders the mappings according to given list of uids. QVector needs to.
Definition at line 148 of file MappingManager.cpp.
References mappingMap, and mappingVector.
Referenced by MainWindow::handleMappingIndexesMoved().
 {
   // Both vector needs to have the same size.
   Q_ASSERT( mappingIds.size() == mappingVector.size() );
   mappingVector.clear();
   int depth = 0;
   for (QVector<uid>::iterator it = mappingIds.begin(); it != mappingIds.end(); ++it)
   {
     // Uid should be a key of the mappingMap.
     Q_ASSERT( mappingMap.contains(*it) );
     // Makes sure the uids are not repeated.
     Q_ASSERT( !mappingVector.contains(mappingMap[*it]) );
     // Adds the mapping at the right place in the vector.
     Mapping::ptr mapping = mappingMap[*it];
     mapping->setDepth(depth);
     mappingVector.push_back( mapping );
     depth++;
   }
 }
QVector< Mapping::ptr > MappingManager::getVisibleMappings () const
Definition at line 122 of file MappingManager.cpp.
References mappingVector.
Referenced by MapperGLCanvas::mousePressEvent().
 {
   QVector<Mapping::ptr> visible;
   // First pass: check if one of the mappings is in solo mode.
   bool hasSolo = false;
   for (QVector<Mapping::ptr>::const_iterator it = mappingVector.begin(); it != mappingVector.end(); ++it)
   {
     if ((*it)->isSolo())
     {
       hasSolo = true;
       break;
     }
   }
   // Second pass: fill the visible vector.
   for (QVector<Mapping::ptr>::const_iterator it = mappingVector.begin(); it != mappingVector.end(); ++it)
   {
     // Solo has priority over invisible (mute)
     if ( (hasSolo && (*it)->isSolo() && (*it)->isVisible()) || (!hasSolo && (*it)->isVisible()) )
       visible.push_back(*it);
   }
   return visible;
 }
void MappingManager::clearAll ()
Definition at line 173 of file MappingManager.cpp.
References mappingMap, mappingVector, paintMap, and paintVector.
Referenced by MainWindow::clearProject().
 {
   paintVector.clear();
   mappingVector.clear();
   paintMap.clear();
   mappingMap.clear();
 }
Member Data Documentation
QVector<Paint::ptr> MappingManager::paintVector private
Container for all paints.
Definition at line 43 of file MappingManager.h.
Referenced by addMapping(), addPaint(), clearAll(), and removePaint().
QMap<uid, Paint::ptr> MappingManager::paintMap private
Maps from uids to paints.
Definition at line 46 of file MappingManager.h.
Referenced by addPaint(), clearAll(), getPaintMappingsById(), and removePaint().
QVector<Mapping::ptr> MappingManager::mappingVector private
Container for all mappings (ordered from bottom layer to top layer).
Definition at line 49 of file MappingManager.h.
Referenced by addMapping(), clearAll(), getPaintMappings(), getVisibleMappings(), removeMapping(), and reorderMappings().
QMap<uid, Mapping::ptr> MappingManager::mappingMap private
Maps from uids to mappings.
Definition at line 52 of file MappingManager.h.
Referenced by addMapping(), clearAll(), removeMapping(), and reorderMappings().
The documentation for this class was generated from the following files:
MappingManager.h
MappingManager.cpp