MapMap: MapperGLCanvas Class Reference
MapperGLCanvas Class Reference abstract
Mother class for OpenGL canvases that allow the display and controls of shapes and vertices.
#include <MapperGLCanvas.h>
Public Slots
void updateCanvas ()
void deselectVertices ()
void deselectAll ()
void wheelEvent (QWheelEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
bool eventFilter (QObject *target, QEvent *event)
Signals
void shapeChanged (MShape *)
void imageChanged ()
Public Member Functions
MapperGLCanvas (MainWindow *mainWindow, QWidget *parent=0, const QGLWidget *shareWidget=0, QGraphicsScene *scene=0)
Constructor.
virtual ~MapperGLCanvas ()
virtual bool isOutput () const =0
Returns shape associated with mapping id.
virtual MShape::ptr getShapeFromMappingId (uid mappingId) const =0
virtual QSharedPointer
< ShapeGraphicsItem > getShapeGraphicsItemFromMappingId (uid mappingId) const =0
MShape::ptr getCurrentShape ()
QSharedPointer< ShapeGraphicsItem > getCurrentShapeGraphicsItem ()
void drawForeground (QPainter *painter, const QRectF &rect)
MainWindow * getMainWindow () const
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
bool hasActiveVertex () const
Returns true iff one of the vertices is currently active.
int getActiveVertexIndex () const
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
void setActiveVertexIndex (int activeVertex)
Set the currently active vertex.
bool shapeGrabbed () const
bool vertexGrabbed () const
qreal getZoomFactor () const
void currentShapeWasChanged ()
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Static Public Attributes
static const int NO_VERTEX = -1
Protected Member Functions
void _glueVertex (QPointF *p)
Private Attributes
MainWindow * _mainWindow
Draws the shapes and controls over the canvas.
QPoint _mousePressedPosition
QPointF _grabbedObjectStartScenePosition
bool _vertexGrabbed
int _activeVertex
bool _shapeGrabbed
bool _shapeFirstGrab
int _zoomLevel
QUndoStack * undoStack
Detailed Description
Mother class for OpenGL canvases that allow the display and controls of shapes and vertices.
Provides common functionality to both main sublasses: SourceGLCanvas and DestinationGLCanvas.
Definition at line 47 of file MapperGLCanvas.h.
Constructor & Destructor Documentation
MapperGLCanvas::MapperGLCanvas (MainWindow * mainWindow, QWidget * parent = 0, const QGLWidget * shareWidget = 0, QGraphicsScene * scene = 0)
Constructor.
Definition at line 26 of file MapperGLCanvas.cpp.
   : QGraphicsView(parent),
     _mainWindow(mainWindow),
     _vertexGrabbed(false),
     _activeVertex(NO_VERTEX),
     _shapeGrabbed(false), // comment out?
     _shapeFirstGrab(false), // comment out?
     _zoomLevel(0)
 {
   // For now clicking on the window doesn't do anything.
   setDragMode(QGraphicsView::NoDrag);
   setRenderHints(QPainter::Antialiasing | QPainter::TextAntialiasing |
                  QPainter::HighQualityAntialiasing | QPainter::SmoothPixmapTransform);
   setResizeAnchor(AnchorViewCenter);
   setInteractive(true);
   //setFrameStyle(Sunken | StyledPanel);
   // TODO: check this
   // setOptimizationFlags(QGraphicsView::DontSavePainterState);
   //setViewportUpdateMode(QGraphicsView::FullViewportUpdate);
   setTransformationAnchor(QGraphicsView::AnchorUnderMouse);
   resetTransform();
   // setAcceptDrops(true);
   // Render with OpenGL.
   setViewport(new QGLWidget(QGLFormat(QGL::SampleBuffers), this, shareWidget));
   setViewportUpdateMode(QGraphicsView::FullViewportUpdate);
   // TODO: do we need to delete scene (or call new QGraphicsScene(this)?)
   setScene(scene ? scene : new QGraphicsScene);
   // Black background.
   this->scene()->setBackgroundBrush(Qt::black);
 }
virtual MapperGLCanvas::~MapperGLCanvas () virtual
Definition at line 53 of file MapperGLCanvas.h.
 {}
Member Function Documentation
virtual bool MapperGLCanvas::isOutput () const pure virtual
Returns shape associated with mapping id.
Implemented in SourceGLCanvas, and DestinationGLCanvas.
Referenced by mousePressEvent().
virtual MShape::ptr MapperGLCanvas::getShapeFromMappingId (uid mappingId) const pure virtual
Implemented in SourceGLCanvas, and DestinationGLCanvas.
Referenced by getCurrentShape(), and mousePressEvent().
virtual QSharedPointer<ShapeGraphicsItem> MapperGLCanvas::getShapeGraphicsItemFromMappingId (uid mappingId) const pure virtual
Implemented in SourceGLCanvas, and DestinationGLCanvas.
Referenced by getCurrentShapeGraphicsItem().
MShape::ptr MapperGLCanvas::getCurrentShape ()
Definition at line 64 of file MapperGLCanvas.cpp.
References getShapeFromMappingId(), and MainWindow::instance().
Referenced by _glueVertex(), currentShapeWasChanged(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), and TransformShapeCommand::TransformShapeCommand().
 {
   return getShapeFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
QSharedPointer< ShapeGraphicsItem > MapperGLCanvas::getCurrentShapeGraphicsItem ()
Definition at line 69 of file MapperGLCanvas.cpp.
References getShapeGraphicsItemFromMappingId(), and MainWindow::instance().
Referenced by drawForeground().
 {
   return getShapeGraphicsItemFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
void MapperGLCanvas::drawForeground (QPainter * painter, const QRectF & rect)
Definition at line 75 of file MapperGLCanvas.cpp.
References _mainWindow, MainWindow::displayControls(), getActiveVertexIndex(), MainWindow::getCurrentMappingId(), getCurrentShapeGraphicsItem(), hasActiveVertex(), and NULL_UID.
Referenced by OutputGLCanvas::drawForeground().
 {
   Q_UNUSED(rect);
   if (_mainWindow->displayControls())
   {
     uid mid = _mainWindow->getCurrentMappingId();
     if (mid != NULL_UID)
     {
       // Use current shape graphics item to draw controls.
       ShapeGraphicsItem::ptr item = getCurrentShapeGraphicsItem();
       if (item)
       {
         QList<int> selected;
         if (hasActiveVertex())
           selected.push_back(getActiveVertexIndex());
         item->getControlPainter()->paint(painter, this, selected);
       }
     }
   }
 }
MainWindow* MapperGLCanvas::getMainWindow () const
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
The distance per coordinate is currently set in dist_stick variable.Returns pointer to main window.
Definition at line 75 of file MapperGLCanvas.h.
Referenced by OutputGLCanvas::drawForeground(), eventFilter(), DestinationGLCanvas::getShapeFromMappingId(), SourceGLCanvas::getShapeFromMappingId(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), OutputGLWindow::OutputGLWindow(), and OutputGLWindow::setFullScreen().
 { return _mainWindow; }
bool MapperGLCanvas::hasActiveVertex () const
Returns true iff one of the vertices is currently active.
Definition at line 78 of file MapperGLCanvas.h.
References _activeVertex, and NO_VERTEX.
Referenced by drawForeground(), keyPressEvent(), and mouseMoveEvent().
 { return _activeVertex != NO_VERTEX; }
int MapperGLCanvas::getActiveVertexIndex () const
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
Definition at line 81 of file MapperGLCanvas.h.
References _activeVertex.
Referenced by drawForeground(), and eventFilter().
 { return _activeVertex; }
void MapperGLCanvas::setActiveVertexIndex (int activeVertex)
Set the currently active vertex.
Definition at line 84 of file MapperGLCanvas.h.
References _activeVertex.
Referenced by eventFilter().
 { _activeVertex = activeVertex; }
bool MapperGLCanvas::shapeGrabbed () const
Definition at line 86 of file MapperGLCanvas.h.
References _shapeGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _shapeGrabbed; }
bool MapperGLCanvas::vertexGrabbed () const
Definition at line 87 of file MapperGLCanvas.h.
References _vertexGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _vertexGrabbed; }
qreal MapperGLCanvas::getZoomFactor () const
Definition at line 89 of file MapperGLCanvas.h.
References _zoomLevel, MM::ZOOM_FACTOR, MM::ZOOM_MAX, and MM::ZOOM_MIN.
Referenced by ShapeControlPainter::_paintVertices(), ShapeControlPainter::getRescaledShapeStroke(), and wheelEvent().
 { return qBound(qPow(MM::ZOOM_FACTOR, _zoomLevel), MM::ZOOM_MIN, MM::ZOOM_MAX); }
void MapperGLCanvas::currentShapeWasChanged ()
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Definition at line 96 of file MapperGLCanvas.cpp.
References getCurrentShape(), and shapeChanged().
Referenced by TransformShapeCommand::redo(), and TransformShapeCommand::undo().
 {
   emit shapeChanged(getCurrentShape().data());
 }
void MapperGLCanvas::shapeChanged (MShape *) signal
Referenced by currentShapeWasChanged().
void MapperGLCanvas::imageChanged () signal
void MapperGLCanvas::updateCanvas () slot
Definition at line 423 of file MapperGLCanvas.cpp.
 {
   update();
   scene()->update();
 }
void MapperGLCanvas::deselectVertices () slot
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are
Definition at line 454 of file MapperGLCanvas.cpp.
References _activeVertex, _vertexGrabbed, and NO_VERTEX.
Referenced by deselectAll(), and mousePressEvent().
 {
   _activeVertex = NO_VERTEX;
   _vertexGrabbed = false;
 }
void MapperGLCanvas::deselectAll () slot
Definition at line 460 of file MapperGLCanvas.cpp.
References _shapeFirstGrab, _shapeGrabbed, and deselectVertices().
Referenced by mousePressEvent().
 {
   deselectVertices();
   _shapeGrabbed = false;
   _shapeFirstGrab = false;
 }
void MapperGLCanvas::wheelEvent (QWheelEvent * event) slot
Definition at line 467 of file MapperGLCanvas.cpp.
References _zoomLevel, getZoomFactor(), MM::ZOOM_FACTOR, MM::ZOOM_MAX, and MM::ZOOM_MIN.
 {
   int deltaLevel = event->delta() / 120;
   qreal zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
   if (deltaLevel > 0)
   {
     // First check if we're already at max.
     while (deltaLevel && zoomFactor < MM::ZOOM_MAX) {
       _zoomLevel++;
       deltaLevel--;
       zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
     }
     zoomFactor = qMin(zoomFactor, MM::ZOOM_MAX);
   }
   else
   {
     // First check if we're already at min.
     while (deltaLevel && zoomFactor > MM::ZOOM_MIN) {
       _zoomLevel--;
       deltaLevel++;
       zoomFactor = qPow(MM::ZOOM_FACTOR, _zoomLevel);
     }
     zoomFactor = qMax(zoomFactor, MM::ZOOM_MIN);
   }
   // Re-bound zoom (for consistency).
   zoomFactor = getZoomFactor();
   // Apply zoom to view.
   QGraphicsView* view = scene()->views().first();
   view->resetMatrix();
   view->scale(zoomFactor, zoomFactor);
   view->update();
   // Accept wheel scrolling event.
   event->accept();
 }
void MapperGLCanvas::mousePressEvent (QMouseEvent * event) slot
Definition at line 103 of file MapperGLCanvas.cpp.
References _activeVertex, _grabbedObjectStartScenePosition, _mousePressedPosition, _shapeFirstGrab, _shapeGrabbed, _vertexGrabbed, deselectAll(), deselectVertices(), dist(), distSq(), getCurrentShape(), getMainWindow(), MainWindow::getMappingManager(), getShapeFromMappingId(), MappingManager::getVisibleMappings(), isOutput(), MainWindow::setCurrentMapping(), sq(), and MM::VERTEX_SELECT_RADIUS.
 {
   bool mousePressedOnSomething = false;
   _mousePressedPosition = event->pos();
   QPointF pos = mapToScene(event->pos());
   // Drag the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     // NOTE: This is a trick code to implement scroll hand drag using the middle button.
     QMouseEvent releaseEvent(QEvent::MouseButtonRelease, event->pos(), event->globalPos(), Qt::LeftButton, 0, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&releaseEvent);
     setDragMode(QGraphicsView::ScrollHandDrag);
     // We need to pretend it is actually the left button that was pressed!
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
                           Qt::LeftButton, event->buttons() | Qt::LeftButton, event->modifiers());
     QGraphicsView::mousePressEvent(&fakeEvent);
   }
   // Check for vertex selection first.
   else if (event->buttons() & Qt::LeftButton)
   {
     MShape::ptr shape = getCurrentShape();
     if (shape)
     {
       // Note: we compare with the square value for fastest computation of the distance
       int minDistance = sq(MM::VERTEX_SELECT_RADIUS);
       // Find the ID of the nearest vertex (from currently selected shape)
       for (int i = 0; i < shape->nVertices(); i++)
       {
         int dist = distSq(_mousePressedPosition, mapFromScene(shape->getVertex(i))); // squared distance
         if (dist < minDistance)
         {
           _activeVertex = i;
           minDistance = dist;
           _vertexGrabbed = true;
           mousePressedOnSomething = true;
           _grabbedObjectStartScenePosition = shape->getVertex(i);
         }
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Check for shape selection.
   if (event->buttons() & (Qt::LeftButton | Qt::RightButton)) // Add Right click for context menu
   {
     MShape::ptr selectedShape = getCurrentShape();
     // Possibility of changing shape in output by clicking on it.
     MappingManager manager = getMainWindow()->getMappingManager();
     QVector<Mapping::ptr> mappings = manager.getVisibleMappings();
     for (QVector<Mapping::ptr>::const_iterator it = mappings.end() - 1; it >= mappings.begin(); --it)
     {
       MShape::ptr shape = getShapeFromMappingId((*it)->getId());
       // Check if mouse was pressed on that shape.
       if (shape && shape->includesPoint(pos))
       {
         mousePressedOnSomething = true;
         // Deselect vertices.
         deselectVertices();
         // Change mapping (only available in destination).
         if (isOutput() && shape != selectedShape)
         {
           // Change current mapping.
           getMainWindow()->setCurrentMapping((*it)->getId());
           // Reset selected shape to new one.
           selectedShape = getCurrentShape();
         }
         break;
       }
     }
     // Grab the shape.
     if (event->buttons() & Qt::LeftButton) // This preserve me from duplicate code above
     {
       if (selectedShape && selectedShape->includesPoint(pos))
       {
         _shapeGrabbed = true;
         _shapeFirstGrab = true;
         _grabbedObjectStartScenePosition = pos;
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Deactivate.
   deselectAll();
 }
void MapperGLCanvas::mouseReleaseEvent (QMouseEvent * event) slot
Definition at line 208 of file MapperGLCanvas.cpp.
References _activeVertex, _glueVertex(), _mainWindow, _shapeGrabbed, _vertexGrabbed, TransformShapeCommand::RELEASE, MainWindow::stickyVertices(), and undoStack.
 {
   Q_UNUSED(event);
   // Wrap-up dragging the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
         Qt::LeftButton, event->buttons() & ~Qt::LeftButton, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&fakeEvent);
     setDragMode(QGraphicsView::NoDrag);
     setCursor(Qt::ArrowCursor);
   }
 //  // Click on vertex ==> select the vertex.
 //  if ((event->buttons() & Qt::LeftButton) && _mousePressedOnVertex)
 //  {
 //  }
   if (_vertexGrabbed)
   {
     // TODO : code repetition here!!!
     QPointF p = mapToScene(event->pos());
     // Stick to vertices.
     if (_mainWindow->stickyVertices())
       _glueVertex(&p);
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::RELEASE, _activeVertex, p));
   }
   else if (_shapeGrabbed)
   {
     undoStack->push(new TranslateShapeCommand(this, TransformShapeCommand::RELEASE, QPointF()));
   }
   _vertexGrabbed = false;
   _shapeGrabbed = false;
 }
void MapperGLCanvas::mouseMoveEvent (QMouseEvent * event) slot
Definition at line 244 of file MapperGLCanvas.cpp.
References _activeVertex, _glueVertex(), _mainWindow, _mousePressedPosition, _shapeFirstGrab, _shapeGrabbed, _vertexGrabbed, TransformShapeCommand::FREE, getCurrentShape(), getMainWindow(), MainWindow::getUndoStack(), hasActiveVertex(), MainWindow::stickyVertices(), and undoStack.
Referenced by OutputGLCanvas::mouseMoveEvent().
 {
   static QPoint lastMousePos;
   QPointF scenePos = mapToScene(event->pos());
   // Prepare to store commands
   undoStack = getMainWindow()->getUndoStack();
   // Vertex grab.
   if (_vertexGrabbed)
   {
     // std::cout << "Move event " << std::endl;
     MShape::ptr shape = getCurrentShape();
     if (shape && hasActiveVertex())
     {
 //      QPointF p = shape->getVertex(_activeVertex);
 //      // Set point to mouse coordinates.
 //      p.setX(pos.x());
 //      p.setY(pos.y());
       QPointF p = scenePos;
       // Stick to vertices.
       if (_mainWindow->stickyVertices())
         _glueVertex(&p);
       undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::FREE, _activeVertex, p));
     }
   }
   // Shape grab.
   else if (_shapeGrabbed)
   {
     // std::cout << "Move event " << std::endl;
     MShape::ptr shape = getCurrentShape();
     if (shape)
     {
       if (_shapeFirstGrab)
       {
         lastMousePos = _mousePressedPosition;
         _shapeFirstGrab = false;
       }
     }
     QPointF diff = scenePos - mapToScene(lastMousePos);
     undoStack->push(new TranslateShapeCommand(this, TransformShapeCommand::FREE, diff));
   }
   // Window translation action
   else if (event->buttons() & Qt::MiddleButton)
   {
     QPointF diff = event->pos() - lastMousePos;
     QGraphicsView* view = scene()->views().first();
     view->translate(diff.x(), diff.y());
 //    view->update();
   }
   // Reset last mouse position.
   lastMousePos = event->pos();
 }
void MapperGLCanvas::keyPressEvent (QKeyEvent * event) slot
Definition at line 307 of file MapperGLCanvas.cpp.
References _activeVertex, getCurrentShape(), getMainWindow(), MainWindow::getUndoStack(), hasActiveVertex(), TransformShapeCommand::STEP, and undoStack.
Referenced by eventFilter().
 {
   // Prepare to store commands.
   undoStack = getMainWindow()->getUndoStack();
   // Checks if the key has been handled by this function or needs to be deferred to superclass.
   bool handledKey = false;
   // Active vertex selected.
   if (hasActiveVertex())
   {
     MShape::ptr shape = getCurrentShape();
     QPoint pos = mapFromScene(shape->getVertex(_activeVertex));
     handledKey = true;
     switch (event->key()) {
     // TODO: key tab should switch to next vertex: not working because somehow caught at a higher level
     // to switch between frames of the layout
 //    case Qt::Key_Tab:
 //      if (shape)
 //        _activeVertex = (_activeVertex + 1) % shape->nVertices();
 //        p = shape->getVertex(_activeVertex); // reset to new vertex
 //        qDebug() << "New active vertex : " << _activeVertex << endl;
 //      break;
     // Handle pixel-wise adjustments of vertex.
     case Qt::Key_Up:
       pos.ry()--;
       break;
     case Qt::Key_Down:
       pos.ry()++;
       break;
     case Qt::Key_Right:
       pos.rx()++;
       break;
     case Qt::Key_Left:
       pos.rx()--;
       break;
     default:
       if (event->matches(QKeySequence::Undo))
         undoStack->undo();
       else if (event->matches(QKeySequence::Redo))
         undoStack->redo();
       else
         handledKey = false;
       break;
     }
     // Remap window position to scene.
     QPointF scenePos = mapToScene(pos);
     // TODO: this will always be called even if no arrow key has been pressed (small performance issue).
     // Enable to Undo and Redo when arrow keys move the position of vertices
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::STEP, _activeVertex, scenePos));
   }
   // Defer unhandled keys to parent.
   if (!handledKey)
   {
     QWidget::keyPressEvent(event);
   }
 //  std::cout << "Key pressed" << std::endl;
 //  int xMove = 0;
 //  int yMove = 0;
 //  switch (event->key()) {
 //  case Qt::Key_Tab:
 //    if (event->modifiers() & Qt::ControlModifier)
 //      switchImage( (Common::getCurrentSourceId() + 1) % Common::nImages());
 //    else
 //    {
 //      Quad& quad = getQuad();
 //      _active_vertex = (_active_vertex + 1 ) % 4;
 //    }
 //    break;
 //  case Qt::Key_Up:
 //    yMove = -1;
 //    break;
 //  case Qt::Key_Down:
 //    yMove = +1;
 //    break;
 //  case Qt::Key_Left:
 //    xMove = -1;
 //    break;
 //  case Qt::Key_Right:
 //    xMove = +1;
 //    break;
 //  default:
 //    std::cerr << "Unhandled key" << std::endl;
 //    QWidget::keyPressEvent(event);
 //    break;
 //  }
 //
 //  Quad& quad = getQuad();
 //  Point *p = quad.getVertex(_active_vertex);
 //  p->x += xMove;
 //  p->y += yMove;
 //  quad.setVertex(_active_vertex, p);
 //
 //  update();
 //
 //  emit quadChanged();
 }
bool MapperGLCanvas::eventFilter (QObject * target, QEvent * event) slot
Definition at line 505 of file MapperGLCanvas.cpp.
References getActiveVertexIndex(), getMainWindow(), keyPressEvent(), and setActiveVertexIndex().
 {
   if (event->type() == QEvent::KeyPress)
   {
     QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
     setActiveVertexIndex(getMainWindow()->getOutputWindow()->getCanvas()->getActiveVertexIndex());
     MapperGLCanvas::keyPressEvent(keyEvent);
     return true;
   }
   else
   {
     return QObject::eventFilter(target, event);
   }
 }
void MapperGLCanvas::_glueVertex (QPointF * p) protected
Definition at line 521 of file MapperGLCanvas.cpp.
References distIsInside(), getCurrentShape(), MappingManager::getMapping(), MainWindow::getMappingManager(), MShape::getVertex(), MainWindow::instance(), MappingManager::nMappings(), MShape::nVertices(), and MM::VERTEX_STICK_RADIUS.
Referenced by mouseMoveEvent(), and mouseReleaseEvent().
 {
   MappingManager manager = MainWindow::instance()->getMappingManager();
   for (int i = 0; i < manager.nMappings(); i++)
   {
     MShape *shape = manager.getMapping(i)->getShape().data();
     if (shape && shape != getCurrentShape())
     {
       for (int vertex = 0; vertex < shape->nVertices(); vertex++)
       {
         const QPointF& v = shape->getVertex(vertex);
         if (distIsInside(v, *p, MM::VERTEX_STICK_RADIUS))
         {
           p->setX(v.x());
           p->setY(v.y());
         }
       }
     }
   }
 }
Member Data Documentation
MainWindow* MapperGLCanvas::_mainWindow private
Draws the shapes and controls over the canvas.
This method calls: enterDraw(painter); doDraw(painter); exitDraw(painter);
Definition at line 127 of file MapperGLCanvas.h.
Referenced by drawForeground(), mouseMoveEvent(), and mouseReleaseEvent().
QPoint MapperGLCanvas::_mousePressedPosition private
Definition at line 130 of file MapperGLCanvas.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
QPointF MapperGLCanvas::_grabbedObjectStartScenePosition private
Definition at line 133 of file MapperGLCanvas.h.
Referenced by mousePressEvent().
bool MapperGLCanvas::_vertexGrabbed private
Definition at line 136 of file MapperGLCanvas.h.
Referenced by deselectVertices(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and vertexGrabbed().
int MapperGLCanvas::_activeVertex private
Definition at line 139 of file MapperGLCanvas.h.
Referenced by deselectVertices(), getActiveVertexIndex(), hasActiveVertex(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setActiveVertexIndex().
bool MapperGLCanvas::_shapeGrabbed private
Definition at line 142 of file MapperGLCanvas.h.
Referenced by deselectAll(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and shapeGrabbed().
bool MapperGLCanvas::_shapeFirstGrab private
Definition at line 145 of file MapperGLCanvas.h.
Referenced by deselectAll(), mouseMoveEvent(), and mousePressEvent().
int MapperGLCanvas::_zoomLevel private
Definition at line 148 of file MapperGLCanvas.h.
Referenced by getZoomFactor(), and wheelEvent().
QUndoStack* MapperGLCanvas::undoStack private
Definition at line 151 of file MapperGLCanvas.h.
Referenced by keyPressEvent(), mouseMoveEvent(), and mouseReleaseEvent().
const int MapperGLCanvas::NO_VERTEX = -1 static
Definition at line 176 of file MapperGLCanvas.h.
Referenced by deselectVertices(), and hasActiveVertex().
The documentation for this class was generated from the following files:
MapperGLCanvas.h
MapperGLCanvas.cpp