MapMap: ShapeControlPainter Class Reference
ShapeControlPainter Class Reference abstract
An object responsible to paint control points for a specific ShapeGraphicsItem.
#include <ShapeControlPainter.h>
Public Types
typedef QSharedPointer
< ShapeControlPainter > ptr
Public Member Functions
ShapeControlPainter (ShapeGraphicsItem *shapeItem)
virtual ~ShapeControlPainter ()
MShape::ptr getShape () const
virtual void paint (QPainter *painter, MapperGLCanvas *canvas, const QList< int > &selectedVertices=QList< int >())
Protected Member Functions
virtual void _paintShape (QPainter *painter, MapperGLCanvas *canvas)=0
virtual void _paintVertices (QPainter *painter, MapperGLCanvas *canvas, const QList< int > &selectedVertices=QList< int >())
QPen getRescaledShapeStroke (MapperGLCanvas *canvas, bool innerStroke=false)
Protected Attributes
ShapeGraphicsItem * _shapeItem
Detailed Description
An object responsible to paint control points for a specific ShapeGraphicsItem.
Definition at line 36 of file ShapeControlPainter.h.
Member Typedef Documentation
typedef QSharedPointer<ShapeControlPainter> ShapeControlPainter::ptr
Definition at line 39 of file ShapeControlPainter.h.
Constructor & Destructor Documentation
ShapeControlPainter::ShapeControlPainter (ShapeGraphicsItem * shapeItem)
Definition at line 24 of file ShapeControlPainter.cpp.
   : _shapeItem(shapeItem)
 {}
virtual ShapeControlPainter::~ShapeControlPainter () virtual
Definition at line 42 of file ShapeControlPainter.h.
 {}
Member Function Documentation
MShape::ptr ShapeControlPainter::getShape () const
Definition at line 28 of file ShapeControlPainter.cpp.
References _shapeItem, and ShapeGraphicsItem::getShape().
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), MeshControlPainter::_paintShape(), and _paintVertices().
 { return _shapeItem->getShape(); }
void ShapeControlPainter::paint (QPainter * painter, MapperGLCanvas * canvas, const QList< int > & selectedVertices = QList<int>()) virtual
Definition at line 30 of file ShapeControlPainter.cpp.
References _paintShape(), and _paintVertices().
 {
   _paintShape(painter, canvas);
   _paintVertices(painter, canvas, selectedVertices);
 }
virtual void ShapeControlPainter::_paintShape (QPainter * painter, MapperGLCanvas * canvas) protected pure virtual
Implemented in MeshControlPainter, EllipseControlPainter, and PolygonControlPainter.
Referenced by paint().
void ShapeControlPainter::_paintVertices (QPainter * painter, MapperGLCanvas * canvas, const QList< int > & selectedVertices = QList<int>()) protected virtual
Definition at line 36 of file ShapeControlPainter.cpp.
References Util::drawControlsVertex(), getShape(), MapperGLCanvas::getZoomFactor(), MM::VERTEX_SELECT_RADIUS, and MM::VERTEX_SELECT_STROKE_WIDTH.
Referenced by paint().
 {
   qreal zoomFactor = canvas->getZoomFactor();
   qreal selectRadius = MM::VERTEX_SELECT_RADIUS / zoomFactor;
   qreal strokeWidth  = MM::VERTEX_SELECT_STROKE_WIDTH / zoomFactor;
   for (int i=0; i<getShape()->nVertices(); i++)
     Util::drawControlsVertex(painter, getShape()->getVertex(i), selectedVertices.contains(i), selectRadius, strokeWidth);
 }
QPen ShapeControlPainter::getRescaledShapeStroke (MapperGLCanvas * canvas, bool innerStroke = false) protected
Definition at line 46 of file ShapeControlPainter.cpp.
References MM::CONTROL_COLOR, MapperGLCanvas::getZoomFactor(), MM::SHAPE_INNER_STROKE_WIDTH, and MM::SHAPE_STROKE_WIDTH.
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), and MeshControlPainter::_paintShape().
 {
   return QPen(QBrush(MM::CONTROL_COLOR), (innerStroke ? MM::SHAPE_INNER_STROKE_WIDTH : MM::SHAPE_STROKE_WIDTH) / canvas->getZoomFactor());
 }
Member Data Documentation
ShapeGraphicsItem* ShapeControlPainter::_shapeItem protected
Definition at line 54 of file ShapeControlPainter.h.
Referenced by MeshControlPainter::_paintShape(), and getShape().
The documentation for this class was generated from the following files:
ShapeControlPainter.h
ShapeControlPainter.cpp