MapMap: MainWindow Class Reference
MainWindow Class Reference
This is the main window of MapMap.
#include <MainWindow.h>
Public Slots
bool clearProject ()
Clears all mappings and paints.
uid createMediaPaint (uid paintId, QString uri, float x, float y, bool isImage, bool live=false, double rate=100.0)
Create or replace a media paint (or image).
uid createColorPaint (uid paintId, QColor color)
Create or replace a color paint.
uid createMeshTextureMapping (uid mappingId, uid paintId, int nColumns, int nRows, const QVector< QPointF > &src, const QVector< QPointF > &dst)
Creates a textured mesh.
uid createTriangleTextureMapping (uid mappingId, uid paintId, const QVector< QPointF > &src, const QVector< QPointF > &dst)
Creates a textured triangle.
uid createEllipseTextureMapping (uid mappingId, uid paintId, const QVector< QPointF > &src, const QVector< QPointF > &dst)
Creates a textured ellipse.
uid createQuadColorMapping (uid mappingId, uid paintId, const QVector< QPointF > &dst)
Creates a color quad.
uid createTriangleColorMapping (uid mappingId, uid paintId, const QVector< QPointF > &dst)
Creates a color triangle.
uid createEllipseColorMapping (uid mappingId, uid paintId, const QVector< QPointF > &dst)
Creates a color ellipse.
void setMappingVisible (uid mappingId, bool visible)
Sets visibility of mapping.
void setMappingSolo (uid mappingId, bool solo)
Sets solo status of mapping.
void setMappingLocked (uid mappingId, bool locked)
Sets locked attribute of mapping.
void deleteMapping (uid mappingId)
Deletes/removes a mapping.
void cloneMappingItem (uid mappingId)
Clone/duplicate a mapping.
void deletePaint (uid paintId, bool replace)
Deletes/removes a paint and all associated mappigns.
void updateCanvases ()
Updates all canvases.
void enableDisplayControls (bool display)
void enableStickyVertices (bool display)
void enableTestSignal (bool enable)
void displayUndoStack (bool display)
void showMappingContextMenu (const QPoint &point)
void showPaintContextMenu (const QPoint &point)
Public Member Functions
MainWindow ()
~MainWindow ()
bool setTextureUri (int texture_id, const std::string &uri)
bool setTextureRate (int texture_id, double rate)
bool setTextureVolume (int texture_id, double volume)
void setTexturePlayState (int texture_id, bool played)
bool loadFile (const QString &fileName)
bool saveFile (const QString &fileName)
void setCurrentFile (const QString &fileName)
void setCurrentVideo (const QString &filename)
bool importMediaFile (const QString &fileName, bool isImage)
bool addColorPaint (const QColor &color)
void addMappingItem (uid mappingId)
void removeMappingItem (uid mappingId)
void addPaintItem (uid paintId, const QIcon &icon, const QString &name)
void updatePaintItem (uid paintId, const QIcon &icon, const QString &name)
void removePaintItem (uid paintId)
void renameMappingItem (uid mappingId, QString name)
void renamePaintItem (uid paintId, QString name)
void clearWindow ()
bool fileExists (const QString file)
QString locateMediaFile (const QString &uri, bool isImage)
MappingManager & getMappingManager () const
MappingGui::ptr getMappingGuiByMappingId (uint id) const
uid getCurrentPaintId () const
uid getCurrentMappingId () const
OutputGLWindow * getOutputWindow () const
bool hasCurrentPaint () const
bool hasCurrentMapping () const
void setCurrentPaint (int uid)
void setCurrentMapping (int uid)
void removeCurrentPaint ()
void removeCurrentMapping ()
MapperGLCanvas * getSourceCanvas () const
MapperGLCanvas * getDestinationCanvas () const
bool displayControls () const
Returns true iff we should display the controls.
bool displayTestSignal () const
Returns true iff we should display the test signal.
bool stickyVertices () const
Returns true iff we want vertices to stick to each other.
QUndoStack * getUndoStack () const
void startFullScreen ()
bool setOscPort (QString portNumber)
bool setOscPort (int portNumber)
int getOscPort () const
void setOutputWindowFullScreen (bool enable)
Static Public Member Functions
static MainWindow * instance ()
static QString strippedName (const QString &fullFileName)
Static Public Attributes
static const int DEFAULT_WIDTH = 1360
static const int DEFAULT_HEIGHT = 768
static const int PAINT_LIST_ITEM_HEIGHT = 40
static const int SHAPE_LIST_ITEM_HEIGHT = 40
static const int PAINT_LIST_MINIMUM_HEIGHT = 290
static const int MAPPING_LIST_MINIMUM_HEIGHT = 290
static const int PAINT_PROPERTY_PANEL_MINIMUM_HEIGHT = 290
static const int MAPPING_PROPERTY_PANEL_MINIMUM_HEIGHT = 290
static const int CANVAS_MINIMUM_WIDTH = 480
static const int CANVAS_MINIMUM_HEIGHT = 270
static const int OUTPUT_WINDOW_MINIMUM_WIDTH = 480
static const int OUTPUT_WINDOW_MINIMUM_HEIGHT = 270
Protected Member Functions
void closeEvent (QCloseEvent *event)
bool eventFilter (QObject *obj, QEvent *event)
Private Types
enum { MaxRecentFiles = 10 }
enum { MaxRecentVideo = 5 }
Private Slots
void newFile ()
void open ()
void preferences ()
bool save ()
bool saveAs ()
void importVideo ()
void importImage ()
void addColor ()
void about ()
void updateStatusBar ()
void openRecentFile ()
void clearRecentFileList ()
void openRecentVideo ()
void quitMapMap ()
void deleteItem ()
Called when the user wants to delete an item.
void cloneItem ()
void deleteMappingItem ()
void renameMappingItem ()
void deletePaintItem ()
void renamePaintItem ()
void handlePaintItemSelectionChanged ()
void handleMappingItemSelectionChanged ()
void handleMappingItemChanged (QListWidgetItem *item)
void handleMappingIndexesMoved ()
void handleItemSelected (QListWidgetItem *item)
void handlePaintChanged (Paint::ptr paint)
void addMesh ()
void addTriangle ()
void addEllipse ()
void play ()
void pause ()
void rewind ()
void windowModified ()
void pollOscInterface ()
Private Member Functions
void createLayout ()
void createActions ()
void createMenus ()
void createMappingContextMenu ()
void createPaintContextMenu ()
void createToolBars ()
void createStatusBar ()
void updateRecentFileActions ()
void updateRecentVideoActions ()
void readSettings ()
void writeSettings ()
void startOscReceiver ()
bool okToContinue ()
void connectProjectWidgets ()
void disconnectProjectWidgets ()
Static Private Member Functions
static uid getItemId (const QListWidgetItem &item)
static void setItemId (QListWidgetItem &item, uid id)
static QListWidgetItem * getItemFromId (const QListWidget &list, uid id)
static int getItemRowFromId (const QListWidget &list, uid id)
static QIcon createColorIcon (const QColor &color)
static QIcon createFileIcon (const QString &filename)
static QIcon createImageIcon (const QString &filename)
Private Attributes
QMenu * fileMenu
QMenu * editMenu
QMenu * viewMenu
QMenu * runMenu
QMenu * helpMenu
QMenu * recentFileMenu
QMenu * recentVideoMenu
QMenu * mappingContextMenu
QMenu * paintContextMenu
QToolBar * mainToolBar
QToolBar * runToolBar
QAction * separatorAction
QAction * newAction
QAction * openAction
QAction * importVideoAction
QAction * importImageAction
QAction * addColorAction
QAction * saveAction
QAction * saveAsAction
QAction * exitAction
QAction * undoAction
QAction * redoAction
QAction * cloneAction
QAction * deleteMappingAction
QAction * renameMappingAction
QAction * deletePaintAction
QAction * renamePaintAction
QAction * preferencesAction
QAction * aboutAction
QAction * clearRecentFileActions
QAction * emptyRecentVideos
QAction * addMeshAction
QAction * addTriangleAction
QAction * addEllipseAction
QAction * playAction
QAction * pauseAction
QAction * rewindAction
QAction * displayOutputWindowAction
QAction * outputWindowFullScreenAction
QAction * displayControlsAction
QAction * displayTestSignalAction
QAction * stickyVerticesAction
QAction * displayUndoStackAction
QAction * recentFileActions [MaxRecentFiles]
QAction * recentVideoActions [MaxRecentVideo]
QTabWidget * contentTab
QSplitter * paintSplitter
QListWidget * paintList
QStackedWidget * paintPropertyPanel
QSplitter * mappingSplitter
QListWidget * mappingList
QStackedWidget * mappingPropertyPanel
QUndoView * undoView
SourceGLCanvas * sourceCanvas
DestinationGLCanvas * destinationCanvas
OutputGLWindow * outputWindow
QSplitter * mainSplitter
QSplitter * canvasSplitter
QStringList recentFiles
QStringList recentVideos
QString curFile
QString curVideo
QSettings settings
MappingManager * mappingManager
int config_osc_receive_port
QTimer * osc_timer
QMap< uid, MappingGui::ptr > mappers
QMap< uid, PaintGui::ptr > paintGuis
uid currentPaintId
uid currentMappingId
bool _hasCurrentMapping
bool _hasCurrentPaint
bool _isPlaying
bool _displayControls
bool _displayTestSignal
bool _stickyVertices
bool _displayUndoStack
QListWidgetItem * currentSelectedItem
QTimer * videoTimer
PreferencesDialog * _preferences_dialog
QUndoStack * undoStack
Detailed Description
This is the main window of MapMap.
It acts as both a view and a controller interface.
Definition at line 55 of file MainWindow.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
MaxRecentFiles
Definition at line 325 of file MainWindow.h.
 { MaxRecentFiles = 10 };
anonymous enum private
Enumerator
MaxRecentVideo
Definition at line 326 of file MainWindow.h.
 { MaxRecentVideo = 5 };
Constructor & Destructor Documentation
MainWindow::MainWindow ()
Definition at line 28 of file MainWindow.cpp.
References _displayControls, _displayTestSignal, _displayUndoStack, _hasCurrentMapping, _hasCurrentPaint, _isPlaying, _preferences_dialog, _stickyVertices, createActions(), createLayout(), createMappingContextMenu(), createMenus(), createPaintContextMenu(), createStatusBar(), createToolBars(), currentMappingId, currentPaintId, currentSelectedItem, MM::FRAMES_PER_SECOND, Media::hasVideoSupport(), mappingManager, NULL_UID, play(), readSettings(), setCurrentFile(), startOscReceiver(), undoStack, updateCanvases(), updateRecentFileActions(), updateRecentVideoActions(), and videoTimer.
Referenced by instance().
 {
   // Create model.
   if (Media::hasVideoSupport())
     std::cout << "Video support: yes" << std::endl;
   else
     std::cout << "Video support: no" << std::endl;
   mappingManager = new MappingManager;
   // Initialize internal variables.
   currentPaintId = NULL_UID;
   currentMappingId = NULL_UID;
   // TODO: not sure we need this anymore since we have NULL_UID
   _hasCurrentPaint = false;
   _hasCurrentMapping = false;
   currentSelectedItem = NULL;
   // Play state.
   _isPlaying = false;
   // Editing toggles.
   _displayControls = true;
   _stickyVertices = true;
   _displayTestSignal = false;
   _displayUndoStack = false;
   // UndoStack
   undoStack = new QUndoStack(this);
   // Create everything.
   createLayout();
   createActions();
   createMenus();
   createMappingContextMenu();
   createPaintContextMenu();
   createToolBars();
   createStatusBar();
   updateRecentFileActions();
   updateRecentVideoActions();
   // Load settings.
   readSettings();
   // Start osc.
   startOscReceiver();
   // Defaults.
   //setWindowIcon(QIcon(":/images/icon.png"));
   setCurrentFile("");
   // Create and start timer.
   videoTimer = new QTimer(this);
   videoTimer->setInterval( int( 1000 / MM::FRAMES_PER_SECOND ) );
   connect(videoTimer, SIGNAL(timeout()), this, SLOT(updateCanvases()));
   videoTimer->start();
   // Start playing by default.
   play();
   // after readSettings():
   _preferences_dialog = new PreferencesDialog(this, this);
 }
MainWindow::~MainWindow ()
Definition at line 92 of file MainWindow.cpp.
References mappingManager, and osc_timer.
 {
   delete mappingManager;
 //  delete _facade;
 #ifdef HAVE_OSC
   delete osc_timer;
 #endif // ifdef
 }
Member Function Documentation
void MainWindow::closeEvent (QCloseEvent * event) protected
Definition at line 263 of file MainWindow.cpp.
References okToContinue(), videoTimer, and writeSettings().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Popup dialog allowing the user to save before closing.
   if (okToContinue())
   {
     writeSettings();
     event->accept();
   }
   else
   {
     event->ignore();
   }
   // Restart video playback. XXX Hack
   videoTimer->start();
 }
bool MainWindow::eventFilter (QObject * obj, QEvent * event) protected
Definition at line 283 of file MainWindow.cpp.
References _isPlaying, addEllipse(), addMesh(), addTriangle(), deleteItem(), newFile(), open(), outputWindow, outputWindowFullScreenAction, pause(), play(), rewind(), save(), OutputGLWindow::setFullScreen(), and undoStack.
 {
     bool eventKey = false;
   if (event->type() == QEvent::KeyPress)
   {
     QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
     eventKey = true;
     // Menubar shortcut
     if (keyEvent->modifiers() == Qt::CTRL)
     {
         switch (keyEvent->key()) {
         case Qt::Key_F:
             if (outputWindow->windowState() != Qt::WindowFullScreen)
             {
               outputWindow->setFullScreen(true);
               outputWindowFullScreenAction->setChecked(true);
               outputWindowFullScreenAction->setEnabled(true);
             }
             break;
           case Qt::Key_N:
             newFile();
             break;
           case Qt::Key_O:
             open();
             break;
           case Qt::Key_S:
             save();
             break;
           case Qt::Key_Q:
             close();
             break;
           case Qt::Key_Delete:
             deleteItem();
             break;
           case Qt::Key_M:
             addMesh();
             break;
           case Qt::Key_T:
             addTriangle();
             break;
           case Qt::Key_E:
             addEllipse();
             break;
           case Qt::Key_W:
             outputWindow->setVisible(true);
             break;
           case Qt::Key_R:
             rewind();
             break;
           case Qt::Key_Z:
             undoStack->undo();
             break;
         }
     }
     else if (keyEvent->matches(QKeySequence::Redo))
     {
       undoStack->redo();
     }
     else if (keyEvent->key() == Qt::Key_Escape)
     {
       outputWindow->setFullScreen(false);
       outputWindowFullScreenAction->setChecked(false);
       outputWindowFullScreenAction->setEnabled(false);
     }
     else if (keyEvent->key() == Qt::Key_Space)
     {
       if (_isPlaying)
       {
         pause();
       }
       else
       {
         play();
       }
     }
     eventKey = false;
     return eventKey;
   }
   else
   {
     // standard event processing
     return QObject::eventFilter(obj, event);
   }
 }
void MainWindow::newFile () private slot
Definition at line 377 of file MainWindow.cpp.
References clearWindow(), okToContinue(), setCurrentFile(), undoStack, and videoTimer.
Referenced by createActions(), and eventFilter().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Popup dialog allowing the user to save before creating a new file.
   if (okToContinue())
   {
     clearWindow();
     setCurrentFile("");
     undoStack->clear();
   }
   // Restart video playback. XXX Hack
   videoTimer->start();
 }
void MainWindow::open () private slot
Definition at line 394 of file MainWindow.cpp.
References MM::FILE_EXTENSION, loadFile(), okToContinue(), settings, and videoTimer.
Referenced by createActions(), and eventFilter().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Popup dialog allowing the user to save before opening a new file.
   if (okToContinue())
   {
     QString fileName = QFileDialog::getOpenFileName(this,
         tr("Open project"),
         settings.value("defaultProjectDir").toString(),
         tr("MapMap files (*.%1)").arg(MM::FILE_EXTENSION));
     if (! fileName.isEmpty())
       loadFile(fileName);
   }
   // Restart video playback. XXX Hack
   videoTimer->start();
 }
void MainWindow::preferences () private slot
Definition at line 414 of file MainWindow.cpp.
References _preferences_dialog.
Referenced by createActions().
 {
   this->_preferences_dialog->show();
 }
bool MainWindow::save () private slot
Definition at line 419 of file MainWindow.cpp.
References curFile, saveAs(), and saveFile().
Referenced by createActions(), eventFilter(), and okToContinue().
 {
   // Popup save-as dialog if file has never been saved.
   if (curFile.isEmpty())
   {
     return saveAs();
   }
   else
   {
     return saveFile(curFile);
   }
 }
bool MainWindow::saveAs () private slot
Definition at line 432 of file MainWindow.cpp.
References MM::FILE_EXTENSION, saveFile(), settings, and videoTimer.
Referenced by createActions(), and save().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Popul file dialog to choose filename.
   QString fileName = QFileDialog::getSaveFileName(this,
       tr("Save project"), settings.value("defaultProjectDir").toString(),
       tr("MapMap files (*.%1)").arg(MM::FILE_EXTENSION));
   // Restart video playback. XXX Hack
   videoTimer->start();
   if (fileName.isEmpty())
     return false;
   if (! fileName.endsWith(MM::FILE_EXTENSION))
   {
     std::cout << "filename doesn't end with expected extension: " <<
       fileName.toStdString() << std::endl;
       fileName.append(".");
       fileName.append(MM::FILE_EXTENSION);
   }
   // Save to filename.
   return saveFile(fileName);
 }
void MainWindow::importVideo () private slot
Definition at line 460 of file MainWindow.cpp.
References importMediaFile(), settings, MM::VIDEO_FILES_FILTER, and videoTimer.
Referenced by createActions().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Pop-up file-choosing dialog to choose media file.
   // TODO: restrict the type of files that can be imported
   QString fileName = QFileDialog::getOpenFileName(this, tr("Import media source file"), settings.value("defaultVideoDir").toString(), tr("Video files (%1);;All files (*)").arg(MM::VIDEO_FILES_FILTER));
   // Restart video playback. XXX Hack
   videoTimer->start();
   if (!fileName.isEmpty())
     importMediaFile(fileName, false);
 }
void MainWindow::importImage () private slot
Definition at line 475 of file MainWindow.cpp.
References MM::IMAGE_FILES_FILTER, importMediaFile(), settings, and videoTimer.
Referenced by createActions().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Pop-up file-choosing dialog to choose media file.
   // TODO: restrict the type of files that can be imported
   QString fileName = QFileDialog::getOpenFileName(this,
       tr("Import media source file"), settings.value("defaultImageDir").toString(), tr("Image files (%1);;All files (*)").arg(MM::IMAGE_FILES_FILTER));
   // Restart video playback. XXX Hack
   videoTimer->start();
   if (!fileName.isEmpty())
     importMediaFile(fileName, true);
 }
void MainWindow::addColor () private slot
Definition at line 492 of file MainWindow.cpp.
References addColorPaint(), and videoTimer.
Referenced by createActions().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Pop-up color-choosing dialog to choose color paint.
   // FIXME: we use a static variable to store the last chosen color
   // it should rather be a member of this class, or so.
   static QColor color = QColor(0, 255, 0, 255);
   color = QColorDialog::getColor(color, this, tr("Select Color"),
     // QColorDialog::DontUseNativeDialog |
     QColorDialog::ShowAlphaChannel);
   if (color.isValid())
   {
     addColorPaint(color);
   }
   // Restart video playback. XXX Hack
   videoTimer->start();
 }
void MainWindow::about () private slot
Definition at line 652 of file MainWindow.cpp.
References MM::COPYRIGHT_OWNERS, MM::VERSION, and videoTimer.
Referenced by createActions().
 {
   // Stop video playback to avoid lags. XXX Hack
   videoTimer->stop();
   // Pop-up about dialog.
   QMessageBox::about(this, tr("About MapMap"),
       tr("<h2><img src=\":mapmap-title\"/> %1</h2>"
           "<p>Copyright &copy; 2013 %2.</p>"
           "<p>MapMap is a free software for video mapping.</p>"
           "<p>Projection mapping, also known as video mapping and spatial augmented reality, "
           "is a projection technology used to turn objects, often irregularly shaped, into "
           "a display surface for video projection. These objects may be complex industrial "
           "landscapes, such as buildings. By using specialized software, a two or three "
           "dimensional object is spatially mapped on the virtual program which mimics the "
           "real environment it is to be projected on. The software can interact with a "
           "projector to fit any desired image onto the surface of that object. This "
           "technique is used by artists and advertisers alike who can add extra dimensions, "
           "optical illusions, and notions of movement onto previously static objects. The "
           "video is commonly combined with, or triggered by, audio to create an "
           "audio-visual narrative."
           "This project was made possible by the support of the International Organization of "
           "La Francophonie.</p>"
           "<p>http://mapmap.info<br />"
           "http://www.francophonie.org</p>"
           ).arg(MM::VERSION, MM::COPYRIGHT_OWNERS));
   // Restart video playback. XXX Hack
   videoTimer->start();
 }
void MainWindow::updateStatusBar () private slot
Definition at line 683 of file MainWindow.cpp.
Referenced by createStatusBar(), and windowModified().
 {
   // Nothing to do for now.
 //  locationLabel->setText(spreadsheet->currentLocation());
 //  formulaLabel->setText(spreadsheet->currentFormula());
 }
void MainWindow::openRecentFile () private slot
Definition at line 789 of file MainWindow.cpp.
References loadFile().
Referenced by createActions().
 {
     QAction *action = qobject_cast<QAction *>(sender());
     if (action)
         loadFile(action->data().toString());
 }
void MainWindow::clearRecentFileList () private slot
Definition at line 2007 of file MainWindow.cpp.
References recentFiles, settings, and updateRecentFileActions().
Referenced by createActions().
 {
     recentFiles = settings.value("recentFiles").toStringList();
     while (recentFiles.size() > 0)
         recentFiles.clear();
     settings.setValue("recentFiles", recentFiles);
     updateRecentFileActions();
 }
void MainWindow::openRecentVideo () private slot
Definition at line 796 of file MainWindow.cpp.
References importMediaFile().
Referenced by createActions().
 {
     QAction *action = qobject_cast<QAction *>(sender());
     if (action)
         importMediaFile(action->data().toString(),false);
 }
void MainWindow::quitMapMap () private slot
Definition at line 2839 of file MainWindow.cpp.
 {
   close();
 }
void MainWindow::deleteItem () private slot
Called when the user wants to delete an item.
Deletes either a Paint or a Mapping.
Definition at line 695 of file MainWindow.cpp.
References contentTab, currentSelectedItem, deletePaint(), getItemId(), mappingList, mappingSplitter, paintList, paintSplitter, and undoStack.
Referenced by eventFilter().
 {
   bool isMappingTabSelected = (mappingSplitter == contentTab->currentWidget());
   bool isPaintTabSelected = (paintSplitter == contentTab->currentWidget());
   if (currentSelectedItem)
   {
     if (isMappingTabSelected) //currentSelectedItem->listWidget() == mappingList)
     {
       // Delete mapping.
       undoStack->push(new DeleteMappingCommand(this, getItemId(*mappingList->currentItem())));
       //currentSelectedItem = NULL;
     }
     else if (isPaintTabSelected) //currentSelectedItem->listWidget() == paintList)
     {
       // Delete paint.
       deletePaint( getItemId(*paintList->currentItem()), false );
       //currentSelectedItem = NULL;
     }
     else
     {
       qCritical() << "Selected item neither a mapping nor a paint." << endl;
     }
     }
 }
void MainWindow::cloneItem () private slot
Definition at line 721 of file MainWindow.cpp.
References cloneMappingItem(), currentSelectedItem, getItemId(), and mappingList.
Referenced by createActions().
 {
   if (currentSelectedItem)
   {
     cloneMappingItem(getItemId(*mappingList->currentItem()));
   }
   else
   {
     qCritical() << "No selected mapping" << endl;
   }
 }
void MainWindow::deleteMappingItem () private slot
Definition at line 733 of file MainWindow.cpp.
References currentSelectedItem, deleteMapping(), getItemId(), and mappingList.
Referenced by createActions().
 {
   if (currentSelectedItem)
   {
     deleteMapping(getItemId(*mappingList->currentItem()));
   }
   else
   {
     qCritical() << "No selected mapping" << endl;
   }
 }
void MainWindow::renameMappingItem () private slot
Definition at line 745 of file MainWindow.cpp.
References contentTab, mappingList, and mappingSplitter.
Referenced by connectProjectWidgets(), and createActions().
 {
   // Set current item editable and rename it
   QListWidgetItem* item = mappingList->currentItem();
   item->setFlags(item->flags() | Qt::ItemIsEditable);
   mappingList->editItem(item);
   contentTab->setCurrentWidget(mappingSplitter);
 }
void MainWindow::deletePaintItem () private slot
Definition at line 761 of file MainWindow.cpp.
References currentSelectedItem, deletePaint(), getItemId(), and paintList.
Referenced by createActions().
 {
   if(currentSelectedItem)
   {
     deletePaint(getItemId(*paintList->currentItem()), false);
   }
   else
   {
     qCritical() << "No selected paint" << endl;
   }
 }
void MainWindow::renamePaintItem () private slot
Definition at line 773 of file MainWindow.cpp.
References contentTab, paintList, and paintSplitter.
Referenced by connectProjectWidgets(), and createActions().
 {
   // Set current item editable and rename it
   QListWidgetItem* item = paintList->currentItem();
   item->setFlags(item->flags() | Qt::ItemIsEditable);
   paintList->editItem(item);
   contentTab->setCurrentWidget(paintSplitter);
 }
void MainWindow::handlePaintItemSelectionChanged () private slot
Definition at line 101 of file MainWindow.cpp.
References addEllipseAction, addMeshAction, addTriangleAction, currentPaintId, currentSelectedItem, getItemId(), paintList, removeCurrentMapping(), removeCurrentPaint(), setCurrentPaint(), and updateCanvases().
Referenced by connectProjectWidgets(), and disconnectProjectWidgets().
 {
   // Set current paint.
   QListWidgetItem* item = paintList->currentItem();
   currentSelectedItem = item;
   // Is a paint item selected?
   bool paintItemSelected = (item ? true : false);
   if (paintItemSelected)
   {
     // Set current paint.
     uid paintId = getItemId(*item);
     // Unselect current mapping.
     if (currentPaintId != paintId)
       removeCurrentMapping();
     // Set current paint.
     setCurrentPaint(paintId);
   }
   else
     removeCurrentPaint();
   // Enable/disable creation of mappings depending on whether a paint is selected.
   addMeshAction->setEnabled(paintItemSelected);
   addTriangleAction->setEnabled(paintItemSelected);
   addEllipseAction->setEnabled(paintItemSelected);
   // Update canvases.
   updateCanvases();
 }
void MainWindow::handleMappingItemSelectionChanged () private slot
Definition at line 132 of file MainWindow.cpp.
References currentSelectedItem, getItemId(), MappingManager::getMappingById(), mappingList, mappingManager, removeCurrentMapping(), setCurrentMapping(), setCurrentPaint(), and updateCanvases().
Referenced by connectProjectWidgets(), and disconnectProjectWidgets().
 {
     if (mappingList->selectedItems().empty())
     {
       removeCurrentMapping();
     }
     else
     {
       QListWidgetItem* item = mappingList->currentItem();
       currentSelectedItem = item;
       // Set current paint and mappings.
       uid mappingId = getItemId(*item);
       Mapping::ptr mapping = mappingManager->getMappingById(mappingId);
       uid paintId = mapping->getPaint()->getId();
       setCurrentMapping(mappingId);
       setCurrentPaint(paintId);
     }
   // Update canvases.
   updateCanvases();
 }
void MainWindow::handleMappingItemChanged (QListWidgetItem * item) private slot
Definition at line 156 of file MainWindow.cpp.
References getItemId(), and setMappingVisible().
Referenced by connectProjectWidgets(), and disconnectProjectWidgets().
 {
   // Toggle visibility of mapping depending on checkbox of item.
   uid mappingId = getItemId(*item);
   setMappingVisible(mappingId, item->checkState() == Qt::Checked);
 }
void MainWindow::handleMappingIndexesMoved () private slot
Definition at line 163 of file MainWindow.cpp.
References mappingList, mappingManager, MappingManager::reorderMappings(), and updateCanvases().
Referenced by connectProjectWidgets(), and disconnectProjectWidgets().
 {
   // Reorder mappings.
   QVector<uid> newOrder;
   for (int row=mappingList->count()-1; row>=0; row--)
   {
     uid layerId = mappingList->item(row)->data(Qt::UserRole).toInt();
     newOrder.push_back(layerId);
   }
   mappingManager->reorderMappings(newOrder);
   // Update canvases according to new order.
   updateCanvases();
 }
void MainWindow::handleItemSelected (QListWidgetItem * item) private slot
Definition at line 178 of file MainWindow.cpp.
References currentSelectedItem.
Referenced by connectProjectWidgets(), and disconnectProjectWidgets().
 {
   Q_UNUSED(item);
   // Change currently selected item.
   currentSelectedItem = item;
 }
void MainWindow::handlePaintChanged (Paint::ptr paint) private slot
Definition at line 224 of file MainWindow.cpp.
References createColorIcon(), createFileIcon(), createImageIcon(), getCurrentMappingId(), MappingManager::getPaintId(), mappingManager, NULL_UID, removeCurrentMapping(), removeCurrentPaint(), setCurrentMapping(), strippedName(), and updatePaintItem().
Referenced by addPaintItem().
{
   // Change currently selected item.
   uid curMappingId = getCurrentMappingId();
   removeCurrentMapping();
   removeCurrentPaint();
   uid paintId = mappingManager->getPaintId(paint);
   if (paint->getType() == "media") {
     QSharedPointer<Media> media = qSharedPointerCast<Media>(paint);
     Q_CHECK_PTR(media);
     updatePaintItem(paintId, createFileIcon(media->getUri()), strippedName(media->getUri()));
 //    QString fileName = QFileDialog::getOpenFileName(this,
 //        tr("Import media source file"), ".");
 //    // Restart video playback. XXX Hack
 //    if (!fileName.isEmpty())
 //      importMediaFile(fileName, paint, false);
   }
   if (paint->getType() == "image") {
     QSharedPointer<Image> image = qSharedPointerCast<Image>(paint);
     Q_CHECK_PTR(image);
     updatePaintItem(paintId, createImageIcon(image->getUri()), strippedName(image->getUri()));
 //    QString fileName = QFileDialog::getOpenFileName(this,
 //        tr("Import media source file"), ".");
 //    // Restart video playback. XXX Hack
 //    if (!fileName.isEmpty())
 //      importMediaFile(fileName, paint, true);
   }
   else if (paint->getType() == "color") {
     // Pop-up color-choosing dialog to choose color paint.
     QSharedPointer<Color> color = qSharedPointerCast<Color>(paint);
     Q_CHECK_PTR(color);
     updatePaintItem(paintId, createColorIcon(color->getColor()), strippedName(color->getColor().name()));
   }
   if (curMappingId != NULL_UID)
     setCurrentMapping(curMappingId);
 }
void MainWindow::addMesh () private slot
Definition at line 513 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), Util::createMeshForTexture(), Util::createQuadForColor(), getCurrentPaintId(), getMappingManager(), MappingManager::getPaintById(), mappingManager, NULL_UID, sourceCanvas, and undoStack.
Referenced by createActions(), and eventFilter().
 {
   // A paint must be selected to add a mapping.
   if (getCurrentPaintId() == NULL_UID)
     return;
   // Retrieve current paint (as texture).
   Paint::ptr paint = getMappingManager().getPaintById(getCurrentPaintId());
   Q_CHECK_PTR(paint);
   // Create input and output quads.
   Mapping* mappingPtr;
   if (paint->getType() == "color")
   {
     MShape::ptr outputQuad = MShape::ptr(Util::createQuadForColor(sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new ColorMapping(paint, outputQuad);
   }
   else
   {
     QSharedPointer<Texture> texture = qSharedPointerCast<Texture>(paint);
     Q_CHECK_PTR(texture);
     MShape::ptr outputQuad = MShape::ptr(Util::createMeshForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     MShape::ptr  inputQuad = MShape::ptr(Util::createMeshForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new TextureMapping(paint, outputQuad, inputQuad);
   }
   // Create texture mapping.
   Mapping::ptr mapping(mappingPtr);
   uint mappingId = mappingManager->addMapping(mapping);
   addMappingItem(mappingId);
   // Implement undoStack Commands
   undoStack->push(new AddShapesCommand(this, mappingId));
 }
void MainWindow::addTriangle () private slot
Definition at line 549 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), Util::createTriangleForColor(), Util::createTriangleForTexture(), getCurrentPaintId(), getMappingManager(), MappingManager::getPaintById(), mappingManager, NULL_UID, sourceCanvas, and undoStack.
Referenced by createActions(), and eventFilter().
 {
   // A paint must be selected to add a mapping.
   if (getCurrentPaintId() == NULL_UID)
     return;
   // Retrieve current paint (as texture).
   Paint::ptr paint = getMappingManager().getPaintById(getCurrentPaintId());
   Q_CHECK_PTR(paint);
   // Create input and output quads.
   Mapping* mappingPtr;
   if (paint->getType() == "color")
   {
     MShape::ptr outputTriangle = MShape::ptr(Util::createTriangleForColor(sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new ColorMapping(paint, outputTriangle);
   }
   else
   {
     QSharedPointer<Texture> texture = qSharedPointerCast<Texture>(paint);
     Q_CHECK_PTR(texture);
     MShape::ptr outputTriangle = MShape::ptr(Util::createTriangleForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     MShape::ptr inputTriangle = MShape::ptr(Util::createTriangleForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new TextureMapping(paint, inputTriangle, outputTriangle);
   }
   // Create mapping.
   Mapping::ptr mapping(mappingPtr);
   uint mappingId = mappingManager->addMapping(mapping);
   addMappingItem(mappingId);
   // Implement undoStack Commands
   undoStack->push(new AddShapesCommand(this, mappingId));
 }
void MainWindow::addEllipse () private slot
Definition at line 585 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), Util::createEllipseForColor(), Util::createEllipseForTexture(), getCurrentPaintId(), getMappingManager(), MappingManager::getPaintById(), mappingManager, NULL_UID, sourceCanvas, and undoStack.
Referenced by createActions(), and eventFilter().
 {
   // A paint must be selected to add a mapping.
   if (getCurrentPaintId() == NULL_UID)
     return;
   // Retrieve current paint (as texture).
   Paint::ptr paint = getMappingManager().getPaintById(getCurrentPaintId());
   Q_CHECK_PTR(paint);
   // Create input and output ellipses.
   Mapping* mappingPtr;
   if (paint->getType() == "color")
   {
     MShape::ptr outputEllipse = MShape::ptr(Util::createEllipseForColor(sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new ColorMapping(paint, outputEllipse);
   }
   else
   {
     QSharedPointer<Texture> texture = qSharedPointerCast<Texture>(paint);
     Q_CHECK_PTR(texture);
     MShape::ptr outputEllipse = MShape::ptr(Util::createEllipseForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     MShape::ptr inputEllipse = MShape::ptr(Util::createEllipseForTexture(texture.data(), sourceCanvas->width(), sourceCanvas->height()));
     mappingPtr = new TextureMapping(paint, inputEllipse, outputEllipse);
   }
   // Create mapping.
   Mapping::ptr mapping(mappingPtr);
   uint mappingId = mappingManager->addMapping(mapping);
   addMappingItem(mappingId);
   // Implement undoStack Commands
   undoStack->push(new AddShapesCommand(this, mappingId));
 }
void MainWindow::play () private slot
Definition at line 621 of file MainWindow.cpp.
References _isPlaying, MappingManager::getPaint(), mappingManager, MappingManager::nPaints(), pauseAction, and playAction.
Referenced by createActions(), eventFilter(), and MainWindow().
 {
   // Update buttons.
   playAction->setVisible(false);
   pauseAction->setVisible(true);
   _isPlaying = true;
   // Start all paints.
   for (int i=0; i<mappingManager->nPaints(); i++)
     mappingManager->getPaint(i)->play();
 }
void MainWindow::pause () private slot
Definition at line 633 of file MainWindow.cpp.
References _isPlaying, MappingManager::getPaint(), mappingManager, MappingManager::nPaints(), pauseAction, and playAction.
Referenced by createActions(), and eventFilter().
 {
   // Update buttons.
   playAction->setVisible(true);
   pauseAction->setVisible(false);
   _isPlaying = false;
   // Pause all paints.
   for (int i=0; i<mappingManager->nPaints(); i++)
     mappingManager->getPaint(i)->pause();
 }
void MainWindow::rewind () private slot
Definition at line 645 of file MainWindow.cpp.
References MappingManager::getPaint(), mappingManager, and MappingManager::nPaints().
Referenced by createActions(), and eventFilter().
 {
   // Rewind all paints.
   for (int i=0; i<mappingManager->nPaints(); i++)
     mappingManager->getPaint(i)->rewind();
 }
void MainWindow::windowModified () private slot
Definition at line 1207 of file MainWindow.cpp.
References updateStatusBar().
Referenced by addMappingItem(), addPaintItem(), clearProject(), removeMappingItem(), removePaintItem(), and updatePaintItem().
 {
   setWindowModified(true);
   updateStatusBar();
 }
void MainWindow::pollOscInterface () private slot
Definition at line 2656 of file MainWindow.cpp.
Referenced by startOscReceiver().
 {
 #ifdef HAVE_OSC
   osc_interface->consume_commands(*this);
 #endif
 }
bool MainWindow::clearProject () slot
Clears all mappings and paints.
Definition at line 803 of file MainWindow.cpp.
References MappingManager::clearAll(), connectProjectWidgets(), destinationCanvas, disconnectProjectWidgets(), mappers, mappingList, mappingManager, mappingPropertyPanel, paintGuis, paintList, removeCurrentMapping(), removeCurrentPaint(), sourceCanvas, and windowModified().
Referenced by clearWindow(), and loadFile().
 {
   // Disconnect signals to avoid problems when clearning mappingList and paintList.
   disconnectProjectWidgets();
   // Clear current paint / mapping.
   removeCurrentPaint();
   removeCurrentMapping();
   // Empty list widgets.
   mappingList->clear();
   paintList->clear();
   // Clear property panel.
   for (int i=mappingPropertyPanel->count()-1; i>=0; i--)
     mappingPropertyPanel->removeWidget(mappingPropertyPanel->widget(i));
   // Disable property panel.
   mappingPropertyPanel->setDisabled(true);
   // Clear list of mappers.
   mappers.clear();
   // Clear list of paint guis.
   paintGuis.clear();
   // Clear model.
   mappingManager->clearAll();
   // Refresh GL canvases to clear them out.
   sourceCanvas->repaint();
   destinationCanvas->repaint();
   // Reconnect everything.
   connectProjectWidgets();
   // Window was modified.
   windowModified();
   return true;
 }
uid MainWindow::createMediaPaint (uid paintId, QString uri, float x, float y, bool isImage, bool live = false, double rate = 100.0) slot
Create or replace a media paint (or image).
Definition at line 845 of file MainWindow.cpp.
References MappingManager::addPaint(), addPaintItem(), createFileIcon(), createImageIcon(), fileExists(), Paint::getUidAllocator(), locateMediaFile(), mappingManager, NULL_UID, Texture::setPosition(), and strippedName().
Referenced by importMediaFile(), and ProjectReader::parsePaint().
 {
   // Cannot create image with already existing id.
   if (Paint::getUidAllocator().exists(paintId))
     return NULL_UID;
   else
   {
     // Check if file exists before
     if (! fileExists(uri))
         uri = locateMediaFile(uri, isImage);
     Texture* tex = 0;
     if (isImage)
       tex = new Image(uri, paintId);
     else {
       tex = new Media(uri, live, rate, paintId);
     }
     // Create new image with corresponding ID.
     tex->setPosition(x, y);
     // Add it to the manager.
     Paint::ptr paint(tex);
     // Add paint to model and return its uid.
     uid id = mappingManager->addPaint(paint);
     // Add paint widget item.
     addPaintItem(id, isImage ? createImageIcon(uri) : createFileIcon(uri), strippedName(uri));
     return id;
   }
 }
uid MainWindow::createColorPaint (uid paintId, QColor color) slot
Create or replace a color paint.
Definition at line 880 of file MainWindow.cpp.
References MappingManager::addPaint(), addPaintItem(), createColorIcon(), Paint::getUidAllocator(), mappingManager, NULL_UID, and strippedName().
Referenced by addColorPaint(), and ProjectReader::parsePaint().
 {
   // Cannot create image with already existing id.
   if (Paint::getUidAllocator().exists(paintId))
     return NULL_UID;
   else
   {
     Color* img = new Color(color, paintId);
     // Add it to the manager.
     Paint::ptr paint(img);
     // Add paint to model and return its uid.
     uid id = mappingManager->addPaint(paint);
     // Add paint widget item.
     addPaintItem(id, createColorIcon(color), strippedName(color.name()));
     return id;
   }
 }
uid MainWindow::createMeshTextureMapping (uid mappingId, uid paintId, int nColumns, int nRows, const QVector< QPointF > & src, const QVector< QPointF > & dst) slot
Creates a textured mesh.
Definition at line 903 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     int nVertices = nColumns * nRows;
     qDebug() << nVertices << " vs " << nColumns << "x" << nRows << " vs " << src.size() << " " << dst.size() << endl;
     Q_ASSERT(src.size() == nVertices && dst.size() == nVertices);
     MShape::ptr inputMesh( new Mesh(src, nColumns, nRows));
     MShape::ptr outputMesh(new Mesh(dst, nColumns, nRows));
     // Add it to the manager.
     Mapping::ptr mapping(new TextureMapping(paint, outputMesh, inputMesh, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
uid MainWindow::createTriangleTextureMapping (uid mappingId, uid paintId, const QVector< QPointF > & src, const QVector< QPointF > & dst) slot
Creates a textured triangle.
Definition at line 936 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     Q_ASSERT(src.size() == 3 && dst.size() == 3);
     MShape::ptr inputTriangle( new Triangle(src[0], src[1], src[2]));
     MShape::ptr outputTriangle(new Triangle(dst[0], dst[1], dst[2]));
     // Add it to the manager.
     Mapping::ptr mapping(new TextureMapping(paint, outputTriangle, inputTriangle, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
uid MainWindow::createEllipseTextureMapping (uid mappingId, uid paintId, const QVector< QPointF > & src, const QVector< QPointF > & dst) slot
Creates a textured ellipse.
Definition at line 966 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     Q_ASSERT(src.size() == 5 && dst.size() == 5);
     MShape::ptr inputEllipse( new Ellipse(src[0], src[1], src[2], src[3], src[4]));
     MShape::ptr outputEllipse(new Ellipse(dst[0], dst[1], dst[2], dst[3], dst[4]));
     // Add it to the manager.
     Mapping::ptr mapping(new TextureMapping(paint, outputEllipse, inputEllipse, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
uid MainWindow::createQuadColorMapping (uid mappingId, uid paintId, const QVector< QPointF > & dst) slot
Creates a color quad.
Definition at line 996 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     Q_ASSERT(dst.size() == 4);
     MShape::ptr outputQuad(new Quad(dst[0], dst[1], dst[2], dst[3]));
     // Add it to the manager.
     Mapping::ptr mapping(new ColorMapping(paint, outputQuad, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
uid MainWindow::createTriangleColorMapping (uid mappingId, uid paintId, const QVector< QPointF > & dst) slot
Creates a color triangle.
Definition at line 1025 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     Q_ASSERT(dst.size() == 3);
     MShape::ptr outputTriangle(new Triangle(dst[0], dst[1], dst[2]));
     // Add it to the manager.
     Mapping::ptr mapping(new ColorMapping(paint, outputTriangle, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
uid MainWindow::createEllipseColorMapping (uid mappingId, uid paintId, const QVector< QPointF > & dst) slot
Creates a color ellipse.
Definition at line 1054 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getPaintById(), Paint::getUidAllocator(), Mapping::getUidAllocator(), mappingManager, and NULL_UID.
Referenced by ProjectReader::parseMapping().
 {
   // Cannot create element with already existing id or element for which no paint exists.
   if (Mapping::getUidAllocator().exists(mappingId) ||
       !Paint::getUidAllocator().exists(paintId) ||
       paintId == NULL_UID)
     return NULL_UID;
   else
   {
     Paint::ptr paint = mappingManager->getPaintById(paintId);
     Q_ASSERT(dst.size() == 4);
     MShape::ptr outputEllipse(new Ellipse(dst[0], dst[1], dst[2], dst[3]));
     // Add it to the manager.
     Mapping::ptr mapping(new ColorMapping(paint, outputEllipse, mappingId));
     uid id = mappingManager->addMapping(mapping);
     // Add it to the GUI.
     addMappingItem(mappingId);
     // Return the id.
     return id;
   }
 }
void MainWindow::setMappingVisible (uid mappingId, bool visible) slot
Sets visibility of mapping.
Definition at line 1084 of file MainWindow.cpp.
References getItemFromId(), MappingManager::getMappingById(), mappingList, mappingManager, and updateCanvases().
Referenced by handleMappingItemChanged(), and ProjectReader::parseMapping().
 {
   // Set mapping visibility
   Mapping::ptr mapping = mappingManager->getMappingById(mappingId);
   if (mapping.isNull())
   {
     qDebug() << "No such mapping id" << endl;
   }
   else
   {
     mapping->setVisible(visible);
     // Change list item check state
     QListWidgetItem* item = getItemFromId(*mappingList, mappingId);
     Q_ASSERT( item );
     item->setCheckState(visible ? Qt::Checked : Qt::Unchecked );
     // Update canvases.
     updateCanvases();
   }
 }
void MainWindow::setMappingSolo (uid mappingId, bool solo) slot
Sets solo status of mapping.
Definition at line 1105 of file MainWindow.cpp.
Referenced by ProjectReader::parseMapping().
 {
   Q_UNUSED(mappingId);
   Q_UNUSED(solo);
 }
void MainWindow::setMappingLocked (uid mappingId, bool locked) slot
Sets locked attribute of mapping.
Definition at line 1111 of file MainWindow.cpp.
Referenced by ProjectReader::parseMapping().
 {
   Q_UNUSED(mappingId);
   Q_UNUSED(locked);
 }
void MainWindow::deleteMapping (uid mappingId) slot
Deletes/removes a mapping.
Definition at line 1117 of file MainWindow.cpp.
References Mapping::getUidAllocator(), and removeMappingItem().
Referenced by deleteMappingItem(), DeleteMappingCommand::redo(), and AddShapesCommand::undo().
 {
   // Cannot delete unexisting mapping.
   if (Mapping::getUidAllocator().exists(mappingId))
   {
     removeMappingItem(mappingId);
     }
 }
void MainWindow::cloneMappingItem (uid mappingId) slot
Clone/duplicate a mapping.
Definition at line 1126 of file MainWindow.cpp.
References MappingManager::addMapping(), addMappingItem(), MappingManager::getMappingById(), Mapping::getType(), and mappingManager.
Referenced by cloneItem().
 {
   // Current Mapping
   Mapping::ptr mappingPtr = mappingManager->getMappingById(mappingId);
   // Get Mapping Paint and Shape
   Paint::ptr paint = mappingPtr->getPaint();
   MShape::ptr shape = mappingPtr->getShape();
   // Temporary shared pointers
   MShape::ptr shapePtr;
   // Create new mapping
   Mapping *mapping;
   QString shapeType = shape->getType();
   // Code below need to be improved it's feel like duplicated
   if (paint->getType() == "color") // Color paint
   {
     if (shapeType == "quad")
       shapePtr = MShape::ptr(new Quad(shape->getVertex(0), shape->getVertex(1),
                                    shape->getVertex(2), shape->getVertex(3)));
     if (shapeType == "triangle")
       shapePtr = MShape::ptr(new Triangle(shape->getVertex(0), shape->getVertex(1), shape->getVertex(2)));
     if (shapeType == "ellipse")
       shapePtr = MShape::ptr(new Ellipse(shape->getVertex(0), shape->getVertex(1), shape->getVertex(2),
                              shape->getVertex(3)));
     mapping = new ColorMapping(paint, shapePtr);
   }
   else // Or Texture Paint
   {
     MShape::ptr inputShape = mappingPtr->getInputShape();
     if (shapeType == "mesh")
       shapePtr = MShape::ptr(new Mesh(shape->getVertex(0), shape->getVertex(1),
                                    shape->getVertex(3), shape->getVertex(2)));
     if (shapeType == "triangle")
       shapePtr = MShape::ptr(new Triangle(shape->getVertex(0), shape->getVertex(1), shape->getVertex(2)));
     if (shapeType == "ellipse")
       shapePtr = MShape::ptr(new Ellipse(shape->getVertex(0), shape->getVertex(1), shape->getVertex(2),
                              shape->getVertex(3), shape->getVertex(4)));
     mapping = new TextureMapping(paint, shapePtr, inputShape);
   }
   // Scaling of duplicated mapping
   if (shapeType == "quad" || shapeType == "mesh")
     shapePtr->translate(QPointF(20, 20));
   else
     shapePtr->translate(QPointF(0, 20));
   // Create new duplicated mapping item
   Mapping::ptr clonedMapping(mapping);
   uint cloneId = mappingManager->addMapping(clonedMapping);
   addMappingItem(cloneId);
 }
void MainWindow::deletePaint (uid paintId, bool replace) slot
Deletes/removes a paint and all associated mappigns.
Definition at line 1188 of file MainWindow.cpp.
References Paint::getUidAllocator(), and removePaintItem().
Referenced by deleteItem(), and deletePaintItem().
 {
   // Cannot delete unexisting paint.
   if (Paint::getUidAllocator().exists(paintId))
   {
     if (replace == false) {
       int r = QMessageBox::warning(this, tr("MapMap"),
           tr("Remove this paint and all its associated mappings?"),
           QMessageBox::Ok | QMessageBox::Cancel);
       if (r == QMessageBox::Ok)
       {
         removePaintItem(paintId);
       }
     }
     else
       removePaintItem(paintId);
   }
 }
void MainWindow::updateCanvases () slot
Updates all canvases.
Definition at line 2394 of file MainWindow.cpp.
References destinationCanvas, OutputGLWindow::getCanvas(), outputWindow, and sourceCanvas.
Referenced by addMappingItem(), enableDisplayControls(), enableTestSignal(), handleMappingIndexesMoved(), handleMappingItemSelectionChanged(), handlePaintItemSelectionChanged(), MainWindow(), removeMappingItem(), removePaintItem(), and setMappingVisible().
 {
   // Update scenes.
   sourceCanvas->scene()->update();
   destinationCanvas->scene()->update();
   // Update canvases.
   sourceCanvas->update();
   destinationCanvas->update();
   outputWindow->getCanvas()->update();
 }
void MainWindow::enableDisplayControls (bool display) slot
Definition at line 2407 of file MainWindow.cpp.
References _displayControls, and updateCanvases().
Referenced by createActions().
 {
   _displayControls = display;
   updateCanvases();
 }
void MainWindow::enableStickyVertices (bool display) slot
Definition at line 2430 of file MainWindow.cpp.
References _stickyVertices.
Referenced by createActions().
 {
   _stickyVertices = value;
 }
void MainWindow::enableTestSignal (bool enable) slot
Definition at line 2413 of file MainWindow.cpp.
References _displayTestSignal, and updateCanvases().
Referenced by addMappingItem(), and createActions().
 {
   _displayTestSignal = enable;
   updateCanvases();
 }
void MainWindow::displayUndoStack (bool display) slot
Definition at line 2419 of file MainWindow.cpp.
References _displayUndoStack, contentTab, and undoView.
Referenced by createActions().
 {
   _displayUndoStack = display;
   if (display) {
     contentTab->addTab(undoView, tr("Undo stack"));
   } else {
     contentTab->removeTab(contentTab->indexOf(undoView));
   }
 }
void MainWindow::showMappingContextMenu (const QPoint & point) slot
Definition at line 2435 of file MainWindow.cpp.
References mappingContextMenu, and mappingList.
Referenced by createMappingContextMenu().
 {
   QWidget *objectSender = dynamic_cast<QWidget*>(sender());
   if (objectSender != NULL && mappingList->count() > 0)
     mappingContextMenu->exec(objectSender->mapToGlobal(point));
 }
void MainWindow::showPaintContextMenu (const QPoint & point) slot
Definition at line 2443 of file MainWindow.cpp.
References paintContextMenu, and paintList.
Referenced by createPaintContextMenu().
 {
   QWidget *objectSender = dynamic_cast<QWidget*>(sender());
   if (objectSender != NULL && paintList->count() > 0)
     paintContextMenu->exec(objectSender->mapToGlobal(point));
 }
bool MainWindow::setTextureUri (int texture_id, const std::string & uri)
Definition at line 2719 of file MainWindow.cpp.
References MappingManager::getPaintById(), mappingManager, Image::setUri(), Media::setUri(), and videoTimer.
 {
     // TODO: const QString &
     bool success = false;
     Paint::ptr paint = this->mappingManager->getPaintById(texture_id);
     if (paint.isNull())
     {
         std::cout << "No such texture paint id " << texture_id << std::endl;
         success = false;
     }
     else
     {
         if (paint->getType() == "media")
         {
           Media *media = static_cast<Media*>(paint.data()); // FIXME: use sharedptr cast
           videoTimer->stop();
           success = media->setUri(QString(uri.c_str()));
           videoTimer->start();
         }
         else if (paint->getType() == "image")
         {
           Image *media = (Image*) paint.data(); // FIXME: use sharedptr cast
           videoTimer->stop();
           success = media->setUri(QString(uri.c_str()));
           videoTimer->start();
         }
         else
         {
             std::cout << "Paint id " << texture_id << " is not a media texture." << std::endl;
             return false;
         }
     }
     return success;
 }
bool MainWindow::setTextureRate (int texture_id, double rate)
Definition at line 2755 of file MainWindow.cpp.
References MappingManager::getPaintById(), mappingManager, Media::setRate(), and videoTimer.
 {
   Paint::ptr paint = this->mappingManager->getPaintById(texture_id);
   if (paint.isNull())
   {
       std::cout << "No such texture paint id " << texture_id << std::endl;
       return false;
   }
   else
   {
       if (paint->getType() == "media")
       {
         Media *media = static_cast<Media*>(paint.data()); // FIXME: use sharedptr cast
         videoTimer->stop();
         media->setRate(rate);
         videoTimer->start();
       }
       else
       {
           std::cout << "Paint id " << texture_id << " is not a media texture." << std::endl;
           return false;
       }
   }
   return true;
 }
bool MainWindow::setTextureVolume (int texture_id, double volume)
Definition at line 2781 of file MainWindow.cpp.
References MappingManager::getPaintById(), mappingManager, Media::setVolume(), and videoTimer.
 {
   Paint::ptr paint = this->mappingManager->getPaintById(texture_id);
   if (paint.isNull())
   {
     std::cout << "No such texture paint id " << texture_id << std::endl;
     return false;
   }
   else
   {
     if (paint->getType() == "media")
     {
         Media *media = static_cast<Media*>(paint.data()); // FIXME: use sharedptr cast
         videoTimer->stop();
         media->setVolume(volume);
         videoTimer->start();
     }
     else
     {
         std::cout << "Paint id " << texture_id << " is not a media texture." << std::endl;
         return false;
     }
   }
   return true;
 }
void MainWindow::setTexturePlayState (int texture_id, bool played)
Definition at line 2807 of file MainWindow.cpp.
References MappingManager::getPaintById(), mappingManager, and videoTimer.
 {
   Paint::ptr paint = this->mappingManager->getPaintById(texture_id);
   if (paint.isNull())
   {
     std::cout << "No such texture paint id " << texture_id << std::endl;
   }
   else
   {
     if (paint->getType() == "media")
     {
       if (played)
       {
         videoTimer->stop();
         paint->play();
         videoTimer->start();
       }
       else
       {
         videoTimer->stop();
         paint->pause();
         videoTimer->start();
       }
     }
     else
     {
       std::cout << "Paint id " << texture_id << " is not a media texture." << std::endl;
     }
   }
 }
void MainWindow::createLayout () private
Definition at line 1213 of file MainWindow.cpp.
References CANVAS_MINIMUM_HEIGHT, CANVAS_MINIMUM_WIDTH, canvasSplitter, connectProjectWidgets(), contentTab, DEFAULT_HEIGHT, DEFAULT_WIDTH, destinationCanvas, OutputGLWindow::getCanvas(), getUndoStack(), mainSplitter, MAPPING_LIST_MINIMUM_HEIGHT, MAPPING_PROPERTY_PANEL_MINIMUM_HEIGHT, mappingList, mappingPropertyPanel, mappingSplitter, outputWindow, PAINT_LIST_MINIMUM_HEIGHT, PAINT_PROPERTY_PANEL_MINIMUM_HEIGHT, paintList, paintPropertyPanel, paintSplitter, sourceCanvas, and undoView.
Referenced by MainWindow().
 {
   // Create paint list.
   paintList = new QListWidget;
   paintList->setSelectionMode(QAbstractItemView::SingleSelection);
   paintList->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
   paintList->setDefaultDropAction(Qt::MoveAction);
   paintList->setDragDropMode(QAbstractItemView::InternalMove);
   paintList->setMinimumWidth(PAINT_LIST_MINIMUM_HEIGHT);
   // Create paint panel.
   paintPropertyPanel = new QStackedWidget;
   paintPropertyPanel->setDisabled(true);
   paintPropertyPanel->setMinimumHeight(PAINT_PROPERTY_PANEL_MINIMUM_HEIGHT);
   // Create mapping list.
   mappingList = new QListWidget;
   mappingList->setSelectionMode(QAbstractItemView::SingleSelection);
   mappingList->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
   //layerList->setDragDropMode(QAbstractItemView::DragDrop);
   mappingList->setDefaultDropAction(Qt::MoveAction);
   mappingList->setDragDropMode(QAbstractItemView::InternalMove);
   mappingList->setMinimumHeight(MAPPING_LIST_MINIMUM_HEIGHT);
   // Create property panel.
   mappingPropertyPanel = new QStackedWidget;
   mappingPropertyPanel->setDisabled(true);
   mappingPropertyPanel->setMinimumHeight(MAPPING_PROPERTY_PANEL_MINIMUM_HEIGHT);
   // Create undo view.
   undoView = new QUndoView(getUndoStack(), this);
   // Create canvases.
   sourceCanvas = new SourceGLCanvas(this);
   sourceCanvas->setFocusPolicy(Qt::ClickFocus);
   sourceCanvas->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
   sourceCanvas->setMinimumSize(CANVAS_MINIMUM_WIDTH, CANVAS_MINIMUM_HEIGHT);
   destinationCanvas = new DestinationGLCanvas(this, 0, (QGLWidget*)sourceCanvas->viewport());
   destinationCanvas->setFocusPolicy(Qt::ClickFocus);
   destinationCanvas->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
   destinationCanvas->setMinimumSize(CANVAS_MINIMUM_WIDTH, CANVAS_MINIMUM_HEIGHT);
   outputWindow = new OutputGLWindow(this, destinationCanvas);
   outputWindow->setVisible(true);
   outputWindow->installEventFilter(destinationCanvas);
   outputWindow->installEventFilter(this);
   // Source scene changed -> change destination.
   connect(sourceCanvas->scene(), SIGNAL(changed(const QList<QRectF>&)),
           destinationCanvas,     SLOT(update()));
   // Destination scene changed -> change output window.
   connect(destinationCanvas->scene(), SIGNAL(changed(const QList<QRectF>&)),
           outputWindow->getCanvas(),  SLOT(update()));
   // Output changed -> change destinatioin
   // XXX si je decommente cette ligne alors quand je clique sur ajouter media ca gele...
 //  connect(outputWindow->getCanvas()->scene(), SIGNAL(changed(const QList<QRectF>&)),
 //          destinationCanvas,                  SLOT(updateCanvas()));
   // Create layout.
   paintSplitter = new QSplitter(Qt::Vertical);
   paintSplitter->addWidget(paintList);
   paintSplitter->addWidget(paintPropertyPanel);
   mappingSplitter = new QSplitter(Qt::Vertical);
   mappingSplitter->addWidget(mappingList);
   mappingSplitter->addWidget(mappingPropertyPanel);
   // Content tab.
   contentTab = new QTabWidget;
   contentTab->addTab(paintSplitter, QIcon(":/add-video"), tr("Paints"));
   contentTab->addTab(mappingSplitter, QIcon(":/add-mesh"), tr("Mappings"));
   canvasSplitter = new QSplitter(Qt::Vertical);
   canvasSplitter->addWidget(sourceCanvas);
   canvasSplitter->addWidget(destinationCanvas);
   mainSplitter = new QSplitter(Qt::Horizontal);
   mainSplitter->addWidget(canvasSplitter);
   mainSplitter->addWidget(contentTab);
   // Initialize size to 9:1 proportions.
   QSize sz = mainSplitter->size();
   QList<int> sizes;
   sizes.append(sz.width() * 0.9);
   sizes.append(sz.width() - sizes.at(0));
   mainSplitter->setSizes(sizes);
   // Upon resizing window, give some extra stretch expansion to canvasSplitter.
   mainSplitter->setStretchFactor(0, 1);
   // Final setups.
   setWindowTitle(tr("MapMap"));
   resize(DEFAULT_WIDTH, DEFAULT_HEIGHT);
   setCentralWidget(mainSplitter);
   // Connect mapping and paint lists signals and slots.
   connectProjectWidgets();
   // Reset focus on main window.
   setFocus();
 }
void MainWindow::createActions () private
Definition at line 1318 of file MainWindow.cpp.
References _displayControls, _displayTestSignal, _displayUndoStack, _stickyVertices, about(), aboutAction, addColor(), addColorAction, addEllipse(), addEllipseAction, addMesh(), addMeshAction, addTriangle(), addTriangleAction, clearRecentFileActions, clearRecentFileList(), cloneAction, cloneItem(), deleteMappingAction, deleteMappingItem(), deletePaintAction, deletePaintItem(), displayControlsAction, displayOutputWindowAction, displayTestSignalAction, displayUndoStack(), displayUndoStackAction, emptyRecentVideos, enableDisplayControls(), enableStickyVertices(), enableTestSignal(), exitAction, importImage(), importImageAction, importVideo(), importVideoAction, MaxRecentFiles, MaxRecentVideo, newAction, newFile(), open(), openAction, openRecentFile(), openRecentVideo(), outputWindow, outputWindowFullScreenAction, pause(), pauseAction, play(), playAction, preferences(), preferencesAction, recentFileActions, recentVideoActions, redoAction, renameMappingAction, renameMappingItem(), renamePaintAction, renamePaintItem(), rewind(), rewindAction, save(), saveAction, saveAs(), saveAsAction, stickyVerticesAction, undoAction, and undoStack.
Referenced by MainWindow().
 {
   // New.
   newAction = new QAction(tr("&New"), this);
   newAction->setIcon(QIcon(":/new"));
   newAction->setShortcut(QKeySequence::New);
   newAction->setStatusTip(tr("Create a new project"));
   newAction->setIconVisibleInMenu(false);
   connect(newAction, SIGNAL(triggered()), this, SLOT(newFile()));
   // Open.
   openAction = new QAction(tr("&Open..."), this);
   openAction->setIcon(QIcon(":/open"));
   openAction->setShortcut(QKeySequence::Open);
   openAction->setStatusTip(tr("Open an existing project"));
   openAction->setIconVisibleInMenu(false);
   connect(openAction, SIGNAL(triggered()), this, SLOT(open()));
   // Save.
   saveAction = new QAction(tr("&Save"), this);
   saveAction->setIcon(QIcon(":/save"));
   saveAction->setShortcut(QKeySequence::Save);
   saveAction->setStatusTip(tr("Save the project"));
   saveAction->setIconVisibleInMenu(false);
   connect(saveAction, SIGNAL(triggered()), this, SLOT(save()));
   // Save as.
   saveAsAction = new QAction(tr("Save &As..."), this);
   saveAsAction->setIcon(QIcon(":/save-as"));
   saveAsAction->setShortcut(tr("Ctrl+Shift+S"));
   saveAsAction->setStatusTip(tr("Save the project as..."));
   saveAsAction->setIconVisibleInMenu(false);
   connect(saveAsAction, SIGNAL(triggered()), this, SLOT(saveAs()));
   // Recents file
   for (int i = 0; i < MaxRecentFiles; i++)
   {
       recentFileActions[i] = new QAction(this);
       recentFileActions[i]->setVisible(false);
       connect(recentFileActions[i], SIGNAL(triggered()),
               this, SLOT(openRecentFile()));
   }
   // Recent video
   for (int i = 0; i < MaxRecentVideo; i++)
   {
       recentVideoActions[i] = new QAction(this);
       recentVideoActions[i]->setVisible(false);
       connect(recentVideoActions[i], SIGNAL(triggered()), this, SLOT(openRecentVideo()));
   }
   // Clear recent video list action
   clearRecentFileActions = new QAction(this);
   clearRecentFileActions->setVisible(true);
   connect(clearRecentFileActions, SIGNAL(triggered()), this, SLOT(clearRecentFileList()));
   // Empty list of recent video action
   emptyRecentVideos = new QAction(tr("No Recents Videos"), this);
   emptyRecentVideos->setEnabled(false);
   // Import video.
   importVideoAction = new QAction(tr("&Import Video File..."), this);
   importVideoAction->setShortcut(tr("Ctrl+I"));
   importVideoAction->setIcon(QIcon(":/add-video"));
   importVideoAction->setStatusTip(tr("Import a video source file..."));
   importVideoAction->setIconVisibleInMenu(false);
   connect(importVideoAction, SIGNAL(triggered()), this, SLOT(importVideo()));
   // Import imiage.
   importImageAction = new QAction(tr("&Import Image File..."), this);
   importImageAction->setShortcut(tr("Ctrl+Shift+I"));
   importImageAction->setIcon(QIcon(":/add-image"));
   importImageAction->setStatusTip(tr("Import a image source file..."));
   importImageAction->setIconVisibleInMenu(false);
   connect(importImageAction, SIGNAL(triggered()), this, SLOT(importImage()));
   // Add color.
   addColorAction = new QAction(tr("Add &Color Paint..."), this);
   addColorAction->setShortcut(tr("Ctrl+Shift+A"));
   addColorAction->setIcon(QIcon(":/add-color"));
   addColorAction->setStatusTip(tr("Add a color paint..."));
   addColorAction->setIconVisibleInMenu(false);
   connect(addColorAction, SIGNAL(triggered()), this, SLOT(addColor()));
   // Exit/quit.
   exitAction = new QAction(tr("E&xit"), this);
   exitAction->setShortcut(tr("Ctrl+Q"));
   exitAction->setStatusTip(tr("Exit the application"));
   exitAction->setIconVisibleInMenu(false);
   connect(exitAction, SIGNAL(triggered()), this, SLOT(close()));
   // Undo action
   undoAction = undoStack->createUndoAction(this, tr("&Undo"));
   undoAction->setShortcut(QKeySequence::Undo);
   undoAction->setIconVisibleInMenu(false);
   undoAction->setShortcutContext(Qt::ApplicationShortcut);
   //Redo action
   redoAction = undoStack->createRedoAction(this, tr("&Redo"));
   redoAction->setShortcut(QKeySequence::Redo);
   redoAction->setIconVisibleInMenu(false);
   redoAction->setShortcutContext(Qt::ApplicationShortcut);
   // About.
   aboutAction = new QAction(tr("&About"), this);
   aboutAction->setStatusTip(tr("Show the application's About box"));
   aboutAction->setIconVisibleInMenu(false);
   connect(aboutAction, SIGNAL(triggered()), this, SLOT(about()));
   // Duplicate.
   cloneAction = new QAction(tr("Duplicate"), this);
   cloneAction->setShortcut(tr("Ctrl+D"));
   cloneAction->setStatusTip(tr("Duplicate item"));
   cloneAction->setIconVisibleInMenu(false);
   connect(cloneAction, SIGNAL(triggered()), this, SLOT(cloneItem()));
   // Delete mapping.
   deleteMappingAction = new QAction(tr("Delete"), this);
   deleteMappingAction->setShortcut(tr("CTRL+DEL"));
   deleteMappingAction->setStatusTip(tr("Delete item"));
   deleteMappingAction->setIconVisibleInMenu(false);
   connect(deleteMappingAction, SIGNAL(triggered()), this, SLOT(deleteMappingItem()));
   // Rename mapping.
   renameMappingAction = new QAction(tr("Rename"), this);
   renameMappingAction->setShortcut(Qt::Key_F2);
   renameMappingAction->setStatusTip(tr("Rename item"));
   renameMappingAction->setIconVisibleInMenu(false);
   connect(renameMappingAction, SIGNAL(triggered()), this, SLOT(renameMappingItem()));
   // Delete paint.
   deletePaintAction = new QAction(tr("Delete"), this);
   //deletePaintAction->setShortcut(tr("CTRL+DEL"));
   deletePaintAction->setStatusTip(tr("Delete item"));
   deletePaintAction->setIconVisibleInMenu(false);
   connect(deletePaintAction, SIGNAL(triggered()), this, SLOT(deletePaintItem()));
   // Rename paint.
   renamePaintAction = new QAction(tr("Rename"), this);
   //renamePaintAction->setShortcut(Qt::Key_F2);
   renamePaintAction->setStatusTip(tr("Rename item"));
   renamePaintAction->setIconVisibleInMenu(false);
   connect(renamePaintAction, SIGNAL(triggered()), this, SLOT(renamePaintItem()));
   // Preferences...
   preferencesAction = new QAction(tr("&Preferences..."), this);
   //preferencesAction->setIcon(QIcon(":/preferences"));
   preferencesAction->setShortcut(tr("CTRL+,"));
   preferencesAction->setStatusTip(tr("Configure preferences..."));
   //preferencesAction->setIconVisibleInMenu(false);
   connect(preferencesAction, SIGNAL(triggered()), this, SLOT(preferences()));
   // Add quad/mesh.
   addMeshAction = new QAction(tr("Add Quad/&Mesh"), this);
   addMeshAction->setShortcut(tr("CTRL+M"));
   addMeshAction->setIcon(QIcon(":/add-mesh"));
   addMeshAction->setStatusTip(tr("Add quad/mesh"));
   addMeshAction->setIconVisibleInMenu(false);
   connect(addMeshAction, SIGNAL(triggered()), this, SLOT(addMesh()));
   addMeshAction->setEnabled(false);
   // Add triangle.
   addTriangleAction = new QAction(tr("Add &Triangle"), this);
   addTriangleAction->setShortcut(tr("CTRL+T"));
   addTriangleAction->setIcon(QIcon(":/add-triangle"));
   addTriangleAction->setStatusTip(tr("Add triangle"));
   addTriangleAction->setIconVisibleInMenu(false);
   connect(addTriangleAction, SIGNAL(triggered()), this, SLOT(addTriangle()));
   addTriangleAction->setEnabled(false);
   // Add ellipse.
   addEllipseAction = new QAction(tr("Add &Ellipse"), this);
   addEllipseAction->setShortcut(tr("CTRL+E"));
   addEllipseAction->setIcon(QIcon(":/add-ellipse"));
   addEllipseAction->setStatusTip(tr("Add ellipse"));
   addEllipseAction->setIconVisibleInMenu(false);
   connect(addEllipseAction, SIGNAL(triggered()), this, SLOT(addEllipse()));
   addEllipseAction->setEnabled(false);
   // Play.
   playAction = new QAction(tr("Play"), this);
   playAction->setShortcut(Qt::Key_Space);
   playAction->setIcon(QIcon(":/play"));
   playAction->setStatusTip(tr("Play"));
   playAction->setIconVisibleInMenu(false);
   connect(playAction, SIGNAL(triggered()), this, SLOT(play()));
   playAction->setVisible(true);
   // Pause.
   pauseAction = new QAction(tr("Pause"), this);
   pauseAction->setShortcut(Qt::Key_Space);
   pauseAction->setIcon(QIcon(":/pause"));
   pauseAction->setStatusTip(tr("Pause"));
   pauseAction->setIconVisibleInMenu(false);
   connect(pauseAction, SIGNAL(triggered()), this, SLOT(pause()));
   pauseAction->setVisible(false);
   // Pause.
   rewindAction = new QAction(tr("Rewind"), this);
   rewindAction->setShortcut(tr("CTRL+R"));
   rewindAction->setIcon(QIcon(":/rewind"));
   rewindAction->setStatusTip(tr("Rewind"));
   rewindAction->setIconVisibleInMenu(false);
   connect(rewindAction, SIGNAL(triggered()), this, SLOT(rewind()));
   // Toggle display of output window.
   displayOutputWindowAction = new QAction(tr("&Display Output Window"), this);
   displayOutputWindowAction->setShortcut(tr("Ctrl+W"));
   displayOutputWindowAction->setIcon(QIcon(":/output-window"));
   displayOutputWindowAction->setStatusTip(tr("Display output window"));
   displayOutputWindowAction->setIconVisibleInMenu(false);
   displayOutputWindowAction->setCheckable(true);
   displayOutputWindowAction->setChecked(true);
   // Manage show/hide of GL output window.
   connect(displayOutputWindowAction, SIGNAL(toggled(bool)), outputWindow, SLOT(setVisible(bool)));
   // When closing the GL output window, uncheck the action in menu.
   connect(outputWindow, SIGNAL(closed()), displayOutputWindowAction, SLOT(toggle()));
   // Toggle display of output window.
   outputWindowFullScreenAction = new QAction(tr("&Fullscreen"), this);
   outputWindowFullScreenAction->setIcon(QIcon(":/fullscreen"));
   outputWindowFullScreenAction->setShortcut(tr("Ctrl+F"));
   outputWindowFullScreenAction->setStatusTip(tr("Full screen"));
   outputWindowFullScreenAction->setIconVisibleInMenu(false);
   outputWindowFullScreenAction->setCheckable(true);
   outputWindowFullScreenAction->setChecked(false);
   // Manage fullscreen mode for output window.
   connect(outputWindowFullScreenAction, SIGNAL(toggled(bool)), outputWindow, SLOT(setFullScreen(bool)));
   // When fullscreen is toggled by the output window (eg. when pressing ESC), change the action checkbox.
   connect(outputWindow, SIGNAL(fullScreenToggled(bool)), outputWindowFullScreenAction, SLOT(setChecked(bool)));
   // Output window should be displayed for full screen option to be available.
   connect(displayOutputWindowAction, SIGNAL(toggled(bool)), outputWindowFullScreenAction, SLOT(setEnabled(bool)));
   // Toggle display of canvas controls.
   displayControlsAction = new QAction(tr("&Display Canvas Controls"), this);
   displayControlsAction->setShortcut(tr("Alt+D"));
   displayControlsAction->setIcon(QIcon(":/control-points"));
   displayControlsAction->setStatusTip(tr("Display canvas controls"));
   displayControlsAction->setIconVisibleInMenu(false);
   displayControlsAction->setCheckable(true);
   displayControlsAction->setChecked(_displayControls);
   // Manage show/hide of canvas controls.
   connect(displayControlsAction, SIGNAL(toggled(bool)), this, SLOT(enableDisplayControls(bool)));
   // Toggle sticky vertices
   stickyVerticesAction = new QAction(tr("&Sticky Vertices"), this);
   stickyVerticesAction->setShortcut(tr("Alt+S"));
   stickyVerticesAction->setIcon(QIcon(":/control-points"));
   stickyVerticesAction->setStatusTip(tr("Enable sticky vertices"));
   stickyVerticesAction->setIconVisibleInMenu(false);
   stickyVerticesAction->setCheckable(true);
   stickyVerticesAction->setChecked(_stickyVertices);
   // Manage sticky vertices
   connect(stickyVerticesAction, SIGNAL(toggled(bool)), this, SLOT(enableStickyVertices(bool)));
   displayTestSignalAction = new QAction(tr("&Display Test Signal"), this);
   displayTestSignalAction->setShortcut(tr("Alt+T"));
   displayTestSignalAction->setIcon(QIcon(":/control-points"));
   displayTestSignalAction->setStatusTip(tr("Display test signal"));
   displayTestSignalAction->setIconVisibleInMenu(false);
   displayTestSignalAction->setCheckable(true);
   displayTestSignalAction->setChecked(_displayTestSignal);
   // Manage show/hide of test signal
   connect(displayTestSignalAction, SIGNAL(toggled(bool)), this, SLOT(enableTestSignal(bool)));
   // Toggle display of Undo Stack
   displayUndoStackAction = new QAction(tr("Display &Undo Stack"), this);
   displayUndoStackAction->setShortcut(tr("Ctrl+U"));
   displayUndoStackAction->setCheckable(true);
   displayUndoStackAction->setChecked(_displayUndoStack);
   // Manage show/hide of Undo Stack
   connect(displayUndoStackAction, SIGNAL(toggled(bool)), this, SLOT(displayUndoStack(bool)));
 }
void MainWindow::createMenus () private
Definition at line 1603 of file MainWindow.cpp.
References aboutAction, addColorAction, clearRecentFileActions, deleteMappingAction, displayControlsAction, displayOutputWindowAction, displayTestSignalAction, displayUndoStackAction, editMenu, emptyRecentVideos, exitAction, fileMenu, helpMenu, importImageAction, importVideoAction, MaxRecentFiles, MaxRecentVideo, newAction, openAction, outputWindowFullScreenAction, pauseAction, playAction, preferencesAction, recentFileActions, recentFileMenu, recentVideoActions, recentVideoMenu, redoAction, rewindAction, runMenu, saveAction, saveAsAction, separatorAction, stickyVerticesAction, undoAction, and viewMenu.
Referenced by MainWindow().
 {
   QMenuBar *menuBar = NULL;
 #ifdef __MACOSX_CORE__
   menuBar = new QMenuBar(0);
   //this->setMenuBar(menuBar);
 #else
   menuBar = this->menuBar();
 #endif
   // File
   fileMenu = menuBar->addMenu(tr("&File"));
   fileMenu->addAction(newAction);
   fileMenu->addAction(openAction);
   fileMenu->addAction(saveAction);
   fileMenu->addAction(saveAsAction);
   fileMenu->addSeparator();
   fileMenu->addAction(importVideoAction);
   fileMenu->addAction(importImageAction);
   fileMenu->addAction(addColorAction);
   // Recent file separator
   separatorAction = fileMenu->addSeparator();
   recentFileMenu = fileMenu->addMenu(tr("Open Recents Projects"));
   for (int i = 0; i < MaxRecentFiles; ++i)
       recentFileMenu->addAction(recentFileActions[i]);
   recentFileMenu->addAction(clearRecentFileActions);
   // Recent import video
   recentVideoMenu = fileMenu->addMenu(tr("Open Recents Videos"));
   recentVideoMenu->addAction(emptyRecentVideos);
   for (int i = 0; i < MaxRecentVideo; ++i)
       recentVideoMenu->addAction(recentVideoActions[i]);
   // Exit
   fileMenu->addSeparator();
   fileMenu->addAction(exitAction);
   // Edit.
   editMenu = menuBar->addMenu(tr("&Edit"));
   editMenu->addAction(undoAction);
   editMenu->addAction(redoAction);
   editMenu->addAction(deleteMappingAction);
   editMenu->addAction(preferencesAction);
   // View.
   viewMenu = menuBar->addMenu(tr("&View"));
   viewMenu->addAction(displayOutputWindowAction);
   viewMenu->addAction(outputWindowFullScreenAction);
   viewMenu->addAction(displayControlsAction);
   viewMenu->addAction(stickyVerticesAction);
   viewMenu->addAction(displayTestSignalAction);
   viewMenu->addSeparator();
   viewMenu->addAction(displayUndoStackAction);
   // Run.
   runMenu = menuBar->addMenu(tr("&Run"));
   runMenu->addAction(playAction);
   runMenu->addAction(pauseAction);
   runMenu->addAction(rewindAction);
   // Help.
   helpMenu = menuBar->addMenu(tr("&Help"));
   helpMenu->addAction(aboutAction);
 //  helpMenu->addAction(aboutQtAction);
 }
void MainWindow::createMappingContextMenu () private
Definition at line 1673 of file MainWindow.cpp.
References cloneAction, deleteMappingAction, destinationCanvas, mappingContextMenu, mappingList, outputWindow, renameMappingAction, and showMappingContextMenu().
Referenced by MainWindow().
 {
   // Context menu.
   mappingContextMenu = new QMenu();
   // Add different Action
   mappingContextMenu->addAction(cloneAction);
   mappingContextMenu->addAction(deleteMappingAction);
   mappingContextMenu->addAction(renameMappingAction);
   // Set context menu policy
   mappingList->setContextMenuPolicy(Qt::CustomContextMenu);
   destinationCanvas->setContextMenuPolicy(Qt::CustomContextMenu);
   outputWindow->setContextMenuPolicy(Qt::CustomContextMenu);
   // Context Menu Connexions
   connect(mappingList, SIGNAL(customContextMenuRequested(const QPoint&)), this, SLOT(showMappingContextMenu(const QPoint&)));
   connect(destinationCanvas, SIGNAL(customContextMenuRequested(const QPoint&)), this, SLOT(showMappingContextMenu(const QPoint&)));
   connect(outputWindow, SIGNAL(customContextMenuRequested(const QPoint&)), this, SLOT(showMappingContextMenu(const QPoint&)));
 }
void MainWindow::createPaintContextMenu () private
Definition at line 1694 of file MainWindow.cpp.
References deletePaintAction, paintContextMenu, paintList, renamePaintAction, showPaintContextMenu(), and sourceCanvas.
Referenced by MainWindow().
 {
   // Paint Context Menu
   paintContextMenu = new QMenu();
   // Add Actions
   paintContextMenu->addAction(deletePaintAction);
   paintContextMenu->addAction(renamePaintAction);
   // Define Context policy
   paintList->setContextMenuPolicy(Qt::CustomContextMenu);
   sourceCanvas->setContextMenuPolicy(Qt::CustomContextMenu);
   // Connexions
   connect(paintList, SIGNAL(customContextMenuRequested(const QPoint&)), this, SLOT(showPaintContextMenu(const QPoint&)));
   connect(sourceCanvas, SIGNAL(customContextMenuRequested(const QPoint&)), this, SLOT(showPaintContextMenu(const QPoint&)));
 }
void MainWindow::createToolBars () private
Definition at line 1712 of file MainWindow.cpp.
References addColorAction, addEllipseAction, addMeshAction, addTriangleAction, displayControlsAction, displayOutputWindowAction, displayTestSignalAction, importImageAction, importVideoAction, mainToolBar, newAction, openAction, outputWindowFullScreenAction, pauseAction, playAction, rewindAction, runToolBar, saveAction, stickyVerticesAction, and MM::TOP_TOOLBAR_ICON_SIZE.
Referenced by MainWindow().
 {
   mainToolBar = addToolBar(tr("&File"));
   mainToolBar->setIconSize(QSize(MM::TOP_TOOLBAR_ICON_SIZE, MM::TOP_TOOLBAR_ICON_SIZE));
   mainToolBar->setMovable(false);
   mainToolBar->addAction(importVideoAction);
   mainToolBar->addAction(importImageAction);
   mainToolBar->addAction(addColorAction);
   mainToolBar->addAction(newAction);
   mainToolBar->addAction(openAction);
   mainToolBar->addAction(saveAction);
   mainToolBar->addSeparator();
   mainToolBar->addAction(addMeshAction);
   mainToolBar->addAction(addTriangleAction);
   mainToolBar->addAction(addEllipseAction);
   mainToolBar->addSeparator();
   mainToolBar->addAction(displayOutputWindowAction);
   mainToolBar->addAction(outputWindowFullScreenAction);
   mainToolBar->addAction(displayControlsAction);
   mainToolBar->addAction(stickyVerticesAction);
   mainToolBar->addAction(displayTestSignalAction);
   runToolBar = addToolBar(tr("&Run"));
   runToolBar->setIconSize(QSize(MM::TOP_TOOLBAR_ICON_SIZE, MM::TOP_TOOLBAR_ICON_SIZE));
   runToolBar->setMovable(false);
   // XXX: style hack: dummy expanding widget allows the placement of toolbar at the top right
   // From: http://www.qtcentre.org/threads/9102-QToolbar-setContentsMargins
   QWidget* spacer = new QWidget(runToolBar);
   spacer->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
   runToolBar->addWidget(spacer);
   runToolBar->addAction(playAction);
   runToolBar->addAction(pauseAction);
   runToolBar->addAction(rewindAction);
   // Add toolbars.
   addToolBar(Qt::TopToolBarArea, mainToolBar);
   addToolBar(Qt::TopToolBarArea, runToolBar);
 //  editToolBar = addToolBar(tr("&Edit"));
 //  editToolBar->addAction(cloneAction);
 //  editToolBar->addAction(deleteAction);
 //  editToolBar->addSeparator();
 //  editToolBar->addAction(findAction);
 //  editToolBar->addAction(goToCellAction);
 }
void MainWindow::createStatusBar () private
Definition at line 1762 of file MainWindow.cpp.
References updateStatusBar().
Referenced by MainWindow().
 {
 //  locationLabel = new QLabel(" W999 ");
 //  locationLabel->setAlignment(Qt::AlignHCenter);
 //  locationLabel->setMinimumSize(locationLabel->sizeHint());
 //
 //  formulaLabel = new QLabel;
 //  formulaLabel->setIndent(3);
 //
 //  statusBar()->addWidget(locationLabel);
 //  statusBar()->addWidget(formulaLabel, 1);
 //
 //  connect(spreadsheet, SIGNAL(currentCellChanged(int, int, int, int)), this,
 //      SLOT(updateStatusBar()));
 //  connect(spreadsheet, SIGNAL(modified()), this, SLOT(spreadsheetModified()));
   updateStatusBar();
 }
void MainWindow::updateRecentFileActions () private
Definition at line 1951 of file MainWindow.cpp.
References clearRecentFileActions, MaxRecentFiles, recentFileActions, recentFiles, separatorAction, settings, and strippedName().
Referenced by clearRecentFileList(), MainWindow(), readSettings(), and setCurrentFile().
 {
   recentFiles = settings.value("recentFiles").toStringList();
   int numRecentFiles = qMin(recentFiles.size(), int(MaxRecentFiles));
   for (int j = 0; j < numRecentFiles; ++j)
   {
     QString text = tr("&%1 %2")
       .arg(j + 1)
       .arg(strippedName(recentFiles[j]));
     recentFileActions[j]->setText(text);
     recentFileActions[j]->setData(recentFiles[j]);
     recentFileActions[j]->setVisible(true);
     clearRecentFileActions->setVisible(true);
   }
   for (int i = numRecentFiles; i < MaxRecentFiles; ++i)
   {
     recentFileActions[i]->setVisible(false);
   }
   if (numRecentFiles > 0)
   {
     separatorAction->setVisible(true);
     clearRecentFileActions->setText(tr("Clear List"));
     clearRecentFileActions->setEnabled(true);
   } else {
     clearRecentFileActions->setText(tr("No Recents Projects"));
     clearRecentFileActions->setEnabled(false);
   }
 }
void MainWindow::updateRecentVideoActions () private
Definition at line 1983 of file MainWindow.cpp.
References emptyRecentVideos, MaxRecentVideo, recentVideoActions, recentVideos, settings, and strippedName().
Referenced by MainWindow(), readSettings(), and setCurrentVideo().
 {
     recentVideos = settings.value("recentVideos").toStringList();
     int numRecentVideos = qMin(recentVideos.size(), int(MaxRecentVideo));
     for (int i = 0; i < numRecentVideos; ++i)
     {
         QString text = tr("&%1 %2")
                 .arg(i + 1)
                 .arg(strippedName(recentVideos[i]));
         recentVideoActions[i]->setText(text);
         recentVideoActions[i]->setData(recentVideos[i]);
         recentVideoActions[i]->setVisible(true);
     }
     for (int j = numRecentVideos; j < MaxRecentVideo; ++j)
         recentVideoActions[j]->setVisible(false);
     if (numRecentVideos >  0)
     {
         emptyRecentVideos->setVisible(false);
     }
 }
void MainWindow::readSettings () private
Definition at line 1781 of file MainWindow.cpp.
References canvasSplitter, config_osc_receive_port, displayOutputWindowAction, displayUndoStackAction, mainSplitter, mappingSplitter, outputWindow, outputWindowFullScreenAction, paintSplitter, settings, updateRecentFileActions(), and updateRecentVideoActions().
Referenced by MainWindow().
 {
   // FIXME: for each setting that is new since the first release in the major version number branch,
   // make sure it exists before reading its value.
   QSettings settings("MapMap", "MapMap");
   // settings present since 0.1.0:
   restoreGeometry(settings.value("geometry").toByteArray());
   mainSplitter->restoreState(settings.value("mainSplitter").toByteArray());
   paintSplitter->restoreState(settings.value("paintSplitter").toByteArray());
   mappingSplitter->restoreState(settings.value("mappingSplitter").toByteArray());
   canvasSplitter->restoreState(settings.value("canvasSplitter").toByteArray());
   outputWindow->restoreGeometry(settings.value("outputWindow").toByteArray());
   // new in 0.1.2:
   if (settings.contains("displayOutputWindow"))
   {
     displayOutputWindowAction->setChecked(settings.value("displayOutputWindow").toBool());
   }
   if (settings.contains("outputWindowFullScreen"))
   {
     outputWindowFullScreenAction->setChecked(settings.value("outputWindowFullScreen").toBool());
   }
   if (settings.contains("displayTestSignal"))
   {
     displayOutputWindowAction->setChecked(settings.value("displayTestSignal").toBool());
   }
   config_osc_receive_port = settings.value("osc_receive_port", 12345).toInt();
   // Update Recent files and video
   updateRecentFileActions();
   updateRecentVideoActions();
   // new in 0.3.2
   if (settings.contains("displayUndoStack"))
     displayUndoStackAction->setChecked(settings.value("displayUndoStack").toBool());
 }
void MainWindow::writeSettings () private
Definition at line 1819 of file MainWindow.cpp.
References canvasSplitter, config_osc_receive_port, displayOutputWindowAction, displayTestSignalAction, displayUndoStackAction, mainSplitter, mappingSplitter, outputWindow, outputWindowFullScreenAction, paintSplitter, and settings.
Referenced by closeEvent().
 {
   QSettings settings("MapMap", "MapMap");
   settings.setValue("geometry", saveGeometry());
   settings.setValue("mainSplitter", mainSplitter->saveState());
   settings.setValue("paintSplitter", paintSplitter->saveState());
   settings.setValue("mappingSplitter", mappingSplitter->saveState());
   settings.setValue("canvasSplitter", canvasSplitter->saveState());
   settings.setValue("outputWindow", outputWindow->saveGeometry());
   settings.setValue("displayOutputWindow", displayOutputWindowAction->isChecked());
   settings.setValue("outputWindowFullScreen", outputWindowFullScreenAction->isChecked());
   settings.setValue("displayTestSignal", displayTestSignalAction->isChecked());
   settings.setValue("osc_receive_port", config_osc_receive_port);
   settings.setValue("displayUndoStack", displayUndoStackAction->isChecked());
 }
void MainWindow::startOscReceiver () private
Definition at line 2607 of file MainWindow.cpp.
References config_osc_receive_port, osc_timer, and pollOscInterface().
Referenced by MainWindow(), and setOscPort().
 {
 #ifdef HAVE_OSC
   int port = config_osc_receive_port;
   std::ostringstream os;
   os << port;
   std::cout << "OSC port: " << port << std::endl;
   osc_interface.reset(new OscInterface(os.str()));
   if (port != 0)
   {
     osc_interface->start();
   }
   osc_timer = new QTimer(this); // FIXME: memleak?
   connect(osc_timer, SIGNAL(timeout()), this, SLOT(pollOscInterface()));
   osc_timer->start();
 #endif
 }
bool MainWindow::okToContinue () private
Definition at line 1836 of file MainWindow.cpp.
References save().
Referenced by closeEvent(), newFile(), and open().
 {
   if (isWindowModified())
   {
     int r = QMessageBox::warning(this, tr("MapMap"),
         tr("The document has been modified.\n"
             "Do you want to save your changes?"),
         QMessageBox::Yes | QMessageBox::No | QMessageBox::Cancel);
     if (r == QMessageBox::Yes)
     {
       return save();
     }
     else if (r == QMessageBox::Cancel)
     {
       return false;
     }
   }
   return true;
 }
bool MainWindow::loadFile (const QString & fileName)
Definition at line 1856 of file MainWindow.cpp.
References clearProject(), ProjectReader::errorString(), ProjectReader::readFile(), setCurrentFile(), and settings.
Referenced by main(), open(), and openRecentFile().
 {
   QFile file(fileName);
   QDir currentDir;
   if (! file.open(QFile::ReadOnly | QFile::Text))
   {
     QMessageBox::warning(this, tr("Error reading mapping project file"),
       tr("Cannot read file %1:\n%2.")
       .arg(fileName)
       .arg(file.errorString()));
       return false;
   }
   // Clear current project.
   clearProject();
   // Read new project
   ProjectReader reader(this);
   if (! reader.readFile(&file))
   {
     QMessageBox::warning(this, tr("Error reading mapping project file"),
       tr("Parse error in file %1:\n\n%2")
       .arg(fileName)
       .arg(reader.errorString()));
   }
   else
   {
     settings.setValue("defaultProjectDir", currentDir.absoluteFilePath(fileName));
     statusBar()->showMessage(tr("File loaded"), 2000);
     setCurrentFile(fileName);
   }
   return true;
 }
bool MainWindow::saveFile (const QString & fileName)
Definition at line 1892 of file MainWindow.cpp.
References mappingManager, setCurrentFile(), and ProjectWriter::writeFile().
Referenced by save(), and saveAs().
 {
   QFile file(fileName);
   if (! file.open(QFile::WriteOnly | QFile::Text))
   {
     QMessageBox::warning(this, tr("Error saving mapping project"),
       tr("Cannot write file %1:\n%2.")
         .arg(fileName)
         .arg(file.errorString()));
     return false;
   }
   ProjectWriter writer(mappingManager);
   if (writer.writeFile(&file))
   {
     setCurrentFile(fileName);
     statusBar()->showMessage(tr("File saved"), 2000);
     return true;
   }
   else
     return false;
 }
void MainWindow::setCurrentFile (const QString & fileName)
Definition at line 1915 of file MainWindow.cpp.
References curFile, MaxRecentFiles, recentFiles, settings, strippedName(), and updateRecentFileActions().
Referenced by loadFile(), MainWindow(), newFile(), and saveFile().
 {
   curFile = fileName;
   setWindowModified(false);
   QString shownName = tr("Untitled");
   if (!curFile.isEmpty())
   {
     shownName = strippedName(curFile);
     recentFiles = settings.value("recentFiles").toStringList();
     recentFiles.removeAll(curFile);
     recentFiles.prepend(curFile);
     while (recentFiles.size() > MaxRecentFiles)
     {
       recentFiles.removeLast();
     }
     settings.setValue("recentFiles", recentFiles);
     updateRecentFileActions();
   }
   setWindowTitle(tr("%1[*] - %2").arg(shownName).arg(tr("MapMap Project")));
 }
void MainWindow::setCurrentVideo (const QString & filename)
Definition at line 1938 of file MainWindow.cpp.
References curVideo, MaxRecentVideo, recentVideos, settings, and updateRecentVideoActions().
Referenced by importMediaFile().
 {
     curVideo = fileName;
     recentVideos = settings.value("recentVideos").toStringList();
     recentVideos.removeAll(curVideo);
     recentVideos.prepend(curVideo);
     while (recentVideos.size() > MaxRecentVideo)
         recentVideos.removeLast();
     settings.setValue("recentVideos", recentVideos);
     updateRecentVideoActions();
 }
bool MainWindow::importMediaFile (const QString & fileName, bool isImage)
Definition at line 2023 of file MainWindow.cpp.
References _isPlaying, createMediaPaint(), MappingManager::getPaintById(), mappingManager, NULL_UID, setCurrentVideo(), settings, and sourceCanvas.
Referenced by importImage(), importVideo(), and openRecentVideo().
 {
   QFile file(fileName);
   QDir currentDir;
   QFileInfo info(fileName);
   QString ext = info.completeSuffix();
   if (!)
   bool live = false;
   if (!file.open(QIODevice::ReadOnly)) {
     if (file.isSequential())
       live = true;
     else {
       QMessageBox::warning(this, tr("MapMap Project"),
                            tr("Cannot read file %1:\n%2.")
                            .arg(file.fileName())
                            .arg(file.errorString()));
       return false;
     }
   }
   QApplication::setOverrideCursor(Qt::WaitCursor);
   // Add media file to model.
   uint mediaId = createMediaPaint(NULL_UID, fileName, 0, 0, isImage, live);
   // Initialize position (center).
   QSharedPointer<Media> media = qSharedPointerCast<Media>(mappingManager->getPaintById(mediaId));
   Q_CHECK_PTR(media);
   if (_isPlaying)
     media->play();
   else
     media->pause();
   media->setPosition((sourceCanvas->width()  - media->getWidth() ) / 2.0f,
                      (sourceCanvas->height() - media->getHeight()) / 2.0f );
   QApplication::restoreOverrideCursor();
   if (!isImage)
   {
     settings.setValue("defaultVideoDir", currentDir.absoluteFilePath(fileName));
     setCurrentVideo(fileName);
   }
   else
   {
     settings.setValue("defaultImageDir", currentDir.absoluteFilePath(fileName));
   }
   statusBar()->showMessage(tr("File imported"), 2000);
   return true;
 }
bool MainWindow::addColorPaint (const QColor & color)
Definition at line 2079 of file MainWindow.cpp.
References _isPlaying, createColorPaint(), MappingManager::getPaintById(), mappingManager, and NULL_UID.
Referenced by addColor().
 {
   QApplication::setOverrideCursor(Qt::WaitCursor);
   // Add color to model.
   uint colorId = createColorPaint(NULL_UID, color);
   // Initialize position (center).
   QSharedPointer<Color> colorPaint = qSharedPointerCast<Color>(mappingManager->getPaintById(colorId));
   Q_CHECK_PTR(colorPaint);
   // Does not do anything...
   if (_isPlaying)
     colorPaint->play();
   else
     colorPaint->pause();
   QApplication::restoreOverrideCursor();
   statusBar()->showMessage(tr("Color paint added"), 2000);
   return true;
 }
void MainWindow::addMappingItem (uid mappingId)
Definition at line 2164 of file MainWindow.cpp.
References contentTab, destinationCanvas, enableTestSignal(), MappingManager::getMappingById(), mappers, mappingList, mappingManager, mappingPropertyPanel, mappingSplitter, setItemId(), SHAPE_LIST_ITEM_HEIGHT, sourceCanvas, updateCanvases(), and windowModified().
Referenced by addEllipse(), addMesh(), addTriangle(), cloneMappingItem(), createEllipseColorMapping(), createEllipseTextureMapping(), createMeshTextureMapping(), createQuadColorMapping(), createTriangleColorMapping(), createTriangleTextureMapping(), AddShapesCommand::redo(), and DeleteMappingCommand::undo().
 {
   Mapping::ptr mapping = mappingManager->getMappingById(mappingId);
   Q_CHECK_PTR(mapping);
   QString label;
   QIcon icon;
   QString shapeType = mapping->getShape()->getType();
   QString paintType = mapping->getPaint()->getType();
   // Add mapper.
   // XXX hardcoded for textures
   QSharedPointer<TextureMapping> textureMapping;
   if (paintType == "media" || paintType == "image")
   {
     textureMapping = qSharedPointerCast<TextureMapping>(mapping);
     Q_CHECK_PTR(textureMapping);
   }
   MappingGui::ptr mapper;
   // XXX Branching on nVertices() is crap
   // Triangle
   if (shapeType == "triangle")
   {
     label = QString("Triangle %1").arg(mappingId);
     icon = QIcon(":/shape-triangle");
     if (paintType == "color")
       mapper = MappingGui::ptr(new PolygonColorMappingGui(mapping));
     else
       mapper = MappingGui::ptr(new TriangleTextureMappingGui(textureMapping));
   }
   // Mesh
   else if (shapeType == "mesh" || shapeType == "quad")
   {
     label = QString(shapeType == "mesh" ? "Mesh %1" : "Quad %1").arg(mappingId);
     icon = QIcon(":/shape-mesh");
     if (paintType == "color")
       mapper = MappingGui::ptr(new PolygonColorMappingGui(mapping));
     else
       mapper = MappingGui::ptr(new MeshTextureMappingGui(textureMapping));
   }
   else if (shapeType == "ellipse")
   {
     label = QString("Ellipse %1").arg(mappingId);
     icon = QIcon(":/shape-ellipse");
     if (paintType == "color")
       mapper = MappingGui::ptr(new EllipseColorMappingGui(mapping));
     else
       mapper = MappingGui::ptr(new EllipseTextureMappingGui(textureMapping));
   }
   else
   {
     label = QString("Polygon %1").arg(mappingId);
     icon = QIcon(":/shape-polygon");
   }
   // Add to list of mappers.
   mappers[mappingId] = mapper;
   QWidget* mapperEditor = mapper->getPropertiesEditor();
   mappingPropertyPanel->addWidget(mapperEditor);
   mappingPropertyPanel->setCurrentWidget(mapperEditor);
   mappingPropertyPanel->setEnabled(true);
   // When mapper value is changed, update canvases.
   connect(mapper.data(), SIGNAL(valueChanged()),
           this,          SLOT(updateCanvases()));
   connect(sourceCanvas,  SIGNAL(shapeChanged(MShape*)),
           mapper.data(), SLOT(updateShape(MShape*)));
   connect(destinationCanvas, SIGNAL(shapeChanged(MShape*)),
           mapper.data(),     SLOT(updateShape(MShape*)));
   // Switch to mapping tab.
   contentTab->setCurrentWidget(mappingSplitter);
   // Add item to layerList widget.
   QListWidgetItem* item = new QListWidgetItem(label);
   item->setFlags(item->flags() | Qt::ItemIsUserCheckable);
   item->setCheckState(Qt::Checked);
   setItemId(*item, mappingId); // TODO: could possibly be replaced by a Paint pointer
   item->setIcon(icon);
   item->setSizeHint(QSize(item->sizeHint().width(), MainWindow::SHAPE_LIST_ITEM_HEIGHT));
   mappingList->insertItem(0, item);
   mappingList->setCurrentItem(item);
   // Disable Test signal when add Shapes
   enableTestSignal(false);
   // Add items to scenes.
   if (mapper->getInputGraphicsItem())
     sourceCanvas->scene()->addItem(mapper->getInputGraphicsItem().data());
   if (mapper->getGraphicsItem())
     destinationCanvas->scene()->addItem(mapper->getGraphicsItem().data());
   // Window was modified.
   windowModified();
 }
void MainWindow::removeMappingItem (uid mappingId)
Definition at line 2268 of file MainWindow.cpp.
References currentSelectedItem, getItemRowFromId(), MappingManager::getMappingById(), mappers, mappingList, mappingManager, mappingPropertyPanel, MappingManager::removeMapping(), updateCanvases(), and windowModified().
Referenced by deleteMapping(), and removePaintItem().
 {
   Mapping::ptr mapping = mappingManager->getMappingById(mappingId);
   Q_CHECK_PTR(mapping);
   // Remove mapping from model.
   mappingManager->removeMapping(mappingId);
   // Remove associated mapper.
   mappingPropertyPanel->removeWidget(mappers[mappingId]->getPropertiesEditor());
   mappers.remove(mappingId);
   // Remove widget from mappingList.
   int row = getItemRowFromId(*mappingList, mappingId);
   Q_ASSERT( row >= 0 );
   QListWidgetItem* item = mappingList->takeItem(row);
   if (item == currentSelectedItem)
     currentSelectedItem = NULL;
   delete item;
   // Update list.
   mappingList->update();
   // Update everything.
   updateCanvases();
   // Window was modified.
   windowModified();
 }
void MainWindow::addPaintItem (uid paintId, const QIcon & icon, const QString & name)
Definition at line 2103 of file MainWindow.cpp.
References contentTab, MappingManager::getPaintById(), handlePaintChanged(), mappingManager, PAINT_LIST_ITEM_HEIGHT, paintGuis, paintList, paintPropertyPanel, paintSplitter, setItemId(), and windowModified().
Referenced by createColorPaint(), and createMediaPaint().
 {
   Paint::ptr paint = mappingManager->getPaintById(paintId);
   Q_CHECK_PTR(paint);
   // Create paint gui.
   PaintGui::ptr paintGui;
   QString paintType = paint->getType();
   if (paintType == "media")
     paintGui = PaintGui::ptr(new MediaGui(paint));
   else if (paintType == "image")
     paintGui = PaintGui::ptr(new ImageGui(paint));
   else if (paintType == "color")
     paintGui = PaintGui::ptr(new ColorGui(paint));
   else
     paintGui = PaintGui::ptr(new PaintGui(paint));
   // Add to list of paint guis..
   paintGuis[paintId] = paintGui;
   QWidget* paintEditor = paintGui->getPropertiesEditor();
   paintPropertyPanel->addWidget(paintEditor);
   paintPropertyPanel->setCurrentWidget(paintEditor);
   paintPropertyPanel->setEnabled(true);
   // When paint value is changed, update canvases.
 //  connect(paintGui.get(), SIGNAL(valueChanged()),
 //          this,           SLOT(updateCanvases()));
   connect(paintGui.data(), SIGNAL(valueChanged(Paint::ptr)),
           this,            SLOT(handlePaintChanged(Paint::ptr)));
   // Add paint item to paintList widget.
   QListWidgetItem* item = new QListWidgetItem(icon, name);
   setItemId(*item, paintId); // TODO: could possibly be replaced by a Paint pointer
   // Set size.
   item->setSizeHint(QSize(item->sizeHint().width(), MainWindow::PAINT_LIST_ITEM_HEIGHT));
   // Switch to paint tab.
   contentTab->setCurrentWidget(paintSplitter);
   // Add item to paint list.
   paintList->addItem(item);
   paintList->setCurrentItem(item);
   // Window was modified.
   windowModified();
 }
void MainWindow::updatePaintItem (uid paintId, const QIcon & icon, const QString & name)
Definition at line 2152 of file MainWindow.cpp.
References getItemFromId(), paintList, and windowModified().
Referenced by handlePaintChanged().
{
   QListWidgetItem* item = getItemFromId(*paintList, paintId);
   Q_ASSERT(item);
   // Update item info.
   item->setIcon(icon);
   item->setText(name);
   // Window was modified.
   windowModified();
 }
void MainWindow::removePaintItem (uid paintId)
Definition at line 2298 of file MainWindow.cpp.
References currentSelectedItem, getItemRowFromId(), MappingManager::getPaintById(), MappingManager::getPaintMappings(), mappingManager, paintGuis, paintList, paintPropertyPanel, removeCurrentPaint(), removeMappingItem(), MappingManager::removePaint(), updateCanvases(), and windowModified().
Referenced by deletePaint().
 {
   Paint::ptr paint = mappingManager->getPaintById(paintId);
   Q_CHECK_PTR(paint);
   // Remove all mappings associated with paint.
   QMap<uid, Mapping::ptr> paintMappings = mappingManager->getPaintMappings(paint);
   for (QMap<uid, Mapping::ptr>::const_iterator it = paintMappings.constBegin();
        it != paintMappings.constEnd(); ++it) {
     removeMappingItem(it.key());
   }
   // Remove paint from model.
   Q_ASSERT( mappingManager->removePaint(paintId) );
   // Remove associated mapper.
   paintPropertyPanel->removeWidget(paintGuis[paintId]->getPropertiesEditor());
   paintGuis.remove(paintId);
   // Remove widget from paintList.
   int row = getItemRowFromId(*paintList, paintId);
   Q_ASSERT( row >= 0 );
   QListWidgetItem* item = paintList->takeItem(row);
   if (item == currentSelectedItem)
     currentSelectedItem = NULL;
   delete item;
   // Update list.
   paintList->update();
   // Reset current paint.
   removeCurrentPaint();
   // Update everything.
   updateCanvases();
   // Window was modified.
   windowModified();
   // Build mapping!
   // FIXME: mapping->build(); // I removed this 2014-04-25
 }
void MainWindow::renameMappingItem (uid mappingId, QString name)
Definition at line 754 of file MainWindow.cpp.
References mappingList.
 {
   if (mappingList->count() > 0) {
     mappingList->item(mappingId)->setText(name);
   }
 }
void MainWindow::renamePaintItem (uid paintId, QString name)
Definition at line 782 of file MainWindow.cpp.
References paintList.
 {
   if (paintList->count() > 0) {
     paintList->item(paintId)->setText(name);
   }
 }
void MainWindow::clearWindow ()
Definition at line 2339 of file MainWindow.cpp.
References clearProject().
Referenced by newFile().
 {
   clearProject();
 }
bool MainWindow::fileExists (const QString file)
Definition at line 2344 of file MainWindow.cpp.
Referenced by createMediaPaint().
 {
   QFileInfo checkFile(file);
   if (checkFile.exists() && checkFile.isFile())
     return true;
   return false;
 }
QString MainWindow::locateMediaFile (const QString & uri, bool isImage)
Definition at line 2354 of file MainWindow.cpp.
References MM::IMAGE_FILES_FILTER, and MM::VIDEO_FILES_FILTER.
Referenced by createMediaPaint().
 {
   // Get more info about url
   QFileInfo file(uri);
   // The name of the file
   QString filename = file.fileName();
   // The directory name
   QString directory = file.absolutePath();
   // Handle the case where it is video or image
   QString mediaFilter = isImage ? MM::IMAGE_FILES_FILTER : MM::VIDEO_FILES_FILTER;
   QString mediaType = isImage ? "Images" : "Videos";
   // New linked uri
   QString url;
   // Show a warning and offer to locate the file
   QMessageBox::warning(this,
     tr("Cannot load movie"),
     tr("Unable to use the file  %1  \n"
     "The original file is not found. Will you locate?")
     .arg(filename));
   // Set the new uri
   url = QFileDialog::getOpenFileName(this,
     tr("Locate file  %1 ").arg(filename),
     directory,
     tr("%1 files (%2)")
     .arg(mediaType)
     .arg(mediaFilter));
   return url;
 }
MainWindow * MainWindow::instance () static
Definition at line 2386 of file MainWindow.cpp.
References MainWindow().
Referenced by MapperGLCanvas::_glueVertex(), ShapeGraphicsItem::getCanvas(), MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getCurrentShapeGraphicsItem(), DestinationGLCanvas::getShapeGraphicsItemFromMappingId(), SourceGLCanvas::getShapeGraphicsItemFromMappingId(), ShapeGraphicsItem::isMappingCurrent(), and main().
{
   static MainWindow* inst = 0;
   if (!inst) {
     inst = new MainWindow;
   }
   return inst;
 }
QString MainWindow::strippedName (const QString & fullFileName) static
Definition at line 2451 of file MainWindow.cpp.
Referenced by createColorPaint(), createMediaPaint(), handlePaintChanged(), setCurrentFile(), updateRecentFileActions(), and updateRecentVideoActions().
 {
   return QFileInfo(fullFileName).fileName();
 }
void MainWindow::connectProjectWidgets () private
Definition at line 2456 of file MainWindow.cpp.
References handleItemSelected(), handleMappingIndexesMoved(), handleMappingItemChanged(), handleMappingItemSelectionChanged(), handlePaintItemSelectionChanged(), mappingList, paintList, renameMappingItem(), and renamePaintItem().
Referenced by clearProject(), and createLayout().
 {
   connect(paintList, SIGNAL(itemSelectionChanged()),
           this,      SLOT(handlePaintItemSelectionChanged()));
   connect(paintList, SIGNAL(itemPressed(QListWidgetItem*)),
           this,      SLOT(handleItemSelected(QListWidgetItem*)));
 //  connect(paintList, SIGNAL(itemDoubleClicked(QListWidgetItem*)),
 //          this,      SLOT(handleItemDoubleClicked(QListWidgetItem*)));
   connect(paintList, SIGNAL(itemActivated(QListWidgetItem*)),
           this,      SLOT(handleItemSelected(QListWidgetItem*)));
   connect(mappingList, SIGNAL(itemSelectionChanged()),
           this,        SLOT(handleMappingItemSelectionChanged()));
   connect(mappingList, SIGNAL(itemChanged(QListWidgetItem*)),
           this,        SLOT(handleMappingItemChanged(QListWidgetItem*)));
   connect(mappingList, SIGNAL(itemPressed(QListWidgetItem*)),
           this,        SLOT(handleItemSelected(QListWidgetItem*)));
   connect(mappingList, SIGNAL(itemActivated(QListWidgetItem*)),
           this,        SLOT(handleItemSelected(QListWidgetItem*)));
   connect(mappingList,  SIGNAL(indexesMoved(const QModelIndexList&)),
           this,                 SLOT(handleMappingIndexesMoved()));
   connect(mappingList->model(), SIGNAL(rowsMoved(const QModelIndex&, int, int, const QModelIndex &, int)),
           this,                 SLOT(handleMappingIndexesMoved()));
     // Rename mapping with double click
     connect(mappingList, SIGNAL(itemDoubleClicked(QListWidgetItem*)),
             this,      SLOT(renameMappingItem()));
     // Rename Paint with double click
     connect(paintList, SIGNAL(itemDoubleClicked(QListWidgetItem*)),
             this,      SLOT(renamePaintItem()));
 }
void MainWindow::disconnectProjectWidgets () private
Definition at line 2495 of file MainWindow.cpp.
References handleItemSelected(), handleMappingIndexesMoved(), handleMappingItemChanged(), handleMappingItemSelectionChanged(), handlePaintItemSelectionChanged(), mappingList, and paintList.
Referenced by clearProject().
 {
   disconnect(paintList, SIGNAL(itemSelectionChanged()),
              this,      SLOT(handlePaintItemSelectionChanged()));
   disconnect(paintList, SIGNAL(itemPressed(QListWidgetItem*)),
              this,      SLOT(handleItemSelected(QListWidgetItem*)));
   disconnect(paintList, SIGNAL(itemActivated(QListWidgetItem*)),
              this,      SLOT(handleItemSelected(QListWidgetItem*)));
   disconnect(mappingList, SIGNAL(itemSelectionChanged()),
              this,        SLOT(handleMappingItemSelectionChanged()));
   disconnect(mappingList, SIGNAL(itemChanged(QListWidgetItem*)),
              this,        SLOT(handleMappingItemChanged(QListWidgetItem*)));
   disconnect(mappingList, SIGNAL(itemPressed(QListWidgetItem*)),
              this,        SLOT(handleItemSelected(QListWidgetItem*)));
   disconnect(mappingList, SIGNAL(itemActivated(QListWidgetItem*)),
              this,        SLOT(handleItemSelected(QListWidgetItem*)));
   disconnect(mappingList->model(), SIGNAL(rowsMoved(const QModelIndex&, int, int, const QModelIndex &, int)),
              this,                 SLOT(handleMappingIndexesMoved()));
 }
uid MainWindow::getItemId (const QListWidgetItem & item) static private
Definition at line 2522 of file MainWindow.cpp.
Referenced by cloneItem(), deleteItem(), deleteMappingItem(), deletePaintItem(), getItemRowFromId(), handleMappingItemChanged(), handleMappingItemSelectionChanged(), and handlePaintItemSelectionChanged().
 {
   return item.data(Qt::UserRole).toInt();
 }
void MainWindow::setItemId (QListWidgetItem & item, uid id) static private
Definition at line 2527 of file MainWindow.cpp.
Referenced by addMappingItem(), and addPaintItem().
 {
   item.setData(Qt::UserRole, id);
 }
QListWidgetItem * MainWindow::getItemFromId (const QListWidget & list, uid id) static private
Definition at line 2532 of file MainWindow.cpp.
References getItemRowFromId().
Referenced by setMappingVisible(), and updatePaintItem().
{
   int row = getItemRowFromId(list, id);
   if (row >= 0)
     return list.item( row );
   else
     return NULL;
 }
int MainWindow::getItemRowFromId (const QListWidget & list, uid id) static private
Definition at line 2540 of file MainWindow.cpp.
References getItemId().
Referenced by getItemFromId(), removeMappingItem(), removePaintItem(), setCurrentMapping(), and setCurrentPaint().
 {
   for (int row=0; row<list.count(); row++)
   {
     QListWidgetItem* item = list.item(row);
     if (getItemId(*item) == id)
       return row;
   }
   return (-1);
 }
QIcon MainWindow::createColorIcon (const QColor & color) static private
Definition at line 2552 of file MainWindow.cpp.
Referenced by createColorPaint(), and handlePaintChanged().
{
   QPixmap pixmap(100,100);
   pixmap.fill(color);
   return QIcon(pixmap);
 }
QIcon MainWindow::createFileIcon (const QString & filename) static private
Definition at line 2558 of file MainWindow.cpp.
Referenced by createMediaPaint(), and handlePaintChanged().
{
   static QFileIconProvider provider;
   return provider.icon(QFileInfo(filename));
 }
QIcon MainWindow::createImageIcon (const QString & filename) static private
Definition at line 2563 of file MainWindow.cpp.
Referenced by createMediaPaint(), and handlePaintChanged().
{
   return QIcon(filename);
 }
MappingManager& MainWindow::getMappingManager () const
Definition at line 414 of file MainWindow.h.
References mappingManager.
Referenced by MapperGLCanvas::_glueVertex(), addEllipse(), addMesh(), addTriangle(), DestinationGLCanvas::getShapeFromMappingId(), SourceGLCanvas::getShapeFromMappingId(), MapperGLCanvas::mousePressEvent(), AddShapesCommand::redo(), DeleteMappingCommand::redo(), AddShapesCommand::undo(), and DeleteMappingCommand::undo().
 { return *mappingManager; }
MappingGui::ptr MainWindow::getMappingGuiByMappingId (uint id) const
Definition at line 415 of file MainWindow.h.
Referenced by DestinationGLCanvas::getShapeGraphicsItemFromMappingId(), and SourceGLCanvas::getShapeGraphicsItemFromMappingId().
 { return mappers[id]; }
uid MainWindow::getCurrentPaintId () const
Definition at line 416 of file MainWindow.h.
References currentPaintId.
Referenced by addEllipse(), addMesh(), and addTriangle().
 { return currentPaintId; }
uid MainWindow::getCurrentMappingId () const
Definition at line 417 of file MainWindow.h.
References currentMappingId.
Referenced by MapperGLCanvas::drawForeground(), handlePaintChanged(), and ShapeGraphicsItem::isMappingCurrent().
 { return currentMappingId; }
OutputGLWindow* MainWindow::getOutputWindow () const
Definition at line 418 of file MainWindow.h.
References outputWindow.
 { return outputWindow; }
bool MainWindow::hasCurrentPaint () const
Definition at line 419 of file MainWindow.h.
References _hasCurrentPaint.
 { return _hasCurrentPaint; }
bool MainWindow::hasCurrentMapping () const
Definition at line 420 of file MainWindow.h.
References _hasCurrentMapping.
 { return _hasCurrentMapping; }
void MainWindow::setCurrentPaint (int uid)
Definition at line 2567 of file MainWindow.cpp.
References _hasCurrentPaint, currentPaintId, getItemRowFromId(), NULL_UID, paintGuis, paintList, paintPropertyPanel, and removeCurrentPaint().
Referenced by handleMappingItemSelectionChanged(), and handlePaintItemSelectionChanged().
 {
   if (uid == NULL_UID)
     removeCurrentPaint();
   else {
     if (currentPaintId != uid) {
       currentPaintId = uid;
       paintList->setCurrentRow( getItemRowFromId(*paintList, uid) );
       paintPropertyPanel->setCurrentWidget(paintGuis[uid]->getPropertiesEditor());
     }
     _hasCurrentPaint = true;
   }
 }
void MainWindow::setCurrentMapping (int uid)
Definition at line 2581 of file MainWindow.cpp.
References _hasCurrentMapping, currentMappingId, getItemRowFromId(), mappers, mappingList, mappingPropertyPanel, NULL_UID, and removeCurrentMapping().
Referenced by handleMappingItemSelectionChanged(), handlePaintChanged(), and MapperGLCanvas::mousePressEvent().
 {
   if (uid == NULL_UID)
     removeCurrentMapping();
   else {
     if (currentMappingId != uid) {
       currentMappingId = uid;
       mappingList->setCurrentRow(  getItemRowFromId(*mappingList, uid) );
       mappingPropertyPanel->setCurrentWidget(mappers[uid]->getPropertiesEditor());
     }
     _hasCurrentMapping = true;
   }
 }
void MainWindow::removeCurrentPaint ()
Definition at line 2595 of file MainWindow.cpp.
References _hasCurrentPaint, currentPaintId, NULL_UID, and paintList.
Referenced by clearProject(), handlePaintChanged(), handlePaintItemSelectionChanged(), removePaintItem(), and setCurrentPaint().
{
   _hasCurrentPaint = false;
   currentPaintId = NULL_UID;
   paintList->clearSelection();
 }
void MainWindow::removeCurrentMapping ()
Definition at line 2601 of file MainWindow.cpp.
References _hasCurrentMapping, currentMappingId, mappingList, and NULL_UID.
Referenced by clearProject(), handleMappingItemSelectionChanged(), handlePaintChanged(), handlePaintItemSelectionChanged(), and setCurrentMapping().
{
   _hasCurrentMapping = false;
   currentMappingId = NULL_UID;
   mappingList->clearSelection();
 }
MapperGLCanvas* MainWindow::getSourceCanvas () const
Definition at line 426 of file MainWindow.h.
References sourceCanvas.
Referenced by ShapeGraphicsItem::getCanvas().
 { return sourceCanvas; }
MapperGLCanvas* MainWindow::getDestinationCanvas () const
Definition at line 427 of file MainWindow.h.
References destinationCanvas.
Referenced by ShapeGraphicsItem::getCanvas().
 { return destinationCanvas; }
bool MainWindow::displayControls () const
Returns true iff we should display the controls.
Definition at line 430 of file MainWindow.h.
References _displayControls.
Referenced by MapperGLCanvas::drawForeground(), and OutputGLWindow::setFullScreen().
 { return _displayControls; }
bool MainWindow::displayTestSignal () const
Returns true iff we should display the test signal.
Definition at line 433 of file MainWindow.h.
References _displayTestSignal.
 { return _displayTestSignal; }
bool MainWindow::stickyVertices () const
Returns true iff we want vertices to stick to each other.
Definition at line 436 of file MainWindow.h.
References _stickyVertices.
Referenced by MapperGLCanvas::mouseMoveEvent(), and MapperGLCanvas::mouseReleaseEvent().
 { return _stickyVertices; }
QUndoStack* MainWindow::getUndoStack () const
Definition at line 439 of file MainWindow.h.
References undoStack.
Referenced by createLayout(), MapperGLCanvas::keyPressEvent(), and MapperGLCanvas::mouseMoveEvent().
 { return undoStack; }
void MainWindow::startFullScreen ()
Definition at line 1593 of file MainWindow.cpp.
References displayControlsAction, displayOutputWindowAction, and outputWindowFullScreenAction.
Referenced by main().
 {
   // Remove canvas controls.
   displayControlsAction->setChecked(false);
   // Display output window.
   displayOutputWindowAction->setChecked(true);
   // Send fullscreen.
   outputWindowFullScreenAction->setChecked(true);
 }
bool MainWindow::setOscPort (QString portNumber)
Definition at line 2635 of file MainWindow.cpp.
References config_osc_receive_port, Util::isNumeric(), and startOscReceiver().
Referenced by PreferencesDialog::accept_cb(), main(), and setOscPort().
 {
   if (Util::isNumeric(portNumber))
   {
     int port = portNumber.toInt();
     if (port <= 1023 || port > 65535)
     {
       std::cout << "OSC port is out of range: " << portNumber.toInt() << std::endl;
       return false;
     }
     config_osc_receive_port = port;
     startOscReceiver();
   }
   else
   {
     std::cout << "OSC port is not a number: " << portNumber.toInt() << std::endl;
     return false;
   }
   return true;
 }
bool MainWindow::setOscPort (int portNumber)
Definition at line 2625 of file MainWindow.cpp.
References setOscPort().
 {
   return this->setOscPort(QString::number(portNumber));
 }
int MainWindow::getOscPort () const
Definition at line 2630 of file MainWindow.cpp.
References config_osc_receive_port.
Referenced by PreferencesDialog::resetValues().
 {
   return config_osc_receive_port;
 }
void MainWindow::setOutputWindowFullScreen (bool enable)
Definition at line 369 of file MainWindow.cpp.
References displayControlsAction, outputWindow, outputWindowFullScreenAction, and OutputGLWindow::setFullScreen().
 {
   outputWindow->setFullScreen(false);
   // setCheckState
   outputWindowFullScreenAction->setChecked(enable);
   displayControlsAction->setChecked(enable);
 }
Member Data Documentation
QMenu* MainWindow::fileMenu private
Definition at line 273 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::editMenu private
Definition at line 274 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::viewMenu private
Definition at line 275 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::runMenu private
Definition at line 276 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::helpMenu private
Definition at line 277 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::recentFileMenu private
Definition at line 278 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::recentVideoMenu private
Definition at line 279 of file MainWindow.h.
Referenced by createMenus().
QMenu* MainWindow::mappingContextMenu private
Definition at line 280 of file MainWindow.h.
Referenced by createMappingContextMenu(), and showMappingContextMenu().
QMenu* MainWindow::paintContextMenu private
Definition at line 281 of file MainWindow.h.
Referenced by createPaintContextMenu(), and showPaintContextMenu().
QToolBar* MainWindow::mainToolBar private
Definition at line 284 of file MainWindow.h.
Referenced by createToolBars().
QToolBar* MainWindow::runToolBar private
Definition at line 285 of file MainWindow.h.
Referenced by createToolBars().
QAction* MainWindow::separatorAction private
Definition at line 288 of file MainWindow.h.
Referenced by createMenus(), and updateRecentFileActions().
QAction* MainWindow::newAction private
Definition at line 289 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::openAction private
Definition at line 290 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::importVideoAction private
Definition at line 291 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::importImageAction private
Definition at line 292 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::addColorAction private
Definition at line 293 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::saveAction private
Definition at line 294 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::saveAsAction private
Definition at line 295 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::exitAction private
Definition at line 296 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::undoAction private
Definition at line 297 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::redoAction private
Definition at line 298 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::cloneAction private
Definition at line 299 of file MainWindow.h.
Referenced by createActions(), and createMappingContextMenu().
QAction* MainWindow::deleteMappingAction private
Definition at line 300 of file MainWindow.h.
Referenced by createActions(), createMappingContextMenu(), and createMenus().
QAction* MainWindow::renameMappingAction private
Definition at line 301 of file MainWindow.h.
Referenced by createActions(), and createMappingContextMenu().
QAction* MainWindow::deletePaintAction private
Definition at line 302 of file MainWindow.h.
Referenced by createActions(), and createPaintContextMenu().
QAction* MainWindow::renamePaintAction private
Definition at line 303 of file MainWindow.h.
Referenced by createActions(), and createPaintContextMenu().
QAction* MainWindow::preferencesAction private
Definition at line 304 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::aboutAction private
Definition at line 305 of file MainWindow.h.
Referenced by createActions(), and createMenus().
QAction* MainWindow::clearRecentFileActions private
Definition at line 306 of file MainWindow.h.
Referenced by createActions(), createMenus(), and updateRecentFileActions().
QAction* MainWindow::emptyRecentVideos private
Definition at line 307 of file MainWindow.h.
Referenced by createActions(), createMenus(), and updateRecentVideoActions().
QAction* MainWindow::addMeshAction private
Definition at line 309 of file MainWindow.h.
Referenced by createActions(), createToolBars(), and handlePaintItemSelectionChanged().
QAction* MainWindow::addTriangleAction private
Definition at line 310 of file MainWindow.h.
Referenced by createActions(), createToolBars(), and handlePaintItemSelectionChanged().
QAction* MainWindow::addEllipseAction private
Definition at line 311 of file MainWindow.h.
Referenced by createActions(), createToolBars(), and handlePaintItemSelectionChanged().
QAction* MainWindow::playAction private
Definition at line 313 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), pause(), and play().
QAction* MainWindow::pauseAction private
Definition at line 314 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), pause(), and play().
QAction* MainWindow::rewindAction private
Definition at line 315 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::displayOutputWindowAction private
Definition at line 317 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), readSettings(), startFullScreen(), and writeSettings().
QAction* MainWindow::outputWindowFullScreenAction private
Definition at line 319 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), eventFilter(), readSettings(), setOutputWindowFullScreen(), startFullScreen(), and writeSettings().
QAction* MainWindow::displayControlsAction private
Definition at line 320 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), setOutputWindowFullScreen(), and startFullScreen().
QAction* MainWindow::displayTestSignalAction private
Definition at line 321 of file MainWindow.h.
Referenced by createActions(), createMenus(), createToolBars(), and writeSettings().
QAction* MainWindow::stickyVerticesAction private
Definition at line 322 of file MainWindow.h.
Referenced by createActions(), createMenus(), and createToolBars().
QAction* MainWindow::displayUndoStackAction private
Definition at line 323 of file MainWindow.h.
Referenced by createActions(), createMenus(), readSettings(), and writeSettings().
QAction* MainWindow::recentFileActions[MaxRecentFiles] private
Definition at line 327 of file MainWindow.h.
Referenced by createActions(), createMenus(), and updateRecentFileActions().
QAction* MainWindow::recentVideoActions[MaxRecentVideo] private
Definition at line 328 of file MainWindow.h.
Referenced by createActions(), createMenus(), and updateRecentVideoActions().
QTabWidget* MainWindow::contentTab private
Definition at line 331 of file MainWindow.h.
Referenced by addMappingItem(), addPaintItem(), createLayout(), deleteItem(), displayUndoStack(), renameMappingItem(), and renamePaintItem().
QSplitter* MainWindow::paintSplitter private
Definition at line 333 of file MainWindow.h.
Referenced by addPaintItem(), createLayout(), deleteItem(), readSettings(), renamePaintItem(), and writeSettings().
QListWidget* MainWindow::paintList private
Definition at line 334 of file MainWindow.h.
Referenced by addPaintItem(), clearProject(), connectProjectWidgets(), createLayout(), createPaintContextMenu(), deleteItem(), deletePaintItem(), disconnectProjectWidgets(), handlePaintItemSelectionChanged(), removeCurrentPaint(), removePaintItem(), renamePaintItem(), setCurrentPaint(), showPaintContextMenu(), and updatePaintItem().
QStackedWidget* MainWindow::paintPropertyPanel private
Definition at line 335 of file MainWindow.h.
Referenced by addPaintItem(), createLayout(), removePaintItem(), and setCurrentPaint().
QSplitter* MainWindow::mappingSplitter private
Definition at line 337 of file MainWindow.h.
Referenced by addMappingItem(), createLayout(), deleteItem(), readSettings(), renameMappingItem(), and writeSettings().
QListWidget* MainWindow::mappingList private
Definition at line 338 of file MainWindow.h.
Referenced by addMappingItem(), clearProject(), cloneItem(), connectProjectWidgets(), createLayout(), createMappingContextMenu(), deleteItem(), deleteMappingItem(), disconnectProjectWidgets(), handleMappingIndexesMoved(), handleMappingItemSelectionChanged(), removeCurrentMapping(), removeMappingItem(), renameMappingItem(), setCurrentMapping(), setMappingVisible(), and showMappingContextMenu().
QStackedWidget* MainWindow::mappingPropertyPanel private
Definition at line 339 of file MainWindow.h.
Referenced by addMappingItem(), clearProject(), createLayout(), removeMappingItem(), and setCurrentMapping().
QUndoView* MainWindow::undoView private
Definition at line 341 of file MainWindow.h.
Referenced by createLayout(), and displayUndoStack().
SourceGLCanvas* MainWindow::sourceCanvas private
Definition at line 343 of file MainWindow.h.
Referenced by addEllipse(), addMappingItem(), addMesh(), addTriangle(), clearProject(), createLayout(), createPaintContextMenu(), getSourceCanvas(), importMediaFile(), and updateCanvases().
DestinationGLCanvas* MainWindow::destinationCanvas private
Definition at line 344 of file MainWindow.h.
Referenced by addMappingItem(), clearProject(), createLayout(), createMappingContextMenu(), getDestinationCanvas(), and updateCanvases().
OutputGLWindow* MainWindow::outputWindow private
Definition at line 345 of file MainWindow.h.
Referenced by createActions(), createLayout(), createMappingContextMenu(), eventFilter(), getOutputWindow(), readSettings(), setOutputWindowFullScreen(), updateCanvases(), and writeSettings().
QSplitter* MainWindow::mainSplitter private
Definition at line 347 of file MainWindow.h.
Referenced by createLayout(), readSettings(), and writeSettings().
QSplitter* MainWindow::canvasSplitter private
Definition at line 348 of file MainWindow.h.
Referenced by createLayout(), readSettings(), and writeSettings().
QStringList MainWindow::recentFiles private
Definition at line 353 of file MainWindow.h.
Referenced by clearRecentFileList(), setCurrentFile(), and updateRecentFileActions().
QStringList MainWindow::recentVideos private
Definition at line 354 of file MainWindow.h.
Referenced by setCurrentVideo(), and updateRecentVideoActions().
QString MainWindow::curFile private
Definition at line 357 of file MainWindow.h.
Referenced by save(), and setCurrentFile().
QString MainWindow::curVideo private
Definition at line 360 of file MainWindow.h.
Referenced by setCurrentVideo().
QSettings MainWindow::settings private
Definition at line 363 of file MainWindow.h.
Referenced by clearRecentFileList(), importImage(), importMediaFile(), importVideo(), loadFile(), open(), readSettings(), saveAs(), setCurrentFile(), setCurrentVideo(), updateRecentFileActions(), updateRecentVideoActions(), and writeSettings().
MappingManager* MainWindow::mappingManager private
Definition at line 366 of file MainWindow.h.
Referenced by addColorPaint(), addEllipse(), addMappingItem(), addMesh(), addPaintItem(), addTriangle(), clearProject(), cloneMappingItem(), createColorPaint(), createEllipseColorMapping(), createEllipseTextureMapping(), createMediaPaint(), createMeshTextureMapping(), createQuadColorMapping(), createTriangleColorMapping(), createTriangleTextureMapping(), getMappingManager(), handleMappingIndexesMoved(), handleMappingItemSelectionChanged(), handlePaintChanged(), importMediaFile(), MainWindow(), pause(), play(), removeMappingItem(), removePaintItem(), rewind(), saveFile(), setMappingVisible(), setTexturePlayState(), setTextureRate(), setTextureUri(), setTextureVolume(), and ~MainWindow().
int MainWindow::config_osc_receive_port private
Definition at line 372 of file MainWindow.h.
Referenced by getOscPort(), readSettings(), setOscPort(), startOscReceiver(), and writeSettings().
QTimer* MainWindow::osc_timer private
Definition at line 373 of file MainWindow.h.
Referenced by startOscReceiver(), and ~MainWindow().
QMap<uid, MappingGui::ptr> MainWindow::mappers private
Definition at line 378 of file MainWindow.h.
Referenced by addMappingItem(), clearProject(), removeMappingItem(), and setCurrentMapping().
QMap<uid, PaintGui::ptr> MainWindow::paintGuis private
Definition at line 379 of file MainWindow.h.
Referenced by addPaintItem(), clearProject(), removePaintItem(), and setCurrentPaint().
uid MainWindow::currentPaintId private
Definition at line 382 of file MainWindow.h.
Referenced by getCurrentPaintId(), handlePaintItemSelectionChanged(), MainWindow(), removeCurrentPaint(), and setCurrentPaint().
uid MainWindow::currentMappingId private
Definition at line 383 of file MainWindow.h.
Referenced by getCurrentMappingId(), MainWindow(), removeCurrentMapping(), and setCurrentMapping().
bool MainWindow::_hasCurrentMapping private
Definition at line 384 of file MainWindow.h.
Referenced by hasCurrentMapping(), MainWindow(), removeCurrentMapping(), and setCurrentMapping().
bool MainWindow::_hasCurrentPaint private
Definition at line 385 of file MainWindow.h.
Referenced by hasCurrentPaint(), MainWindow(), removeCurrentPaint(), and setCurrentPaint().
bool MainWindow::_isPlaying private
Definition at line 388 of file MainWindow.h.
Referenced by addColorPaint(), eventFilter(), importMediaFile(), MainWindow(), pause(), and play().
bool MainWindow::_displayControls private
Definition at line 391 of file MainWindow.h.
Referenced by createActions(), displayControls(), enableDisplayControls(), and MainWindow().
bool MainWindow::_displayTestSignal private
Definition at line 394 of file MainWindow.h.
Referenced by createActions(), displayTestSignal(), enableTestSignal(), and MainWindow().
bool MainWindow::_stickyVertices private
Definition at line 397 of file MainWindow.h.
Referenced by createActions(), enableStickyVertices(), MainWindow(), and stickyVertices().
bool MainWindow::_displayUndoStack private
Definition at line 399 of file MainWindow.h.
Referenced by createActions(), displayUndoStack(), and MainWindow().
QListWidgetItem* MainWindow::currentSelectedItem private
Definition at line 402 of file MainWindow.h.
Referenced by cloneItem(), deleteItem(), deleteMappingItem(), deletePaintItem(), handleItemSelected(), handleMappingItemSelectionChanged(), handlePaintItemSelectionChanged(), MainWindow(), removeMappingItem(), and removePaintItem().
QTimer* MainWindow::videoTimer private
Definition at line 403 of file MainWindow.h.
Referenced by about(), addColor(), closeEvent(), importImage(), importVideo(), MainWindow(), newFile(), open(), saveAs(), setTexturePlayState(), setTextureRate(), setTextureUri(), and setTextureVolume().
PreferencesDialog* MainWindow::_preferences_dialog private
Definition at line 405 of file MainWindow.h.
Referenced by MainWindow(), and preferences().
QUndoStack* MainWindow::undoStack private
Definition at line 408 of file MainWindow.h.
Referenced by addEllipse(), addMesh(), addTriangle(), createActions(), deleteItem(), eventFilter(), getUndoStack(), MainWindow(), and newFile().
const int MainWindow::DEFAULT_WIDTH = 1360 static
Definition at line 448 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::DEFAULT_HEIGHT = 768 static
Definition at line 449 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::PAINT_LIST_ITEM_HEIGHT = 40 static
Definition at line 450 of file MainWindow.h.
Referenced by addPaintItem().
const int MainWindow::SHAPE_LIST_ITEM_HEIGHT = 40 static
Definition at line 451 of file MainWindow.h.
Referenced by addMappingItem().
const int MainWindow::PAINT_LIST_MINIMUM_HEIGHT = 290 static
Definition at line 452 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::MAPPING_LIST_MINIMUM_HEIGHT = 290 static
Definition at line 453 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::PAINT_PROPERTY_PANEL_MINIMUM_HEIGHT = 290 static
Definition at line 454 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::MAPPING_PROPERTY_PANEL_MINIMUM_HEIGHT = 290 static
Definition at line 455 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::CANVAS_MINIMUM_WIDTH = 480 static
Definition at line 456 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::CANVAS_MINIMUM_HEIGHT = 270 static
Definition at line 457 of file MainWindow.h.
Referenced by createLayout().
const int MainWindow::OUTPUT_WINDOW_MINIMUM_WIDTH = 480 static
Definition at line 458 of file MainWindow.h.
Referenced by OutputGLWindow::OutputGLWindow().
const int MainWindow::OUTPUT_WINDOW_MINIMUM_HEIGHT = 270 static
Definition at line 459 of file MainWindow.h.
Referenced by OutputGLWindow::OutputGLWindow().
The documentation for this class was generated from the following files:
MainWindow.h
MainWindow.cpp