MapMap: OutputGLWindow Class Reference
OutputGLWindow Class Reference
This class acts as the pop-up window containing a copy of the destination canvas (see OutputGLCanvas) and that can be put to fullscreen.
#include <OutputGLWindow.h>
Public Slots
void setFullScreen (bool fullScreen)
Signals
void closed ()
void fullScreenToggled (bool fullScreen)
Public Member Functions
OutputGLWindow (QWidget *parent, const DestinationGLCanvas *canvas_)
DestinationGLCanvas * getCanvas () const
void setPointerHasMoved ()
void setCursorVisible (bool visible)
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Attributes
OutputGLCanvas * canvas
QByteArray _geometry
bool _pointerIsVisible
Detailed Description
This class acts as the pop-up window containing a copy of the destination canvas (see OutputGLCanvas) and that can be put to fullscreen.
Aside from the fullscreen functionality, it adds the possibility of removing the cursor and displaying a cross-hair.
Definition at line 37 of file OutputGLWindow.h.
Constructor & Destructor Documentation
OutputGLWindow::OutputGLWindow (QWidget * parent, const DestinationGLCanvas * canvas_)
Definition at line 26 of file OutputGLWindow.cpp.
References _geometry, _pointerIsVisible, canvas, MapperGLCanvas::getMainWindow(), MainWindow::OUTPUT_WINDOW_MINIMUM_HEIGHT, and MainWindow::OUTPUT_WINDOW_MINIMUM_WIDTH.
                                                                                    : QDialog(parent)
 {
   resize(MainWindow::OUTPUT_WINDOW_MINIMUM_WIDTH, MainWindow::OUTPUT_WINDOW_MINIMUM_HEIGHT);
   canvas = new OutputGLCanvas(canvas_->getMainWindow(), this, (const QGLWidget*)canvas_->viewport(), canvas_->scene());
   canvas->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
   canvas->setMinimumSize(MainWindow::OUTPUT_WINDOW_MINIMUM_WIDTH, MainWindow::OUTPUT_WINDOW_MINIMUM_HEIGHT);
   QLayout* layout = new QVBoxLayout;
   layout->setContentsMargins(0,0,0,0); // remove margin
   layout->addWidget(canvas);
   setLayout(layout);
   // Save window geometry.
   _geometry = saveGeometry();
   _pointerIsVisible = true;
 }
Member Function Documentation
void OutputGLWindow::setFullScreen (bool fullScreen) slot
Definition at line 88 of file OutputGLWindow.cpp.
References _geometry, canvas, MainWindow::displayControls(), fullScreenToggled(), MapperGLCanvas::getMainWindow(), setCursorVisible(), and OutputGLCanvas::setDisplayCrosshair().
Referenced by MainWindow::eventFilter(), and MainWindow::setOutputWindowFullScreen().
 {
   setCursorVisible(!fullscreen);
   emit fullScreenToggled(fullscreen);
   // Activate crosshair in fullscreen mode.
   // should be only drawn if the controls should be shown
   canvas->setDisplayCrosshair(fullscreen && canvas->getMainWindow()->displayControls());
   // NOTE: The showFullScreen() method does not work well under Ubuntu Linux. The code below fixes the issue.
   // Notice that there might be problems with the fullscreen in other OS / window managers. If so, please add
   // the code to fix those issues here.
   // See: http://qt-project.org/doc/qt-4.8/qwidget.html#showFullScreen
   // Source: http://stackoverflow.com/questions/12645880/fullscreen-for-qdialog-from-within-mainwindow-only-working-sometimes
 #ifdef Q_OS_UNIX
   const QString session = QString(getenv("DESKTOP_SESSION")).toLower();
 #endif
   if (fullscreen)
   {
     // Save window geometry.
     _geometry = saveGeometry();
     //qDebug() << "Saving Geometry " << _geometry.toHex() << endl;
     // Move window to second screen before fullscreening it.
     if (QApplication::desktop()->screenCount() > 1)
       setGeometry(QApplication::desktop()->screenGeometry(1));
 #ifdef Q_OS_UNIX
     // Special case for Unity.
     if (session == "ubuntu" || session == "cinnamon" || session == "default") {
       setWindowFlags(Qt::Window);
       setVisible(true);
       setWindowState( windowState() ^ Qt::WindowFullScreen );
       show();
     } else {
       showFullScreen();
     }
 #else
     showFullScreen();
 #endif
   }
   else
   {
     // Restore geometry of window to what it was before full screen call.
     //restoreGeometry(_geometry);
 #ifdef Q_OS_UNIX
     // Special case for Unity.
     if (session == "ubuntu") {
       showNormal();
     } else {
       restoreGeometry(_geometry);
       showNormal();
       setWindowFlags( windowFlags() & ~Qt::Window );
     }
 #else
     restoreGeometry(_geometry);
     showNormal();
 #endif
   }
 }
void OutputGLWindow::closeEvent (QCloseEvent * event) protected
Definition at line 82 of file OutputGLWindow.cpp.
References closed().
 {
   emit closed();
   event->accept();
 }
void OutputGLWindow::closed () signal
Referenced by closeEvent().
void OutputGLWindow::fullScreenToggled (bool fullScreen) signal
Referenced by setFullScreen().
DestinationGLCanvas* OutputGLWindow::getCanvas () const
Definition at line 56 of file OutputGLWindow.h.
References canvas.
Referenced by MainWindow::createLayout(), and MainWindow::updateCanvases().
 { return canvas; }
void OutputGLWindow::setPointerHasMoved ()
void OutputGLWindow::setCursorVisible (bool visible)
Definition at line 65 of file OutputGLWindow.cpp.
References _pointerIsVisible.
Referenced by setFullScreen().
 {
   _pointerIsVisible = visible;
   if (_pointerIsVisible)
   {
     this->setCursor(Qt::ArrowCursor);
     _pointerIsVisible = true;
   }
   else
   {
     this->setCursor(Qt::ArrowCursor);
     this->setCursor(Qt::BlankCursor);
     _pointerIsVisible = false;
   }
 }
Member Data Documentation
OutputGLCanvas* OutputGLWindow::canvas private
Definition at line 61 of file OutputGLWindow.h.
Referenced by getCanvas(), OutputGLWindow(), and setFullScreen().
QByteArray OutputGLWindow::_geometry private
Definition at line 62 of file OutputGLWindow.h.
Referenced by OutputGLWindow(), and setFullScreen().
bool OutputGLWindow::_pointerIsVisible private
Definition at line 64 of file OutputGLWindow.h.
Referenced by OutputGLWindow(), and setCursorVisible().
The documentation for this class was generated from the following files:
OutputGLWindow.h
OutputGLWindow.cpp