MapMap: Ellipse Class Reference
Ellipse Class Reference
#include <Shape.h>
Public Types
typedef QSharedPointer< MShape > ptr
Public Member Functions
Ellipse ()
Ellipse (QPointF p1, QPointF p2, QPointF p3, QPointF p4, QPointF p5)
Ellipse (QPointF p1, QPointF p2, QPointF p3, QPointF p4, bool hasCenterControl=true)
virtual ~Ellipse ()
void sanitize ()
Remaps points so as to make sure this is a correct ellipse, keeping vertices 0 and 2 as reference for the horizzontal axis.
virtual QString getType () const
qreal getRotationRadians () const
qreal getRotation () const
bool hasCenterControl () const
QPointF clipInside (const QPointF &v) const
If v is outside boundaries, remap it to the border.
QPointF getCenter () const
QVector2D getHorizontalAxis () const
QVector2D getVerticalAxis () const
qreal getHorizontalRadius () const
qreal getVerticalRadius () const
QTransform toUnitCircle () const
Remaps point from ellipse to a circle with radius 1 set at origin (0,0).
QTransform fromUnitCircle () const
Remaps point from circle with radius 1 set at origin (0,0) to ellipse coordinates.
virtual bool includesPoint (qreal x, qreal y)
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
virtual bool includesPoint (const QPointF &p)
virtual void setVertex (int i, const QPointF &v)
virtual void build ()
int nVertices () const
QPointF getVertex (int i) const
virtual void setVertex (int i, qreal x, qreal y)
virtual void translate (const QPointF &offset)
Translate all vertices of shape by the vector (x,y).
virtual void copyFrom (const MShape &shape)
virtual MShape * clone () const
Protected Member Functions
virtual MShape * _create () const
Returns a new MShape (using default constructor).
void _addVertex (const QPointF &vertex)
void _rawSetVertex (int i, const QPointF &v)
Protected Attributes
QVector< QPointF > vertices
Detailed Description
Definition at line 267 of file Shape.h.
Member Typedef Documentation
typedef QSharedPointer<MShape> MShape::ptr inherited
Definition at line 47 of file Shape.h.
Constructor & Destructor Documentation
Ellipse::Ellipse ()
Definition at line 269 of file Shape.h.
Referenced by _create().
 {}
Ellipse::Ellipse (QPointF p1, QPointF p2, QPointF p3, QPointF p4, QPointF p5)
Definition at line 270 of file Shape.h.
References MShape::_addVertex(), and sanitize().
   {
     _addVertex(p1);
     _addVertex(p2);
     _addVertex(p3);
     _addVertex(p4);
     _addVertex(p5);
     sanitize();
   }
Ellipse::Ellipse (QPointF p1, QPointF p2, QPointF p3, QPointF p4, bool hasCenterControl = true)
Definition at line 280 of file Shape.h.
References MShape::_addVertex(), getCenter(), hasCenterControl(), and sanitize().
   {
     _addVertex(p1);
     _addVertex(p2);
     _addVertex(p3);
     _addVertex(p4);
     if (hasCenterControl)
       _addVertex(getCenter());
     sanitize();
   }
virtual Ellipse::~Ellipse () virtual
Definition at line 291 of file Shape.h.
 {}
Member Function Documentation
void Ellipse::sanitize ()
Remaps points so as to make sure this is a correct ellipse, keeping vertices 0 and 2 as reference for the horizzontal axis.
Definition at line 566 of file Shape.cpp.
References clipInside(), getCenter(), getHorizontalAxis(), MShape::getVertex(), hasCenterControl(), and MShape::setVertex().
Referenced by Ellipse(), and setVertex().
 {
   // Get horizontal axis rotated 90 degrees CW
   QVector2D hAxis = getHorizontalAxis();
   const QVector2D center(getCenter());
   QVector2D hAxisRotated(hAxis.y(), -hAxis.x());
   // Project vertex 1 onto it.
   QVector2D vAxisNormalized = hAxisRotated.normalized();
   QVector2D vFromCenter = QVector2D(getVertex(1)) - center;
   const QVector2D& projection = QVector2D::dotProduct( vFromCenter, vAxisNormalized ) * vAxisNormalized;
   MShape::setVertex(1, (center + projection).toPointF());
   MShape::setVertex(3, (center - projection).toPointF());
   if (hasCenterControl())
   {
     // Clip control point.
     MShape::setVertex(4, clipInside(getVertex(4)));
   }
 }
virtual QString Ellipse::getType () const virtual
Implements MShape.
Definition at line 297 of file Shape.h.
 { return "ellipse"; }
qreal Ellipse::getRotationRadians () const
Definition at line 299 of file Shape.h.
References getHorizontalAxis().
Referenced by getRotation(), and toUnitCircle().
   {
     QVector2D hAxis = getHorizontalAxis();
     return atan2( hAxis.y(), hAxis.x() );
   }
qreal Ellipse::getRotation () const
Definition at line 305 of file Shape.h.
References getRotationRadians(), and radiansToDegrees().
Referenced by EllipseControlPainter::_paintShape(), Util::drawControlsEllipse(), EllipseColorGraphicsItem::shape(), and EllipseTextureGraphicsItem::shape().
   {
     return radiansToDegrees( getRotationRadians() );
   }
bool Ellipse::hasCenterControl () const
Definition at line 310 of file Shape.h.
References MShape::nVertices().
Referenced by Ellipse(), sanitize(), and setVertex().
   {
     return (nVertices() == 5);
   }
QPointF Ellipse::clipInside (const QPointF & v) const
If v is outside boundaries, remap it to the border.
Definition at line 588 of file Shape.cpp.
References fromUnitCircle(), and toUnitCircle().
Referenced by sanitize(), and setVertex().
 {
   // Map point as vector on a unit circle.
   QVector2D vector(toUnitCircle().map(v));
   // Clip control point.
   return (vector.length() <= 1 ?
                              v :
                              fromUnitCircle().map(vector.normalized().toPointF()));
 }
QPointF Ellipse::getCenter () const
Definition at line 323 of file Shape.h.
References getHorizontalAxis(), and MShape::getVertex().
Referenced by EllipseControlPainter::_paintShape(), Util::drawControlsEllipse(), Ellipse(), sanitize(), setVertex(), EllipseColorGraphicsItem::shape(), EllipseTextureGraphicsItem::shape(), and toUnitCircle().
   {
     return (QVector2D(getVertex(0)) - (getHorizontalAxis() / 2)).toPointF();
   }
QVector2D Ellipse::getHorizontalAxis () const
Definition at line 328 of file Shape.h.
References MShape::getVertex().
Referenced by getCenter(), getHorizontalRadius(), getRotationRadians(), and sanitize().
   {
     return QVector2D(getVertex(0)) - QVector2D(getVertex(2));
   }
QVector2D Ellipse::getVerticalAxis () const
Definition at line 333 of file Shape.h.
References MShape::getVertex().
Referenced by getVerticalRadius(), and setVertex().
   {
     return QVector2D(getVertex(1)) - QVector2D(getVertex(3));
   }
qreal Ellipse::getHorizontalRadius () const
Definition at line 338 of file Shape.h.
References getHorizontalAxis().
Referenced by EllipseControlPainter::_paintShape(), Util::drawControlsEllipse(), EllipseColorGraphicsItem::shape(), EllipseTextureGraphicsItem::shape(), and toUnitCircle().
   {
     return getHorizontalAxis().length() / 2;
   }
qreal Ellipse::getVerticalRadius () const
Definition at line 343 of file Shape.h.
References getVerticalAxis().
Referenced by EllipseControlPainter::_paintShape(), Util::drawControlsEllipse(), EllipseColorGraphicsItem::shape(), EllipseTextureGraphicsItem::shape(), and toUnitCircle().
   {
     return getVerticalAxis().length() / 2;
   }
QTransform Ellipse::toUnitCircle () const
Remaps point from ellipse to a circle with radius 1 set at origin (0,0).
Definition at line 600 of file Shape.cpp.
References getCenter(), getHorizontalRadius(), getRotationRadians(), and getVerticalRadius().
Referenced by clipInside(), fromUnitCircle(), includesPoint(), and setVertex().
 {
   const QPointF& center = getCenter();
   return QTransform().scale(1.0/getHorizontalRadius(), 1.0/getVerticalRadius())
                      .rotateRadians(-getRotationRadians())
                      .translate(-center.x(), -center.y());
 }
QTransform Ellipse::fromUnitCircle () const
Remaps point from circle with radius 1 set at origin (0,0) to ellipse coordinates.
Definition at line 608 of file Shape.cpp.
References toUnitCircle().
Referenced by clipInside(), and setVertex().
 {
   return toUnitCircle().inverted();
 }
bool Ellipse::includesPoint (qreal x, qreal y) virtual
Return true if Shape includes point (x,y), false otherwise Algorithm should work for all polygons, including non-convex Found at http://www.cs.tufts.edu/comp/163/notes05/point_inclusion_handout.pdf.
Reimplemented from MShape.
Definition at line 613 of file Shape.cpp.
References toUnitCircle().
Referenced by includesPoint().
 {
   return (QVector2D(toUnitCircle().map(QPointF(x, y))).length() <= 1);
 }
virtual bool Ellipse::includesPoint (const QPointF & p) virtual
Implements MShape.
Definition at line 360 of file Shape.h.
References includesPoint().
   {
     return includesPoint(p.x(), p.y());
   }
void Ellipse::setVertex (int i, const QPointF & v) virtual
Reimplemented from MShape.
Definition at line 618 of file Shape.cpp.
References MShape::_rawSetVertex(), clipInside(), fromUnitCircle(), getCenter(), MShape::getVertex(), getVerticalAxis(), hasCenterControl(), sanitize(), MShape::setVertex(), and toUnitCircle().
 {
   // Save vertical axis vector.
   const QVector2D& vAxis  = getVerticalAxis();
   // If changed one of the two rotation-controlling points, adjust the other two points.
   if (i == 0 || i == 2)
   {
     // Transformation ellipse_t --> circle.
     QTransform transform = toUnitCircle();
     // Change the vertex.
     _rawSetVertex(i, v);
     // Combine with transformation circle -> ellipse_{t+1}.
     transform *= fromUnitCircle();
     // Set vertices.
     MShape::setVertex(1, transform.map( getVertex(1) ));
     MShape::setVertex(3, transform.map( getVertex(3) ));
     if (hasCenterControl())
       MShape::setVertex(4, transform.map( getVertex(4) ));
   }
   // If changed one of the two other points, just change the vertical axis.
   else if (i == 1 || i == 3)
   {
     // Retrieve the new horizontal axis vector and center.
     const QVector2D center(getCenter());
     QVector2D vFromCenter = QVector2D(v) - center;
     // Find projection of v onto vAxis / 2.
     QVector2D vAxisNormalized = vAxis.normalized();
     const QVector2D& projection = QVector2D::dotProduct( vFromCenter, vAxisNormalized ) * vAxisNormalized;
     // Assign vertical control points.
     QPointF v1;
     QPointF v3;
     if (i == 1)
     {
       v1 = (center + projection).toPointF();
       v3 = (center - projection).toPointF();
     }
     else
     {
       v1 = (center - projection).toPointF();
       v3 = (center + projection).toPointF();
     }
     // Transformation ellipse_t --> circle.
     QTransform transform = toUnitCircle();
     // Change vertical points.
     _rawSetVertex(1, v1);
     _rawSetVertex(3, v3);
     // Combine with transformation circle -> ellipse_{t+1}.
     transform *= fromUnitCircle();
     // Set vertices.
     if (hasCenterControl())
       _rawSetVertex(4, transform.map( getVertex(4) ));
   }
   // Center control point (make sure it stays inside!).
   else if (hasCenterControl())
   {
     // Clip control point.
     _rawSetVertex(4, clipInside(v));
   }
   // Just to be sure.
   sanitize();
 }
virtual MShape* Ellipse::_create () const protected virtual
Returns a new MShape (using default constructor).
Implements MShape.
Definition at line 370 of file Shape.h.
References Ellipse().
 { return new Ellipse(); }
virtual void MShape::build () virtual inherited
Definition at line 55 of file Shape.h.
 {}
int MShape::nVertices () const inherited
Definition at line 57 of file Shape.h.
References MShape::vertices.
Referenced by MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MappingGui::_updateShapeProperty(), Mesh::addColumn(), Mesh::addRow(), Util::drawControlsVertices(), hasCenterControl(), and ProjectWriter::writeShapeVertices().
 { return vertices.size(); }
QPointF MShape::getVertex (int i) const inherited
Definition at line 59 of file Shape.h.
References MShape::vertices.
Referenced by MeshTextureGraphicsItem::_buildCacheQuadItem(), MappingGui::_buildShapeProperty(), MeshTextureGraphicsItem::_doDrawOutput(), MapperGLCanvas::_glueVertex(), MeshTextureGraphicsItem::_split(), MappingGui::_updateShapeProperty(), Util::drawControlsVertices(), getCenter(), getHorizontalAxis(), getVerticalAxis(), sanitize(), MappingGui::setValue(), setVertex(), and ProjectWriter::writeShapeVertices().
   {
     return vertices[i];
   }
virtual void MShape::setVertex (int i, qreal x, qreal y) virtual inherited
Definition at line 69 of file Shape.h.
References MShape::setVertex().
   {
     setVertex(i, QPointF(x, y));
   }
void MShape::translate (const QPointF & offset) virtual inherited
Translate all vertices of shape by the vector (x,y).
Definition at line 34 of file Shape.cpp.
References MShape::vertices.
 {
   // We can feel free to translate every vertex without check by default.
   for (QVector<QPointF>::iterator it = vertices.begin(); it != vertices.end(); ++it)
     *it += offset;
 }
void MShape::copyFrom (const MShape & shape) virtual inherited
Definition at line 22 of file Shape.cpp.
References MShape::vertices.
Referenced by MShape::clone().
 {
   // Just copy vertices.
   vertices = shape.vertices;
 }
MShape * MShape::clone () const virtual inherited
Definition at line 28 of file Shape.cpp.
References MShape::_create(), and MShape::copyFrom().
{
   MShape* copyShape = _create();
   copyShape->copyFrom(*this);
   return copyShape;
 }
void MShape::_addVertex (const QPointF & vertex) protected inherited
Definition at line 96 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), Ellipse(), Quad::Quad(), and Triangle::Triangle().
   {
     vertices.push_back(vertex);
   }
void MShape::_rawSetVertex (int i, const QPointF & v) protected inherited
Definition at line 101 of file Shape.h.
Referenced by Mesh::addColumn(), Mesh::addRow(), MShape::setVertex(), Polygon::setVertex(), Mesh::setVertex(), and setVertex().
   {
     vertices[i] = v;
   }
Member Data Documentation
QVector<QPointF> MShape::vertices protected inherited
Definition at line 94 of file Shape.h.
Referenced by Mesh::_reorderVertices(), MShape::copyFrom(), MShape::getVertex(), Mesh::getVertex2d(), Mesh::init(), MShape::nVertices(), Mesh::removeColumn(), Mesh::removeRow(), Mesh::setVertex2d(), Polygon::toPolygon(), and MShape::translate().
The documentation for this class was generated from the following files:
Shape.h
Shape.cpp