MapMap: TextureMapping Class Reference
TextureMapping Class Reference
Object whose paint is an image texture.
#include <Mapping.h>
Public Types
typedef QSharedPointer< Mapping > ptr
Public Member Functions
TextureMapping (Paint::ptr paint, MShape::ptr shape, MShape::ptr inputShape, uid id=NULL_UID)
virtual void build ()
Sets up this Mapping: its Paint and its Shape.
virtual QString getType () const
The type of the mapping (expressed as a string).
virtual bool hasInputShape () const
Returns true iff the mapping possesses an input (source) shape.
virtual MShape::ptr getInputShape () const
Returns the input (source) shape (if this mapping has one) or a null pointer if not.
Paint::ptr getPaint () const
Returns the paint.
MShape::ptr getShape () const
Returns the (output) shape.
uid getId () const
void setLocked (bool locked)
void setSolo (bool solo)
void setVisible (bool visible)
void setRawOpacity (float opacity)
void setDepth (int depth)
void toggleLocked ()
void toggleSolo ()
void toggleVisible ()
bool isLocked () const
bool isSolo () const
bool isVisible () const
float getRawOpacity () const
int getDepth () const
float getOpacity () const
void setPaint (Paint::ptr p)
void setName (const QString &name)
QString getName () const
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Attributes
Paint::ptr _paint
The input Paint instance.
MShape::ptr _shape
The output Shape instance.
Private Attributes
MShape::ptr _inputShape
Detailed Description
Object whose paint is an image texture.
In the case of a texture mapping we require an additional input shape to specify the area on the image where we pick the pixels.
Definition at line 150 of file Mapping.h.
Member Typedef Documentation
typedef QSharedPointer<Mapping> Mapping::ptr inherited
Definition at line 70 of file Mapping.h.
Constructor & Destructor Documentation
TextureMapping::TextureMapping (Paint::ptr paint, MShape::ptr shape, MShape::ptr inputShape, uid id = NULL_UID)
Definition at line 156 of file Mapping.h.
     : Mapping(paint, shape, id),
       _inputShape(inputShape)
   {
     // Only supports shape of the same type (for now).
     Q_ASSERT(shape->getType() == inputShape->getType());
   }
Member Function Documentation
virtual void TextureMapping::build () virtual
Sets up this Mapping: its Paint and its Shape.
Calls the build() method of its Paint and Shape.
Reimplemented from Mapping.
Definition at line 166 of file Mapping.h.
References Mapping::build().
{
     Mapping::build();
     _inputShape->build();
   }
virtual QString TextureMapping::getType () const virtual
The type of the mapping (expressed as a string).
Implements Mapping.
Definition at line 171 of file Mapping.h.
References Mapping::getShape().
{
     return getShape()->getType() + "_texture";
   }
virtual bool TextureMapping::hasInputShape () const virtual
Returns true iff the mapping possesses an input (source) shape.
Reimplemented from Mapping.
Definition at line 176 of file Mapping.h.
 { return true; }
virtual MShape::ptr TextureMapping::getInputShape () const virtual
Returns the input (source) shape (if this mapping has one) or a null pointer if not.
Reimplemented from Mapping.
Definition at line 177 of file Mapping.h.
References _inputShape.
Referenced by ProjectWriter::writeItem().
 { return _inputShape; }
static const UidAllocator& Mapping::getUidAllocator () static inherited
Definition at line 74 of file Mapping.h.
References Mapping::allocator.
Referenced by MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deleteMapping().
 { return allocator; }
Paint::ptr Mapping::getPaint () const inherited
Returns the paint.
Definition at line 89 of file Mapping.h.
References Mapping::_paint.
Referenced by ProjectWriter::writeItem().
 { return _paint; }
MShape::ptr Mapping::getShape () const inherited
Returns the (output) shape.
Definition at line 92 of file Mapping.h.
References Mapping::_shape.
Referenced by ColorMapping::getType(), getType(), and ProjectWriter::writeItem().
 { return _shape; }
uid Mapping::getId () const inherited
Definition at line 100 of file Mapping.h.
References Mapping::_id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
void Mapping::setLocked (bool locked) inherited
Definition at line 102 of file Mapping.h.
 { _isLocked = locked; }
void Mapping::setSolo (bool solo) inherited
Definition at line 103 of file Mapping.h.
 { _isSolo = solo; }
void Mapping::setVisible (bool visible) inherited
Definition at line 104 of file Mapping.h.
 { _isVisible = visible; }
void Mapping::setRawOpacity (float opacity) inherited
Definition at line 105 of file Mapping.h.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
void Mapping::setDepth (int depth) inherited
Definition at line 109 of file Mapping.h.
 { _depth = depth; }
void Mapping::toggleLocked () inherited
Definition at line 111 of file Mapping.h.
References Mapping::_isLocked.
 { _isLocked = !_isLocked; }
void Mapping::toggleSolo () inherited
Definition at line 112 of file Mapping.h.
References Mapping::_isSolo.
 { _isSolo = !_isSolo; }
void Mapping::toggleVisible () inherited
Definition at line 113 of file Mapping.h.
References Mapping::_isVisible.
 { _isVisible = !_isVisible; }
bool Mapping::isLocked () const inherited
Definition at line 115 of file Mapping.h.
References Mapping::_isLocked.
Referenced by ProjectWriter::writeItem().
 { return _isLocked; }
bool Mapping::isSolo () const inherited
Definition at line 116 of file Mapping.h.
References Mapping::_isSolo.
Referenced by ProjectWriter::writeItem().
 { return _isSolo; }
bool Mapping::isVisible () const inherited
Definition at line 117 of file Mapping.h.
References Mapping::_isVisible.
Referenced by ProjectWriter::writeItem().
 { return _isVisible; }
float Mapping::getRawOpacity () const inherited
Definition at line 118 of file Mapping.h.
References Mapping::_opacity.
 { return _opacity; }
int Mapping::getDepth () const inherited
Definition at line 119 of file Mapping.h.
References Mapping::_depth.
 { return _depth; }
float Mapping::getOpacity () const inherited
Definition at line 121 of file Mapping.h.
 { return _opacity * _paint->getOpacity(); }
void Mapping::setPaint (Paint::ptr p) inherited
Definition at line 123 of file Mapping.h.
 { _paint = p; }
void Mapping::setName (const QString & name) inherited
Definition at line 125 of file Mapping.h.
 { _name = name; }
QString Mapping::getName () const inherited
Definition at line 127 of file Mapping.h.
References Mapping::_name.
Referenced by ProjectWriter::writeItem().
 { return _name; }
Member Data Documentation
MShape::ptr TextureMapping::_inputShape private
Definition at line 153 of file Mapping.h.
Referenced by getInputShape().
Paint::ptr Mapping::_paint protected inherited
The input Paint instance.
Definition at line 46 of file Mapping.h.
Referenced by Mapping::getPaint().
MShape::ptr Mapping::_shape protected inherited
The output Shape instance.
Definition at line 49 of file Mapping.h.
Referenced by Mapping::getShape().
The documentation for this class was generated from the following file:
Mapping.h