MapMap: Image Class Reference
Image Class Reference
Paint that is a Texture loaded from an image file.
#include <Paint.h>
Public Types
typedef QSharedPointer< Paint > ptr
Public Member Functions
Image (const QString uri_, uid id=NULL_UID)
virtual ~Image ()
virtual void build ()
const QString getUri () const
bool setUri (const QString &uri)
virtual QString getType () const
virtual int getWidth () const
virtual int getHeight () const
virtual const uchar * getBits ()
Returns image bits data. Next call to bitsHaveChanged() will be false.
virtual bool bitsHaveChanged () const
Returns true iff bits have changed since last call to getBits().
GLuint getTextureId () const
virtual void setPosition (GLfloat xPos, GLfloat yPos)
virtual GLfloat getX () const
virtual GLfloat getY () const
virtual QRectF getRect () const
virtual void update ()
This method should be called at each call of draw().
virtual void play ()
Starts playback.
virtual void pause ()
Pauses playback.
virtual void rewind ()
Rewinds.
virtual void lockMutex ()
Locks mutex (default = no effect).
virtual void unlockMutex ()
Unlocks mutex (default = no effect).
void setName (const QString &name)
QString getName () const
uid getId () const
float getOpacity () const
void setOpacity (float opacity)
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Attributes
QString uri
QImage image
GLuint textureId
GLfloat x
GLfloat y
bool bitsChanged
Detailed Description
Paint that is a Texture loaded from an image file.
Definition at line 167 of file Paint.h.
Member Typedef Documentation
typedef QSharedPointer<Paint> Paint::ptr inherited
Definition at line 57 of file Paint.h.
Constructor & Destructor Documentation
Image::Image (const QString uri_, uid id = NULL_UID)
Definition at line 174 of file Paint.h.
References setUri().
                                              :
     Texture(id)
   {
     setUri(uri_);
   }
virtual Image::~Image () virtual
Definition at line 180 of file Paint.h.
 {}
Member Function Documentation
virtual void Image::build () virtual
Reimplemented from Paint.
Definition at line 182 of file Paint.h.
References Texture::bitsChanged.
Referenced by setUri().
{
     image = QGLWidget::convertToGLFormat(QImage(uri)).mirrored(true, false).transformed(QTransform().rotate(180));
     bitsChanged = true;
   }
const QString Image::getUri () const
Definition at line 187 of file Paint.h.
References uri.
Referenced by ProjectWriter::writeItem().
 { return uri; }
bool Image::setUri (const QString & uri)
Definition at line 46 of file Paint.cpp.
References build(), and uri.
Referenced by Image(), and MainWindow::setTextureUri().
 {
   this->uri = uri;
   build();
   return true;
 }
virtual QString Image::getType () const virtual
Implements Paint.
Definition at line 190 of file Paint.h.
 { return "image"; }
virtual int Image::getWidth () const virtual
Implements Texture.
Definition at line 192 of file Paint.h.
 { return image.width(); }
virtual int Image::getHeight () const virtual
Implements Texture.
Definition at line 193 of file Paint.h.
 { return image.height(); }
virtual const uchar* Image::getBits () virtual
Returns image bits data. Next call to bitsHaveChanged() will be false.
Implements Texture.
Definition at line 195 of file Paint.h.
References Texture::bitsChanged.
{
     bitsChanged = false;
     return image.bits();
   }
virtual bool Image::bitsHaveChanged () const virtual
Returns true iff bits have changed since last call to getBits().
Implements Texture.
Definition at line 200 of file Paint.h.
References Texture::bitsChanged.
 { return bitsChanged; }
GLuint Texture::getTextureId () const inherited
Definition at line 144 of file Paint.h.
References Texture::textureId.
 { return textureId; }
virtual void Texture::setPosition (GLfloat xPos, GLfloat yPos) virtual inherited
Definition at line 154 of file Paint.h.
Referenced by MainWindow::createMediaPaint().
{
     x = xPos;
     y = yPos;
   }
virtual GLfloat Texture::getX () const virtual inherited
Definition at line 158 of file Paint.h.
References Texture::x.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), Texture::getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return x; }
virtual GLfloat Texture::getY () const virtual inherited
Definition at line 159 of file Paint.h.
References Texture::y.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), Texture::getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return y; }
virtual QRectF Texture::getRect () const virtual inherited
Definition at line 161 of file Paint.h.
References Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
 { return QRectF(getX(), getY(), getWidth(), getHeight()); }
static const UidAllocator& Paint::getUidAllocator () static inherited
Definition at line 61 of file Paint.h.
References Paint::allocator.
Referenced by MainWindow::createColorPaint(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMediaPaint(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deletePaint().
 { return allocator; }
virtual void Paint::update () virtual inherited
This method should be called at each call of draw().
Reimplemented in Media.
Definition at line 66 of file Paint.h.
 {}
virtual void Paint::play () virtual inherited
Starts playback.
Reimplemented in Media.
Definition at line 69 of file Paint.h.
 {}
virtual void Paint::pause () virtual inherited
Pauses playback.
Reimplemented in Media.
Definition at line 72 of file Paint.h.
 {}
virtual void Paint::rewind () virtual inherited
Rewinds.
Reimplemented in Media.
Definition at line 75 of file Paint.h.
 {}
virtual void Paint::lockMutex () virtual inherited
Locks mutex (default = no effect).
Reimplemented in Media.
Definition at line 78 of file Paint.h.
 {}
virtual void Paint::unlockMutex () virtual inherited
Unlocks mutex (default = no effect).
Reimplemented in Media.
Definition at line 81 of file Paint.h.
 {}
void Paint::setName (const QString & name) inherited
Definition at line 83 of file Paint.h.
References Paint::_name.
 { _name = name; }
QString Paint::getName () const inherited
Definition at line 84 of file Paint.h.
References Paint::_name.
 { return _name; }
uid Paint::getId () const inherited
Definition at line 85 of file Paint.h.
References Paint::_id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
float Paint::getOpacity () const inherited
Definition at line 87 of file Paint.h.
References Paint::_opacity.
 { return _opacity; }
void Paint::setOpacity (float opacity) inherited
Definition at line 88 of file Paint.h.
References Paint::_opacity.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
Member Data Documentation
QString Image::uri protected
Definition at line 170 of file Paint.h.
Referenced by getUri(), and setUri().
QImage Image::image protected
Definition at line 171 of file Paint.h.
GLuint Texture::textureId protected inherited
Definition at line 123 of file Paint.h.
Referenced by Texture::getTextureId().
GLfloat Texture::x protected inherited
Definition at line 124 of file Paint.h.
Referenced by Texture::getX().
GLfloat Texture::y protected inherited
Definition at line 125 of file Paint.h.
Referenced by Texture::getY().
bool Texture::bitsChanged mutable protected inherited
Definition at line 126 of file Paint.h.
Referenced by bitsHaveChanged(), build(), and getBits().
The documentation for this class was generated from the following files:
Paint.h
Paint.cpp