MapMap: MediaImpl Class Reference
MediaImpl Class Reference
Private declaration of the video player.
#include <MediaImpl.h>
Classes
struct GstPadHandlerData
Public Member Functions
MediaImpl (const QString uri, bool live)
Constructor.
~MediaImpl ()
void build ()
Sets up the player.
int getWidth () const
Returns the width of the video image.
int getHeight () const
Returns the height of the video image.
QString getUri () const
Returns the path to the media file being played.
bool getAttached ()
When using the shared memory source, returns whether or not we are attached to a shared memory socket.
const uchar * getBits ()
Returns the raw image of the last video frame.
bool bitsHaveChanged () const
Returns true iff bits have changed since last call to getBits().
bool isReady () const
Checks if the pipeline is ready.
bool videoIsConnected () const
void update ()
Performs regular updates (checks if movie is ready and checks messages).
bool loadMovie (QString filename)
Loads a new movie file.
bool setPlayState (bool play)
void setAttached (bool attach)
Tells the MediaImpl that we are actually reading from a shmsrc.
void setRate (double rate=1.0)
double getRate () const
void setVolume (double rate=0.0)
double getVolume () const
void resetMovie ()
void lockMutex ()
Locks mutex (default = no effect).
void unlockMutex ()
Unlocks mutex (default = no effect).
Static Public Member Functions
static bool hasVideoSupport ()
Returns whether or not GStreamer video support is ok.
static GstFlowReturn gstNewSampleCallback (GstElement *, MediaImpl *p)
static void gstPadAddedCallback (GstElement *src, GstPad *newPad, MediaImpl::GstPadHandlerData *data)
FIXME: remove GOTO.
Protected Member Functions
void unloadMovie ()
void freeResources ()
Private Member Functions
bool _eos () const
Checks if we reached the end of the video file.
void _checkMessages ()
void _setMovieReady (bool ready)
bool _isMovieReady () const
bool getPlayState () const
void _setFinished (bool finished)
void _updateRate ()
void _freeCurrentSample ()
Private Attributes
GstBus * _bus
GstElement * _pipeline
GstElement * _uridecodebin0
GstElement * _shmsrc0
GstElement * _gdpdepay0
GstElement * _queue0
GstElement * _videoconvert0
GstElement * _appsink0
GstElement * _audioqueue0
GstElement * _audioconvert0
GstElement * _audioresample0
GstElement * _audiovolume0
GstElement * _audiosink0
GstSample * _currentFrameSample
Temporary contains the image data of the last frame.
GstBuffer * _currentFrameBuffer
GstMapInfo _mapInfo
bool _bitsChanged
GSource * _pollSource
shmsrc socket poller.
GstPadHandlerData _padHandlerData
int _width
int _height
uchar * _data
Raw image data of the last video frame.
bool _seekEnabled
Is seek enabled on the current pipeline?
double _rate
Playback rate (negative ==> reverse).
double _volume
Audio playback volume (0.0 ==> 1.0).
bool _isSharedMemorySource
Whether or not we are reading video from a shmsrc.
bool _attached
Whether or not we are attached to a shmsrc, if using a shmsrc.
bool _terminate
bool _movieReady
Is the movie (or rather pipeline) ready to play.
bool _playState
Is the movie playing (as opposed to paused).
QMutex _mutex
Main mutex.
QMutexLocker * _mutexLocker
Main mutex locker (for the lockMutex() / unlockMutex() methods).
QString _uri
Path of the movie file being played.
Static Private Attributes
static const int MAX_SAMPLES_IN_BUFFER_QUEUES = 30
Detailed Description
Private declaration of the video player.
This is to prevent the GStreamer header to be included in the whole project. (it just needs to be included in this file).
Definition at line 50 of file MediaImpl.h.
Constructor & Destructor Documentation
MediaImpl::MediaImpl (const QString uri, bool live)
Constructor.
This media player works for both video files and shared memory sockets. If live is true, it's a shared memory socket.
Definition at line 209 of file MediaImpl.cpp.
References _mutex, _mutexLocker, _pollSource, and loadMovie().
                                                  :
 _bus(NULL),
 _pipeline(NULL),
 _uridecodebin0(NULL),
 _queue0(NULL),
 _videoconvert0(NULL),
 _appsink0(NULL),
 _audioqueue0(NULL),
 _audioconvert0(NULL),
 _audioresample0(NULL),
 _audiovolume0(NULL),
 _audiosink0(NULL),
 _currentFrameSample(NULL),
 _currentFrameBuffer(NULL),
 _bitsChanged(false),
 _width(640), // unused
 _height(480), // unused
 _data(NULL),
 _seekEnabled(false),
 _rate(1.0),
 _isSharedMemorySource(live),
 _attached(false),
 _movieReady(false),
 _playState(false),
 _uri(uri)
 {
   _pollSource = NULL;
   if (uri != "")
   {
     loadMovie(uri);
   }
   _mutexLocker = new QMutexLocker(&_mutex);
 }
MediaImpl::~MediaImpl ()
Definition at line 125 of file MediaImpl.cpp.
References _mutexLocker, and freeResources().
 {
   // Free all resources.
   freeResources();
   // Free mutex locker object.
   delete _mutexLocker;
 }
Member Function Documentation
bool MediaImpl::hasVideoSupport () static
Returns whether or not GStreamer video support is ok.
Definition at line 30 of file MediaImpl.cpp.
Referenced by Media::hasVideoSupport().
 {
   static bool did_print_gst_version = false;
   if (! did_print_gst_version)
   {
     qDebug() << "Using GStreamer version " <<
       GST_VERSION_MAJOR << "." <<
       GST_VERSION_MINOR << "." <<
       GST_VERSION_MICRO;
     did_print_gst_version = true;
   }
   // TODO: actually check if we have it
   return true;
 }
void MediaImpl::build ()
Sets up the player.
Basically calls loadMovie().
Definition at line 116 of file MediaImpl.cpp.
References _uri, and loadMovie().
Referenced by Media::build().
 {
   qDebug() << "Building video impl";
   if (!loadMovie(_uri))
   {
     qDebug() << "Cannot load movie " << _uri << ".";
   }
 }
int MediaImpl::getWidth () const
Returns the width of the video image.
Definition at line 45 of file MediaImpl.cpp.
References _padHandlerData, videoIsConnected(), and MediaImpl::GstPadHandlerData::width.
Referenced by Media::getWidth().
 {
   Q_ASSERT(videoIsConnected());
   return _padHandlerData.width;
 }
int MediaImpl::getHeight () const
Returns the height of the video image.
Definition at line 51 of file MediaImpl.cpp.
References _padHandlerData, MediaImpl::GstPadHandlerData::height, and videoIsConnected().
Referenced by Media::getHeight().
 {
   Q_ASSERT(videoIsConnected());
   return _padHandlerData.height;
 }
QString MediaImpl::getUri () const
Returns the path to the media file being played.
Definition at line 69 of file MediaImpl.cpp.
References _uri.
Referenced by gstPollShmsrc().
 {
   return _uri;
 }
bool MediaImpl::getAttached ()
When using the shared memory source, returns whether or not we are attached to a shared memory socket.
Definition at line 74 of file MediaImpl.cpp.
References _attached.
Referenced by gstPollShmsrc().
 {
   return _attached;
 }
const uchar * MediaImpl::getBits ()
Returns the raw image of the last video frame.
It is currently unused!
Definition at line 57 of file MediaImpl.cpp.
References _bitsChanged, _currentFrameSample, and _data.
Referenced by Media::getBits().
 {
   // Reset bits changed.
   _bitsChanged = false;
   // Return data.
   if (_currentFrameSample == NULL)
     return NULL;
   else
     return _data;
 }
bool MediaImpl::bitsHaveChanged () const
Returns true iff bits have changed since last call to getBits().
Definition at line 101 of file MediaImpl.h.
References _bitsChanged.
Referenced by Media::bitsHaveChanged().
 { return _bitsChanged; }
bool MediaImpl::isReady () const
Checks if the pipeline is ready.
Returns whether or not the elements in the pipeline are connected, and if we are using shmsrc, if the shared memory socket is being read.
Definition at line 109 of file MediaImpl.h.
References _movieReady, _padHandlerData, and MediaImpl::GstPadHandlerData::videoIsConnected.
 { return _movieReady && _padHandlerData.videoIsConnected; }
bool MediaImpl::videoIsConnected () const
Definition at line 111 of file MediaImpl.h.
References _padHandlerData, and MediaImpl::GstPadHandlerData::videoIsConnected.
Referenced by getHeight(), Media::getHeight(), getWidth(), and Media::getWidth().
 { return _padHandlerData.videoIsConnected; }
void MediaImpl::update ()
Performs regular updates (checks if movie is ready and checks messages).
Definition at line 568 of file MediaImpl.cpp.
References _checkMessages(), _eos(), _setFinished(), _terminate, and resetMovie().
Referenced by Media::update().
 {
   // Check for end-of-stream or terminate.
   if (_eos() || _terminate)
   {
     _setFinished(true);
     resetMovie();
   }
   else
   {
     _setFinished(false);
   }
 //  // Check if movie is ready and connected.
 //  if (!isReady())
 //  {
 //    _bitsChanged = false;
 //  }
 //
   // Check gstreamer messages on bus.
   _checkMessages();
 }
bool MediaImpl::loadMovie (QString filename)
Loads a new movie file.
Creates a new GStreamer pipeline, opens a movie or a shmsrc socket.
Definition at line 346 of file MediaImpl.cpp.
References _appsink0, _audioconvert0, _audioqueue0, _audioresample0, _audiosink0, _audiovolume0, _bus, _gdpdepay0, _isSharedMemorySource, _padHandlerData, _pipeline, _pollSource, _queue0, _shmsrc0, _uri, _uridecodebin0, _videoconvert0, MediaImpl::GstPadHandlerData::audioToConnect, freeResources(), gstNewSampleCallback(), gstPadAddedCallback(), gstPollShmsrc(), setPlayState(), unloadMovie(), MediaImpl::GstPadHandlerData::videoIsConnected, MediaImpl::GstPadHandlerData::videoSink, and MediaImpl::GstPadHandlerData::videoToConnect.
Referenced by build(), MediaImpl(), resetMovie(), and Media::setUri().
 {
   gchar* filetestpath = (gchar*) filename.toUtf8().constData();
   if (FALSE == g_file_test(filetestpath, G_FILE_TEST_EXISTS))
   {
       std::cout << "File " << filetestpath << " does not exist" << std::endl;
       return false;
   }
   _uri = filename;
   qDebug() << "Opening movie: " << filename << ".";
   // Free previously allocated structures
   unloadMovie();
   // Initialize GStreamer.
   GstElement *capsfilter0 = NULL;
   GstElement *videoscale0 = NULL;
   // Create the elements.
   if (_isSharedMemorySource)
   {
     _shmsrc0 = gst_element_factory_make ("shmsrc", "shmsrc0");
     _gdpdepay0 = gst_element_factory_make ("gdpdepay", "gdpdepay0");
     _pollSource = g_timeout_source_new (500);
     g_source_set_callback (_pollSource,
         gstPollShmsrc,
         this,
         NULL);
     g_source_attach (_pollSource, g_main_context_default());
     g_source_unref (_pollSource);
   }
   else {
     _uridecodebin0 = gst_element_factory_make ("uridecodebin", "uridecodebin0");
   }
   _queue0 = gst_element_factory_make ("queue", "queue0");
   _videoconvert0 = gst_element_factory_make ("videoconvert", "videoconvert0");
   videoscale0 = gst_element_factory_make ("videoscale", "videoscale0");
   capsfilter0 = gst_element_factory_make ("capsfilter", "capsfilter0");
   _appsink0 = gst_element_factory_make ("appsink", "appsink0");
   // Prepare handler data.
   _padHandlerData.videoToConnect = _queue0;
   _padHandlerData.videoSink = _appsink0;
   _padHandlerData.videoIsConnected = false;
   _audioqueue0 = gst_element_factory_make ("queue", "audioqueue0");
   _audioconvert0 = gst_element_factory_make ("audioconvert", "audioconvert0");
   _audioresample0 = gst_element_factory_make ("audioresample", "audioresample0");
   _audiovolume0 = gst_element_factory_make ("volume", "audiovolume0");
   _audiosink0 = gst_element_factory_make ("autoaudiosink", "audiosink0");
   _padHandlerData.audioToConnect = _audioqueue0;
   // Create the empty pipeline.
   _pipeline = gst_pipeline_new ( "video-source-pipeline" );
   if (!_pipeline ||
       !_queue0 || !_videoconvert0 || ! videoscale0 || ! capsfilter0 ||
       !_appsink0 || !_audioqueue0 || !_audioconvert0 || !_audioresample0 ||
       !_audiovolume0 || !_audiosink0)
   {
     g_printerr ("Not all elements could be created.\n");
     if (! _pipeline) g_printerr("_pipeline");
     if (! _queue0) g_printerr("_queue0");
     if (! _videoconvert0) g_printerr("_videoconvert0");
     if (! videoscale0) g_printerr("videoscale0");
     if (! capsfilter0) g_printerr("capsfilter0");
     if (! _appsink0) g_printerr("_appsink0");
     if (! _audioqueue0) g_printerr("_audioqueue0");
     if (! _audioconvert0) g_printerr("_audioconvert0");
     if (! _audioresample0) g_printerr("_audioresample0");
     if (! _audiovolume0) g_printerr("_audiovolume0");
     if (! _audiosink0) g_printerr("_audiosink0");
     unloadMovie();
     return -1;
   }
   if (_isSharedMemorySource)
   {
     if (! _shmsrc0 || ! _gdpdepay0)
     {
       g_printerr ("Not all elements could be created.\n");
       if (! _shmsrc0) g_printerr("_shmsrc0");
       if (! _gdpdepay0) g_printerr("_gdpdepay0");
       unloadMovie();
       return -1;
     }
   }
   else
   {
     if (! _uridecodebin0)
     {
       g_printerr ("Not all elements could be created.\n");
       if (! _uridecodebin0) g_printerr("_uridecodebin0");
       unloadMovie();
       return -1;
     }
   }
   // Build the pipeline. Note that we are NOT linking the source at this
   // point. We will do it later.
   gst_bin_add_many (GST_BIN (_pipeline),
     _isSharedMemorySource ? _shmsrc0 : _uridecodebin0, _queue0,
     _videoconvert0, videoscale0, capsfilter0, _appsink0,
 //    _audioqueue0, _audioconvert0, _audioresample0, _audiovolume0, _audiosink0,
     NULL);
   // special case for shmsrc
   if (_isSharedMemorySource)
   {
     gst_bin_add (GST_BIN(_pipeline), _gdpdepay0);
     if (! gst_element_link_many (_shmsrc0, _gdpdepay0, _queue0, NULL))
     {
       g_printerr ("Could not link shmsrc, deserializer and video queue.\n");
     }
   }
   // link uridecodebin -> queue will be performed by callback
   if (! gst_element_link_many (_queue0, _videoconvert0, capsfilter0, videoscale0, _appsink0, NULL))
   {
     g_printerr ("Could not link video queue, colorspace converter, caps filter, scaler and app sink.\n");
     unloadMovie();
     return false;
   }
 //  if (! gst_element_link_many (_audioqueue0, _audioconvert0, _audioresample0,
 //        _audiovolume0, _audiosink0, NULL))
 //  {
 //    g_printerr ("Could not link audio queue, converter, resampler and audio sink.\n");
 //    unloadMovie();
 //    return false;
 //  }
   // Process URI.
   QByteArray ba = filename.toLocal8Bit();
   gchar *filename_tmp = g_strdup((gchar*) filename.toUtf8().constData());
   gchar* uri = NULL; //  (gchar*) filename.toUtf8().constData();
   if (! _isSharedMemorySource && ! gst_uri_is_valid(uri))
   {
     // Try to convert filename to URI.
     GError* error = NULL;
     qDebug() << "Calling gst_filename_to_uri : " << uri;
     uri = gst_filename_to_uri(filename_tmp, &error);
     if (error)
     {
       qDebug() << "Filename to URI error: " << error->message;
       g_error_free(error);
       gst_object_unref (uri);
       freeResources();
       return false;
     }
   }
   g_free(filename_tmp);
   if (_isSharedMemorySource)
   {
     uri =  (gchar*) ba.data();
   }
   // Set URI to be played.
   qDebug() << "URI for uridecodebin: " << uri;
   // FIXME: sometimes it's just the path to the directory that is given, not the file itself.
   // Connect to the pad-added signal
   if (! _isSharedMemorySource)
   {
     g_signal_connect (_uridecodebin0, "pad-added", G_CALLBACK (MediaImpl::gstPadAddedCallback), &_padHandlerData);
     g_object_set (_uridecodebin0, "uri", uri, NULL);
   }
   else
   {
     //qDebug() << "LIVE mode" << uri;
     g_object_set (_shmsrc0, "socket-path", uri, NULL);
     g_object_set (_shmsrc0, "is-live", TRUE, NULL);
     _padHandlerData.videoIsConnected = true;
   }
   g_free(uri);
   // Configure audio appsink.
   // TODO: change from mono to stereo
 //  gchar* audioCapsText = g_strdup_printf ("audio/x-raw-float,channels=1,rate=%d,signed=(boolean)true,width=%d,depth=%d,endianness=BYTE_ORDER",
 //                                          Engine::signalInfo().sampleRate(), (int)(sizeof(Signal_T)*8), (int)(sizeof(Signal_T)*8) );
 //  GstCaps* audioCaps = gst_caps_from_string (audioCapsText);
 //  g_object_set (_audioSink, "emit-signals", TRUE,
 //                            "caps", audioCaps,
 //                            NULL);
 //  g_signal_connect (_audioSink, "new-buffer", G_CALLBACK (VideoImpl::gstNewAudioBufferCallback), &_newAudioBufferHandlerData);
 //  gst_caps_unref (audioCaps);
 //  g_free (audioCapsText);
   // Configure video appsink.
   GstCaps *videoCaps = gst_caps_from_string ("video/x-raw,format=RGBA");
   g_object_set (capsfilter0, "caps", videoCaps, NULL);
   g_object_set (_appsink0, "emit-signals", TRUE,
                             "max-buffers", 1,     // only one buffer (the last) is maintained in the queue
                             "drop", TRUE,         // ... other buffers are dropped
                             "sync", TRUE,
                             NULL);
   g_signal_connect (_appsink0, "new-sample", G_CALLBACK (MediaImpl::gstNewSampleCallback), this);
   gst_caps_unref (videoCaps);
   g_object_set (_audiovolume0, "mute", false, NULL);
   g_object_set (_audiovolume0, "volume", 0.0, NULL);
   // Listen to the bus.
   _bus = gst_element_get_bus (_pipeline);
   // Start playing.
   if (! _isSharedMemorySource && ! setPlayState(true))
   {
     return false;
   }
   return true;
 }
bool MediaImpl::setPlayState (bool play)
Definition at line 591 of file MediaImpl.cpp.
References _pipeline, _playState, and unloadMovie().
Referenced by gstPollShmsrc(), loadMovie(), Media::pause(), Media::play(), and unloadMovie().
 {
   if (_pipeline == NULL)
   {
     return false;
   }
   GstStateChangeReturn ret = gst_element_set_state (_pipeline, (play ? GST_STATE_PLAYING : GST_STATE_PAUSED));
   if (ret == GST_STATE_CHANGE_FAILURE)
   {
     qDebug() << "Unable to set the pipeline to the playing state.";
     unloadMovie();
     return false;
   }
   else
   {
     _playState = play;
     return true;
   }
 }
void MediaImpl::setAttached (bool attach)
Tells the MediaImpl that we are actually reading from a shmsrc.
Called from the GStreamer callback of the shmsrc.
Definition at line 79 of file MediaImpl.cpp.
References _attached.
Referenced by gstPollShmsrc().
 {
   _attached = attach;
 }
void MediaImpl::setRate (double rate = 1.0)
Definition at line 85 of file MediaImpl.cpp.
References _rate, _seekEnabled, and _updateRate().
Referenced by Media::setRate().
 {
   if (rate == 0)
   {
     qDebug() << "Cannot set rate to zero, ignoring rate " << rate << endl;
     return;
   }
   // Only update rate if needed.
   if (_rate != rate)
   {
     _rate = rate;
     // Send seek events to activate rate.
     if (_seekEnabled)
       _updateRate();
   }
 }
double MediaImpl::getRate () const
Definition at line 136 of file MediaImpl.h.
References _rate.
Referenced by Media::getRate().
 { return _rate; }
void MediaImpl::setVolume (double rate = 0.0)
Definition at line 104 of file MediaImpl.cpp.
References _audiovolume0, and _volume.
Referenced by Media::setVolume().
 {
   // Only update volume if needed.
   if (_volume != volume)
   {
     _volume = volume;
     // Set volume element property.
     g_object_set (_audiovolume0, "volume", _volume, NULL);
   }
 }
double MediaImpl::getVolume () const
Definition at line 139 of file MediaImpl.h.
References _volume.
Referenced by Media::getVolume().
 { return _volume; }
void MediaImpl::resetMovie ()
Definition at line 298 of file MediaImpl.cpp.
References _appsink0, _rate, _seekEnabled, _setMovieReady(), _uri, and loadMovie().
Referenced by _checkMessages(), Media::rewind(), and update().
 {
   // XXX: There used to be an issue that when we reached EOS (_eos() == true) we could not seek anymore.
   if (_seekEnabled)
   {
     qDebug() << "Seeking at position 0.";
     GstEvent* seek_event;
     if (_rate > 0) {
       seek_event = gst_event_new_seek (_rate, GST_FORMAT_TIME, GstSeekFlags( GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_ACCURATE ),
           GST_SEEK_TYPE_SET, 0, GST_SEEK_TYPE_NONE, 0);
     } else {
       seek_event = gst_event_new_seek (_rate, GST_FORMAT_TIME, GstSeekFlags( GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_ACCURATE ),
           GST_SEEK_TYPE_SET, 0, GST_SEEK_TYPE_END, 0);
     }
     /* Send the event */
     gst_element_send_event (_appsink0, seek_event);
 //    gst_element_seek_simple (_pipeline, GST_FORMAT_TIME,
 //                             (GstSeekFlags) (GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_KEY_UNIT), 0);
 //    this->_currentFrameSample = NULL;
     _setMovieReady(true);
   }
   else
   {
     // Just reload movie.
     qDebug() << "Reloading the movie" << _seekEnabled;
     loadMovie(_uri);
   }
 }
void MediaImpl::unloadMovie () protected
Definition at line 243 of file MediaImpl.cpp.
References _seekEnabled, _setMovieReady(), _terminate, freeResources(), and setPlayState().
Referenced by loadMovie(), and setPlayState().
 {
   // Reset variables.
   _terminate = false;
   _seekEnabled = false;
   // Un-ready.
   _setMovieReady(false);
   setPlayState(false);
   // Free allocated resources.
   freeResources();
 }
void MediaImpl::freeResources () protected
Definition at line 257 of file MediaImpl.cpp.
References _appsink0, _bitsChanged, _bus, _freeCurrentSample(), _padHandlerData, _pipeline, _pollSource, _queue0, _uridecodebin0, and _videoconvert0.
Referenced by loadMovie(), unloadMovie(), and ~MediaImpl().
 {
   // Free resources.
   if (_bus)
   {
     gst_object_unref (_bus);
     _bus = NULL;
   }
   if (_pipeline)
   {
     gst_element_set_state (_pipeline, GST_STATE_NULL);
     gst_object_unref (_pipeline);
     _pipeline = NULL;
   }
   // Reset pipeline elements.
   _uridecodebin0 = NULL;
   _queue0 = NULL;
   _videoconvert0 = NULL;
   _appsink0 = NULL;
   // Reset pad handler.
   _padHandlerData = GstPadHandlerData();
   // Unref the shmsrc poller.
   if (_pollSource)
   {
      g_source_unref(_pollSource);
      _pollSource = NULL;
   }
   qDebug() << "Freeing remaining samples/buffers" << endl;
   // Frees current sample and buffer.
   _freeCurrentSample();
   // Resets bits changed.
   _bitsChanged = false;
 }
bool MediaImpl::_eos () const private
Checks if we reached the end of the video file.
Returns false if the pipeline is not ready yet.
Definition at line 134 of file MediaImpl.cpp.
References _appsink0, _movieReady, _pipeline, and _rate.
Referenced by update().
 {
   if (_movieReady)
   {
     Q_ASSERT( _appsink0 );
     if (_rate > 0)
     {
       gboolean videoEos;
       g_object_get (G_OBJECT (_appsink0), "eos", &videoEos, NULL);
       return (bool) (videoEos);
     }
     else
     {
       /* Obtain the current position, needed for the seek event */
       gint64 position;
       if (!gst_element_query_position (_pipeline, GST_FORMAT_TIME, &position)) {
         g_printerr ("Unable to retrieve current position.\n");
         return false;
       }
       return (position == 0);
     }
   }
   else
     return false;
 }
void MediaImpl::_checkMessages () private
Definition at line 632 of file MediaImpl.cpp.
References _attached, _bus, _isMovieReady(), _isSharedMemorySource, _pipeline, _seekEnabled, _setMovieReady(), _terminate, _uri, and resetMovie().
Referenced by update().
 {
   if (_bus != NULL)
   {
     // Get message.
     GstMessage *msg = gst_bus_timed_pop_filtered(
                         _bus, 0,
                         (GstMessageType) (GST_MESSAGE_STATE_CHANGED | GST_MESSAGE_ERROR | GST_MESSAGE_EOS | GST_MESSAGE_ASYNC_DONE));
     if (msg != NULL)
     {
       GError *err;
       gchar *debug_info;
       switch (GST_MESSAGE_TYPE (msg))
       {
       // Error ////////////////////////////////////////////////
       case GST_MESSAGE_ERROR:
         gst_message_parse_error(msg, &err, &debug_info);
         g_printerr("Error received from element %s: %s\n",
             GST_OBJECT_NAME (msg->src), err->message);
         g_printerr("Debugging information: %s\n",
             debug_info ? debug_info : "none");
         g_clear_error(&err);
         g_free(debug_info);
         if (!_isSharedMemorySource)
         {
           _terminate = true;
         }
         else
         {
           _attached = false;
           gst_element_set_state (_pipeline, GST_STATE_PAUSED);
           gst_element_set_state (_pipeline, GST_STATE_NULL);
           gst_element_set_state (_pipeline, GST_STATE_READY);
         }
 //        _finish();
         break;
       // End-of-stream ////////////////////////////////////////
       case GST_MESSAGE_EOS:
         // Automatically loop back.
         g_print("End-Of-Stream reached.\n");
         resetMovie();
 //        _terminate = true;
 //        _finish();
         break;
       // Pipeline has prerolled/ready to play ///////////////
       case GST_MESSAGE_ASYNC_DONE:
         if (!_isMovieReady())
         {
           // Check if seeking is allowed.
           gint64 start, end;
           GstQuery *query = gst_query_new_seeking (GST_FORMAT_TIME);
           if (gst_element_query (_pipeline, query))
           {
             gst_query_parse_seeking (query, NULL, (gboolean*)&_seekEnabled, &start, &end);
             if (_seekEnabled)
             {
               g_print ("Seeking is ENABLED from %" GST_TIME_FORMAT " to %" GST_TIME_FORMAT "\n",
                        GST_TIME_ARGS (start), GST_TIME_ARGS (end));
             }
             else
             {
               g_print ("Seeking is DISABLED for this stream.\n");
             }
           }
           else
           {
             g_printerr ("Seeking query failed.");
           }
           gst_query_unref (query);
           // Movie is ready!
           _setMovieReady(true);
         }
         break;
       case GST_MESSAGE_STATE_CHANGED:
         // We are only interested in state-changed messages from the pipeline.
         if (GST_MESSAGE_SRC (msg) == GST_OBJECT (_pipeline))
         {
           GstState oldState, newState, pendingState;
           gst_message_parse_state_changed(msg, &oldState, &newState,
               &pendingState);
           g_print("Pipeline state for movie %s changed from %s to %s:\n",
               _uri.toUtf8().constData(),
               gst_element_state_get_name(oldState),
               gst_element_state_get_name(newState));
         }
         break;
       default:
         // We should not reach here.
         g_printerr("Unexpected message received.\n");
         break;
       }
       gst_message_unref(msg);
     }
   }
 }
void MediaImpl::_setMovieReady (bool ready) private
Definition at line 739 of file MediaImpl.cpp.
References _movieReady.
Referenced by _checkMessages(), resetMovie(), and unloadMovie().
 {
   _movieReady = ready;
 }
bool MediaImpl::_isMovieReady () const private
Definition at line 161 of file MediaImpl.h.
References _movieReady.
Referenced by _checkMessages(), and _updateRate().
 { return _movieReady; }
bool MediaImpl::getPlayState () const private
Definition at line 162 of file MediaImpl.h.
References _playState.
 { return _playState; }
void MediaImpl::_setFinished (bool finished) private
Definition at line 744 of file MediaImpl.cpp.
Referenced by update().
 {
   Q_UNUSED(finished);
   //  qDebug() << "Clip " << (finished ? "finished" : "not finished");
 }
void MediaImpl::_updateRate () private
Definition at line 750 of file MediaImpl.cpp.
References _appsink0, _isMovieReady(), _pipeline, _rate, and _seekEnabled.
Referenced by setRate().
 {
   if (_pipeline == NULL)
   {
     qDebug() << "Cannot set rate: no pipeline!" << endl;
     return;
   }
   if (!_seekEnabled)
   {
     qDebug() << "Cannot set rate: seek not working" << endl;
     return;
   }
   if (!_isMovieReady())
   {
     qDebug() << "Movie is not yet ready to play, cannot seek yet." << endl;
   }
   gint64 position;
   GstEvent *seekEvent;
   /* Obtain the current position, needed for the seek event */
   if (!gst_element_query_position (_pipeline, GST_FORMAT_TIME, &position)) {
     g_printerr ("Unable to retrieve current position.\n");
     return;
   }
   /* Create the seek event */
   if (_rate > 0) {
     seekEvent = gst_event_new_seek (_rate, GST_FORMAT_TIME, GstSeekFlags( GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_ACCURATE ),
         GST_SEEK_TYPE_SET, position, GST_SEEK_TYPE_NONE, 0);
   } else {
     seekEvent = gst_event_new_seek (_rate, GST_FORMAT_TIME, GstSeekFlags( GST_SEEK_FLAG_FLUSH | GST_SEEK_FLAG_ACCURATE ),
         GST_SEEK_TYPE_SET, 0, GST_SEEK_TYPE_SET, position);
   }
   if (_appsink0 == NULL) {
     /* If we have not done so, obtain the sink through which we will send the seek events */
     g_object_get (_pipeline, "video-sink", &_appsink0, NULL);
   }
   /* Send the event */
   gst_element_send_event (_appsink0, seekEvent);
   g_print ("Current rate: %g\n", _rate);
 }
void MediaImpl::_freeCurrentSample () private
Definition at line 798 of file MediaImpl.cpp.
References _currentFrameBuffer, _currentFrameSample, _data, and _mapInfo.
Referenced by freeResources(), and gstNewSampleCallback().
{
   if (_currentFrameBuffer != NULL)
   {
     gst_buffer_unmap(_currentFrameBuffer, &_mapInfo);
   }
   if (_currentFrameSample != NULL)
   {
     gst_sample_unref(_currentFrameSample);
   }
   _currentFrameSample = NULL;
   _currentFrameBuffer = NULL;
   _data = NULL;
 }
GstFlowReturn MediaImpl::gstNewSampleCallback (GstElement * , MediaImpl * p) static
Definition at line 160 of file MediaImpl.cpp.
References _appsink0, _bitsChanged, _currentFrameBuffer, _currentFrameSample, _data, _freeCurrentSample(), _isSharedMemorySource, _mapInfo, _padHandlerData, MediaImpl::GstPadHandlerData::height, lockMutex(), unlockMutex(), and MediaImpl::GstPadHandlerData::width.
Referenced by loadMovie().
 {
   // Make it thread-safe.
   p->lockMutex();
   // Get next frame.
   GstSample *sample = gst_app_sink_pull_sample(GST_APP_SINK(p->_appsink0));
   // Unref last frame.
   p->_freeCurrentSample();
   // Set current frame.
   p->_currentFrameSample = sample;
   // For live sources, video dimensions have not been set, because
   // gstPadAddedCallback is never called. Fix dimensions from first sample /
   // caps we receive.
   if (p->_isSharedMemorySource && ( p->_padHandlerData.width == -1 ||
         p->_padHandlerData.height == -1)) {
     GstCaps *caps = gst_sample_get_caps(sample);
     GstStructure *structure;
     structure = gst_caps_get_structure(caps, 0);
     gst_structure_get_int(structure, "width",  &p->_padHandlerData.width);
     gst_structure_get_int(structure, "height", &p->_padHandlerData.height);
     // g_print("Size is %u x %u\n", _padHandlerData.width, _padHandlerData.height);
   }
   // Try to retrieve data bits of frame.
   GstMapInfo& map = p->_mapInfo;
   GstBuffer *buffer = gst_sample_get_buffer( sample );
   if (gst_buffer_map(buffer, &map, GST_MAP_READ))
   {
     p->_currentFrameBuffer = buffer;
     // For debugging:
     //gst_util_dump_mem(map.data, map.size)
     // Retrieve data from map info.
     p->_data = map.data;
     // Bits have changed.
     p->_bitsChanged = true;
   }
   p->unlockMutex();
   return GST_FLOW_OK;
 }
void MediaImpl::gstPadAddedCallback (GstElement * src, GstPad * newPad, MediaImpl::GstPadHandlerData * data) static
FIXME: remove GOTO.
Definition at line 817 of file MediaImpl.cpp.
References MediaImpl::GstPadHandlerData::audioToConnect, MediaImpl::GstPadHandlerData::height, MediaImpl::GstPadHandlerData::videoIsConnected, MediaImpl::GstPadHandlerData::videoToConnect, and MediaImpl::GstPadHandlerData::width.
Referenced by loadMovie().
 {
   g_print ("Received new pad '%s' from '%s':\n", GST_PAD_NAME (newPad), GST_ELEMENT_NAME (src));
   GstPad *sinkPad = NULL;
   // Check the new pad's type.
   GstCaps *newPadCaps = gst_pad_query_caps (newPad, NULL);
   GstStructure *newPadStruct = gst_caps_get_structure (newPadCaps, 0);
   const gchar *newPadType   = gst_structure_get_name (newPadStruct);
   gchar *newPadStructStr = gst_structure_to_string(newPadStruct);
   g_print("Structure is %s\n", newPadStructStr);
   g_free(newPadStructStr);
   if (g_str_has_prefix (newPadType, "video/x-raw"))
   {
     sinkPad = gst_element_get_static_pad (data->videoToConnect, "sink");
     gst_structure_get_int(newPadStruct, "width",  &data->width);
     gst_structure_get_int(newPadStruct, "height", &data->height);
   }
   else if (g_str_has_prefix (newPadType, "audio/x-raw"))
   {
     sinkPad = gst_element_get_static_pad (data->audioToConnect, "sink");
   }
   else {
     g_print ("  It has type '%s' which is not raw audio/video. Ignoring.\n", newPadType);
     goto exit;
   }
   // If our converter is already linked, we have nothing to do here.
   if (gst_pad_is_linked (sinkPad))
   {
     // Best prefixes.
     if (g_str_has_prefix (newPadType, "audio/x-raw-float") ||
         g_str_has_prefix (newPadType, "video/x-raw-int") )
     {
       g_print ("  Found a better pad.\n");
       GstPad* oldPad = gst_pad_get_peer(sinkPad);
       gst_pad_unlink(oldPad, sinkPad);
       g_object_unref(oldPad);
     }
     else
     {
       g_print ("  We are already linked. Ignoring.\n");
       goto exit;
     }
   }
   // Attempt the link
   if (GST_PAD_LINK_FAILED (gst_pad_link (newPad, sinkPad)))
   {
     g_print ("  Type is '%s' but link failed.\n", newPadType);
     goto exit;
   } else {
     data->videoIsConnected = true;
     g_print ("  Link succeeded (type '%s').\n", newPadType);
   }
 exit:
   // Unreference the new pad's caps, if we got them.
   if (newPadCaps != NULL)
   {
     gst_caps_unref (newPadCaps);
   }
   // Unreference the sink pad.
   if (sinkPad != NULL)
   {
     gst_object_unref (sinkPad);
   }
 }
void MediaImpl::lockMutex ()
Locks mutex (default = no effect).
Definition at line 887 of file MediaImpl.cpp.
References _mutexLocker.
Referenced by gstNewSampleCallback(), and Media::lockMutex().
 {
   _mutexLocker->relock();
 }
void MediaImpl::unlockMutex ()
Unlocks mutex (default = no effect).
Definition at line 892 of file MediaImpl.cpp.
References _mutexLocker.
Referenced by gstNewSampleCallback(), and Media::unlockMutex().
 {
   _mutexLocker->unlock();
 }
Member Data Documentation
GstBus* MediaImpl::_bus private
Definition at line 207 of file MediaImpl.h.
Referenced by _checkMessages(), freeResources(), and loadMovie().
GstElement* MediaImpl::_pipeline private
Definition at line 208 of file MediaImpl.h.
Referenced by _checkMessages(), _eos(), _updateRate(), freeResources(), loadMovie(), and setPlayState().
GstElement* MediaImpl::_uridecodebin0 private
Definition at line 209 of file MediaImpl.h.
Referenced by freeResources(), and loadMovie().
GstElement* MediaImpl::_shmsrc0 private
Definition at line 210 of file MediaImpl.h.
Referenced by loadMovie().
GstElement* MediaImpl::_gdpdepay0 private
Definition at line 211 of file MediaImpl.h.
Referenced by loadMovie().
GstElement* MediaImpl::_queue0 private
Definition at line 212 of file MediaImpl.h.
Referenced by freeResources(), and loadMovie().
GstElement* MediaImpl::_videoconvert0 private
Definition at line 213 of file MediaImpl.h.
Referenced by freeResources(), and loadMovie().
GstElement* MediaImpl::_appsink0 private
Definition at line 214 of file MediaImpl.h.
Referenced by _eos(), _updateRate(), freeResources(), gstNewSampleCallback(), loadMovie(), and resetMovie().
GstElement* MediaImpl::_audioqueue0 private
Definition at line 215 of file MediaImpl.h.
Referenced by loadMovie().
GstElement* MediaImpl::_audioconvert0 private
Definition at line 216 of file MediaImpl.h.
Referenced by loadMovie().
GstElement* MediaImpl::_audioresample0 private
Definition at line 217 of file MediaImpl.h.
Referenced by loadMovie().
GstElement* MediaImpl::_audiovolume0 private
Definition at line 218 of file MediaImpl.h.
Referenced by loadMovie(), and setVolume().
GstElement* MediaImpl::_audiosink0 private
Definition at line 219 of file MediaImpl.h.
Referenced by loadMovie().
GstSample* MediaImpl::_currentFrameSample private
Temporary contains the image data of the last frame.
Definition at line 224 of file MediaImpl.h.
Referenced by _freeCurrentSample(), getBits(), and gstNewSampleCallback().
GstBuffer* MediaImpl::_currentFrameBuffer private
Definition at line 225 of file MediaImpl.h.
Referenced by _freeCurrentSample(), and gstNewSampleCallback().
GstMapInfo MediaImpl::_mapInfo private
Definition at line 226 of file MediaImpl.h.
Referenced by _freeCurrentSample(), and gstNewSampleCallback().
bool MediaImpl::_bitsChanged private
Definition at line 227 of file MediaImpl.h.
Referenced by bitsHaveChanged(), freeResources(), getBits(), and gstNewSampleCallback().
GSource* MediaImpl::_pollSource private
shmsrc socket poller.
Definition at line 232 of file MediaImpl.h.
Referenced by freeResources(), loadMovie(), and MediaImpl().
GstPadHandlerData MediaImpl::_padHandlerData private
Definition at line 234 of file MediaImpl.h.
Referenced by freeResources(), getHeight(), getWidth(), gstNewSampleCallback(), isReady(), loadMovie(), and videoIsConnected().
int MediaImpl::_width private
Definition at line 237 of file MediaImpl.h.
int MediaImpl::_height private
Definition at line 239 of file MediaImpl.h.
uchar* MediaImpl::_data private
Raw image data of the last video frame.
Definition at line 242 of file MediaImpl.h.
Referenced by _freeCurrentSample(), getBits(), and gstNewSampleCallback().
bool MediaImpl::_seekEnabled private
Is seek enabled on the current pipeline?
Definition at line 245 of file MediaImpl.h.
Referenced by _checkMessages(), _updateRate(), resetMovie(), setRate(), and unloadMovie().
double MediaImpl::_rate private
Playback rate (negative ==> reverse).
Definition at line 248 of file MediaImpl.h.
Referenced by _eos(), _updateRate(), getRate(), resetMovie(), and setRate().
double MediaImpl::_volume private
Audio playback volume (0.0 ==> 1.0).
Definition at line 250 of file MediaImpl.h.
Referenced by getVolume(), and setVolume().
bool MediaImpl::_isSharedMemorySource private
Whether or not we are reading video from a shmsrc.
Definition at line 253 of file MediaImpl.h.
Referenced by _checkMessages(), gstNewSampleCallback(), and loadMovie().
bool MediaImpl::_attached private
Whether or not we are attached to a shmsrc, if using a shmsrc.
Definition at line 256 of file MediaImpl.h.
Referenced by _checkMessages(), getAttached(), and setAttached().
bool MediaImpl::_terminate private
Definition at line 259 of file MediaImpl.h.
Referenced by _checkMessages(), unloadMovie(), and update().
bool MediaImpl::_movieReady private
Is the movie (or rather pipeline) ready to play.
Definition at line 262 of file MediaImpl.h.
Referenced by _eos(), _isMovieReady(), _setMovieReady(), and isReady().
bool MediaImpl::_playState private
Is the movie playing (as opposed to paused).
Definition at line 265 of file MediaImpl.h.
Referenced by getPlayState(), and setPlayState().
QMutex MediaImpl::_mutex private
Main mutex.
Definition at line 268 of file MediaImpl.h.
Referenced by MediaImpl().
QMutexLocker* MediaImpl::_mutexLocker private
Main mutex locker (for the lockMutex() / unlockMutex() methods).
Definition at line 271 of file MediaImpl.h.
Referenced by lockMutex(), MediaImpl(), unlockMutex(), and ~MediaImpl().
QString MediaImpl::_uri private
Path of the movie file being played.
Definition at line 277 of file MediaImpl.h.
Referenced by _checkMessages(), build(), getUri(), loadMovie(), and resetMovie().
const int MediaImpl::MAX_SAMPLES_IN_BUFFER_QUEUES = 30 static private
Definition at line 279 of file MediaImpl.h.
The documentation for this class was generated from the following files:
MediaImpl.h
MediaImpl.cpp