MapMap: Paint Class Reference
Paint Class Reference abstract
A Paint is a style that can be applied when drawing potentially any shape.
#include <Paint.h>
Public Types
typedef QSharedPointer< Paint > ptr
Public Member Functions
virtual ~Paint ()
virtual void build ()
virtual void update ()
This method should be called at each call of draw().
virtual void play ()
Starts playback.
virtual void pause ()
Pauses playback.
virtual void rewind ()
Rewinds.
virtual void lockMutex ()
Locks mutex (default = no effect).
virtual void unlockMutex ()
Unlocks mutex (default = no effect).
void setName (const QString &name)
QString getName () const
uid getId () const
float getOpacity () const
void setOpacity (float opacity)
virtual QString getType () const =0
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Member Functions
Paint (uid id=NULL_UID)
Private Attributes
uid _id
QString _name
float _opacity
Static Private Attributes
static UidAllocator allocator
Detailed Description
A Paint is a style that can be applied when drawing potentially any shape.
Defines the way to draw any shape. There must be a MappingGui that implements this paint for every shape so that this shape might be drawn with it.
Definition at line 46 of file Paint.h.
Member Typedef Documentation
typedef QSharedPointer<Paint> Paint::ptr
Definition at line 57 of file Paint.h.
Constructor & Destructor Documentation
Paint::Paint (uid id = NULL_UID) protected
Definition at line 27 of file Paint.cpp.
References _id, UidAllocator::allocate(), allocator, UidAllocator::exists(), NULL_UID, and UidAllocator::reserve().
   : _opacity(1.0f)
 {
   if (id == NULL_UID)
     id = allocator.allocate();
   else
   {
     Q_ASSERT(!allocator.exists(id));
     allocator.reserve(id);
   }
   // Assign id.
   _id = id;
 }
Paint::~Paint () virtual
Definition at line 41 of file Paint.cpp.
References _id, allocator, and UidAllocator::free().
 {
   allocator.free(_id);
 }
Member Function Documentation
static const UidAllocator& Paint::getUidAllocator () static
Definition at line 61 of file Paint.h.
References allocator.
Referenced by MainWindow::createColorPaint(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMediaPaint(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deletePaint().
 { return allocator; }
virtual void Paint::build () virtual
Reimplemented in Media, and Image.
Definition at line 63 of file Paint.h.
 {}
virtual void Paint::update () virtual
This method should be called at each call of draw().
Reimplemented in Media.
Definition at line 66 of file Paint.h.
 {}
virtual void Paint::play () virtual
Starts playback.
Reimplemented in Media.
Definition at line 69 of file Paint.h.
 {}
virtual void Paint::pause () virtual
Pauses playback.
Reimplemented in Media.
Definition at line 72 of file Paint.h.
 {}
virtual void Paint::rewind () virtual
Rewinds.
Reimplemented in Media.
Definition at line 75 of file Paint.h.
 {}
virtual void Paint::lockMutex () virtual
Locks mutex (default = no effect).
Reimplemented in Media.
Definition at line 78 of file Paint.h.
 {}
virtual void Paint::unlockMutex () virtual
Unlocks mutex (default = no effect).
Reimplemented in Media.
Definition at line 81 of file Paint.h.
 {}
void Paint::setName (const QString & name)
Definition at line 83 of file Paint.h.
References _name.
 { _name = name; }
QString Paint::getName () const
Definition at line 84 of file Paint.h.
References _name.
Referenced by ProjectWriter::writeItem().
 { return _name; }
uid Paint::getId () const
Definition at line 85 of file Paint.h.
References _id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
float Paint::getOpacity () const
Definition at line 87 of file Paint.h.
References _opacity.
 { return _opacity; }
void Paint::setOpacity (float opacity)
Definition at line 88 of file Paint.h.
References _opacity.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
virtual QString Paint::getType () const pure virtual
Implemented in Media, Image, and Color.
Referenced by ProjectWriter::writeItem().
Member Data Documentation
UidAllocator Paint::allocator static private
Definition at line 49 of file Paint.h.
Referenced by getUidAllocator(), Paint(), and ~Paint().
uid Paint::_id private
Definition at line 51 of file Paint.h.
Referenced by getId(), Paint(), and ~Paint().
QString Paint::_name private
Definition at line 96 of file Paint.h.
Referenced by getName(), and setName().
float Paint::_opacity private
Definition at line 97 of file Paint.h.
Referenced by getOpacity(), and setOpacity().
The documentation for this class was generated from the following files:
Paint.h
Paint.cpp