MapMap: EllipseControlPainter Class Reference
EllipseControlPainter Class Reference
Control painter for ellipses.
#include <ShapeControlPainter.h>
Public Types
typedef QSharedPointer
< ShapeControlPainter > ptr
Public Member Functions
EllipseControlPainter (ShapeGraphicsItem *shapeItem)
virtual ~EllipseControlPainter ()
MShape::ptr getShape () const
virtual void paint (QPainter *painter, MapperGLCanvas *canvas, const QList< int > &selectedVertices=QList< int >())
Protected Member Functions
virtual void _paintShape (QPainter *painter, MapperGLCanvas *canvas)
virtual void _paintVertices (QPainter *painter, MapperGLCanvas *canvas, const QList< int > &selectedVertices=QList< int >())
QPen getRescaledShapeStroke (MapperGLCanvas *canvas, bool innerStroke=false)
Protected Attributes
ShapeGraphicsItem * _shapeItem
Detailed Description
Control painter for ellipses.
Definition at line 69 of file ShapeControlPainter.h.
Member Typedef Documentation
typedef QSharedPointer<ShapeControlPainter> ShapeControlPainter::ptr inherited
Definition at line 39 of file ShapeControlPainter.h.
Constructor & Destructor Documentation
EllipseControlPainter::EllipseControlPainter (ShapeGraphicsItem * shapeItem)
Definition at line 72 of file ShapeControlPainter.h.
 : ShapeControlPainter(shapeItem) {}
virtual EllipseControlPainter::~EllipseControlPainter () virtual
Definition at line 73 of file ShapeControlPainter.h.
 {}
Member Function Documentation
void EllipseControlPainter::_paintShape (QPainter * painter, MapperGLCanvas * canvas) protected virtual
Implements ShapeControlPainter.
Definition at line 64 of file ShapeControlPainter.cpp.
References Ellipse::getCenter(), Ellipse::getHorizontalRadius(), ShapeControlPainter::getRescaledShapeStroke(), Ellipse::getRotation(), ShapeControlPainter::getShape(), and Ellipse::getVerticalRadius().
 {
   Ellipse* ellipse = static_cast<Ellipse*>(getShape().data());
   Q_ASSERT(ellipse);
   // Init colors and stroke.
   painter->setPen(getRescaledShapeStroke(canvas));
   painter->setBrush(Qt::NoBrush);
   // Draw ellipse contour.
   QPainterPath path;
   QTransform transform;
   transform.translate(ellipse->getCenter().x(), ellipse->getCenter().y());
   transform.rotate(ellipse->getRotation());
   path.addEllipse(QPoint(0,0), ellipse->getHorizontalRadius(), ellipse->getVerticalRadius());
   painter->drawPath(transform.map(path));
 }
MShape::ptr ShapeControlPainter::getShape () const inherited
Definition at line 28 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_shapeItem, and ShapeGraphicsItem::getShape().
Referenced by PolygonControlPainter::_paintShape(), _paintShape(), MeshControlPainter::_paintShape(), and ShapeControlPainter::_paintVertices().
 { return _shapeItem->getShape(); }
void ShapeControlPainter::paint (QPainter * painter, MapperGLCanvas * canvas, const QList< int > & selectedVertices = QList<int>()) virtual inherited
Definition at line 30 of file ShapeControlPainter.cpp.
References ShapeControlPainter::_paintShape(), and ShapeControlPainter::_paintVertices().
 {
   _paintShape(painter, canvas);
   _paintVertices(painter, canvas, selectedVertices);
 }
void ShapeControlPainter::_paintVertices (QPainter * painter, MapperGLCanvas * canvas, const QList< int > & selectedVertices = QList<int>()) protected virtual inherited
Definition at line 36 of file ShapeControlPainter.cpp.
References Util::drawControlsVertex(), ShapeControlPainter::getShape(), MapperGLCanvas::getZoomFactor(), MM::VERTEX_SELECT_RADIUS, and MM::VERTEX_SELECT_STROKE_WIDTH.
Referenced by ShapeControlPainter::paint().
 {
   qreal zoomFactor = canvas->getZoomFactor();
   qreal selectRadius = MM::VERTEX_SELECT_RADIUS / zoomFactor;
   qreal strokeWidth  = MM::VERTEX_SELECT_STROKE_WIDTH / zoomFactor;
   for (int i=0; i<getShape()->nVertices(); i++)
     Util::drawControlsVertex(painter, getShape()->getVertex(i), selectedVertices.contains(i), selectRadius, strokeWidth);
 }
QPen ShapeControlPainter::getRescaledShapeStroke (MapperGLCanvas * canvas, bool innerStroke = false) protected inherited
Definition at line 46 of file ShapeControlPainter.cpp.
References MM::CONTROL_COLOR, MapperGLCanvas::getZoomFactor(), MM::SHAPE_INNER_STROKE_WIDTH, and MM::SHAPE_STROKE_WIDTH.
Referenced by PolygonControlPainter::_paintShape(), _paintShape(), and MeshControlPainter::_paintShape().
 {
   return QPen(QBrush(MM::CONTROL_COLOR), (innerStroke ? MM::SHAPE_INNER_STROKE_WIDTH : MM::SHAPE_STROKE_WIDTH) / canvas->getZoomFactor());
 }
Member Data Documentation
ShapeGraphicsItem* ShapeControlPainter::_shapeItem protected inherited
Definition at line 54 of file ShapeControlPainter.h.
Referenced by MeshControlPainter::_paintShape(), and ShapeControlPainter::getShape().
The documentation for this class was generated from the following files:
ShapeControlPainter.h
ShapeControlPainter.cpp