MapMap: Texture Class Reference
Texture Class Reference abstract
Paint that uses an OpenGL texture to paint on potentially any MappingGui.
#include <Paint.h>
Public Types
typedef QSharedPointer< Paint > ptr
Public Member Functions
virtual ~Texture ()
GLuint getTextureId () const
virtual int getWidth () const =0
virtual int getHeight () const =0
virtual const uchar * getBits ()=0
Returns image bits data. Next call to bitsHaveChanged() will be false.
virtual bool bitsHaveChanged () const =0
Returns true iff bits have changed since last call to getBits().
virtual void setPosition (GLfloat xPos, GLfloat yPos)
virtual GLfloat getX () const
virtual GLfloat getY () const
virtual QRectF getRect () const
virtual void build ()
virtual void update ()
This method should be called at each call of draw().
virtual void play ()
Starts playback.
virtual void pause ()
Pauses playback.
virtual void rewind ()
Rewinds.
virtual void lockMutex ()
Locks mutex (default = no effect).
virtual void unlockMutex ()
Unlocks mutex (default = no effect).
void setName (const QString &name)
QString getName () const
uid getId () const
float getOpacity () const
void setOpacity (float opacity)
virtual QString getType () const =0
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Member Functions
Texture (uid id=NULL_UID)
Protected Attributes
GLuint textureId
GLfloat x
GLfloat y
bool bitsChanged
Detailed Description
Paint that uses an OpenGL texture to paint on potentially any MappingGui.
This video texture is actually an OpenGL texture.
Definition at line 120 of file Paint.h.
Member Typedef Documentation
typedef QSharedPointer<Paint> Paint::ptr inherited
Definition at line 57 of file Paint.h.
Constructor & Destructor Documentation
Texture::Texture (uid id = NULL_UID) protected
Definition at line 128 of file Paint.h.
                            :
     Paint(id),
     textureId(0),
     x(0),
     y(0)
   {
     glGenTextures(1, &textureId);
   }
virtual Texture::~Texture () virtual
Definition at line 138 of file Paint.h.
                      {
     if (textureId != 0)
       glDeleteTextures(1, &textureId);
   }
Member Function Documentation
GLuint Texture::getTextureId () const
Definition at line 144 of file Paint.h.
References textureId.
 { return textureId; }
virtual int Texture::getWidth () const pure virtual
Implemented in Media, and Image.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), getRect(), and Util::setGlTexPoint().
virtual int Texture::getHeight () const pure virtual
Implemented in Media, and Image.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), getRect(), and Util::setGlTexPoint().
virtual const uchar* Texture::getBits () pure virtual
Returns image bits data. Next call to bitsHaveChanged() will be false.
Implemented in Media, and Image.
virtual bool Texture::bitsHaveChanged () const pure virtual
Returns true iff bits have changed since last call to getBits().
Implemented in Media, and Image.
virtual void Texture::setPosition (GLfloat xPos, GLfloat yPos) virtual
Definition at line 154 of file Paint.h.
Referenced by MainWindow::createMediaPaint().
{
     x = xPos;
     y = yPos;
   }
virtual GLfloat Texture::getX () const virtual
Definition at line 158 of file Paint.h.
References x.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return x; }
virtual GLfloat Texture::getY () const virtual
Definition at line 159 of file Paint.h.
References y.
Referenced by Util::createEllipseForTexture(), Util::createMeshForTexture(), Util::createTriangleForTexture(), getRect(), Util::setGlTexPoint(), and ProjectWriter::writeItem().
 { return y; }
virtual QRectF Texture::getRect () const virtual
Definition at line 161 of file Paint.h.
References getHeight(), getWidth(), getX(), and getY().
 { return QRectF(getX(), getY(), getWidth(), getHeight()); }
static const UidAllocator& Paint::getUidAllocator () static inherited
Definition at line 61 of file Paint.h.
References Paint::allocator.
Referenced by MainWindow::createColorPaint(), MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMediaPaint(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deletePaint().
 { return allocator; }
virtual void Paint::build () virtual inherited
Reimplemented in Media, and Image.
Definition at line 63 of file Paint.h.
 {}
virtual void Paint::update () virtual inherited
This method should be called at each call of draw().
Reimplemented in Media.
Definition at line 66 of file Paint.h.
 {}
virtual void Paint::play () virtual inherited
Starts playback.
Reimplemented in Media.
Definition at line 69 of file Paint.h.
 {}
virtual void Paint::pause () virtual inherited
Pauses playback.
Reimplemented in Media.
Definition at line 72 of file Paint.h.
 {}
virtual void Paint::rewind () virtual inherited
Rewinds.
Reimplemented in Media.
Definition at line 75 of file Paint.h.
 {}
virtual void Paint::lockMutex () virtual inherited
Locks mutex (default = no effect).
Reimplemented in Media.
Definition at line 78 of file Paint.h.
 {}
virtual void Paint::unlockMutex () virtual inherited
Unlocks mutex (default = no effect).
Reimplemented in Media.
Definition at line 81 of file Paint.h.
 {}
void Paint::setName (const QString & name) inherited
Definition at line 83 of file Paint.h.
References Paint::_name.
 { _name = name; }
QString Paint::getName () const inherited
Definition at line 84 of file Paint.h.
References Paint::_name.
 { return _name; }
uid Paint::getId () const inherited
Definition at line 85 of file Paint.h.
References Paint::_id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
float Paint::getOpacity () const inherited
Definition at line 87 of file Paint.h.
References Paint::_opacity.
 { return _opacity; }
void Paint::setOpacity (float opacity) inherited
Definition at line 88 of file Paint.h.
References Paint::_opacity.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
virtual QString Paint::getType () const pure virtual inherited
Implemented in Media, Image, and Color.
Referenced by ProjectWriter::writeItem().
Member Data Documentation
GLuint Texture::textureId protected
Definition at line 123 of file Paint.h.
Referenced by getTextureId().
GLfloat Texture::x protected
Definition at line 124 of file Paint.h.
Referenced by getX().
GLfloat Texture::y protected
Definition at line 125 of file Paint.h.
Referenced by getY().
bool Texture::bitsChanged mutable protected
Definition at line 126 of file Paint.h.
Referenced by Image::bitsHaveChanged(), Image::build(), and Image::getBits().
The documentation for this class was generated from the following file:
Paint.h