MapMap: ProjectWriter Class Reference
ProjectWriter Class Reference
#include <ProjectWriter.h>
Public Member Functions
ProjectWriter (MappingManager *manager)
bool writeFile (QIODevice *device)
Private Member Functions
void writeItem (Paint *item)
void writeItem (Mapping *item)
void writeShapeVertices (MShape *shape)
Private Attributes
QXmlStreamWriter _xml
MappingManager * _manager
Detailed Description
Definition at line 26 of file ProjectWriter.h.
Constructor & Destructor Documentation
ProjectWriter::ProjectWriter (MappingManager * manager)
Definition at line 23 of file ProjectWriter.cpp.
References _xml.
                                                     :
     _manager(manager)
 {
   _xml.setAutoFormatting(true);
 }
Member Function Documentation
bool ProjectWriter::writeFile (QIODevice * device)
Definition at line 29 of file ProjectWriter.cpp.
References _manager, _xml, MappingManager::getMapping(), MappingManager::getPaint(), MappingManager::nMappings(), MappingManager::nPaints(), and writeItem().
Referenced by MainWindow::saveFile().
 {
   _xml.setDevice(device);
   _xml.writeStartDocument();
   _xml.writeDTD("<!DOCTYPE mapmap>");
   _xml.writeStartElement("project");
   _xml.writeAttribute("version", "0.1"); // Similar to pkg-config version numbers.
   _xml.writeStartElement("paints");
   for (int i = 0; i < _manager->nPaints(); i++)
     writeItem(_manager->getPaint(i).data());
   _xml.writeEndElement();
   _xml.writeStartElement("mappings");
   for (int i = 0; i < _manager->nMappings(); i++)
     writeItem(_manager->getMapping(i).data());
   _xml.writeEndElement();
   _xml.writeEndElement();
   _xml.writeEndDocument();
   return true;
 }
void ProjectWriter::writeItem (Paint * item) private
Definition at line 53 of file ProjectWriter.cpp.
References _xml, Color::getColor(), Paint::getId(), Paint::getName(), Media::getRate(), Paint::getType(), Image::getUri(), Media::getUri(), Texture::getX(), and Texture::getY().
Referenced by writeFile().
 {
   _xml.writeStartElement("paint");
   _xml.writeAttribute("id", QString::number(item->getId()));
   _xml.writeAttribute("name", item->getName());
   _xml.writeAttribute("type", item->getType());
   if (item->getType() == "media")
   {
     // FIXME: check paint type before casting to Media
     Media *media = (Media *) item;
     _xml.writeTextElement("uri", media->getUri());
     {
       std::ostringstream os;
       os << media->getX();
       _xml.writeTextElement("x", os.str().c_str());
     }
     {
       std::ostringstream os;
       os << media->getY();
       _xml.writeTextElement("y", os.str().c_str());
     }
     {
       std::ostringstream os;
       os << media->getRate();
       _xml.writeTextElement("rate", os.str().c_str());
     }
     _xml.writeEndElement();
     //_xml.writeEmptyElement("hello");
   }
   else if (item->getType() == "image")
   {
     // FIXME: check paint type before casting to Image
     Image *media = (Image *) item;
     _xml.writeTextElement("uri", media->getUri());
     {
       std::ostringstream os;
       os << media->getX();
       _xml.writeTextElement("x", os.str().c_str());
     }
     {
       std::ostringstream os;
       os << media->getY();
       _xml.writeTextElement("y", os.str().c_str());
     }
     _xml.writeEndElement();
     //_xml.writeEmptyElement("hello");
   }
   else if (item->getType() == "color")
   {
     // FIXME: check paint type before casting to Image
     Color *color = (Color *) item;
     _xml.writeTextElement("rgb", color->getColor().name());
     _xml.writeEndElement();
   }
   else
     qDebug() << "Unknown type, cannot save: " << item->getType() << endl;
 }
void ProjectWriter::writeItem (Mapping * item) private
Definition at line 140 of file ProjectWriter.cpp.
References _xml, Mapping::getId(), TextureMapping::getInputShape(), Mapping::getName(), Mapping::getPaint(), Mapping::getShape(), MShape::getType(), Mapping::getType(), Mapping::isLocked(), Mapping::isSolo(), Mapping::isVisible(), and writeShapeVertices().
 {
   _xml.writeStartElement("mapping");
   qDebug() << "ID: " << item->getId() << endl;
   _xml.writeAttribute("id", QString::number(item->getId()));
   _xml.writeAttribute("name", item->getName());
   _xml.writeAttribute("paint_id", QString::number(item->getPaint()->getId()));
   _xml.writeAttribute("type", item->getType());
   // boolean attributes:
   _xml.writeAttribute("locked", QString::number((int) item->isLocked() ? 1 : 0));
   _xml.writeAttribute("solo", QString::number((int) item->isSolo() ? 1 : 0));
   _xml.writeAttribute("visible", QString::number((int) item->isVisible() ? 1 : 0));
   MShape *shape = item->getShape().data();
   _xml.writeStartElement("destination");
   _xml.writeAttribute("shape", shape->getType());
   writeShapeVertices(shape);
   _xml.writeEndElement(); // shape
   if (item->getType().endsWith("_texture"))
   {
     TextureMapping *tex = (TextureMapping *) item;
     shape = tex->getInputShape().data();
     _xml.writeStartElement("source");
     _xml.writeAttribute("shape", shape->getType());
     writeShapeVertices(shape);
     _xml.writeEndElement(); // shape
     _xml.writeEndElement(); // mapping
   }
   else if (item->getType().endsWith("_color"))
   {
     _xml.writeEndElement(); // mapping
   }
   else
     qDebug() << "Unknown type, cannot save: " << item->getType() << endl;
 }
void ProjectWriter::writeShapeVertices (MShape * shape) private
Definition at line 120 of file ProjectWriter.cpp.
References _xml, MShape::getType(), MShape::getVertex(), Mesh::nColumns(), Mesh::nRows(), and MShape::nVertices().
Referenced by writeItem().
 {
   if (shape->getType() == "mesh") {
     Mesh* mesh = (Mesh*) shape;
     _xml.writeStartElement("dimensions");
     _xml.writeAttribute("columns", QString::number(mesh->nColumns()));
     _xml.writeAttribute("rows", QString::number(mesh->nRows()));
     _xml.writeEndElement(); // vertex
   }
   for (int i = 0; i < shape->nVertices(); i++)
   {
     const QPointF& point = shape->getVertex(i);
     _xml.writeStartElement("vertex");
     _xml.writeAttribute("x", QString::number(point.x()));
     _xml.writeAttribute("y", QString::number(point.y()));
     _xml.writeEndElement(); // vertex
   }
 }
Member Data Documentation
QXmlStreamWriter ProjectWriter::_xml private
Definition at line 36 of file ProjectWriter.h.
Referenced by ProjectWriter(), writeFile(), writeItem(), and writeShapeVertices().
MappingManager* ProjectWriter::_manager private
Definition at line 37 of file ProjectWriter.h.
Referenced by writeFile().
The documentation for this class was generated from the following files:
ProjectWriter.h
ProjectWriter.cpp