MapMap: Mapping Class Reference
Mapping Class Reference abstract
Mapping is the central concept of this software.
#include <Mapping.h>
Public Types
typedef QSharedPointer< Mapping > ptr
Public Member Functions
virtual ~Mapping ()
virtual void build ()
Sets up this Mapping: its Paint and its Shape.
virtual QString getType () const =0
The type of the mapping (expressed as a string).
Paint::ptr getPaint () const
Returns the paint.
MShape::ptr getShape () const
Returns the (output) shape.
virtual bool hasInputShape () const
Returns true iff the mapping possesses an input (source) shape.
virtual MShape::ptr getInputShape () const
Returns the input (source) shape (if this mapping has one) or a null pointer if not.
uid getId () const
void setLocked (bool locked)
void setSolo (bool solo)
void setVisible (bool visible)
void setRawOpacity (float opacity)
void setDepth (int depth)
void toggleLocked ()
void toggleSolo ()
void toggleVisible ()
bool isLocked () const
bool isSolo () const
bool isVisible () const
float getRawOpacity () const
int getDepth () const
float getOpacity () const
void setPaint (Paint::ptr p)
void setName (const QString &name)
QString getName () const
Static Public Member Functions
static const UidAllocator & getUidAllocator ()
Protected Member Functions
Mapping (Paint::ptr paint, MShape::ptr shape, uid id=NULL_UID)
Constructor.
Protected Attributes
Paint::ptr _paint
The input Paint instance.
MShape::ptr _shape
The output Shape instance.
Private Attributes
uid _id
bool _isLocked
bool _isSolo
bool _isVisible
float _opacity
int _depth
QString _name
Static Private Attributes
static UidAllocator allocator
Detailed Description
Mapping is the central concept of this software.
A Mapping represents a relationship between an input Paint and and output Shape where the paint (possibly modified by some other attributes or an input Shape in the case of TextureMapping) is projected on the output shape.
Mapping instances are stacked as layers by the MappingManager. One can thus change their opacity level, toggle their visibility, set them in "solo" mode and lock them.
Definition at line 42 of file Mapping.h.
Member Typedef Documentation
typedef QSharedPointer<Mapping> Mapping::ptr
Definition at line 70 of file Mapping.h.
Constructor & Destructor Documentation
Mapping::Mapping (Paint::ptr paint, MShape::ptr shape, uid id = NULL_UID) protected
Constructor.
Definition at line 25 of file Mapping.cpp.
References _depth, _id, UidAllocator::allocate(), allocator, UidAllocator::exists(), NULL_UID, and UidAllocator::reserve().
   : _paint(paint), _shape(shape),
     _isLocked(false), _isSolo(false), _isVisible(true), _opacity(1.0f)
 {
   if (id == NULL_UID)
     id = allocator.allocate();
   else
   {
     Q_ASSERT(!allocator.exists(id));
     allocator.reserve(id);
   }
   // Assign id.
   _id = id;
   // Default.
   _depth = _id;
 }
Mapping::~Mapping () virtual
Definition at line 44 of file Mapping.cpp.
References _id, allocator, and UidAllocator::free().
                   {
   allocator.free(_id);
 }
Member Function Documentation
static const UidAllocator& Mapping::getUidAllocator () static
Definition at line 74 of file Mapping.h.
References allocator.
Referenced by MainWindow::createEllipseColorMapping(), MainWindow::createEllipseTextureMapping(), MainWindow::createMeshTextureMapping(), MainWindow::createQuadColorMapping(), MainWindow::createTriangleColorMapping(), MainWindow::createTriangleTextureMapping(), and MainWindow::deleteMapping().
 { return allocator; }
virtual void Mapping::build () virtual
Sets up this Mapping: its Paint and its Shape.
Calls the build() method of its Paint and Shape.
Reimplemented in TextureMapping.
Definition at line 80 of file Mapping.h.
Referenced by TextureMapping::build().
{
     _paint->build();
     _shape->build();
   }
virtual QString Mapping::getType () const pure virtual
The type of the mapping (expressed as a string).
Implemented in TextureMapping, and ColorMapping.
Referenced by MainWindow::duplicateMapping(), and ProjectWriter::writeItem().
Paint::ptr Mapping::getPaint () const
Returns the paint.
Definition at line 89 of file Mapping.h.
References _paint.
Referenced by ProjectWriter::writeItem().
 { return _paint; }
MShape::ptr Mapping::getShape () const
Returns the (output) shape.
Definition at line 92 of file Mapping.h.
References _shape.
Referenced by ColorMapping::getType(), TextureMapping::getType(), and ProjectWriter::writeItem().
 { return _shape; }
virtual bool Mapping::hasInputShape () const virtual
Returns true iff the mapping possesses an input (source) shape.
Reimplemented in TextureMapping.
Definition at line 95 of file Mapping.h.
 { return false; }
virtual MShape::ptr Mapping::getInputShape () const virtual
Returns the input (source) shape (if this mapping has one) or a null pointer if not.
Reimplemented in TextureMapping.
Definition at line 98 of file Mapping.h.
 { return MShape::ptr(); }
uid Mapping::getId () const
Definition at line 100 of file Mapping.h.
References _id.
Referenced by ProjectWriter::writeItem().
 { return _id; }
void Mapping::setLocked (bool locked)
Definition at line 102 of file Mapping.h.
 { _isLocked = locked; }
void Mapping::setSolo (bool solo)
Definition at line 103 of file Mapping.h.
 { _isSolo = solo; }
void Mapping::setVisible (bool visible)
Definition at line 104 of file Mapping.h.
 { _isVisible = visible; }
void Mapping::setRawOpacity (float opacity)
Definition at line 105 of file Mapping.h.
{
     Q_ASSERT(0.0f <= opacity && opacity <= 1.0f);
     _opacity = opacity;
   }
void Mapping::setDepth (int depth)
Definition at line 109 of file Mapping.h.
 { _depth = depth; }
void Mapping::toggleLocked ()
Definition at line 111 of file Mapping.h.
References _isLocked.
 { _isLocked = !_isLocked; }
void Mapping::toggleSolo ()
Definition at line 112 of file Mapping.h.
References _isSolo.
 { _isSolo = !_isSolo; }
void Mapping::toggleVisible ()
Definition at line 113 of file Mapping.h.
References _isVisible.
 { _isVisible = !_isVisible; }
bool Mapping::isLocked () const
Definition at line 115 of file Mapping.h.
References _isLocked.
Referenced by ProjectWriter::writeItem().
 { return _isLocked; }
bool Mapping::isSolo () const
Definition at line 116 of file Mapping.h.
References _isSolo.
Referenced by ProjectWriter::writeItem().
 { return _isSolo; }
bool Mapping::isVisible () const
Definition at line 117 of file Mapping.h.
References _isVisible.
Referenced by ProjectWriter::writeItem().
 { return _isVisible; }
float Mapping::getRawOpacity () const
Definition at line 118 of file Mapping.h.
References _opacity.
 { return _opacity; }
int Mapping::getDepth () const
Definition at line 119 of file Mapping.h.
References _depth.
 { return _depth; }
float Mapping::getOpacity () const
Definition at line 121 of file Mapping.h.
 { return _opacity * _paint->getOpacity(); }
void Mapping::setPaint (Paint::ptr p)
Definition at line 123 of file Mapping.h.
 { _paint = p; }
void Mapping::setName (const QString & name)
Definition at line 125 of file Mapping.h.
 { _name = name; }
QString Mapping::getName () const
Definition at line 127 of file Mapping.h.
References _name.
Referenced by ProjectWriter::writeItem().
 { return _name; }
Member Data Documentation
Paint::ptr Mapping::_paint protected
The input Paint instance.
Definition at line 46 of file Mapping.h.
Referenced by getPaint().
MShape::ptr Mapping::_shape protected
The output Shape instance.
Definition at line 49 of file Mapping.h.
Referenced by getShape().
UidAllocator Mapping::allocator static private
Definition at line 52 of file Mapping.h.
Referenced by getUidAllocator(), Mapping(), and ~Mapping().
uid Mapping::_id private
Definition at line 54 of file Mapping.h.
Referenced by getId(), Mapping(), and ~Mapping().
bool Mapping::_isLocked private
Definition at line 56 of file Mapping.h.
Referenced by isLocked(), and toggleLocked().
bool Mapping::_isSolo private
Definition at line 57 of file Mapping.h.
Referenced by isSolo(), and toggleSolo().
bool Mapping::_isVisible private
Definition at line 58 of file Mapping.h.
Referenced by isVisible(), and toggleVisible().
float Mapping::_opacity private
Definition at line 59 of file Mapping.h.
Referenced by getRawOpacity().
int Mapping::_depth private
Definition at line 60 of file Mapping.h.
Referenced by getDepth(), and Mapping().
QString Mapping::_name private
Definition at line 63 of file Mapping.h.
Referenced by getName().
The documentation for this class was generated from the following files:
Mapping.h
Mapping.cpp