MapMap: OutputGLCanvas Class Reference
OutputGLCanvas Class Reference
#include <OutputGLCanvas.h>
Public Slots
void updateCanvas ()
void deselectVertices ()
void deselectAll ()
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *event)
bool eventFilter (QObject *target, QEvent *event)
Signals
void shapeChanged (MShape *)
void imageChanged ()
Public Member Functions
OutputGLCanvas (MainWindow *mainWindow, QWidget *parent=0, const QGLWidget *shareWidget=0, QGraphicsScene *scene=0)
virtual ~OutputGLCanvas ()
void setDisplayCrosshair (bool displayCrosshair)
void drawForeground (QPainter *painter, const QRectF &rect)
virtual bool isOutput () const
Returns shape associated with mapping id.
virtual MShape::ptr getShapeFromMappingId (uid mappingId) const
virtual QSharedPointer
< ShapeGraphicsItem > getShapeGraphicsItemFromMappingId (uid mappingId) const
MShape::ptr getCurrentShape ()
QSharedPointer< ShapeGraphicsItem > getCurrentShapeGraphicsItem ()
MainWindow * getMainWindow () const
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
bool hasActiveVertex () const
Returns true iff one of the vertices is currently active.
int getActiveVertexIndex () const
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
void setActiveVertexIndex (int activeVertex)
Set the currently active vertex.
bool shapeGrabbed () const
bool vertexGrabbed () const
qreal getZoomFactor () const
void currentShapeWasChanged ()
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Static Public Attributes
static const int NO_VERTEX = -1
Protected Member Functions
virtual void resizeGL (int width, int height)
void wheelEvent (QWheelEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void _glueVertex (QPointF *p)
Private Member Functions
void _drawTestSignal (QPainter *painter)
Private Attributes
bool _displayCrosshair
QImage _svg_test_signal
QBrush _brush_test_signal
Detailed Description
Definition at line 26 of file OutputGLCanvas.h.
Constructor & Destructor Documentation
OutputGLCanvas::OutputGLCanvas (MainWindow * mainWindow, QWidget * parent = 0, const QGLWidget * shareWidget = 0, QGraphicsScene * scene = 0)
Definition at line 24 of file OutputGLCanvas.cpp.
 : DestinationGLCanvas(mainWindow, parent, shareWidget, scene),
   _displayCrosshair(false),
   _svg_test_signal(":/test-signal"),
   _brush_test_signal(_svg_test_signal)
 {
   // Disable scrollbars.
   setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
   setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
 }
virtual OutputGLCanvas::~OutputGLCanvas () virtual
Definition at line 32 of file OutputGLCanvas.h.
 {}
Member Function Documentation
void OutputGLCanvas::setDisplayCrosshair (bool displayCrosshair)
Definition at line 34 of file OutputGLCanvas.h.
References _displayCrosshair.
Referenced by OutputGLWindow::setFullScreen().
{
     _displayCrosshair = displayCrosshair;
   }
void OutputGLCanvas::drawForeground (QPainter * painter, const QRectF & rect)
Definition at line 35 of file OutputGLCanvas.cpp.
References _displayCrosshair, _drawTestSignal(), MM::CONTROL_COLOR, MapperGLCanvas::drawForeground(), and MapperGLCanvas::getMainWindow().
 {
   if (getMainWindow()->displayTestSignal())
   {
     glPushMatrix();
     painter->translate(rect.x(), rect.y());
     painter->save();
     _drawTestSignal(painter);
     painter->restore();
     glPopMatrix();
   }
   else
   {
     MapperGLCanvas::drawForeground(painter, rect);
     // Display crosshair cursor.
     if (_displayCrosshair)
     {
       QPointF cursorPosition = mapToScene(mapFromGlobal(cursor().pos()));// - rect.topLeft();//(QCursor::pos());///*this->mapFromGlobal(*/QCursor::pos()/*)*/;
       if (rect.contains(cursorPosition))
       {
         painter->setPen(MM::CONTROL_COLOR);
         painter->drawLine(cursorPosition.x(), rect.y(), cursorPosition.x(), rect.height());
         painter->drawLine(rect.x(), cursorPosition.y(), rect.width(), cursorPosition.y());
       }
     }
   }
 }
void OutputGLCanvas::_drawTestSignal (QPainter * painter) private
Definition at line 65 of file OutputGLCanvas.cpp.
References _brush_test_signal, _svg_test_signal, and MM::CONTROL_COLOR.
Referenced by drawForeground().
 {
   const QRect& geo = geometry();
   painter->setPen(MM::CONTROL_COLOR);
   int rect_size = 10;
   QColor color_0(191, 191, 191);
   QColor color_1(128, 128, 128);
   QBrush brush_0(color_0);
   QBrush brush_1(color_1);
   painter->setPen(Qt::NoPen);
   // Draw checkerboard pattern.
   for (int x = geo.x(); x < geo.width(); x += rect_size)
   {
     for (int y = geo.y(); y < geo.height(); y += rect_size)
     {
       if (((x + y) % 20) == 0)
       {
         painter->setBrush(brush_0);
       } else {
         painter->setBrush(brush_1);
       }
       painter->drawRect(x, y, rect_size, rect_size);
     }
   }
   // Create responsive image
   QImage test_signal = _svg_test_signal.scaled(geo.height(), geo.height(), Qt::KeepAspectRatio);
   // Set new brush
   this->_brush_test_signal = QBrush(test_signal);
   // Center the brush
   painter->translate((geo.width() - test_signal.width()) / 2, (geo.height() - test_signal.height()) / 2);
   // Draw the actual brush.
   painter->fillRect(0, 0, test_signal.width(), test_signal.height(), this->_brush_test_signal);
 }
void OutputGLCanvas::resizeGL (int width, int height) protected virtual
Definition at line 102 of file OutputGLCanvas.cpp.
 {
   int side_length = width;
   if (height < width)
   {
     side_length = height;
   }
   (void) side_length; // to get rid of warnings
   // TODO: reload SVG with the new size
   // TODO: _svg_test_signal.load(":/test-signal");
   // TODO: _brush_test_signal(_svg_test_signal)
 }
void OutputGLCanvas::wheelEvent (QWheelEvent * event) protected
Definition at line 116 of file OutputGLCanvas.cpp.
 {
   event->ignore();
 }
void OutputGLCanvas::mouseMoveEvent (QMouseEvent * event) protected
Definition at line 121 of file OutputGLCanvas.cpp.
References MapperGLCanvas::mouseMoveEvent().
 {
   // Click-and-drag translate view.
   if (event->buttons() & Qt::MiddleButton)
   {
     event->ignore();
   }
   else
   {
     DestinationGLCanvas::mouseMoveEvent(event);
   }
 }
virtual bool DestinationGLCanvas::isOutput () const virtual inherited
Returns shape associated with mapping id.
Implements MapperGLCanvas.
Definition at line 37 of file DestinationGLCanvas.h.
 { return true; }
MShape::ptr DestinationGLCanvas::getShapeFromMappingId (uid mappingId) const virtual inherited
Implements MapperGLCanvas.
Definition at line 29 of file DestinationGLCanvas.cpp.
References MapperGLCanvas::getMainWindow(), MappingManager::getMappingById(), MainWindow::getMappingManager(), and NULL_UID.
 {
   if (mappingId == NULL_UID)
     return MShape::ptr();
   else
     return getMainWindow()->getMappingManager().getMappingById(mappingId)->getShape();
 }
QSharedPointer< ShapeGraphicsItem > DestinationGLCanvas::getShapeGraphicsItemFromMappingId (uid mappingId) const virtual inherited
Implements MapperGLCanvas.
Definition at line 37 of file DestinationGLCanvas.cpp.
References MainWindow::getMappingGuiByMappingId(), MainWindow::instance(), and NULL_UID.
 {
   if (mappingId == NULL_UID)
     return QSharedPointer<ShapeGraphicsItem>();
   else
   {
     return MainWindow::instance()->getMappingGuiByMappingId(mappingId)->getGraphicsItem();
   }
 }
MShape::ptr MapperGLCanvas::getCurrentShape () inherited
Definition at line 64 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getShapeFromMappingId(), and MainWindow::instance().
Referenced by MapperGLCanvas::_glueVertex(), MapperGLCanvas::currentShapeWasChanged(), MapperGLCanvas::keyPressEvent(), MapperGLCanvas::mouseMoveEvent(), MapperGLCanvas::mousePressEvent(), and TransformShapeCommand::TransformShapeCommand().
 {
   return getShapeFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
QSharedPointer< ShapeGraphicsItem > MapperGLCanvas::getCurrentShapeGraphicsItem () inherited
Definition at line 69 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getShapeGraphicsItemFromMappingId(), and MainWindow::instance().
Referenced by MapperGLCanvas::drawForeground().
 {
   return getShapeGraphicsItemFromMappingId(MainWindow::instance()->getCurrentMappingId());
 }
MainWindow* MapperGLCanvas::getMainWindow () const inherited
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are close enough.
The distance per coordinate is currently set in dist_stick variable.Returns pointer to main window.
Definition at line 75 of file MapperGLCanvas.h.
Referenced by drawForeground(), MapperGLCanvas::eventFilter(), DestinationGLCanvas::getShapeFromMappingId(), SourceGLCanvas::getShapeFromMappingId(), MapperGLCanvas::keyPressEvent(), MapperGLCanvas::mouseMoveEvent(), MapperGLCanvas::mousePressEvent(), OutputGLWindow::OutputGLWindow(), and OutputGLWindow::setFullScreen().
 { return _mainWindow; }
bool MapperGLCanvas::hasActiveVertex () const inherited
Returns true iff one of the vertices is currently active.
Definition at line 78 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex, and MapperGLCanvas::NO_VERTEX.
Referenced by MapperGLCanvas::drawForeground(), MapperGLCanvas::keyPressEvent(), and MapperGLCanvas::mouseMoveEvent().
 { return _activeVertex != NO_VERTEX; }
int MapperGLCanvas::getActiveVertexIndex () const inherited
Returns the currently active (ie. selected) vertex, or NO_VERTEX if none is currently active.
Definition at line 81 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex.
Referenced by MapperGLCanvas::drawForeground(), and MapperGLCanvas::eventFilter().
 { return _activeVertex; }
void MapperGLCanvas::setActiveVertexIndex (int activeVertex) inherited
Set the currently active vertex.
Definition at line 84 of file MapperGLCanvas.h.
References MapperGLCanvas::_activeVertex.
Referenced by MapperGLCanvas::eventFilter().
 { _activeVertex = activeVertex; }
bool MapperGLCanvas::shapeGrabbed () const inherited
Definition at line 86 of file MapperGLCanvas.h.
References MapperGLCanvas::_shapeGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _shapeGrabbed; }
bool MapperGLCanvas::vertexGrabbed () const inherited
Definition at line 87 of file MapperGLCanvas.h.
References MapperGLCanvas::_vertexGrabbed.
Referenced by MeshTextureGraphicsItem::_doDrawOutput().
 { return _vertexGrabbed; }
qreal MapperGLCanvas::getZoomFactor () const inherited
Definition at line 89 of file MapperGLCanvas.h.
References MapperGLCanvas::_zoomLevel, MM::ZOOM_FACTOR, MM::ZOOM_MAX, and MM::ZOOM_MIN.
Referenced by ShapeControlPainter::_paintVertices(), ShapeControlPainter::getRescaledShapeStroke(), and MapperGLCanvas::wheelEvent().
 { return qBound(qPow(MM::ZOOM_FACTOR, _zoomLevel), MM::ZOOM_MIN, MM::ZOOM_MAX); }
void MapperGLCanvas::currentShapeWasChanged () inherited
This function needs to be called after a shape inside the canvas has been changed for appropriate signals to be activated.
Definition at line 96 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getCurrentShape(), and MapperGLCanvas::shapeChanged().
Referenced by TransformShapeCommand::redo(), and TransformShapeCommand::undo().
 {
   emit shapeChanged(getCurrentShape().data());
 }
void MapperGLCanvas::shapeChanged (MShape *) signal inherited
Referenced by MapperGLCanvas::currentShapeWasChanged().
void MapperGLCanvas::imageChanged () signal inherited
void MapperGLCanvas::updateCanvas () slot inherited
Definition at line 423 of file MapperGLCanvas.cpp.
 {
   update();
   scene()->update();
 }
void MapperGLCanvas::deselectVertices () slot inherited
Stick vertex p of Shape orig to another Shape's vertex, if the 2 vertices are
Definition at line 454 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_vertexGrabbed, and MapperGLCanvas::NO_VERTEX.
Referenced by MapperGLCanvas::deselectAll(), and MapperGLCanvas::mousePressEvent().
 {
   _activeVertex = NO_VERTEX;
   _vertexGrabbed = false;
 }
void MapperGLCanvas::deselectAll () slot inherited
Definition at line 460 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_shapeFirstGrab, MapperGLCanvas::_shapeGrabbed, and MapperGLCanvas::deselectVertices().
Referenced by MapperGLCanvas::mousePressEvent().
 {
   deselectVertices();
   _shapeGrabbed = false;
   _shapeFirstGrab = false;
 }
void MapperGLCanvas::mousePressEvent (QMouseEvent * event) slot inherited
Definition at line 103 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_grabbedObjectStartScenePosition, MapperGLCanvas::_mousePressedPosition, MapperGLCanvas::_shapeFirstGrab, MapperGLCanvas::_shapeGrabbed, MapperGLCanvas::_vertexGrabbed, MapperGLCanvas::deselectAll(), MapperGLCanvas::deselectVertices(), dist(), distSq(), MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getMainWindow(), MainWindow::getMappingManager(), MapperGLCanvas::getShapeFromMappingId(), MappingManager::getVisibleMappings(), MapperGLCanvas::isOutput(), MainWindow::setCurrentMapping(), sq(), and MM::VERTEX_SELECT_RADIUS.
 {
   bool mousePressedOnSomething = false;
   _mousePressedPosition = event->pos();
   QPointF pos = mapToScene(event->pos());
   // Drag the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     // NOTE: This is a trick code to implement scroll hand drag using the middle button.
     QMouseEvent releaseEvent(QEvent::MouseButtonRelease, event->pos(), event->globalPos(), Qt::LeftButton, 0, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&releaseEvent);
     setDragMode(QGraphicsView::ScrollHandDrag);
     // We need to pretend it is actually the left button that was pressed!
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
                           Qt::LeftButton, event->buttons() | Qt::LeftButton, event->modifiers());
     QGraphicsView::mousePressEvent(&fakeEvent);
   }
   // Check for vertex selection first.
   else if (event->buttons() & Qt::LeftButton)
   {
     MShape::ptr shape = getCurrentShape();
     if (shape)
     {
       // Note: we compare with the square value for fastest computation of the distance
       int minDistance = sq(MM::VERTEX_SELECT_RADIUS);
       // Find the ID of the nearest vertex (from currently selected shape)
       for (int i = 0; i < shape->nVertices(); i++)
       {
         int dist = distSq(_mousePressedPosition, mapFromScene(shape->getVertex(i))); // squared distance
         if (dist < minDistance)
         {
           _activeVertex = i;
           minDistance = dist;
           _vertexGrabbed = true;
           mousePressedOnSomething = true;
           _grabbedObjectStartScenePosition = shape->getVertex(i);
         }
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Check for shape selection.
   if (event->buttons() & (Qt::LeftButton | Qt::RightButton)) // Add Right click for context menu
   {
     MShape::ptr selectedShape = getCurrentShape();
     // Possibility of changing shape in output by clicking on it.
     MappingManager manager = getMainWindow()->getMappingManager();
     QVector<Mapping::ptr> mappings = manager.getVisibleMappings();
     for (QVector<Mapping::ptr>::const_iterator it = mappings.end() - 1; it >= mappings.begin(); --it)
     {
       MShape::ptr shape = getShapeFromMappingId((*it)->getId());
       // Check if mouse was pressed on that shape.
       if (shape && shape->includesPoint(pos))
       {
         mousePressedOnSomething = true;
         // Deselect vertices.
         deselectVertices();
         // Change mapping (only available in destination).
         if (isOutput() && shape != selectedShape)
         {
           // Change current mapping.
           getMainWindow()->setCurrentMapping((*it)->getId());
           // Reset selected shape to new one.
           selectedShape = getCurrentShape();
         }
         break;
       }
     }
     // Grab the shape.
     if (event->buttons() & Qt::LeftButton) // This preserve me from duplicate code above
     {
       if (selectedShape && selectedShape->includesPoint(pos))
       {
         _shapeGrabbed = true;
         _shapeFirstGrab = true;
         _grabbedObjectStartScenePosition = pos;
       }
     }
   }
   if (mousePressedOnSomething)
     return;
   // Deactivate.
   deselectAll();
 }
void MapperGLCanvas::mouseReleaseEvent (QMouseEvent * event) slot inherited
Definition at line 208 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::_glueVertex(), MapperGLCanvas::_mainWindow, MapperGLCanvas::_shapeGrabbed, MapperGLCanvas::_vertexGrabbed, TransformShapeCommand::RELEASE, MainWindow::stickyVertices(), and MapperGLCanvas::undoStack.
 {
   Q_UNUSED(event);
   // Wrap-up dragging the scene with middle button.
   if (event->buttons() & Qt::MiddleButton)
   {
     QMouseEvent fakeEvent(event->type(), event->pos(), event->globalPos(),
         Qt::LeftButton, event->buttons() & ~Qt::LeftButton, event->modifiers());
     QGraphicsView::mouseReleaseEvent(&fakeEvent);
     setDragMode(QGraphicsView::NoDrag);
     setCursor(Qt::ArrowCursor);
   }
 //  // Click on vertex ==> select the vertex.
 //  if ((event->buttons() & Qt::LeftButton) && _mousePressedOnVertex)
 //  {
 //  }
   if (_vertexGrabbed)
   {
     // TODO : code repetition here!!!
     QPointF p = mapToScene(event->pos());
     // Stick to vertices.
     if (_mainWindow->stickyVertices())
       _glueVertex(&p);
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::RELEASE, _activeVertex, p));
   }
   else if (_shapeGrabbed)
   {
     undoStack->push(new TranslateShapeCommand(this, TransformShapeCommand::RELEASE, QPointF()));
   }
   _vertexGrabbed = false;
   _shapeGrabbed = false;
 }
void MapperGLCanvas::keyPressEvent (QKeyEvent * event) slot inherited
Definition at line 307 of file MapperGLCanvas.cpp.
References MapperGLCanvas::_activeVertex, MapperGLCanvas::getCurrentShape(), MapperGLCanvas::getMainWindow(), MainWindow::getUndoStack(), MapperGLCanvas::hasActiveVertex(), TransformShapeCommand::STEP, and MapperGLCanvas::undoStack.
Referenced by MapperGLCanvas::eventFilter().
 {
   // Prepare to store commands.
   undoStack = getMainWindow()->getUndoStack();
   // Checks if the key has been handled by this function or needs to be deferred to superclass.
   bool handledKey = false;
   // Active vertex selected.
   if (hasActiveVertex())
   {
     MShape::ptr shape = getCurrentShape();
     QPoint pos = mapFromScene(shape->getVertex(_activeVertex));
     handledKey = true;
     switch (event->key()) {
     // TODO: key tab should switch to next vertex: not working because somehow caught at a higher level
     // to switch between frames of the layout
 //    case Qt::Key_Tab:
 //      if (shape)
 //        _activeVertex = (_activeVertex + 1) % shape->nVertices();
 //        p = shape->getVertex(_activeVertex); // reset to new vertex
 //        qDebug() << "New active vertex : " << _activeVertex << endl;
 //      break;
     // Handle pixel-wise adjustments of vertex.
     case Qt::Key_Up:
       pos.ry()--;
       break;
     case Qt::Key_Down:
       pos.ry()++;
       break;
     case Qt::Key_Right:
       pos.rx()++;
       break;
     case Qt::Key_Left:
       pos.rx()--;
       break;
     default:
       if (event->matches(QKeySequence::Undo))
         undoStack->undo();
       else if (event->matches(QKeySequence::Redo))
         undoStack->redo();
       else
         handledKey = false;
       break;
     }
     // Remap window position to scene.
     QPointF scenePos = mapToScene(pos);
     // TODO: this will always be called even if no arrow key has been pressed (small performance issue).
     // Enable to Undo and Redo when arrow keys move the position of vertices
     undoStack->push(new MoveVertexCommand(this, TransformShapeCommand::STEP, _activeVertex, scenePos));
   }
   // Defer unhandled keys to parent.
   if (!handledKey)
   {
     QWidget::keyPressEvent(event);
   }
 //  std::cout << "Key pressed" << std::endl;
 //  int xMove = 0;
 //  int yMove = 0;
 //  switch (event->key()) {
 //  case Qt::Key_Tab:
 //    if (event->modifiers() & Qt::ControlModifier)
 //      switchImage( (Common::getCurrentSourceId() + 1) % Common::nImages());
 //    else
 //    {
 //      Quad& quad = getQuad();
 //      _active_vertex = (_active_vertex + 1 ) % 4;
 //    }
 //    break;
 //  case Qt::Key_Up:
 //    yMove = -1;
 //    break;
 //  case Qt::Key_Down:
 //    yMove = +1;
 //    break;
 //  case Qt::Key_Left:
 //    xMove = -1;
 //    break;
 //  case Qt::Key_Right:
 //    xMove = +1;
 //    break;
 //  default:
 //    std::cerr << "Unhandled key" << std::endl;
 //    QWidget::keyPressEvent(event);
 //    break;
 //  }
 //
 //  Quad& quad = getQuad();
 //  Point *p = quad.getVertex(_active_vertex);
 //  p->x += xMove;
 //  p->y += yMove;
 //  quad.setVertex(_active_vertex, p);
 //
 //  update();
 //
 //  emit quadChanged();
 }
bool MapperGLCanvas::eventFilter (QObject * target, QEvent * event) slot inherited
Definition at line 505 of file MapperGLCanvas.cpp.
References MapperGLCanvas::getActiveVertexIndex(), MapperGLCanvas::getMainWindow(), MapperGLCanvas::keyPressEvent(), and MapperGLCanvas::setActiveVertexIndex().
 {
   if (event->type() == QEvent::KeyPress)
   {
     QKeyEvent *keyEvent = static_cast<QKeyEvent *>(event);
     setActiveVertexIndex(getMainWindow()->getOutputWindow()->getCanvas()->getActiveVertexIndex());
     MapperGLCanvas::keyPressEvent(keyEvent);
     return true;
   }
   else
   {
     return QObject::eventFilter(target, event);
   }
 }
void MapperGLCanvas::_glueVertex (QPointF * p) protected inherited
Definition at line 521 of file MapperGLCanvas.cpp.
References distIsInside(), MapperGLCanvas::getCurrentShape(), MappingManager::getMapping(), MainWindow::getMappingManager(), MShape::getVertex(), MainWindow::instance(), MappingManager::nMappings(), MShape::nVertices(), and MM::VERTEX_STICK_RADIUS.
Referenced by MapperGLCanvas::mouseMoveEvent(), and MapperGLCanvas::mouseReleaseEvent().
 {
   MappingManager manager = MainWindow::instance()->getMappingManager();
   for (int i = 0; i < manager.nMappings(); i++)
   {
     MShape *shape = manager.getMapping(i)->getShape().data();
     if (shape && shape != getCurrentShape())
     {
       for (int vertex = 0; vertex < shape->nVertices(); vertex++)
       {
         const QPointF& v = shape->getVertex(vertex);
         if (distIsInside(v, *p, MM::VERTEX_STICK_RADIUS))
         {
           p->setX(v.x());
           p->setY(v.y());
         }
       }
     }
   }
 }
Member Data Documentation
bool OutputGLCanvas::_displayCrosshair private
Definition at line 44 of file OutputGLCanvas.h.
Referenced by drawForeground(), and setDisplayCrosshair().
QImage OutputGLCanvas::_svg_test_signal private
Definition at line 45 of file OutputGLCanvas.h.
Referenced by _drawTestSignal().
QBrush OutputGLCanvas::_brush_test_signal private
Definition at line 46 of file OutputGLCanvas.h.
Referenced by _drawTestSignal().
const int MapperGLCanvas::NO_VERTEX = -1 static inherited
Definition at line 176 of file MapperGLCanvas.h.
Referenced by MapperGLCanvas::deselectVertices(), and MapperGLCanvas::hasActiveVertex().
The documentation for this class was generated from the following files:
OutputGLCanvas.h
OutputGLCanvas.cpp