MapMap: PaintGui Class Reference
PaintGui Class Reference
The view components corresponding to a Paint (which is the model) in the interface.
#include <PaintGui.h>
Public Types
typedef QSharedPointer< PaintGui > ptr
Public Slots
virtual void setValue (QtProperty *property, const QVariant &value)
Signals
void valueChanged (Paint::ptr)
Public Member Functions
PaintGui (Paint::ptr paint)
Constructor. A paint gui applies to a paint.
virtual ~PaintGui ()
virtual QWidget * getPropertiesEditor ()
Returns a pointer to the properties editor for that mapper.
Protected Attributes
Paint::ptr _paint
QtAbstractPropertyBrowser * _propertyBrowser
QtVariantEditorFactory * _variantFactory
QtVariantPropertyManager * _variantManager
QtProperty * _topItem
QtVariantProperty * _opacityItem
Detailed Description
The view components corresponding to a Paint (which is the model) in the interface.
Mainly manages the property browser for the Paint.
In other words the PaintGui is to Paint what MappingGui is to Mapping.
Definition at line 51 of file PaintGui.h.
Member Typedef Documentation
typedef QSharedPointer<PaintGui> PaintGui::ptr
Definition at line 55 of file PaintGui.h.
Constructor & Destructor Documentation
PaintGui::PaintGui (Paint::ptr paint)
Constructor. A paint gui applies to a paint.
Definition at line 22 of file PaintGui.cpp.
References _opacityItem, _paint, _propertyBrowser, _topItem, _variantFactory, _variantManager, setValue(), and valueChanged().
   : _paint(paint)
 {
   // Create editor.
   _propertyBrowser = new QtTreePropertyBrowser;
   _variantManager = new VariantManager;
   _variantFactory = new VariantFactory;
   _topItem = _variantManager->addProperty(QtVariantPropertyManager::groupTypeId(),
                                           QObject::tr("Paint"));
   _propertyBrowser->setFactoryForManager(_variantManager, _variantFactory);
   connect(_variantManager, SIGNAL(valueChanged(QtProperty*, const QVariant&)),
           this,            SLOT(setValue(QtProperty*, const QVariant&)));
   _propertyBrowser->addProperty(_topItem);
   // Paint basic properties.
   _opacityItem = _variantManager->addProperty(QVariant::Double, QObject::tr("Opacity (%)"));
   _opacityItem->setAttribute("minimum", 0.0);
   _opacityItem->setAttribute("maximum", 100.0);
   _opacityItem->setAttribute("decimals", 1);
   _opacityItem->setValue(_paint->getOpacity()*100.0);
   _topItem->addSubProperty(_opacityItem);
 }
PaintGui::~PaintGui () virtual
Definition at line 49 of file PaintGui.cpp.
References _propertyBrowser.
 {
   delete _propertyBrowser;
 }
Member Function Documentation
QWidget * PaintGui::getPropertiesEditor () virtual
Returns a pointer to the properties editor for that mapper.
Definition at line 54 of file PaintGui.cpp.
References _propertyBrowser.
 {
   return _propertyBrowser;
 }
void PaintGui::setValue (QtProperty * property, const QVariant & value) virtual slot
Definition at line 59 of file PaintGui.cpp.
References _opacityItem, _paint, and valueChanged().
Referenced by PaintGui(), ColorGui::setValue(), ImageGui::setValue(), and MediaGui::setValue().
 {
   if (property == _opacityItem)
   {
     double opacity = qBound(value.toDouble() / 100.0, 0.0, 1.0);
     if (opacity != _paint->getOpacity())
     {
       _paint->setOpacity(opacity);
       emit valueChanged(_paint);
     }
   }
 }
void PaintGui::valueChanged (Paint::ptr) signal
Referenced by PaintGui(), setValue(), ColorGui::setValue(), ImageGui::setValue(), and MediaGui::setValue().
Member Data Documentation
Paint::ptr PaintGui::_paint protected
Definition at line 74 of file PaintGui.h.
Referenced by PaintGui(), setValue(), ColorGui::setValue(), ImageGui::setValue(), and MediaGui::setValue().
QtAbstractPropertyBrowser* PaintGui::_propertyBrowser protected
Definition at line 75 of file PaintGui.h.
Referenced by getPropertiesEditor(), PaintGui(), and ~PaintGui().
QtVariantEditorFactory* PaintGui::_variantFactory protected
Definition at line 76 of file PaintGui.h.
Referenced by PaintGui().
QtVariantPropertyManager* PaintGui::_variantManager protected
Definition at line 77 of file PaintGui.h.
Referenced by ColorGui::ColorGui(), ImageGui::ImageGui(), MediaGui::MediaGui(), and PaintGui().
QtProperty* PaintGui::_topItem protected
Definition at line 78 of file PaintGui.h.
Referenced by ColorGui::ColorGui(), ImageGui::ImageGui(), MediaGui::MediaGui(), and PaintGui().
QtVariantProperty* PaintGui::_opacityItem protected
Definition at line 79 of file PaintGui.h.
Referenced by PaintGui(), and setValue().
The documentation for this class was generated from the following files:
PaintGui.h
PaintGui.cpp