MapMap: ShapeGraphicsItem Class Reference
ShapeGraphicsItem Class Reference abstract
Represents a shape as part of a scene graph in one of the GL canvas.
#include <ShapeGraphicsItem.h>
Public Types
typedef QSharedPointer
< ShapeGraphicsItem > ptr
Public Member Functions
virtual ~ShapeGraphicsItem ()
MShape::ptr getShape () const
Returns the MShape (depends on mapping and whether this is an input or output).
Mapping::ptr getMapping () const
Returns the mapping.
QSharedPointer
< ShapeControlPainter > getControlPainter ()
Returns the control painter (see below).
bool isOutput () const
Return whether the item is in the destination/output (true) or source/input (false).
MapperGLCanvas * getCanvas () const
Returns pointer to GL canvas.
bool isMappingCurrent () const
Returns whether the mapping this shape is associated with is currently selected.
bool isMappingVisible () const
Returns whether the mapping this shape is associated should be visible.
virtual QRectF boundingRect () const
Returns the bounding rectangle of this item.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Built-in function: paints the shape.
QPen getRescaledShapeStroke (bool innerStroke=false)
Utility function: returns a stroke with rescaled width such that the stroke appears invariant to the zoom level (to be used in paint functions).
Protected Member Functions
ShapeGraphicsItem (Mapping::ptr mapping, bool output=true)
virtual void _doPaint (QPainter *painter, const QStyleOptionGraphicsItem *option)=0
Main paint function that needs to be overriden (called by paint()).
virtual void _prePaint (QPainter *painter, const QStyleOptionGraphicsItem *option)
Can be overriden to perform operations before _doPaint() is called.
virtual void _postPaint (QPainter *painter, const QStyleOptionGraphicsItem *option)
Can be overriden to perform operations after _doPaint() is called.
Protected Attributes
QWeakPointer< Mapping > _mapping
QWeakPointer< MShape > _shape
QSharedPointer
< ShapeControlPainter > _controlPainter
bool _output
Detailed Description
Represents a shape as part of a scene graph in one of the GL canvas.
A ShapeGraphicsItem contains a Mapping and is identified as either an input (source) or an output (destination).
Definition at line 47 of file ShapeGraphicsItem.h.
Member Typedef Documentation
typedef QSharedPointer<ShapeGraphicsItem> ShapeGraphicsItem::ptr
Definition at line 51 of file ShapeGraphicsItem.h.
Constructor & Destructor Documentation
ShapeGraphicsItem::ShapeGraphicsItem (Mapping::ptr mapping, bool output = true) protected
Definition at line 25 of file ShapeGraphicsItem.cpp.
References _shape, and getMapping().
   : _mapping(mapping), _output(output)
 {
   _shape = output ? getMapping()->getShape() : getMapping()->getInputShape();
 }
virtual ShapeGraphicsItem::~ShapeGraphicsItem () virtual
Definition at line 56 of file ShapeGraphicsItem.h.
 {}
Member Function Documentation
MShape::ptr ShapeGraphicsItem::getShape () const
Returns the MShape (depends on mapping and whether this is an input or output).
Definition at line 60 of file ShapeGraphicsItem.h.
References _shape.
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), and ShapeControlPainter::getShape().
 { return _shape.toStrongRef(); }
Mapping::ptr ShapeGraphicsItem::getMapping () const
Returns the mapping.
Definition at line 63 of file ShapeGraphicsItem.h.
References _mapping.
Referenced by ColorGraphicsItem::_prePaint(), TextureGraphicsItem::_prePaint(), isMappingCurrent(), isMappingVisible(), paint(), and ShapeGraphicsItem().
 { return _mapping.toStrongRef(); }
QSharedPointer<ShapeControlPainter> ShapeGraphicsItem::getControlPainter ()
Returns the control painter (see below).
Definition at line 66 of file ShapeGraphicsItem.h.
References _controlPainter.
 { return _controlPainter; }
bool ShapeGraphicsItem::isOutput () const
Return whether the item is in the destination/output (true) or source/input (false).
Definition at line 69 of file ShapeGraphicsItem.h.
References _output.
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), MeshTextureGraphicsItem::_doDrawOutput(), TextureGraphicsItem::_doPaint(), TextureGraphicsItem::_prePaint(), getCanvas(), and paint().
 { return _output; }
MapperGLCanvas * ShapeGraphicsItem::getCanvas () const
Returns pointer to GL canvas.
Definition at line 31 of file ShapeGraphicsItem.cpp.
References MainWindow::getDestinationCanvas(), MainWindow::getSourceCanvas(), MainWindow::instance(), and isOutput().
Referenced by MeshTextureGraphicsItem::_doDrawOutput(), ShapeControlPainter::_paintVertices(), and getRescaledShapeStroke().
 {
   MainWindow* win = MainWindow::instance();
   return isOutput() ? win->getDestinationCanvas() : win->getSourceCanvas();
 }
bool ShapeGraphicsItem::isMappingCurrent () const
Returns whether the mapping this shape is associated with is currently selected.
Definition at line 37 of file ShapeGraphicsItem.cpp.
References MainWindow::getCurrentMappingId(), getMapping(), and MainWindow::instance().
Referenced by TextureGraphicsItem::_doDrawInput(), and MeshTextureGraphicsItem::_doDrawOutput().
{
   return MainWindow::instance()->getCurrentMappingId() == getMapping()->getId();
 }
bool ShapeGraphicsItem::isMappingVisible () const
Returns whether the mapping this shape is associated should be visible.
Definition at line 78 of file ShapeGraphicsItem.h.
References getMapping().
Referenced by paint().
 { return getMapping()->isVisible(); }
virtual QRectF ShapeGraphicsItem::boundingRect () const virtual
Returns the bounding rectangle of this item.
Reimplemented in EllipseTextureGraphicsItem, and PolygonTextureGraphicsItem.
Definition at line 81 of file ShapeGraphicsItem.h.
Referenced by TextureGraphicsItem::_doDrawInput().
 { return shape().boundingRect(); }
void ShapeGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget) virtual
Built-in function: paints the shape.
Definition at line 41 of file ShapeGraphicsItem.cpp.
References _doPaint(), _postPaint(), _prePaint(), getMapping(), isMappingVisible(), and isOutput().
 {
   Q_UNUSED(widget);
   // Sync depth of figure with that of mapping (for layered output).
   if (isOutput())
     setZValue(getMapping()->getDepth());
   // Paint if visible.
   if (isMappingVisible())
   {
     // Paint whatever needs to be painted.
     _prePaint(painter, option);
     _doPaint(painter, option);
     _postPaint(painter, option);
   }
 }
virtual void ShapeGraphicsItem::_doPaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected pure virtual
Main paint function that needs to be overriden (called by paint()).
Implemented in TextureGraphicsItem, EllipseColorGraphicsItem, and PolygonColorGraphicsItem.
Referenced by paint().
virtual void ShapeGraphicsItem::_prePaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected virtual
Can be overriden to perform operations before _doPaint() is called.
Reimplemented in TextureGraphicsItem, and ColorGraphicsItem.
Definition at line 97 of file ShapeGraphicsItem.h.
Referenced by paint().
   { Q_UNUSED(painter); Q_UNUSED(option); }
virtual void ShapeGraphicsItem::_postPaint (QPainter * painter, const QStyleOptionGraphicsItem * option) protected virtual
Can be overriden to perform operations after _doPaint() is called.
Reimplemented in TextureGraphicsItem.
Definition at line 101 of file ShapeGraphicsItem.h.
Referenced by paint().
   { Q_UNUSED(painter); Q_UNUSED(option); }
QPen ShapeGraphicsItem::getRescaledShapeStroke (bool innerStroke = false)
Utility function: returns a stroke with rescaled width such that the stroke appears invariant to the zoom level (to be used in paint functions).
Definition at line 60 of file ShapeGraphicsItem.cpp.
References MM::CONTROL_COLOR, getCanvas(), MM::SHAPE_INNER_STROKE_WIDTH, and MM::SHAPE_STROKE_WIDTH.
Referenced by PolygonControlPainter::_paintShape(), EllipseControlPainter::_paintShape(), and MeshControlPainter::_paintShape().
 {
   return QPen(QBrush(MM::CONTROL_COLOR), (innerStroke ? MM::SHAPE_INNER_STROKE_WIDTH : MM::SHAPE_STROKE_WIDTH) / getCanvas()->getZoomFactor());
 }
Member Data Documentation
QWeakPointer<Mapping> ShapeGraphicsItem::_mapping protected
Definition at line 112 of file ShapeGraphicsItem.h.
Referenced by getMapping().
QWeakPointer<MShape> ShapeGraphicsItem::_shape protected
Definition at line 113 of file ShapeGraphicsItem.h.
Referenced by MeshTextureGraphicsItem::_doDrawOutput(), EllipseTextureGraphicsItem::_doDrawOutput(), PolygonColorGraphicsItem::_doPaint(), getShape(), PolygonColorGraphicsItem::shape(), EllipseColorGraphicsItem::shape(), PolygonTextureGraphicsItem::shape(), EllipseTextureGraphicsItem::shape(), and ShapeGraphicsItem().
QSharedPointer<ShapeControlPainter> ShapeGraphicsItem::_controlPainter protected
Definition at line 114 of file ShapeGraphicsItem.h.
Referenced by EllipseColorGraphicsItem::EllipseColorGraphicsItem(), EllipseTextureGraphicsItem::EllipseTextureGraphicsItem(), getControlPainter(), MeshTextureGraphicsItem::MeshTextureGraphicsItem(), PolygonColorGraphicsItem::PolygonColorGraphicsItem(), and PolygonTextureGraphicsItem::PolygonTextureGraphicsItem().
bool ShapeGraphicsItem::_output protected
Definition at line 115 of file ShapeGraphicsItem.h.
Referenced by isOutput().
The documentation for this class was generated from the following files:
ShapeGraphicsItem.h
ShapeGraphicsItem.cpp