MapMap: Maths.h File Reference
Maths.h File Reference
#include <QtGlobal>
#include <cmath>
Functions
qreal degreesToRadians (qreal degrees)
Converts from degrees to radians.
qreal radiansToDegrees (qreal radians)
Converts from radians to degrees.
int wrapAround (int index, int max)
Wrap value around ie. wrapAround(-1, 3) ==> 2.
qreal sq (qreal x)
Square of x.
qreal distSq (const QPointF &p1, const QPointF &p2)
Returns the squared euclidian distance between two points.
qreal dist (const QPointF &p1, const QPointF &p2)
Euclidian distance between two points.
bool distIsInside (const QPointF &p1, const QPointF &p2, qreal radius)
Returns true iff point #p1# is within distance #radius# of #p2# (using euclidian distance).
Function Documentation
qreal degreesToRadians (qreal degrees)
Converts from degrees to radians.
Definition at line 29 of file Maths.h.
 { return degrees / 180.0f * M_PI; }
qreal radiansToDegrees (qreal radians)
Converts from radians to degrees.
Definition at line 32 of file Maths.h.
Referenced by Ellipse::getRotation().
 { return radians / M_PI * 180.0f; }
int wrapAround (int index, int max)
Wrap value around ie. wrapAround(-1, 3) ==> 2.
Definition at line 35 of file Maths.h.
Referenced by Polygon::_constrainVertex().
 { return (index + max) % max; }
qreal sq (qreal x)
Square of x.
Definition at line 38 of file Maths.h.
Referenced by distIsInside(), distSq(), and MapperGLCanvas::mousePressEvent().
 { return x*x; }
qreal distSq (const QPointF & p1, const QPointF & p2)
Returns the squared euclidian distance between two points.
This can be used rather than dist() to compute the distance faster (prevents the sqrt() computation).
Definition at line 44 of file Maths.h.
References sq().
Referenced by dist(), distIsInside(), and MapperGLCanvas::mousePressEvent().
{
   return sq(p1.x() - p2.x()) + sq(p1.y() - p2.y());
 }
qreal dist (const QPointF & p1, const QPointF & p2)
Euclidian distance between two points.
Definition at line 49 of file Maths.h.
References distSq().
Referenced by MapperGLCanvas::mousePressEvent().
{
   return sqrt( distSq(p1, p2) );
 }
bool distIsInside (const QPointF & p1, const QPointF & p2, qreal radius)
Returns true iff point #p1# is within distance #radius# of #p2# (using euclidian distance).
Definition at line 54 of file Maths.h.
References distSq(), and sq().
Referenced by MapperGLCanvas::_glueVertex().
{
   return distSq(p1, p2) < sq(radius);
 }