MapMap: MediaImpl.cpp File Reference
MediaImpl.cpp File Reference
#include "MediaImpl.h"
#include <cstring>
#include <iostream>
Functions
gboolean gstPollShmsrc (void *user_data)
Function Documentation
gboolean gstPollShmsrc (void * user_data)
Definition at line 329 of file MediaImpl.cpp.
References MediaImpl::getAttached(), MediaImpl::getUri(), MediaImpl::setAttached(), and MediaImpl::setPlayState().
Referenced by MediaImpl::loadMovie().
 {
   MediaImpl *p = (MediaImpl*) user_data;
   if (g_file_test(p->getUri().toUtf8().constData(), G_FILE_TEST_EXISTS) &&
     ! p->getAttached())
   {
     if (! p->setPlayState(true))
     {
       qDebug() << "tried to attach, but starting pipeline failed!" << endl;
       return false;
     }
     //qDebug() << "attached, started pipeline!" << endl;
     p->setAttached(true);
   }
   return true;
 }