MapMap: Util Namespace Reference
Util Namespace Reference
Useful functions.
Functions
void correctGlTexCoord (GLfloat x, GLfloat y)
Calls glTexCoord2f() with the corrected texture coordinates.
void setGlTexPoint (const Texture &texture, const QPointF &inputPoint, const QPointF &outputPoint)
Takes a point (intputPoint) on texture and outputs it as a GL vertex on output (outputPoint).
float map_float (float value, float istart, float istop, float ostart, float ostop)
Convenience function to map a variable from one coordinate space to another.
int map_int (int value, int istart, int istop, int ostart, int ostop)
See map_float.
Mesh * createMeshForTexture (Texture *texture, int frameWidth, int frameHeight)
Triangle * createTriangleForTexture (Texture *texture, int frameWidth, int frameHeight)
Ellipse * createEllipseForTexture (Texture *texture, int frameWidth, int frameHeight)
Quad * createQuadForColor (int frameWidth, int frameHeight)
Triangle * createTriangleForColor (int frameWidth, int frameHeight)
Ellipse * createEllipseForColor (int frameWidth, int frameHeight)
void drawControlsVertex (QPainter *painter, const QPointF &vertex, bool selected, qreal radius, qreal strokeWidth)
void drawControlsVertices (QPainter *painter, const QList< int > *selectedVertices, const MShape &shape)
void drawControlsEllipse (QPainter *painter, const QList< int > *selectedVertices, const Ellipse &ellipse)
void drawControlsQuad (QPainter *painter, const QList< int > *selectedVertices, const Quad &quad)
void drawControlsMesh (QPainter *painter, const QList< int > *selectedVertices, const Mesh &mesh)
void drawControlsPolygon (QPainter *painter, const QList< int > *selectedVertices, const Polygon &polygon)
bool fileExists (const QString &filename)
Checks if a file exists or not.
bool eraseFile (const QString &filename)
bool eraseSettings ()
bool isNumeric (const QString &text)
Detailed Description
Useful functions.
Function Documentation
void Util::correctGlTexCoord (GLfloat x, GLfloat y)
Calls glTexCoord2f() with the corrected texture coordinates.
Definition at line 31 of file Util.cpp.
Referenced by TextureGraphicsItem::_doDrawInput(), and setGlTexPoint().
 {
   glTexCoord2f (x, y);
 }
void Util::setGlTexPoint (const Texture & texture, const QPointF & inputPoint, const QPointF & outputPoint)
Takes a point (intputPoint) on texture and outputs it as a GL vertex on output (outputPoint).
Useful in texture mappings, where one often needs to call this function to project points from texture between glBegin(<GL_SHAPE>) and glEnd() calls.
Definition at line 36 of file Util.cpp.
References correctGlTexCoord(), Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
Referenced by TriangleTextureGraphicsItem::_doDrawOutput(), MeshTextureGraphicsItem::_doDrawOutput(), and EllipseTextureGraphicsItem::_doDrawOutput().
 {
   // Set point in texture.
   correctGlTexCoord(
     (inputPoint.x() - texture.getX()) / (GLfloat) texture.getWidth(),
     (inputPoint.y() - texture.getY()) / (GLfloat) texture.getHeight());
   // Add point in output.
   glVertex2f(
     outputPoint.x(),
     outputPoint.y()
   );
 }
float Util::map_float (float value, float istart, float istop, float ostart, float ostop)
Convenience function to map a variable from one coordinate space to another.
The result is clipped in the range [ostart, ostop] Make sure ostop is bigger than ostart.
To map a MIDI control value into the [0,1] range: map(value, 0.0, 1.0, 0. 127.);
Depends on: #include <algorithm>
Definition at line 60 of file Util.cpp.
 {
     float ret = ostart + (ostop - ostart) * ((value - istart) / (istop - istart));
     // In Processing, they don't do the following: (clipping)
     return std::max(std::min(ret, ostop), ostart);
 }
int Util::map_int (int value, int istart, int istop, int ostart, int ostop)
See map_float.
Definition at line 70 of file Util.cpp.
 {
     float ret = ostart + (ostop - ostart) * ((value - istart) / float(istop - istart));
     //g_print("%f = %d + (%d-%d) * ((%d-%d) / (%d-%d))", ret, ostart, ostop, ostart, value, istart, istop, istart);
     // In Processing, they don't do the following: (clipping)
     return std::max(std::min(int(ret), ostop), ostart);
 }
Mesh * Util::createMeshForTexture (Texture * texture, int frameWidth, int frameHeight)
Definition at line 78 of file Util.cpp.
References Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
Referenced by MainWindow::addMesh().
 {
   Q_UNUSED(frameHeight);
   Q_UNUSED(frameWidth);
   return new Mesh(
     QPointF(texture->getX(), texture->getY()),
     QPointF(texture->getX() + texture->getWidth(), texture->getY()),
     QPointF(texture->getX() + texture->getWidth(), texture->getY() + texture->getHeight()),
     QPointF(texture->getX(), texture->getY() + texture->getHeight())
   );
 }
Triangle * Util::createTriangleForTexture (Texture * texture, int frameWidth, int frameHeight)
Definition at line 91 of file Util.cpp.
References Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
Referenced by MainWindow::addTriangle().
 {
   Q_UNUSED(frameHeight);
   Q_UNUSED(frameWidth);
   return new Triangle(
     QPointF(texture->getX(), texture->getY() + texture->getHeight()),
     QPointF(texture->getX() + texture->getWidth(), texture->getY() + texture->getHeight()),
     QPointF(texture->getX() + texture->getWidth() / 2, texture->getY())
   );
 }
Ellipse * Util::createEllipseForTexture (Texture * texture, int frameWidth, int frameHeight)
Definition at line 103 of file Util.cpp.
References Texture::getHeight(), Texture::getWidth(), Texture::getX(), and Texture::getY().
Referenced by MainWindow::addEllipse().
 {
   Q_UNUSED(frameHeight);
   Q_UNUSED(frameWidth);
   qreal halfWidth  = texture->getWidth() / 2;
   qreal halfHeight = texture->getHeight() / 2;
   return new Ellipse(
     QPointF(texture->getX(), texture->getY() + halfHeight),
     QPointF(texture->getX() + halfWidth, texture->getY()),
     QPointF(texture->getX() + texture->getWidth(), texture->getY() + halfHeight),
     QPointF(texture->getX() + halfWidth, texture->getY() + texture->getHeight()),
     true
   );
 }
Quad * Util::createQuadForColor (int frameWidth, int frameHeight)
Definition at line 123 of file Util.cpp.
Referenced by MainWindow::addMesh().
 {
   return new Quad(
     QPointF(frameWidth / 4, frameHeight / 4),
     QPointF(frameWidth * 3 / 4, frameHeight / 4),
     QPointF(frameWidth * 3 / 4, frameHeight * 3/ 4),
     QPointF(frameWidth / 4, frameHeight * 3 / 4)
   );
 }
Triangle * Util::createTriangleForColor (int frameWidth, int frameHeight)
Definition at line 133 of file Util.cpp.
Referenced by MainWindow::addTriangle().
 {
   return new Triangle(
     QPointF(frameWidth / 4, frameHeight * 3 / 4),
     QPointF(frameWidth * 3 / 4, frameHeight * 3 / 4),
     QPointF(frameWidth / 2, frameHeight / 4)
   );
 }
Ellipse * Util::createEllipseForColor (int frameWidth, int frameHeight)
Definition at line 142 of file Util.cpp.
Referenced by MainWindow::addEllipse().
 {
   return new Ellipse(
     QPointF(frameWidth / 4, frameHeight / 2),
     QPointF(frameWidth / 2, frameHeight / 4),
     QPointF(frameWidth * 3 / 4, frameHeight / 2),
     QPointF(frameWidth / 2, frameHeight * 3 / 4),
     false
   );
 }
void Util::drawControlsVertex (QPainter * painter, const QPointF & vertex, bool selected, qreal radius, qreal strokeWidth)
Definition at line 153 of file Util.cpp.
References MM::CONTROL_COLOR, MM::VERTEX_BACKGROUND, and MM::VERTEX_SELECTED_BACKGROUND.
Referenced by ShapeControlPainter::_paintVertices(), and drawControlsVertices().
 {
   // Init colors and stroke.
   painter->setBrush(selected ? MM::VERTEX_SELECTED_BACKGROUND : MM::VERTEX_BACKGROUND);
   painter->setPen(QPen(MM::CONTROL_COLOR, strokeWidth));
   // Draw ellipse.
   painter->drawEllipse(vertex, radius, radius);
   // Draw cross.
   qreal offset = sin(M_PI/4) * radius;
   painter->drawLine( vertex + QPointF(offset, offset),  vertex + QPointF(-offset, -offset) );
   painter->drawLine( vertex + QPointF(offset, -offset), vertex + QPointF(-offset, offset) );
 }
void Util::drawControlsVertices (QPainter * painter, const QList< int > * selectedVertices, const MShape & shape)
Definition at line 168 of file Util.cpp.
References drawControlsVertex(), MShape::getVertex(), and MShape::nVertices().
Referenced by drawControlsEllipse(), drawControlsMesh(), and drawControlsQuad().
 {
   if (!selectedVertices)
     for (int i=0; i<shape.nVertices(); i++)
       drawControlsVertex(painter, shape.getVertex(i), false);
   else
     for (int i=0; i<shape.nVertices(); i++)
       drawControlsVertex(painter, shape.getVertex(i), selectedVertices->contains(i));
 }
void Util::drawControlsEllipse (QPainter * painter, const QList< int > * selectedVertices, const Ellipse & ellipse)
Definition at line 178 of file Util.cpp.
References drawControlsVertices(), Ellipse::getCenter(), Ellipse::getHorizontalRadius(), Ellipse::getRotation(), Ellipse::getVerticalRadius(), and MM::SHAPE_STROKE.
 {
   // Init colors and stroke.
   painter->setPen(MM::SHAPE_STROKE);
   painter->setBrush(Qt::NoBrush);
   // Draw ellipse contour.
   qreal rotation = ellipse.getRotation();
   painter->save(); // save painter state
   painter->resetTransform();
   const QPointF& center = ellipse.getCenter();
   painter->translate(center);
   painter->rotate(rotation);
   painter->drawEllipse(QPointF(0,0), ellipse.getHorizontalRadius(), ellipse.getVerticalRadius());
   painter->restore(); // restore saved painter state
   // Draw control points.
   drawControlsVertices(painter, selectedVertices, ellipse);
 }
void Util::drawControlsQuad (QPainter * painter, const QList< int > * selectedVertices, const Quad & quad)
Definition at line 201 of file Util.cpp.
References drawControlsVertices(), MM::SHAPE_STROKE, and Polygon::toPolygon().
 {
   // Init colors and stroke.
   painter->setPen(MM::SHAPE_STROKE);
   // Draw quad.
   painter->drawPolygon(quad.toPolygon());
   // Draw control points.
   drawControlsVertices(painter, selectedVertices, quad);
 }
void Util::drawControlsMesh (QPainter * painter, const QList< int > * selectedVertices, const Mesh & mesh)
Definition at line 213 of file Util.cpp.
References drawControlsVertices(), Mesh::getQuads(), MM::SHAPE_INNER_STROKE, MM::SHAPE_STROKE, and Mesh::toPolygon().
 {
   // Init colors and stroke.
   painter->setPen(MM::SHAPE_INNER_STROKE);
   // Draw inner quads.
   QVector<Quad> quads = mesh.getQuads();
   for (QVector<Quad>::const_iterator it = quads.begin(); it != quads.end(); ++it)
   {
     painter->drawPolygon(it->toPolygon());
   }
   // Draw outer quad.
   painter->setPen(MM::SHAPE_STROKE);
   painter->drawPolygon(mesh.toPolygon());
   // Draw control points.
   drawControlsVertices(painter, selectedVertices, mesh);
 }
void Util::drawControlsPolygon (QPainter * painter, const QList< int > * selectedVertices, const Polygon & polygon)
Definition at line 233 of file Util.cpp.
References MM::SHAPE_STROKE, and Polygon::toPolygon().
 {
   // Init colors and stroke.
    painter->setPen(MM::SHAPE_STROKE);
    // Draw inner quads.
    painter->drawPolygon(polygon.toPolygon());
    // Draw control points.
    //drawControlsVertices(painter, selectedVertices, polygon);
 }
bool Util::fileExists (const QString & filename)
Checks if a file exists or not.
Definition at line 245 of file Util.cpp.
Referenced by eraseFile().
 {
   return QFile::exists(filename);
   // gchar* filetestpath = (gchar*) filename.toUtf8().constData();
   // if (FALSE == g_file_test(filetestpath, G_FILE_TEST_EXISTS))
   // {
   //     //std::cout << "File " << filetestpath << " does not exist" << std::endl;
   //     return false;
   // }
   // return true;
 }
bool Util::eraseFile (const QString & filename)
Definition at line 257 of file Util.cpp.
References fileExists().
 {
   if (! fileExists(filename))
   {
     return false;
   }
   QFile file(filename);
   file.close();
   return file.remove();
 }
bool Util::eraseSettings ()
Definition at line 268 of file Util.cpp.
Referenced by main().
 {
   QString homePath = QDir::homePath();
   QString settingsFilePath = QDir(homePath).filePath(".config/MapMap/MapMap.conf");
   QFile settingsFile(settingsFilePath);
   if (! settingsFile.exists())
   {
     return false;
   }
   else
   {
     std::cout << "Erase MapMap settings." << std::endl;
     settingsFile.close();
     return settingsFile.remove();
   }
 }
bool Util::isNumeric (const QString & text)
Definition at line 285 of file Util.cpp.
Referenced by MainWindow::setOscPort().
 {
   QRegExp re("\\d*"); // a digit (\d), zero or more times (*)
   return (re.exactMatch(text));
 }